langchain-ai/langchainjs

docs/docs/modules/chains/llm_chain.md, examples/src/chains/llm_chain_stream.ts, langchain/llms/base.ts, langchain/llms/index.ts, langchain/llms/openai.ts, langchain/package.json, yarn.lock
This PR implements streaming of inner completion results via `callbackManager`.
Similar PR to the Python counterpart: https://github.com/hwchase17/langchain/pull/986
*Usage*:
```typescript
const model = new OpenAI({
streaming: true,
callbackManager: {
handleNewToken(token) {
...
},
},
});
```
=> Implement OpenAI LLM completion streaming

docs/docs/getting-started.md, docs/docs/modules/agents/load_from_hub.md, docs/docs/modules/agents/overview.md
The docs said to 'install the SerpAPI Python package'. I changed it to 'SerpAPI package for JavaScript/TypeScript' to make the instructions more precise.
=> Update SerpAPI installation instructions

docs/docs/modules/indexes/vectorstore.md, examples/package.json, examples/src/indexes/vectorstores_pinecone.ts, langchain/package.json, langchain/vectorstores/base.ts, langchain/vectorstores/hnswlib.ts, langchain/vectorstores/index.ts, langchain/vectorstores/pinecone.ts, yarn.lock
Uses https://github.com/rileytomasek/pinecone-client as the client for Pinecone. 
The [official client](https://github.com/pinecone-io/pinecone-ts-client) is currently marked as `beta` and uses `axios`, which may further prevent us to support Edge runtime etc.
=> Add support for Pinecone vectorstore

docs/docs/modules/indexes/text_splitter.md, examples/package.json, examples/src/indexes/token_text_splitter.ts, langchain/package.json, langchain/tests/text_splitter.test.ts, langchain/text_splitter.ts, yarn.lock
This PR aims to implement TokenTextSplitter by utilising JS-Rust binding of [`openai/tiktoken`](https://github.com/openai/tiktoken): 
Disclaimer: The bindings are maintained in a separate repository https://github.com/dqbd/tiktoken, aiming to upstream the changes back to the official repository.
=> Add implementation of TokenTextSplitter

docs/docs/modules/llms/openai.md, examples/src/llm_promptlayer.ts, langchain/llms/index.ts, langchain/llms/openai.ts
This PR adds the unofficial PromptLayer integration, which will capture the requests and responses and send them to PromptLayer.
Note: I don't think there is an official support for streaming responses, which is why it is ignored for now.
=> Add PromptLayer OpenAI wrapper integration

docs/docs/getting-started.md
The getting started guide references itself as a tutorial so the word notebook suggests copy-pasta from the Python lib
=> docs: changed notebook -> tutorial to keep consistent language in getting started guide

docs/docusaurus.config.js
on a mobile device so i can't test it, and i'm not familiar with docusaurus so i don't know for sure, but this image matches the one that twitter is unfurling the links with. saw @hwchase17 added a placeholder langchain image in the directory, so just slapping that one on as a temporary solution? 🤷
=> UNTESTED attempt to replace default docusaurus social card image

docs/docs/modules/chains/question_answering.md, langchain/llms/base.ts, langchain/llms/cohere.ts, langchain/llms/openai.ts, langchain/package.json, yarn.lock
See also #90. We only want 1 of these.
Using https://github.com/sindresorhus/p-queue
This enables all LLMs to be soft "rate-limited" with a queue, especially useful when dealing with APIs that are heavily rate-limited, like OpenAI.
=> Proposal 2 of 2: Add concurrency control to BaseLLM

langchain/vectorstores/chroma.ts
@nfcampos This fixes the document and metadata loading for chroma similarity search. Comments in the code describe why this change was needed :)
=> fix document and metadata loading from query in chroma

langchain/src/vectorstores/hnswlib.ts
Feel free to close, but seems like we can provide safer access to .index with a getter that throws if it hasn't been init'd 
Also added a static method to init the HNSW Lib so we don't have to dupe the error handling each time
Oh yeah, thanks for making this, super cool
=> hnswlib: Throw error in index getter to dedupe code and have safer usage

examples/package.json, examples/src/indexes/token_text_splitter.ts, langchain/package.json, langchain/text_splitter.ts, yarn.lock
Upgrade the `@dqbd/tiktoken` dependency to version 0.4.0, which includes feature parity with its Python counterpart.
Closes #122
=> Add support for (dis)allowed special and tokens in token text splitter

langchain/src/vectorstores/pinecone.ts
Pinecone is great (and free!), but they only allow you to run a single pod/single index on the free plan. Namespaces are nice because you can fit more stuff into one Pinecone index. [Here's a blog post on how they work.](https://docs.pinecone.io/docs/namespaces) I added namespaces to pinecone.ts so Langchain users can use them for multi-tenant vector database use-cases. 
An example use case might be if you have 10 users with unique documents. Instead of creating 10 Indexes, you can create 1 Index with 10 namespaces (`user-1`, `user-2`, etc). When you run a similarity search, it will be scoped by namespace.
_I need to test this change still, this is just a PoC._
=> Update pinecone.ts to set a default namespace and make it configurable

docs/docs/modules/chains/summarization.md
I was scratching my head for a while not knowing why the Summarization Chain example was not working for me, turns out I was not awaiting for the promise returned from this line of code which was missing in docs:
```typescript
const docs = textSplitter.createDocuments([text]);
```
=> Add missing await in Summarization Chain example (docs)

langchain/src/vectorstores/pinecone.ts
This is a fix to the Pinecone similarity search function [issue](https://github.com/hwchase17/langchainjs/issues/160) discussed and resolved with @nfcampos. 
In essence the `similaritySearchVectorWithScore` function threw the error below because the `namespace` property was missing in the `queryRequest`. Pinecone vectors have namespaces that need to be specified in the query, otherwise the metadata will be undefined. 
error: `error TypeError: Cannot destructure 'res.metadata' as it is undefined. at PineconeStore.similaritySearchVectorWithScore`
A defensive handle was also applied in the case `res.metadata` is undefined, an empty object is returned.
`const { [this.textKey]: pageContent, ...metadata } = (res.metadata ?? {}) as PineconeMetadata;`
These changes have been tested locally.
=> Update pinecone.ts to fix undefined metadata in similaritySearchVectorWithScore function

docs/docs/modules/chains/chat_vector_db_qa.md
Small update to Chat Vector DB & QA chain docs. `textSplitter.createDocuments([text])` returns a promise and should be awaited.
=> fix: await createDocuments() promise

docs/docs/modules/agents/agent_toolkits/sql.md, examples/src/agents/sql.ts
Javascript constructor are synchronous. The `await` can be dropped.
Also update imports for consistency
=> fix: Remove unneeded `await` in constructor

docs/package.json, docs/src/theme/SearchBar.js, yarn.lock
Mendable now has 2 types of search on the component: Mendable Chat and the Normal Search Bar. CMD K will trigger the mendable component and on the top right, there are 2 tabs that you can toggle between the different types of search.
Shoutout to @calebpeffer and @ericciarla for implementing regular keyword search.
@hwchase17 + team, let us know if you have any additional feedback. We will continue to improve it.
=> docs: Added regular search

langchain/src/chains/chat_vector_db_chain.ts
Hi!
I had some struggles in achieving a chat-like experience using the `ChatVectorDBQAChain`. After some digging I found that the generated question based on chat history is not used in the following `QAChain` call. Is this intentional?
In the python repo it seems like it's using new question
https://github.com/hwchase17/langchain/blob/master/langchain/chains/chat_vector_db/base.py#L96
=> fix: Use new question when calling QA chain

langchain/src/chains/chat_vector_db_chain.ts
Allow options to be passed to fromLLM constructor. 
Allow the options: inputKey, outputKey, k, returnSourceDocuments to be passed when creating a chain fromLLM.
=> Allow options to be passed to fromLLM constructor in ChatVectorDBQAChain

docs/docs/modules/indexes/vector_stores/pinecone.md, langchain/src/chains/vector_db_qa.ts
allows for passing `VectorDBQAChain` options into `VectorDBQAChain.fromLLM`.
updated the doc for discoverability
sorry about https://github.com/hwchase17/langchainjs/pull/287 I was struggling with my fork 🤓
=> add options to VectorDBQAChain.fromLLM

langchain/src/llms/hf.ts
yarn add huggingface not working anymore deprecated. use yarn add @huggingface/inference` instead.
=> update error message to new hf package

examples/tsconfig.json, langchain/src/embeddings/base.ts, langchain/src/embeddings/fake.ts, langchain/src/embeddings/openai.ts, langchain/src/util/async_caller.ts, langchain/src/util/tests/async_caller.test.ts, langchain/tsconfig.json, test-exports/tsconfig.json
This class contains generic logic useful for calling any "expensive" resource, eg. an API or LLM. This logic up to now has lived in various forms in subclassess of BaseLLM. As a follow on this will be applied across all those places.
As a follow on to this and to #277 will open a future PR using this in BaseLanguageModel
=> Create reusable AsyncCaller class for calling "expensive" resources like APIs or LLMs

examples/src/chains/chat_vector_db_chroma.ts, examples/src/indexes/vector_stores/supabase.ts, langchain/src/vectorstores/base.ts, langchain/src/vectorstores/chroma.ts, langchain/src/vectorstores/hnswlib.ts, langchain/src/vectorstores/pinecone.ts, langchain/src/vectorstores/supabase.ts, langchain/src/vectorstores/tests/pinecone.int.test.ts, langchain/src/vectorstores/tests/pinecone.test.ts, langchain/src/vectorstores/tests/supabase.int.test.ts, test-exports/index.cjs, test-exports/index.mjs
Closes #282
I hate to churn this, but in the refactor that got merged, the constructor options weren't exposed from `fromDocuments` or `fromTexts` or `fromExisting`
And a recent pr added an options struct for `fromDocuments` and moved the client into there
So why not always take client in the options at the same time?
=> supabase: refactor to expose constructor options

langchain/src/tests/text_splitter.test.ts, langchain/src/text_splitter.ts
This PR adds a feature called `MarkdownTextSplitter` which is equal to the [Markdown Text Splitter in Python](https://langchain.readthedocs.io/en/latest/modules/indexes/examples/textsplitter.html#markdown-text-splitter).
https://github.com/hwchase17/langchain/pull/1169.
=> feat: add MarkdownTextSplitter

langchain/src/agents/agent.ts
Im working with only returning json blob, and parsing it entirely as json in the agent. 
```
export const PREFIX = `You have access to the following actions:`
export const FORMAT_INSTRUCTIONS = `You MUST only respond only via a JSON array of Action or Response type objects defined below. You may use mulitple Action objects, but only ever one Response object. If you do not need to use an Action, the last element in the array MUST be a Response type object.
\`\`\`
type Action = {{
// you should always think about which action to take
thought: string
// the action from the list above to take
action: string
// the valid input to the action 
action_input: string
// the resulting observation
observation: string
}}
type Response = {{
// think about how to answer the original Question with the …
```
=> agent: allow not to set stop

langchain/src/embeddings/openai.ts, langchain/src/llms/openai-chat.ts, langchain/src/llms/openai.ts
This PR adds support for full configuration of OpenAI SDK models that were previously not exposed in the repository. The changes enable passing the complete configuration to OpenAI models through the API, providing greater flexibility and customization.
Previously, OpenAI models used a limited set of pre-defined configurations, which limited the ability of users to customize their models for specific use cases. With this change, we can now support more advanced use cases by enabling users to pass in their own custom configurations.
These changes are particularly useful for developers who are working with OpenAI models and want to fine-tune their configurations. The updated API enables them to do so without having to modify the source code or switch to a different SDK.
Overall, this PR …
=> Add full configuration support for OpenAI SDK models

langchain/src/llms/openai.ts
GPT-4 is classified the same way as GPT-3.5, and uses the `v1/chat/completions` endpoint rather than the `v1/completions` endpoint.
=> Use OpenAIChat class to initialize gpt-4 models

examples/src/chat/memory.ts
I know that `BufferMemory` uses a default `memoryKey = "history"`, but for the [example Chat Memory docs](https://hwchase17.github.io/langchainjs/docs/modules/chat_models/examples/memory) I think it'd be useful to explicitly show the `memoryKey` being set, like is done in the [Chat Overview](https://hwchase17.github.io/langchainjs/docs/modules/chat_models/overview#stateful-chains) section.
=> Update `memory.ts` example to explicitly set `memoryKey`

docs/docs/modules/chains/chat_vector_db_qa.md, langchain/.gitignore, langchain/create-entrypoints.js, langchain/package.json, langchain/src/agents/agent.ts, langchain/src/agents/agent_toolkits/json/json.ts, langchain/src/agents/agent_toolkits/openapi/openapi.ts, langchain/src/agents/agent_toolkits/sql/sql.ts, langchain/src/agents/agent_toolkits/vectorstore/vectorstore.ts, langchain/src/agents/load.ts, langchain/src/agents/tools/vectorstore.ts, langchain/src/base_language/index.ts, langchain/src/chains/chat_vector_db_chain.ts, langchain/src/chains/llm_chain.ts, langchain/src/chains/prompt_selector.ts, langchain/src/chains/question_answering/load.ts, langchain/src/chains/sql_db/sql_db_chain.ts, langchain/src/chains/summarization/load.ts, langchain/src/chains/tests/llm_chain.int.test.ts, langchain/src/chains/vector_db_qa.ts, langchain/src/chat_models/base.ts, langchain/src/llms/load.ts, langchain/tsconfig.json
This mostly does the chains.  I havent looked into agents yet. I know recent Prs are making a whole new class for agent for the new model anyway..
I looked around the python I dont think ser/de is done there either so not sure of the format or if it needs to be supported in order to merge this.
But tests pass and the touched examples run with either model. I dont know if its time to default examples into the ChatOpenAI class yet?
I have not tested the langchain/base_language export as my typescript tooling is poor these days, still working that out but this would seem to do it.
=> BaseLLM -> Base language

langchain/src/agents/chat_convo/index.ts
This issue is the same as https://github.com/hwchase17/langchain/pull/1734
<code>/Git/chatbot-llm-ecommerce/node_modules/langchain/dist/agents/chat_convo/index.js:122
throw new Error(`Unable to parse JSON response from chat agent.\n\n${text}`);
^
[Error: Unable to parse JSON response from chat agent.
My apologies for the confusion. Here are some pots that are available in the store:
```json
{
"action": "Product Info",
"action_input": "pots"
}
``` 
The items with the IDs clay-plant-pot, white-ceramic-pot, and biodegradable-cardboard-pots are all pots.]
</code>
i.e. The response had a text before & after the expected JSON, leading to JSONDecodeError. It's fixed now, by removing text after '```' to remove unwanted text.
Code to reproduce …
```
=> fix: agent json parser fails with text in suffix

langchain/src/agents/tools/zapier.ts
Hey @GautierT this should fix the error you described in #386 
Zapier errors are not always defined by a non 2XX status code, but instead Zapier can return an object with an error key.
Co-authored by [bloop](https://bloop.ai/).
=> Update zapier.ts to handle errors in return JSON object

langchain/src/document_loaders/github.ts
@nfcampos it's mayo here. As discussed, here is the first draft of the github loader that parses the files of a given github url into the `Document` format. This is done recurssively for directories (if it's not set to false).
You can test it with this url: "https://github.com/hwchase17/langchainjs/tree/main/langchain". It works on my end 
I have also filtered out binary files in the logic.
Note that the test file has not yet been included, as I anticipate you may want to make some changes via discussion first. Cheers.
=> feat: Add Github Loader 

docs/docs/getting-started.md, docs/docs/modules/prompts/few_shot_examples.md, docs/docs/modules/prompts/load_from_hub.md, docs/docs/modules/prompts/prompt_template.md, examples/src/prompts/load_from_hub.ts, examples/src/prompts/prompts.ts
Most examples and documentation using the format function i.e. `prompt.format` fail to return the promise because the `await` keyword is missing.
These changes fix these bugs across the repo. Example: `await prompt.format`
=> Fix: Missing 'await' keyword is most examples using the format function

langchain/src/vectorstores/pinecone.ts
@nfcampos as discussed, users are frequently complaining about upsert errors whilst using LangChain alongside Pinecone. The main culprit is that Pinecone has a max size for an upsert request at 2MB and a recommended upsert limit of 100 vectors per request as per the [docs](https://docs.pinecone.io/docs/limits#:~:text=Max%20size%20for%20an%20upsert,to%20queries%20immediately%20after%20upserting.)
The solution is simply to add logic that splits the vectors into chunks of approx. 50, before calling the upsert function for each chunk.
I've tested this locally and it works fine.
=> Fix: Pinecone upsert errors due to large size

docs/docs/modules/llms/openai.md
It threw me an error, and then checked the source code to verify. 
From `PROMPT_LAYER_API_KEY` to `PROMPTLAYER_API_KEY`.
Check here: https://github.com/hwchase17/langchainjs/blob/edd6ed610a6fde4daae1df9e9963e05438eb9102/langchain/src/llms/openai.ts#L389
=> Fixed PromptLayer's API Key envrionment variable name. 

docs/docs/install.md
Currently it's necessary to spend a bit of time wrangling build scripts to get started with a Langchain project using TS. This adds a 'quickstart' section to the langchain.js docs, with a link to a starter repository with scripts set up. 
The linked [starter repo](https://github.com/domeccleston/langchain-ts-starter) is under my name but I'd be happy to move it into this repo. Currently it's just a repository to clone, but in future we could make it a node script with some configuration options.
Thanks for the amazing work on this project!
=> Add quickstart example to langchain.js docs

langchain/src/vectorstores/base.ts, langchain/src/vectorstores/chroma.ts, langchain/src/vectorstores/hnswlib.ts, langchain/src/vectorstores/pinecone.ts, langchain/src/vectorstores/supabase.ts
This allows a single metadata object to be applied to an entire collection of text, for when we want to insert text from a single corpus into a vectorstore, or similar.
=> feat(vectorstores): allow single metadata object to span across all text

langchain/src/output_parsers/structured.ts, langchain/src/output_parsers/tests/structured.test.ts
Zod allowed me to make the .describe on a top level object, but we didnt print it. 
Seems like we should? But I honestly dont incredibly need this right now, did what I wanted by templating around the schema anyway
=> feat: print top level object describe

langchain/docker-compose.yaml
@agola11 thoughts on this? Only one of my Macs needed this, no clue why
=> Make docker compose work in m1 mac

examples/src/agents/mrkl_with_tracing.ts, langchain/src/agents/executor.ts, langchain/src/callbacks/base.ts, langchain/src/callbacks/tests/callbacks.test.ts, langchain/src/callbacks/tests/langchain_tracer.int.test.ts, langchain/src/callbacks/tests/tracer.test.ts, langchain/src/callbacks/tracers.ts, langchain/src/chains/llm_chain.ts
We need to get rid of the tracer's stack and, instead, explicitly assign the parent uuid for a specific run. This is because, in the middle of a run, we could spawn multiple concurrent child runs (this would be the case with multi-output agents, in each step, we could spawn multiple tool runs concurrently).
To avoid having to pass the parent run id to each call of the callback manager, we can wrap this with a child callback manager. The child callback manager would get a parentRunId from the parent callback manager and pass it through to the callbacks.
=> Add ability to create child callback managers

langchain/src/output_parsers/structured.ts
This change allows us to work with schemas where the base object is an array and which contain number fields.
=> Allow structured parser to work with array inputs, numbers

docs/docs/modules/indexes/text_splitters/examples/character.mdx, docs/docs/modules/indexes/text_splitters/examples/markdown.mdx, docs/docs/modules/indexes/text_splitters/examples/recursive_character.mdx, docs/docs/modules/indexes/text_splitters/examples/token.mdx
The `TextSplitter` class `createDocuments` and `splitDocuments` methods return [promises](http://localhost:3000/docs/modules/indexes/text_splitters/). That wasn't made obvious by looking at the examples in the docs, so I updated them to make it more clear.
=> Update the docs for TextSplitter

docs/docs/modules/memory/examples/buffer_memory.md, docs/docs/modules/memory/examples/buffer_memory_chat.mdx, langchain/src/memory/buffer_memory.ts, langchain/src/memory/buffer_window_memory.ts, langchain/src/memory/tests/buffer_memory.test.ts, langchain/src/memory/tests/buffer_window_memory.test.ts
Followup to #538 
The `chatHistory` field was not getting passed through to the `BaseChatMemory` constructor. This fixes that issue, adds tests, and updates the docs with an example.
=> `Fix passing chat history into buffer memory, add tests, update docs

langchain/src/prompts/base.ts
Object.keys will run many times but it is unnecessary, use for...of instead for better performance and readability.
=> feature: optimize iterate code with Object.entries

langchain/src/agents/agent.ts
=> saving stop in constructor

examples/src/retrievers/supabase_hybrid.ts, langchain/src/retrievers/supabase-hybrid-search.ts
Adding Supabase default assumptions to the docs and some comments.
Few important variable defaults were missing from the Supabase Hybrid Search example. Namely:
- tableName: "documents"
- similarityQueryName: "match_documents"
- keywordQueryName: "kw_match_documents"
=> Adding Supabase Hybrid Search default assumptions to the docs

langchain/src/agents/agent.ts
Currently, the `stop` input doesn't seem to function correctly.
Added `this.stop = input.stop` to LLMSingleActionAgent constructor.
=> Fix: LLMSingleActionAgent constructor

docs/docs/ecosystem/unstructured.md
Adds a documentation page for the `UnstructuredLoader`, and also documents the endpoint for the live Unstructured API.
=> docs: adds ecosystem docs for `UnstructuredLoader`

examples/src/document_loaders/unstructured.ts
Unstructured now uses the major version in its urls to avoid having to track every change.
=> Update url in UnstructuredLoader example

docs/docs/modules/models/llms/integrations.mdx
Added key to huggingface, cohere and replicate
=> docs: Add apiKey param for model instantiation

docs/package.json, examples/package.json, langchain/package.json, package.json, yarn.lock
Closes #44 
Only include lint-staged in top-level package.json as outlined in docs: https://github.com/okonet/lint-staged#how-to-use-lint-staged-in-a-multi-package-monorepo
Moves lint-staged config to top-level package.json since the same configuration works for all workspaces. lint-staged discovers the closest configuration to each staged file, so workspace specific configs can be added in the future if there are conflicts with the global config.
=> Configure lint-staged precommit on all workspaces

langchain/src/util/async_caller.ts
Existing code gives this error
node_modules/langchain/dist/util/async_caller.d.ts:30:22 - error TS2702: 'PQueueMod' only refers to a type, but is being used as a namespace here.
30     protected queue: PQueueMod.default;
This PR fixes it..
=> Update queue type to avoid build error

docs/docs/getting-started/guide-chat.mdx, docs/docs/getting-started/guide-llm.mdx, examples/src/models/chat/chat_streaming_stdout.ts, examples/src/models/llm/llm_streaming_stdout.ts
1. ppl wanted to know how to do the equivalent of `sys.stdout.write` for streaming in python in ts
2. the examples in the docs were wrong
=> improve streaming example in getting started guide

langchain/src/agents/executor.ts, langchain/src/agents/tools/base.ts, langchain/src/callbacks/base.ts, langchain/src/chains/base.ts, langchain/src/chat_models/base.ts, langchain/src/llms/base.ts
I think it will be really hard to get rid of self.callback_manager / this.callbackManager the way things are set up now, because sometimes we only want certain callbacks on certain objects (like we in the case of the ConversationalRetrievalChain , we want the llm associated with the QA chain to hit the on_llm_new_token callback and not the question gen one).
=> Merge CallbackManagers when passed through

docs/docs/modules/models/chat/integrations.mdx, docs/docs/modules/models/embeddings/integrations.mdx, docs/docs/modules/models/llms/integrations.mdx
=> Update docs for passing `apiKey` arg in non-Node envs

docs/docs/ecosystem/unstructured.md
the code which import UnstructuredLoader in docs, missing a 's'
```javascript
import { UnstructuredLoader } from "langchain/document_loader";
```
should be:
```javascript
import { UnstructuredLoader } from "langchain/document_loaders";
```
or it will get type error
=> docs: add missing 's'

docs/docs/modules/agents/tools/agents_with_vectorstores.md
This PR fixes the import of `Calculator` in `Agents with Vector Stores` page.
=> Docs - Fixes Calculator import

docs/docs/getting-started/guide-chat.mdx, docs/docs/getting-started/guide-llm.mdx, docs/docs/modules/agents/executor/getting-started.md, docs/docs/modules/agents/tools/agents_with_vectorstores.md, docs/docs/production/tracing.md, examples/src/agents/chat_convo_with_tracing.ts, examples/src/agents/chat_mrkl.ts, examples/src/agents/chat_mrkl_with_tracing.ts, examples/src/agents/concurrent_mrkl.ts, examples/src/agents/custom_agent.ts, examples/src/agents/custom_llm_agent.ts, examples/src/agents/custom_llm_agent_chat.ts, examples/src/agents/load_from_hub.ts, examples/src/agents/mrkl.ts, examples/src/agents/mrkl_with_tracing.ts, examples/src/chat/agent.ts, examples/src/chat/overview.ts, langchain/src/agents/tests/agent.int.test.ts, langchain/src/callbacks/tests/langchain_tracer.int.test.ts, langchain/src/tools/serpapi.ts
closes https://github.com/hwchase17/langchainjs/issues/765
I contacted support because just going back to a search from last weeks It was all in english (Im in Phoenix USA)
So I dont think we changed anything in the api. 
TLDR is unless you set location (and possibly hl and gl) they dont seem to guarantee anything
Just setting location fixed it for me for now.. It seems like alot to add the hg and gl as well, maybe we can get away without it
Updated all examples with a default location. their docs mention Austin so I just used that
>The first thing I notice is that you have not used any location parameters. For consistent language/location results, you need to specify the location, hl and gl parameters. Without these, your search can take the proxy's location, which may deliver unexpected …
=> serpapi results coming back in another region/languge

langchain/src/tools/dynamic.ts
DynamicTool is missing the option to return direct the output of the tool.
=> Adds `returnDirect` to DynamicTool

langchain/src/output_parsers/structured.ts
When using `Zod` with the `StructuredOutputParser`, it always fails as the `instanceof` checks never passes as `instanceof` only works when the class used is the exact same one as the one being compared to. This issue occurs when dealing with monorepos where the same package may have multiple instances.
```ts
const parser = StructuredOutputParser.fromZodSchema(
z.object({
name: z.string().describe('The name'),
artists: z
.array(z.string())
.describe('An array of artists'),
})
);
```
The error received is:
```
Error: Cannot read properties of undefined (reading 'typeName')
```
So using the `schema._def.typeName` is a lot more reliable in performing these checks.
=> fix: printSchema in StructuredOutputParser failing when using Zod

docs/docs/modules/indexes/vector_stores/integrations/milvus.md
Current name produces an error when using Milvus 2.3.0
```
Invalid collection name: goldel-escher-bach.  collection name can only contain numbers, letters and underscores
```
=> fix: correct collection name for Milvus store to use underscores

langchain/src/text_splitter.ts
Exclude documents with undefined `pageContent` in `TextSplitter::splitDocuments.`
related: https://github.com/hwchase17/langchainjs/issues/808
=> reject document which `pageContent` is `undefined`

langchain/src/chains/combine_docs_chain.ts
I found that `MapReduceDocumentsChain` implements `StuffDocumentsChainInput`, but `MapReduceDocumentsChainInput` was not being used. So I updated it and fixed a typo.
=> Update the implements of MapReduceDocumentsChain and fix typo

examples/src/models/chat/chat_streaming_stdout.ts, examples/src/models/llm/llm_streaming_stdout.ts
followup for https://github.com/hwchase17/langchainjs/pull/691
1. import statement has warning
2. example exits immediately with no output
=> Add missing function execution in streaming example in getting started guide

docs/docs/modules/schema/chat-messages.md
It's annoying to research something, only to then have to look somewhere else to figure out how to actually implement it. These improvements follow the example of the "Documents" page in the same section, which explains how to import before using.
=> Including import statements

langchain/src/tools/bingserpapi.ts
The search behavior of the langchainjs `BingSerpAPI` tool is different from the Python version of langchain. This may cause the chain or agent available in Python version to fail when ported to `LangChainJS`. This improvement makes the execution results of both to be as consistent as possible.
```python
def run(self, query: str) -> str:
for result in results:
snippets.append(result["snippet"])
return " ".join(snippets)
```
```typescript
//langchain/src/tools/bingserpapi.ts
async _call(input: string): Promise<string> {
// ...
// In typescript version: Only returned the snippet of the first result here
const myresponse = res.webPages.value[0].snippet;
return myresponse;
}
```
=> Improve bing search tool results

langchain/src/agents/executor.ts, langchain/src/base_language/index.ts, langchain/src/callbacks/manager.ts, langchain/src/callbacks/tests/callbacks.test.ts, langchain/src/chains/base.ts, langchain/src/chains/llm_chain.ts, langchain/src/chat_models/anthropic.ts, langchain/src/chat_models/base.ts, langchain/src/chat_models/openai.ts, langchain/src/llms/base.ts, langchain/src/llms/openai-chat.ts, langchain/src/llms/openai.ts, langchain/src/tools/base.ts
- A callback manager without a currentRunId does not offer non-start methods 
- A callback manager cannot be mutated to add a currentRunId, to do so create a new specialised instance for that run, by calling the respective handleStart method
- An unbound callback manager does not offer getChild, as you shouldn't be able to create a child manager without before calling start
=> Suggestion on how to make callback managers more type safe and harder to misuse

examples/src/prompts/combining_parser.ts, examples/src/prompts/regex_parser.ts, langchain/src/output_parsers/regex.ts
RegexParser was including the /regex/ slashes in its output, but those are already included when converting a RegExp to string. Therefore prompts looked like //0-9//, which is not a common regex notation. Models get confused and include literal // in their responses, which can be seen in the examples.
Fix: remove slashes from RegexParser output, and rely on those from converting RegExp to string.
Also included an example of how to use RegexParser.
Also re-ran examples and pasted output in comments.
=> Fix RegexParser including double slashes in prompt

langchain/src/memory/motorhead_memory.ts
Motorhead memory was not using `getInputValue` to determine the name of the field from which save its contents.
Fixes issue: https://github.com/hwchase17/langchainjs/issues/861
=> fix: Motorhead memory needs to use correct keys

examples/package.json, examples/src/retrievers/metal.ts, langchain/package.json, langchain/src/retrievers/tests/metal.int.test.ts, yarn.lock
We made a major update to index + retrieve based on Metal `Indexes` (instead of `apps`). With this change, we accept an `index` instead of an `app` in each of our respective core apis. [More details here](https://docs.getmetal.io/api-reference/core/indexing).
=> Bump Metal-sdk to v2.0.1

langchain/src/agents/agent.ts, langchain/src/agents/chat/index.ts, langchain/src/agents/chat_convo/index.ts
Ive been carrying this patch for a bit, so it feels worth pushing
Ive done stuff where i reach back out to get something (dynamicContext) or i have an agent with a vectorstore built in where I add and get from the vector store
=> feat: agent make constructScratchPad async

langchain/src/tools/chain.ts
This brings the ChainTool up to snuff with the base Tool, and allows users of the ChainTool to include a callbackManager.
I'm exploring making a standard callback manager for my project where we are able to log to a database every interaction consistently. So this will let us use this utility tool.
=> feat: add verbose and callbackManager to ChainTool

langchain/src/agents/agent.ts, langchain/src/agents/chat/index.ts, langchain/src/agents/chat/outputParser.ts, langchain/src/agents/chat_convo/index.ts, langchain/src/agents/chat_convo/outputParser.ts, langchain/src/agents/index.ts, langchain/src/agents/mrkl/index.ts, langchain/src/agents/mrkl/outputParser.ts
I have an issue with the new outputparser refactors. you cant take in Final Tool name as a variable to getDefaultOutputParser (which is abstract so has to be there)
=> feat: getDefaultOutputParser fields

docs/docs/modules/indexes/document_loaders/examples/web_loaders/s3.mdx, examples/src/document_loaders/s3.ts, langchain/src/document_loaders/web/s3.ts
This change allows the access key / secret access key / region of your S3 bucket to be provided in the constructor of `S3Loader`. This means that you do not need to run `aws configure` before using the class, which was an item that had caused some confusion. 
Also updated the documentation to reflect this change.
=> Update s3 loader so that you can provide credentials in class constructor

langchain/src/document_loaders/web/github.ts
added ignoreFiles parameter on GithubRepoLoader constructor so it can ignore irrelevant large files (e.g. package-lock.json). It accepts array of strings or RegExp to test path name.
=> added ignoreFiles on github document loader

langchain/src/chains/base.ts, langchain/src/chat_models/base.ts, langchain/src/llms/base.ts, langchain/src/schema/index.ts
- it does not show up when calling Object.keys
- it isn't included when calling JSON.stringify on the output object (eg. in the tracer)
This ensures that we don't break eg the logic that powers memory updates, and sequential application of chains
=> Make __run special key non-enumerable, ie. you can only access it specifcally by name

langchain/src/tools/chain.ts, langchain/src/tools/dynamic.ts
It will be helpful to have the `_runManager` in the dynamic function.
We can use it as a context with the `runId`.
=> feat: pass _runManager to func in the DynamicTool

langchain/src/agents/initialize.ts
There was a non-existent function name `initializeAgentExecutor` in the comments, so I changed it to the actual function name `initializeAgentExecutorWithOptions`.
=> Rename `initializeAgentExecutor` to `initializeAgentExecutorWithOptions` in comment

langchain/src/retrievers/supabase.ts, langchain/src/vectorstores/supabase.ts
So now if there's an error its clear what the error is, instead of printing out [object object].
=> unrolled error in supabase vectorstore and retrievers

docs/docs/ecosystem/unstructured.md, langchain/src/document_loaders/tests/unstructured.test.ts
Updates the URL in `unstructured.test.ts` to the URL for the live Unstructured API and enables the tests. Also adds a link to the Unstructured API Swagger docs to the Unstructured ecosystem docs page.
`yarn test` should run successfully with the updated URL.
=> test: update unstructured API url and enable test

.github/workflows/ci.yml, langchain/package.json, langchain/src/document_loaders/tests/pdf.test.ts, test-exports-vercel/src/pages/index.tsx, yarn.lock
It currently builds/downloads some things that aren't needed, and this cuts down on that which both makes it faster and less likely to fail. Also rethink the matrix strategy, no need to test all 9 combinations, enough to test all node versions against one OS and all OSs against one node version
=> CI: Speed up and less flaky

langchain/src/tools/serpapi.ts, langchain/src/tools/tests/serpapi.test.ts
Aims close #982 by adding a base url parameter to the serpapi class. Should allow one to push the serpapi tool through a proxy.
=> Serp base param

langchain/src/vectorstores/pinecone.ts
Langchain checks for null properties and deletes these before upserting to the Index. I've added an additional check for empty objects in the metadata, as these are not handled when the array is flattened. 
I had issues when upserting to Pinecone, and I realised this was because of the fact that sometimes there were empty objects as properties in the PDF metadata. The proposed change fixed this issue.
=> Added additional check for empty object when upserting to Pinecone Index

langchain/src/callbacks/manager.ts
When using the langchain track, I found that the LANGCHAIN_SESSION environment variable does not take effect, and in python's documentation, it is supported.
ref: https://python.langchain.com/en/latest/tracing.html#changing-sessions
=> Fix the issue where the track function does not support the LANGCHAIN_SESSION environment variable

langchain/src/memory/buffer_window_memory.ts
Useful when using `returnIntermediateSteps` - makes it ISO with `BufferMemory`.
=> Add inputKey and outputKey fields to BufferWindowMemory

langchain/package.json, yarn.lock
=> Add fix for NextJS 13 route handlers

langchain/src/chains/sql_db/sql_db_chain.ts
This change allows for the information related to `sqlCommand` to be displayed correctly in the logs.
At first, I thought this was a bug in my prompt/code because I was seeing the following output:
```
SQLQuery:NaN
SQLResult: [{"COUNT(*)":0}]
Answer:
```
With the new code this should now display the actual Command the LLM is suggesting.
=> Making sure that the SQL command is properly displayed in the logs

docs/docs/modules/indexes/retrievers/hyde.mdx, examples/src/retrievers/hyde.ts, langchain/.gitignore, langchain/package.json, langchain/scripts/create-entrypoints.js, langchain/src/prompts/base.ts, langchain/src/retrievers/hyde.ts, langchain/src/retrievers/tests/hyde.int.test.ts, langchain/src/vectorstores/base.ts, langchain/tsconfig.json, test-exports-cf/src/entrypoints.js, test-exports-cjs/src/entrypoints.js, test-exports-cra/src/entrypoints.js, test-exports-esm/src/entrypoints.js, test-exports-vercel/src/entrypoints.js, test-exports-vite/src/entrypoints.js
This adds the ability to retrieve documents from a vector store using the HyDE method as described [here](https://wfhbrian.com/revolutionizing-search-how-hypothetical-document-embeddings-hyde-can-save-time-and-increase-productivity/) 
"The HyDE method is a way to find information in a large set of documents using artificial intelligence. It starts by having a Large Language Model (LLM), like ChatGPT, create a document based on a specific question or topic. This document may contain some false information, but it also has relevant patterns that can be used to find similar documents in a trusted knowledge base.
Next, another AI model is used to turn the created document into an embedding vector, which is then used to find other documents similar to the one the AI model created."
=> feat: Implement HyDE style document retriever

langchain/src/chat_models/openai.ts, langchain/src/llms/openai-chat.ts
(which is the value the openai api expects for this behaviour)
=> If -1 is passed as maxTokens to an openai chat model set it to undefined

langchain/src/util/axios-fetch-adapter.js, langchain/src/util/tests/openai-stream.test.ts
OpenAI returns `application/json` content-type for errors even when expecting a stream in cases like token limit error or other openai related errors. Right now, `axios-fetch-adapter.js:getResponse` only throws a very generic error message, making it impossible to understand what the actual problem is.
```js
// This is very generic and makes it impossible to understand the real error.
throw new Error(
`Expected content-type to be ${EventStreamContentType}, Actual: ${contentType}`
);
```
My fix gets the json body and if there is a proper Error object found inside, throws the real error, making it possible to debug or notify users in such cases.
This issue also seems to be about the same problem: #670
=> Properly handle OpenAI JSON error responses when expecting stream response

docs/docs/modules/chains/other_chains/summarization.mdx, langchain/src/chains/index.ts, langchain/src/chains/summarization/load.ts, langchain/src/chains/summarization/refine_prompts.ts, langchain/src/chains/summarization/tests/load.int.test.ts
Adds refine type for summarization chain based on https://github.com/hwchase17/langchain/blob/d7e17fc8fefb347affd9d1ae6db4764b9685537a/langchain/chains/summarize/__init__.py#L88
=> Add `refine` type for summarization chain

docs/docs/modules/prompts/example_selectors/index.mdx, docs/docs/modules/prompts/output_parsers/index.mdx
While looking into writing docs for #1049, I noticed a few broken links in the `Prompts` section of the docs. I've fixed them here.
=> Update broken docs links

langchain/src/chains/chat_vector_db_chain.ts, langchain/src/chains/conversational_retrieval_chain.ts, langchain/src/chains/question_answering/load.ts
This change makes it easier to investigate what is going on inside ~~`ChatVectorDBQAChain`~~ `ConversationalRetrievalQAChain`.
=> Add `verbose` option to `ConversationalRetrievalQAChain` and question answering chains

langchain/src/output_parsers/list.ts, langchain/src/output_parsers/regex.ts, langchain/src/output_parsers/structured.ts, langchain/src/schema/output_parser.ts
I think it would be nice to recover the offending text in a catch block outside a chain. For instance sometimes if text can't parse it very well might still be usable and worth showing to the user.
=> feat: OutputParserException store offending text

docs/docs/modules/chains/other_chains/summarization.mdx, examples/src/chains/summarization_map_reduce.ts, examples/src/chains/summarization_map_reduce_intermediate_steps.ts, langchain/src/chains/combine_docs_chain.ts, langchain/src/chains/index.ts, langchain/src/chains/question_answering/load.ts, langchain/src/chains/summarization/load.ts, langchain/src/chains/tests/combine_docs_chain.test.ts
Added the `returnIntermediateSteps` flag to `MapReduceChain` to add towards feature parity with the Python Library. 
Fixes #171 
Side note:
I noticed while doing this that in the `loadQAChain` it is calling slightly different prompts compared to when you directly use the `loadQAMapReduceChain`, `loadQAStuffChain` and `loadQARefineChain` instead of specifying a `type`. Is there a reason for this? If not, I can make another PR to fix that up and to make it reference the functions directly.
=> feat: added `returnIntermediateSteps` flag to `MapReduceChain`

langchain/src/chains/question_answering/load.ts
The `loadQAChain` code was repeating the same code defined in other functions specified already for each type. Just DRY-ing it up to reduce any issues in the future when these functions are updated.
=> chore: DRY-up the `loadQAChain` code so it's just using the same functions

.vscode/settings.json
By default, VSCode uses its built-in TypeScript version, which is currently 5.x, however langchainjs is using 4.x for its build, so it's possible for contributors to see errors in their editor that don't match the output from the build, or vice-versa.
This default behavior surprised me; it bit me a few times while working on an [experiment](https://github.com/namuol/langchainjs/pull/1) to improve type-coverage for prompts, as there were changes to how types are inferred in TS 5.
This PR modifies the VSCode workspace settings to use the version from the workspace (4.x), rather than VSCode's built-in version, which should hopefully save contributors the same frustrations.
To do this I just used the `Select TypeScript version` command from VSCode, like so: …
=> Use workspace TS version in VSCode

langchain/src/chains/llm_chain.ts
LLMChain predict can return string and object since we have structured output parser now.
- Extend LLMChain class with generic type T, defaulting to string
- Modify predict method to return Promise<T>
- Accommodate StructuredOutputParser to enable object return type
=> Added type to LLMChain to be used on predict

docs/docs/modules/chains/index_related_chains/conversational_retrieval.mdx
In [ConversationalRetrievalQAChain](https://js.langchain.com/docs/modules/chains/index_related_chains/conversational_retrieval) doc, a return type in the example is still old.
=> [ConversationalRetrievalQAChain] Fix wrong return type in Doc

docs/docs/getting-started/guide-chat.mdx
In the past, [the quickstart tutorial](https://js.langchain.com/docs/getting-started/guide-chat#model--prompt--llmchain) has a step to explain `ConversationChain` https://github.com/hwchase17/langchainjs/commit/2b54606c0ff2f46704a3aef8f0ebb05f6e67d216
However, the PR above looks to have forgotten to move some explanations, so it causes confusion.
https://github.com/hwchase17/langchainjs/issues/1161
=> [Doc][QuickStart] Move steps forget to move

langchain/src/callbacks/handlers/tracers.ts, langchain/src/client/langchainplus.ts, langchain/src/client/tests/langchainplus.int.test.ts
Create a LangChainPlus client that contains methods to
- upload csv dataset (blob)
- read dataset
- list datasets
- delete dataset
- create/read/list/delete example
Tested with an int test
Next PR will be to add the 'runOnDataset' functionality
=> Add LCP Client with CRD methods for datasets and examples

langchain/src/callbacks/handlers/initialize.ts, langchain/src/callbacks/manager.ts
- Add a LANGCHAIN_TRACING_V2 environment variables to enable v2 tracing
- Initialize a v2 tracer if this is set (has precedence over the regular tracing env var)
=> Add V2 Env Var for Callbacks

examples/src/client/tracing_datasets.ts, langchain/.gitignore, langchain/package.json, langchain/scripts/create-entrypoints.js, langchain/src/callbacks/handlers/tracers.ts, langchain/src/client/index.ts, langchain/src/client/langchainplus.ts, langchain/src/client/tests/langchainplus.int.test.ts, langchain/tsconfig.json, test-exports-cf/src/entrypoints.js, test-exports-cjs/src/entrypoints.js, test-exports-cra/src/entrypoints.js, test-exports-esm/src/entrypoints.js, test-exports-vercel/src/entrypoints.js, test-exports-vite/src/entrypoints.js
Part 3 of the client PRs.
- Part 1 https://github.com/hwchase17/langchainjs/pull/1174 creates the V2 tracer and breaks the type signatures of the BaseTracer 
- Part 2 https://github.com/hwchase17/langchainjs/pull/1190 adds the client along with creation / read / deletion methods for datasets and examples. 
This PR adds a method to run a chain or LLM over a dataset.
It doesn't yet introduce concurrency or properly support chat models. I'll try to add that in a fourth PR (this is too big already).
=> Run the Client over a Dataset

langchain/src/callbacks/manager.ts
Assign the `tracingEnabled` flag to be True if tracingV2Enabled is set
=> Fix tracing variable check

langchain/src/chains/summarization/load.ts
Expose the `verbose` option to the `loadSummarizationChain` similar to other `loadX` functions.
=> feat: allow passing in verbose flag in loadSummarizationChain

langchain/src/util/axios-fetch-adapter.js
=> Convert to Uint8Array to avoid Content-Type override

langchain/src/callbacks/base.ts, langchain/src/callbacks/handlers/tracers.ts, langchain/src/callbacks/manager.ts, langchain/src/callbacks/tests/callbacks.test.ts, langchain/src/callbacks/tests/langchain_tracer_v2.int.test.ts, langchain/src/callbacks/tests/tracer.test.ts, langchain/src/chat_models/base.ts
- Add `handleChatModelStart` to callback handler and manager
- Fallback to `handleLLMStart` if not implemented
Still needs tests - will add tomorrow
=> Add Chat Message Handling

langchain/src/chat_models/openai.ts, langchain/src/chat_models/tests/chatopenai.test.ts
getNumTokensFromMessages wasn't doing the same thing as described in: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb
because it didn't include in calculation message role, name content and didn't add 3 to total count
=> fix bug in getNumTokensFromMessages

langchain/src/client/langchainplus.ts, langchain/src/client/tests/langchainplus.int.test.ts
Also adds integration tests with a simpler data set that should run easier
=> Adds chat model support in the LC+ dataset runner

langchain/src/callbacks/handlers/tracer.ts, langchain/src/callbacks/tests/tracer.test.ts, langchain/src/stores/message/dynamodb.ts, langchain/src/stores/message/redis.ts, langchain/src/stores/message/utils.ts, langchain/src/stores/tests/utils.test.ts
Unify format with the python lib, which was [defined of yore as](https://github.com/hwchase17/langchain/blob/4ee47926cafba0eb00851972783c1d66236f6f00/langchain/schema.py#L121)
```
def _message_to_dict(message: BaseMessage) -> dict:
return {"type": message.type, "data": message.dict()}
def messages_to_dict(messages: List[BaseMessage]) -> List[dict]:
return [_message_to_dict(m) for m in messages]
def _message_from_dict(message: dict) -> BaseMessage:
_type = message["type"]
if _type == "human":
return HumanMessage(**message["data"])
elif _type == "ai":
return AIMessage(**message["data"])
elif _type == "system":
return SystemMessage(**message["data"])
elif _type == "chat":
return ChatMessage(**message["data"])
else:
raise ValueError(f"Got unexpected type: {_type}")
def …
```
=> Update Chat Model Serialization

examples/src/chains/sequential_chain.ts, langchain/src/chains/sequential_chain.ts, langchain/src/chains/tests/sequential_chain.int.test.ts, langchain/src/chains/tests/simple_sequential_chain.int.test.ts
Replacing wrong references to "Tempalte" in the documentation and examples related to sequential chains.
=> [DOC] Fixing typos related in the sequential chain documentation

langchain/src/callbacks/handlers/tracer.ts
Parent runs can be missing from a tracer's run map if a user sets different callbacks on different parts of a chain. 
One example of how this could occur is if a user sets `verbose: true` on the LLM within a chain but not on the chain itself.
=> Relax restrictions on tracer parent runs missing from run map

langchain/scripts/create-entrypoints.js, test-exports-esbuild/src/entrypoints.js
Syncing entrypoints with `esm` modules since esbuild/esm should have the same imports. This should give us the expected CI test coverage in `esbuild`.
It seems like these were missed because in the time `esbuild` was added, `esm` already had two more commits that added entrypoints.
Compare to `esm`:
https://github.com/hwchase17/langchainjs/blob/main/test-exports-esm/src/entrypoints.js
Test plan:
- CI tests
=> [test-exports-esbuild] Add missing entrypoints

examples/src/client/tracing_datasets.ts, langchain/src/client/langchainplus.ts, langchain/src/client/tests/langchainplus.int.test.ts
To enable independent trials over datasets
=> Update to Use a Factory Method

langchain/src/callbacks/handlers/tracer_langchain.ts, langchain/src/util/env.ts, langchain/src/util/tests/environment.test.ts
I'm very confident I'm doing this sub-optimally so could use some feedback
=> Add Environment Info to Run Logs

docs/docs/use_cases/api.mdx
=> fix: typo (missing word "simple")

langchain/package.json, langchain/src/chat_models/openai.ts, langchain/src/embeddings/openai.ts, langchain/src/llms/openai-chat.ts, langchain/src/llms/openai.ts, langchain/src/tools/webbrowser.ts, langchain/src/util/env.ts, yarn.lock
Closes #1268
It does seem like Supabase Deno Functions only provides a global Deno functions _without_ `versions` property, which will mark `isDeno` as `false` and because of NodeJS compat, will mark `isNode` as `true`.
This PR aims to correct both of the properties, which is required to force the `axios-fetch-adapter` in these environments.
=> Fix env detection for Deno in Supabase Edge Functions

langchain/src/agents/tests/json.test.ts, langchain/src/tools/json.ts
This PR addresses escaping special characters (`/` and `~`) when listing keys in JsonListKeyTool.
The following agent will now work properly:
```typescript
import { OpenAI } from "langchain/llms/openai";
import { JsonSpec, JsonObject } from "langchain/tools";
import { JsonToolkit, createJsonAgent } from "langchain/agents";
export const run = async () => {
const data: JsonObject = {
paths: {
"/IDSGenericFXCrossRate": "32",
},
};
const toolkit = new JsonToolkit(new JsonSpec(data));
const model = new OpenAI({ temperature: 0 });
const executor = createJsonAgent(model, toolkit);
const input = `What is the value found in IDSGenericFXCrossRate?`;
console.log(`Executing with input "${input}"...`);
const result = await executor.call({ input });
console.log(`Got output ${result.output}`); …
```
=> Fix escaping of special characters in JsonListKeyTool

langchain/src/util/event-source-parse.ts, langchain/src/util/tests/openai-stream.test.ts
This pull request introduces several enhancements to the handling of event stream parsing. This pull request closes #1299.
In summary, the changes made include:
1. Fixing existing test cases to handle an additional 'done' flag, which ensures that all message chunks have been successfully processed from the stream.
2. Introducing a new test case designed to simulate the behaviour of Azure OpenAI's event streams. This case was initially expected to fail as it illustrated the problem of the last message being ignored due to the absence of a trailing blank line.
3. Implementing a 'flush' mechanism in the stream processing functions within `event-source-parse.ts`. This mechanism ensures that any pending messages are correctly processed when the stream ends, addressing the issue identified in …
=> Handle incompatibility of `ChatOpenAI` with Azure OpenAI

.devcontainer/devcontainer.json, README.md
As an avid Codespaces users, I'm just bring this to parity with the python project. I also updated it with an NPM badge which lists weekly downloads, similary to the downloads badge on the main project.
Summary of changes:
- Add .devcontainer for use with Codespaces and VSCode (Something
the python version has)
- Add Codespace badge
- Add VSCode badge
- Add badge to link to NPM package and show weekly downloads
=> Add devcontainer and update readme badges

langchain/src/agents/mrkl/outputParser.ts
for example, an image generator may need the following input. the current regex can not match multi line text.
<pre>I need to generate an image of the Mona Lisa in the style of traditional Chinese painting.
Action: image-generator
Action Input: 
{
"Subject": "Mona Lisa",
"Style": "Chinese traditional painting",
"Color": "Mainly wash tones of ink, with small color blocks in some parts",
"Details": "Mona Lisa should have long hair, a silk dress, holding a fan. The background should have mountains and trees.",
"Emotion": "Serene and elegant"
}<pre>
=> add support of parsing multi-line text

langchain/src/tests/text_splitter.test.ts, langchain/src/text_splitter.ts
I have been playing around with langchain and langchainjs and noticed that the textsplitters were producing different results. My goal is to align the textsplitters in langchainjs to be more similar to the langchain textsplitters.
I changed one line of conditional logic that was different between the two libraries. In the mergeSplits function:
langchain: if (total + _len + (separator_len if len(current_doc) > 0 else 0) > self._chunk_size):
langchainjs: if (total + _len >= this.chunkSize)
new langchainjs: if (total + _len + (currentDoc.length > 0 ? separator.length : 0) > this.chunkSize)
=> changed TextSplitter class to align with langchain

examples/src/agents/sql.ts, langchain/src/agents/agent_toolkits/sql/sql.ts, langchain/src/tools/sql.ts
Addresses and fixes #1202 by allowing the user to pass a preconfigured model into a SQL Toolkit.
=> Allow creation of a SQL toolkit with a custom language model

langchain/src/chains/tests/vector_db_qa_chain.int.test.ts, langchain/src/chains/vector_db_qa.ts
- extract "filter" key from ChainValues passed to ".call"
- pass filter value to "similaritySearch" call
- if user does not supply "filter" value it remains "undefined" as before
- if the shape of filter does not conform to value expected by VectorStore, error returns as expected
=> Allow filter value in ".call" invocation for VectorDBQAChain

langchain/src/chains/sql_db/sql_db_chain.ts
I found that after adding the sqlOutputKey, the intermediateStep had no effect, so I removed it
=> chore: remove useless code

langchain/src/stores/message/redis.ts, langchain/src/stores/tests/redis.int.test.ts
=> Fix redis chat message history message hydration

langchain/src/chat_models/anthropic.ts, langchain/src/chat_models/tests/chatanthropic.int.test.ts
Fixes #1255 
This updates `ChatAnthropic` to support passing an overridden `apiUrl` through to `anthropic-sdk-typescript`.  The default API URL is defined here:
https://github.com/anthropics/anthropic-sdk-typescript/blob/main/src/index.ts#L22
The Anthropic `Client` allows passing an `apiUrl` on an `options` object:
https://github.com/anthropics/anthropic-sdk-typescript/blob/main/src/index.ts#L42
=> Allow passing Anthropic apiUrl to ChatAnthropic constructor

langchain/src/document_loaders/tests/gitbook.int.test.ts, langchain/src/document_loaders/web/gitbook.ts
Gitbook's server-side rendering means that when we fetch the contents of the index page
the sub-menu items are not rendered and thus are invisible to $('nav a').
This patch makes the loader use sitemap.xml which has an index of all pages.
Inspired by the Python version.
=> Scrape all pages, not only level 1 navigation

docs/docs/modules/models/chat/integrations.mdx, examples/src/models/chat/integration_googlevertexai-examples.ts, examples/src/models/chat/integration_googlevertexai.ts, langchain/.gitignore, langchain/package.json, langchain/scripts/create-entrypoints.js, langchain/src/chat_models/googlevertexai.ts, langchain/src/chat_models/tests/chatgooglevertexai.int.test.ts, langchain/src/chat_models/tests/chatgooglevertexai.test.ts, langchain/src/schema/index.ts, langchain/tsconfig.json
Implements the Google Vertex AI PaLM chat model, as referenced in #1240 and building off the work first done in pull request #1273.
Note that the LangChain BaseChatMessage pattern is completely followed here, although Google-specific extensions are included (and documented through unit and integration tests, examples, and the documentation).
=> Feature: Google Vertex AI Chat model

langchain/src/callbacks/handlers/tracer_langchain.ts, langchain/src/callbacks/handlers/tracer_langchain_v1.ts, langchain/src/callbacks/manager.ts, langchain/src/chains/openai_moderation.ts, langchain/src/chat_models/anthropic.ts, langchain/src/chat_models/openai.ts, langchain/src/client/langchainplus.ts, langchain/src/document_loaders/web/apify_dataset.ts, langchain/src/document_loaders/web/github.ts, langchain/src/embeddings/cohere.ts, langchain/src/embeddings/hf.ts, langchain/src/embeddings/openai.ts, langchain/src/llms/cohere.ts, langchain/src/llms/hf.ts, langchain/src/llms/openai-chat.ts, langchain/src/llms/openai.ts, langchain/src/llms/replicate.ts, langchain/src/tools/bingserpapi.ts, langchain/src/tools/google_custom_search.ts, langchain/src/tools/serpapi.ts, langchain/src/tools/serper.ts, langchain/src/tools/zapier.ts, langchain/src/util/env.ts, langchain/src/util/hub.ts, langchain/src/vectorstores/milvus.ts, langchain/src/vectorstores/qdrant.ts
Some Deno configurations will throw an error if any attempt is made to access an environment variable. This PR refactors `process.env` access into a util method. Should also remove the need to have TS compiler ignore comments in many places as well.
Fixes #1412
=> Factor out and wrap environment variable access in a try/catch

docs/docs/modules/models/chat/index.mdx
According to the docs there is more than ChatOpenAi model only --> ChatAnthropic etc...
What was removed:
> Note: Currently, the only chat-based model we support is ChatOpenAI (with gpt-4 and gpt-3.5-turbo), but anticipate adding more in the future.
=> Remove outdated remark in docs/modules/models/chat/index.mdx

langchain/src/vectorstores/milvus.ts
Fixes # (issue) https://github.com/hwchase17/langchainjs/issues/1451
=> fix ssl for Milvus.fromText

docs/docs/modules/chains/index_related_chains/conversational_retrieval.mdx, langchain/src/chains/conversational_retrieval_chain.ts, langchain/src/chains/tests/conversational_retrieval_chain.int.test.ts
Fixes #1417 (which is supported in Python), and adds the ability to use different LLMs for the combination step.
=> Refactor conversational retrieval QA chain factory method

langchain/src/tools/requests.ts
StructuredAgent needs to format this to {action, action_input} format where `action_input: string`. However, gpt-3.5-turbo very frequently fails to do so. Instead it generates formats like this: `{action, action_input: {url}}`.
This tiny prompt change makes it more reliable.
=> Make the get request tool more reliable for StructuredAgent

langchain/src/memory/zep.ts
=> Zep::getMemory should return [] instead of throwing an error

langchain/src/callbacks/handlers/tracer_langchain.ts, langchain/src/callbacks/tests/langchain_tracer.int.test.ts, langchain/src/callbacks/tests/tracer.test.ts, langchain/src/client/langchainplus.ts
- Remove GET /tenants as the API will infer the tenant_id from the api key
- Remove session creation as POST /runs now accepts session name
- Add timeout (default to 5s), limit retries to 2
- Update Client in the same vein
=> Update tracer to use new simpler api

docs/docs/getting-started/guide-llm.mdx, examples/src/prompts/structured_parser.ts
There are three changes are made in this PR:
1. Code-block 3.2 on https://js.langchain.com/docs/getting-started/guide-llm is updated from `bash` to `typescript`
- [Preview](https://langchainjs-docs-git-fork-m14t-fix-docs-paris-3d0cf4-langchain.vercel.app/docs/getting-started/guide-llm#building-a-language-model-application)
3. The parsed JSON on [Structured Output Parser](https://js.langchain.com/docs/modules/prompts/output_parsers/#structured-output-parser) now matches the string version
- Previously the string was referencing `https://en.wikipedia.org/wiki/Paris` but somehow it parsed to `https://en.wikipedia.org/wiki/France`
- [Preview](https://langchainjs-docs-git-fork-m14t-fix-docs-paris-3d0cf4-langchain.vercel.app/docs/modules/prompts/output_parsers/#structured-output-parser)
4. …
=> Minor documentation updates

langchain/src/vectorstores/tests/chroma.test.ts
Per request, mocked out the chroma backend, and wrote unit tests that validate basic functionality of the Chroma VectorStore class
Fixes #96  (issue)
Twitter handle: https://twitter.com/cparker7
=> Add unit tests to chromadb integration

langchain/src/document_loaders/fs/unstructured.ts
Update the list of file extensions supported by Unstructured to add the following:
* `.htm` (`.html` was already supported, no reason this shouldn't be included)
* `.rtf` (Rich Text Format)
* `.xlsx`(MS Excel files since 2007)
* `.xls` (older MS Excel files)
* `.odt` (OpenDocument files)
* `.epub` (open e-book format)
=> Add new filetypes supported by Unstructured

langchain/src/vectorstores/pinecone.ts, langchain/src/vectorstores/tests/pinecone.test.ts
Pinecone documents support string arrays, so they shouldn't be flattened.
This fix basically removes all arrays from the metadata object which contain only strings and appends them after the remaining metadata object was flattened.
Fixes #1446
=> Add pinecone metadata string array support

langchain/package.json, langchain/src/vectorstores/chroma.ts, langchain/src/vectorstores/tests/chroma.test.ts, yarn.lock
Upgrade chroma to 1.5.2
chomadb@1.5.1 introduces a breaking change, switching from `snake_case` to `camelCase` arguments in `collection.query`. 
chromadb@1.5.2 fixes a type error introduced in 1.5.0
Fixes #1481 
`$ yarn test:single langchain/src/vectorstores/tests/chroma.test.ts ` passes
=> Upgrade Chroma to 1.5.2

docs/docs/modules/indexes/vector_stores/integrations/prisma.mdx, examples/src/indexes/vector_stores/prisma_vectorstore/prisma.ts, examples/src/indexes/vector_stores/prisma_vectorstore/prisma/migrations/00_init/migration.sql, examples/src/indexes/vector_stores/prisma_vectorstore/prisma/schema.prisma, langchain/src/vectorstores/prisma.ts
=> feat: Add filter support for Prisma

docs/docs/modules/chains/index_related_chains/conversational_retrieval.mdx, examples/src/chains/conversational_qa_customization.ts, langchain/src/chains/tests/conversational_retrieval_chain.int.test.ts
Clarify examples around the `ConversationalRetrievalQAChain`.
=> Update docs with a memory + returnSourceDocuments example and test

langchain/src/memory/zep.ts
=> Include memory key when getMemory returns NotFoundError.

docs/docusaurus.config.js, docs/package.json, yarn.lock
Should speed up build times and hopefully reduce memory/flaky CI
See discussion here: https://github.com/facebook/docusaurus/issues/4765
And here: https://github.com/rancher/rancher-docs/pull/667
=> Use swc-loader to build docs instead of babel-loader

langchain/src/callbacks/manager.ts, langchain/src/callbacks/tests/manager.int.test.ts
Add helper function for grouping traces similar to the context manager in the [python library](https://github.com/hwchase17/langchain/blob/a0d847f63628c77d34e9e6003f45af6d59d83288/langchain/callbacks/manager.py#L131)
=> Add Trace Grouping Helper

.github/workflows/ci.yml, docker-compose.yml, scripts/docker-ci-entrypoint.sh
Noticed that when running `yarn test:exports:docker`, `yarn` packages are always being pulled, even with `yarn.lock` being present.
This PR fixes the following:
- Copy both .yarn folder and .yarnrc.yml to use Yarn Berry to match the correct version found in yarn.lock
- Avoid copying inner node_modules and build artifacts in the entrypoint
- Mount a volume to cache downloaded packages
=> ci: ensure ci step uses yarn 2.x, cache dependencies

langchain/src/chains/combine_docs_chain.ts, langchain/src/chains/tests/combine_docs_chain.test.ts
In the refine and stuff chain the input keys are the input keys of the llm chains used and the input key of the chain. This causes issues because in these chains some of the inputs to the llm chain are given by the chain: 
```typescript
const model = new OpenAI({ temperature: 0 });
const chain = loadSummarizationChain(model, { type: "refine" });
const textSplitter = new RecursiveCharacterTextSplitter({ chunkSize: 1000 });
const docs = await textSplitter.createDocuments(["test"]);
console.log(chain.inputKeys)
// ['input_documents', 'existing_answer', 'text']. Should be ['input_documents']
console.log(await chain.call({"input_documents":docs}))
// output_text: Test is a process used to evaluate a syst…termine its performance and functionality.'
console.log(await chain.run(docs))
// Uncaught …
```
=> fix input keys in refine and stuff chains

langchain/src/embeddings/googlevertexai.ts, langchain/src/embeddings/tests/googlevertexai.int.test.ts
As mentioned here: https://github.com/hwchase17/langchain/issues/5316 Vertex AI accepts 5 instances max when requesting text embeddings.
This PR chunks the embedding requests to a maximum length of 5.
=> Add pagination to GoogleVertexAIEmbeddings

docs/docs/getting-started/install.md
The docs for running Langchain with Node.js 16 have a typo that says you need to polyfill `unstructuredClone`, when it should really say `structuredClone`.
Docs link: https://js.langchain.com/docs/getting-started/install#unsupported-nodejs-16
=> Fix docs typo from `unstructuredClone` to `structuredClone`

langchain/src/agents/index.ts
Unlike other agents the new OpenAIAgent and the interfaces related to it are not exported and thus cannot be used directly.
This patch exports them.
=> Export the agent

langchain/src/chains/combine_docs_chain.ts, langchain/src/chains/serde.ts
=> Fix token count in map reduce to reflect the actual tokens used in the final prompt

langchain/src/embeddings/openai.ts
when use dotenv.config(), batchSize still not right, so init batchSize value in constructor
=> bugfix: ajust batchSize for azure embeddings

langchain/src/agents/mrkl/outputParser.ts
Fix for #1673 - TypeError: Cannot read properties of undefined (reading 'trim') 
A "TypeError" occurred when trying to call the "trim()" method on an undefined object. This happened in the parse method of the "ZeroShotAgentOutputParser" class.
```
An error occurred: TypeError: Cannot read properties of undefined (reading 'trim')
at ZeroShotAgentOutputParser.parse (file:///Users/dev/docker/ai-chatbot/node_modules/langchain/dist/agents/mrkl/outputParser.js:30:33)
at ZeroShotAgent._plan (file:///Users/dev/docker/ai-chatbot/node_modules/langchain/dist/agents/agent.js:198:34)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async AgentExecutor._call (file:///Users/dev/docker/ai-chatbot/node_modules/langchain/dist/agents/executor.js:82:28)
at async …
```
=> Update outputParser.ts - Fix TypeError

langchain/src/tools/webbrowser.ts
Fixes #800  (issue)
Made textSplitter a field of `WebBrowser` and added it as an optional field to its constructor.
=> Make the TextSplitter in WebBrowser Tool configurable

langchain/package.json, yarn.lock
=> Downgrade decamelize for browser compatibility

docs/docs/modules/agents/tools/dynamic.mdx, docs/docs/modules/chains/other_chains/api_chain.mdx, examples/src/chains/api_chain.ts, examples/src/chains/api_chain_headers.ts
There are 2 changes made to the Documentation in this PR:
1. added an example for using headers with APIChain in [Here](https://js.langchain.com/docs/modules/chains/other_chains/api_chain).
- [Versel Build Link](https://langchainjs-docs-git-fork-srilals-main-langchain.vercel.app/docs/modules/chains/other_chains/api_chain)
2. fixed the missing async declaration in the dynamic tool example in docs in [Here](https://js.langchain.com/docs/modules/chains/other_chains/api_chain).
- [Versel Build Link](https://langchainjs-docs-git-fork-srilals-main-langchain.vercel.app/docs/modules/agents/tools/dynamic)
Twitter: [@SrilalSS](https://twitter.com/srilalss)
=> added APIchain headers example and fixed an error in dynamic tool example.

docs/docs/modules/models/llms/integrations.mdx, examples/src/llms/googlevertexai-code-bison.ts, examples/src/llms/googlevertexai-code-gecko.ts, langchain/src/llms/googlevertexai.ts, langchain/src/llms/tests/googlevertexai.int.test.ts
Related to #1575 
Refactoring how the GoogleVertexAI llm support is implemented and removes the GoogleVertexAICode class (which is a breaking change, but one I think folks are unlikely to run into).
=> Refactor how the Google Vertex AI PaLM Codey  code- models are implemented

langchain/src/callbacks/manager.ts
What was happening was that the runManager was only added to the managers array after the callback handlers finished executing, so eg if the callback handlers for the second run finished first the runManager for prompt #2 would actually be in position #1 of the returned array.
=> Ensure that run managers are returned from handleLLMStart/handleChatModelStart always in the same order as the prompts passed in

langchain/src/vectorstores/qdrant.ts
Adds support for `apiKey`
From the official [Qdrant JS Client docs](https://github.com/qdrant/qdrant-js): 
```javascript
import {QdrantClient} from '@qdrant/js-client-rest';
// TO connect to Qdrant running locally
const client = new QdrantClient({url: 'http://127.0.0.1:6333'});
// or connect to Qdrant Cloud
const client = new QdrantClient({
url: 'https://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.us-east-0-1.aws.cloud.qdrant.io',
apiKey: '<your-api-key>',
});
```
=> qdrant.ts: add support for QDRANT_API_KEY 

docs/docs/modules/models/llms/additional_functionality.mdx, examples/src/cache/upstash_redis.ts, examples/src/cache/upstash_redis_advanced.ts, langchain/.gitignore, langchain/package.json, langchain/scripts/create-entrypoints.js, langchain/src/cache/tests/upstash_redis.test.ts, langchain/src/cache/upstash_redis.ts, langchain/src/load/import_constants.ts, langchain/src/load/import_type.d.ts, langchain/tsconfig.json
This PR adds an Upstash Redis-based cache under `langchain/cache/upstash_redis` to supplement the existing [Redis-based cache](https://js.langchain.com/docs/modules/models/llms/additional_functionality#caching-with-redis) under `langchain/cache/redis`. This adds parity with `langchain/stores/message/redis` and `langchain/stores/message/upstash_redis`.
Closes #1428
=> Add Upstash Redis cache

examples/src/indexes/vector_stores/lancedb/load.ts
The new LanceDB example has an extraneous await, this removes it.
=> Fix wrongly awaited new in LanceDB example

langchain/src/tools/zapier.ts
Description: This copies over OAuth access token support from the Zapier wrapper in langchain and mirroring the capability for langchainjs.
I ran these unit tests for this PR:
OAuth
```
ZAPIER_NLA_OAUTH_ACCESS_TOKEN=<redacted> yarn test:single langchain/src/agents/tests/zapier_toolkit.int.test.ts
PASS  src/agents/tests/zapier_toolkit.int.test.ts (10.339 s)
ZapierNLAWrapper
✓ loads ZapierToolKit (1029 ms)
✓ Zapier NLA has connected actions (269 ms)
Giphy action
✓ returns a GIF (4428 ms)
Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        10.39 s, estimated 13 s
```
API Key
```
ZAPIER_NLA_API_KEY=<redacted> yarn test:single langchain/src/agents/tests/zapier_toolkit.int.test.ts
PASS  src/agents/tests/zapier_toolkit.int.test.ts (9.458 s) …
```
=> Add oauth access token support to Zapier

docs/docs/modules/agents/tools/zapier_agent.mdx, langchain/src/tools/zapier.ts
Updating docs to call out how to attach Zapier NLA auth.  Also removed email address as developers can now self serve.
Question: 
With this PR https://github.com/hwchase17/langchainjs/pull/1798 I updated the Wrapper class params, yet documentation doesn't reflect that change currently https://js.langchain.com/docs/api/tools/classes/ZapierNLAWrapper.  I tried running `yarn docs` but it did not generate any updated documentation.  How do I get this MD file updated?
I should get the class updated to call out params can be set via `params` or the equivalent env var.
=> Update Zapier agent docs

langchain/src/tools/zapier.ts
This PR mirrors the update we did in the `langchain` repository.  The list endpoint is always used when the wrapper class is initiated and run.  This PR makes 401 error messages more clear to the end user to double check their key/token and make sure it's refreshed if needed.
=> Update error message for Zapier tool when listing endpoints fails

langchain/src/chat_models/openai.ts, langchain/src/embeddings/openai.ts, langchain/src/llms/openai-chat.ts, langchain/src/llms/openai.ts
The way it's written now it's not clear that this an "or" check. It sounds like
the package may be configured to use the azure version of openai instead of standard
openai. I think this wording makes it a bit more clear that langchain checked for both API
keys and didn't find any.
=> fix: make the api error message more clear

docs/docs/modules/prompts/output_parsers/index.mdx
it was unclear to me that the basic schema parser did not support things like arrays of strings. This makes it a bit more clear.
=> docs: note about complex schema

langchain/src/vectorstores/tests/typesense.test.ts, langchain/src/vectorstores/typesense.ts
Typesense vector search provides the vector_distance in the search result:
https://typesense.org/docs/0.24.1/api/vector-search.html#nearest-neighbor-vector-search
=> typesense: add vector_distance as score

langchain/src/chains/openai_functions/openapi.ts, langchain/src/chains/openai_functions/tests/openapi.int.test.ts
In the OpenAPIChain, some schema fields were getting converted to objects rather than their intended type - this PR should fix that!
(mostly) Fixes #1870, #1849
=> Fixes conversion issue in OpenAPIChain

langchain/src/embeddings/openai.ts
According to the operator precedence in JavaScript, the nullish coalescing operator `(??)` has a lower precedence than the conditional operator `(? :)`. Therefore, the expression is actually evaluated as
```
this.batchSize = (fields?.batchSize ?? azureApiKey) ? 1 : this.batchSize
```
so the `batchSize` parameter will not work
=> Fix the batchSize parameter of OpenAIEmbeddings

langchain/package.json, langchain/src/chat_models/anthropic.ts, langchain/src/chat_models/tests/chatanthropic.int.test.ts, test-exports-vercel/package.json, yarn.lock
Anthropic has released Claude V2 which makes use of an updated API. The TypeScript SDK 0.5.X has been rewritten to support the new API schema which also applies to Claude V1. 
It should be noted that the TypeScript SDK no longer supports `AbortController` inherently and so it can only be used for streaming responses to short circuit what is returned by the LangchainJS client.
=> Update Anthropic SDK to 0.5.X to support Claude V2

docs/docs/modules/indexes/text_splitters/index.mdx, examples/src/agents/vectorstore.ts
tokens and characters are mentioned in the same line, this makes it clear that splitters work off of characters (being able to split based on token count would be way better imho).
=> docs: make it clear that chunks are characters and not tokens

langchain/src/util/async_caller.ts
Fixes #1929. 
Previously, such errors would be mistaken for retryable rate limit errors and retried with an exponential backoff, causing apps to confusingly hang.
=> Avoid retries and surface better error message for OpenAI quota cutoff errors

langchain/src/document_loaders/tests/sonix_audio.int.test.ts, langchain/src/document_loaders/web/sonix_audio.ts
Updating sonix integration to throw in case of error. This is to address comment from previous pr https://github.com/hwchase17/langchainjs/pull/1917#discussion_r1260170911.
Also creating tests for the new behavior.
=> Update sonix behaviour on error

langchain/src/chat_models/anthropic.ts
Fixes #1958
The CJS version of langchain resolved the anthropic SDK like so:
```
const sdk_1 = require("@anthropic-ai/sdk");
[...code here...]
this.streamingClient = new sdk_1.Anthropic({
...options,
apiKey: this.anthropicApiKey,
});
```
The above code appears to has issues when the CJS version of langchain was consumed. I think the issue is that `sdk_1.Anthropic` from the package `@anthropic-ai/sdk` resolves to a namespace and/or has a collision since the Anthropic client and a namespace are both exported under `Anthropic` in the anthropic package.
The change raised here uses the explicit default export from `@anthropic-ai/sdk`. This results in the following CJS code in the langchain build:
```
const sdk_1 = __importStar(require("@anthropic-ai/sdk"));
[...code here...] …
```
=> Use default export from Anthropic SDK instead of named

langchain/src/embeddings/fake.ts, langchain/src/embeddings/tests/fake.test.ts
This provides a SyntheticEmbeddings class which is created with a specified vector size. It then creates a vector of this size based on the input.
* Identical inputs should yield the same output for the same vector size. ("this" will always have the same vector)
* Similar inputs of the same size should yield nearby vectors, depending (very roughly) how similar. ("this" and "that" should have nearby vectors, but it depends on the vector size)
* Inputs of different sizes may give similar vectors, depending in the input sizes and vector size. In some cases. ("this" and "thing" may have nearby vectors, but it depends largely on the vector size. If the vector size is 10, for example, the first three components in the vector should be the same.)
This class is meant to be used for testing in …
=> A quick way to create a fake, but consistent, pseudo-embeddings

langchain/src/text_splitter.ts
Allows for async lengthFunctions to be passed in to a splitter (Eg: llm.getNumTokens)
Tag Maintainers: @jacoblee93 @nfcampos @hwchase17 
Related previous PR regarding addition of lengthFunction: https://github.com/hwchase17/langchainjs/pull/1955
=> Allow promise<number> for splitter lengthFunction; Async mergeSplits

langchain/src/vectorstores/faiss.ts
Fixes # ([Bug: TypeError: value.toDocument is not a function](https://github.com/hwchase17/langchainjs/issues/1976))
=> Add langchain.docstore.document bind

docs/package.json, yarn.lock
This new version fixes the"Verified Sources" display that got broken. Instead of displaying the full URL in the source item, it shows the title of the page the source is from.
=> docs: Mendable: Fixes pretty sources not working

examples/src/chains/openai_moderation.ts
This example didn't align with how the code is actually structured. 
It is expected on instantiation of the moderation chain [here](https://github.com/hwchase17/langchainjs/blob/c09f8310a3a2197e98e188167ee39f04dbe18a1d/langchain/src/chains/openai_moderation.ts#L51), but this example is setting it on the call which doesn't do anything.
=> fix: broken OpenAIModerationChain example

langchain/package.json, langchain/src/chat_models/anthropic.ts, yarn.lock
Addresses the following issues: 
- crash when importing Anthropic SDK to non-NextJS Edge Functions
- Inconsistencies with CJS and ESM version of Anthropic SDK (we can remove the previous workaround)
=> Update Anthropic SDK to 0.5.7

langchain/src/chat_models/openai.ts
This is a mistake in the documentation.
Specifically, the docs here link out to OpenAI's /chat/completions endpoint, but the link itself contains the following text:
```
openai.createCompletion
```
This is the wrong function for the /chat/completions endpoint. The correct function (which you can see clearly in the [README for the OpenAI Node module](https://github.com/openai/openai-node#usage)) is:
```
openai.createChatCompletion
```
=> Fix mistake in ChatOpenAI docs

langchain/src/output_parsers/structured.ts, langchain/src/output_parsers/tests/structured.test.ts
Hello, first of all, thanks for this great project and for helping AI get closer to Javascript.
There's an error with `StructuredOutputParser` which makes it unable to work with `OutputFixingParser`.
Currently, `StructuredOutputParser` was not "awaiting" the schema check, so the try-catch clause did not run when the schema check failed. Because of this, the error that surfaced was a "ZodError" (in my case using zod).
Because `OutputFixingParser` (rightfully so) expect that the error received to be `OutputParserException` it will not properly try to fix these errors and just bail.
This fix just introduced the "await" so the try-catch clause work and also a regression test to validate.
=> fix(StructuredOutputParser): Do not obscure OutputParserException

docs/snippets/modules/chains/popular/chat_vector_db.mdx, examples/src/chains/conversational_qa_external_memory.ts, langchain/src/chains/conversational_retrieval_chain.ts, langchain/src/chains/tests/conversational_retrieval_chain.int.test.ts
Some popular examples in the wild have been using an unexpected format for external memory for the ConversationalRetrievalQAChain. This PR fixes the chain for those users, and logs a warning pointing them to the updated docs.
Fixes #2029 and likely others.
=> Adds temporary shim for convo retrieval qa chain legacy users

langchain/src/chains/llm_chain.ts
I think this was unintentionally forgotten during the previous update? I would have expected this to be caught by the linter or compiler since it kind of breaks proper inheritance?
=> Support Callback Config in LLMChain

langchain/src/vectorstores/milvus.ts
With this PR we can change the fields name in Milvus DB, for example instead of name: "langchain_primaryid", the developer can change to: "some_primaryid". 
The constructor contains already these fields:  args.textField, args.primaryField and args.vectorField
=> Feature: Enable to change the fields name in Milvus 

langchain/src/util/math_utils.ts, langchain/src/util/tests/math_utils.test.ts
Fixed a bad "in" check for already selected embeddings, added a test for duplicates check
=> fix: duplicates in Max Marginal Relevance output

langchain/src/retrievers/amazon_kendra.ts
Fix a small bug when getting an empty 'AnswerText' attr while using Kendra Api query.
Example:
```
TypeError: Cannot read properties of undefined (reading 'Key')
at CustomAmazonKendraRetriever.getQueryItemExcerpt 
```
=> Fix kendra api query - getQueryItemExcerpt

docs/extras/modules/data_connection/document_loaders/integrations/web_loaders/web_playwright.md, langchain/src/document_loaders/web/playwright.ts
This PR introduces an enhancement to the PlaywrightWebBaseLoader in LangChain, a feature update that gives you more control over the HTTP responses when loading web pages using the Playwright library.
The original implementation of PlaywrightWebBaseLoader doesn't deal with the Response object returned by Playwright's page navigation function. With this PR, PlaywrightWebBaseLoader is adjusted to capture and use this Response object, enabling additional processing based on the HTTP response.
Here's a snippet of how to use this enhanced functionality:
```typescript
import {
PlaywrightWebBaseLoader,
Page,
Browser,
Response,
} from "langchain/document_loaders/web/playwright";
const loader = new PlaywrightWebBaseLoader("https://your-web-url", {
async evaluate(page: Page, browser: Browser, …
```
=> Enhance PlaywrightWebBaseLoader with HTTP response handling

langchain/src/types/googlevertexai-types.ts, langchain/src/util/googlevertexai-connection.ts
This PR allows overwriting the auth options for Vertex AI that differ from the variables from environment such as `GOOGLE_APPLICATION_CREDENTIALS`. 
ref: https://github.com/googleapis/google-auth-library-nodejs/blob/main/src/auth/googleauth.ts#L85
=> Feat: make projectId configurable for vertex ai

examples/src/agents/structured_chat.ts
Dynamic structured tool has a property called returnDirect that allows the tool to return the output directly. I have added this missing declaration to the documentation.
Fixes #2109 
twitter_handle: @SkenosP
=> Added missing property declaration

langchain/src/vectorstores/base.ts, langchain/src/vectorstores/milvus.ts, langchain/src/vectorstores/tests/milvus.int.test.ts
A filter type has been added to Milvus DB, so we can pass filter object with a property called `filterStr`
=> Feature - add filter type for Milvus DB

docs/snippets/modules/model_io/prompts/prompt_templates/partial.mdx
The typo can be seen [here](https://js.langchain.com/docs/modules/model_io/prompts/prompt_templates/partial#partial-with-strings).
=> Fix: Partial Prompt Template docs typo

langchain/src/evaluation/index.ts
Fix import { QAEvalChain } from 'langchain/evaluation'.
=> 🧑‍💻 Make 'QAEvalChain' available.

examples/package.json, langchain/package.json
The `tsc` check required a separate `yarn build` run to work in some cases. This should reduce friction for contributors.
=> Remove precommit compilation hook

docs/extras/modules/data_connection/vectorstores/integrations/xata.mdx, examples/package.json, examples/src/indexes/vector_stores/xata.ts, examples/src/indexes/vector_stores/xata_metadata.ts, langchain/.gitignore, langchain/package.json, langchain/scripts/create-entrypoints.js, langchain/src/load/import_map.ts, langchain/src/vectorstores/tests/xata.int.test.ts, langchain/src/vectorstores/xata.ts, langchain/tsconfig.json, package.json, test-exports-cf/src/entrypoints.js, test-exports-cjs/src/entrypoints.js, test-exports-esbuild/src/entrypoints.js, test-exports-esm/src/entrypoints.js, test-exports-vercel/src/entrypoints.js, test-exports-vite/src/entrypoints.js, yarn.lock
This adds supports for [Xata](https://xata.io) (serverless data platform based on Postgres) as a vector store. There were a [couple](https://github.com/hwchase17/langchainjs/pull/967) of [attempts](https://github.com/hwchase17/langchainjs/pull/543) from the community to add Xata as a vector store, but they stopped short of adding sample code and docs. This PR includes sample code and docs and it's coming from us at Xata so we'll make sure to keep it maintained.
Opening in draft mode for now because I'd like a colleague (@SferaDev) to have a look at the types used. But the PR is otherwise functional and any feedback would be appreciated already.
You will need to create a DB in xata (see the docs), then run something like:
```
OPENAI_API_KEY=sk-... XATA_API_KEY=xau_... …
```
=> Add support for Xata as a vector store

langchain/src/llms/googlevertexai.ts
Fixes # 
we can handle version of the model vertex ai by adding like `@001` in the end of model name. official document is [here](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/code-completion)
thus If I set model name as `code-gecko@001`, it don't work and this is not implementer want.
=> Update code model defaults for code-gecko in GoogleVertexAI

langchain/src/chains/transform.ts, langchain/src/output_parsers/noop.ts, langchain/src/schema/output_parser.ts, langchain/src/schema/runnable.ts, langchain/src/schema/tests/output_parser.test.ts, langchain/src/schema/tests/runnable.test.ts
Primary use-case is to allow LLM/chat model streaming with an output parser that can handle streamed generated chunks.
=> Allow runnables to implement transform streaming

langchain/src/vectorstores/chroma.ts, langchain/src/vectorstores/tests/chroma.test.ts
Chroma doesn't save multi level objects. Seemingly since 0.4.0. See chroma [types.ts](https://github.com/chroma-core/chroma/blob/77c1675c49a1aeab5a1b0c81b4aacc1afdf877b5/clients/js/src/types.ts#L12), which doesn't include object as an allowed value.
The storing succeeds, but the loc object is empty.
If you store the object as a single property (`locFrom`, `locTo`), it works.
This PR maps the langchain `loc` when storing and the new `locFrom` when reading.
=> fix non saving chroma loc

langchain/src/retrievers/self_query/functional.ts, langchain/src/retrievers/self_query/tests/hnswlib_self_query.int.test.ts
If no filter could be generated for a given query, the translator would throw a cryptic error. 
This PR makes the filter return false for all documents.
=> Adds base case for functional translator filter

docs/extras/modules/data_connection/retrievers/integrations/parent-document-retriever.mdx, examples/src/retrievers/parent_document_retriever.ts, langchain/.gitignore, langchain/package.json, langchain/scripts/create-entrypoints.js, langchain/src/load/import_map.ts, langchain/src/retrievers/parent_document.ts, langchain/src/retrievers/tests/parent_document.int.test.ts, langchain/tsconfig.json, test-exports-cf/src/entrypoints.js, test-exports-cjs/src/entrypoints.js, test-exports-esbuild/src/entrypoints.js, test-exports-esm/src/entrypoints.js, test-exports-vercel/src/entrypoints.js, test-exports-vite/src/entrypoints.js
When splitting documents for retrieval, there are often conflicting desires:
1. You may want to have small documents, so that their embeddings can most accurately reflect their meaning. If too long, then the embeddings can lose meaning.
2. You want to have long enough documents that the context of each chunk is retained.
The ParentDocumentRetriever strikes that balance by splitting and storing small chunks of data. During retrieval, it first fetches the small chunks but then looks up the parent ids for those chunks and returns those larger documents.
=> Adds parent document retriever

langchain/src/vectorstores/chroma.ts
metadata was lost if no line-of-code keys present
=> fix loose metadata when retrieve from Chroma

langchain/src/agents/toolkits/conversational_retrieval/tool.ts, langchain/src/agents/toolkits/tests/conversational_retrieval.int.test.ts
Fixes #2258.
The retriever tool extended the standard tool class sets a default schema equivalent to `{input?: string}`. This changes the tool to extend structured tool and pass a schema equivalent to `{input: string}` instead.
=> Mark retriever tool input schema as required

langchain/src/chat_models/openai.ts, langchain/src/llms/openai-chat.ts, langchain/src/llms/openai.ts, langchain/src/types/openai-types.ts
Added support for optional 'user' input parameter for OpenAI API.
> A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse
Relevant documentation links:
- https://platform.openai.com/docs/api-reference/completions/create
- https://platform.openai.com/docs/api-reference/chat/create
=> Optional 'user' input param for OpenAI API

langchain/src/callbacks/manager.ts
Seems like if you set to ="false" you'd expect tracing to not be performed
=> Check that env var is truthy

langchain/src/schema/index.ts, langchain/src/stores/message/utils.ts
Added `function` message option to Stored Messages to Chat Messages mapper. Modified constructor for compatibility.
Fixes #2303
=> Fix stored function message mapping to chat (#2303)

langchain/src/vectorstores/myscale.ts
We update the default index type from `IVFFLAT` to `MSTG`, a new vector type developed by MyScale.
=> update myscale default index type

docs/extras/modules/data_connection/vectorstores/integrations/hnswlib.mdx, examples/src/indexes/vector_stores/hnswlib_delete.ts, langchain/src/vectorstores/hnswlib.ts, langchain/src/vectorstores/tests/hnswlib.int.test.ts
Adding delete function for `hnswlib.ts`. Useful when you have limited disk space or use many indexes and need to clean them up.
Fixes #1107
=> add delete function to hnswlib index

langchain/src/chat_models/baiduwenxin.ts
Now, `ERNIE-Bot` and `ERNIE-Bot-turbo` share the same API.
=> fix: ERNIE-Bot-turbo supports temperature and more

langchain/package.json, langchain/src/vectorstores/tests/vectara.int.test.ts, langchain/src/vectorstores/vectara.ts
This PR adds the document metadata to the response metadata object.
Metadata before this change (this is the response metadata only):
```
[
{ name: 'lang', value: 'fra' },
{ name: 'offset', value: '218' },
{ name: 'len', value: '138' }
]
```
Metadata after this change (both document and response metadata are added):
```
[
{ name: 'lang', value: 'fra' },
{ name: 'offset', value: '218' },
{ name: 'len', value: '138' },
{ name: 'document_id', value: '-1848969058' },
{ name: 'title', value: "The hitchhiker's guide to the galaxy" },
{ name: 'author', value: 'Douglas Adams' },
{ name: 'genre', value: 'fiction' }
]
```
=> Add Vectara document metadata

langchain/src/schema/output_parser.ts
Missing `langchain` prefix in `lc_namespace` causes the deserialisation of StrOutputParser and BytesOutputParser to fail
SImilar to #2329
=> Fix serialisation of StrOutputParser and ByteOutputParser

langchain/src/callbacks/index.ts
This simply makes the CallbackManagerForRetrieverRun available, just like the other classes in the file (e.g. CallbackManagerForLLMRun, CallbackManagerForChainRun etc). I'm using it in a new MultiQueryRetriever.
=> Export CallbackManagerForRetrieverRun

langchain/src/agents/tests/sql.test.ts, langchain/src/tools/sql.ts
The issue was that the ListTablesSqlTool was iterating through all tables in the SqlDatabase instance without considering the includeTables and ignoreTables options. This resulted in the tool listing all tables, regardless of the specified options.
To resolve this issue, the following changes were made:
In the `ListTablesSqlTool` class, the tool now considers the `includesTables` and `ignoreTables` options of the associated `SqlDatabase` instance. The tool uses conditional logic to filter the list of tables based on the provided options, ensuring that only the appropriate tables are listed.
1. Modified ListTablesSqlTool implementation to correctly consider `includesTables` and `ignoreTables` options.
2. Added new tests to the test suite to cover scenarios with both includeTables and …
=> fix: ListTablesSqlTool to consider includeTables and ignoreTables

langchain/src/agents/tests/sql.test.ts, langchain/src/sql_db.ts, langchain/src/util/sql_utils.ts
This PR adds implementation and test for custom descriptions for tables in SqlDatabase ( already existing in [python version](libs/langchain/langchain/utilities/sql_database.py)) those descriptions are added to the db class and then used in the get tables info command.
@polpuigdemont
=> feat: custom descriptions to SqlDatabase

langchain/src/chains/retrieval_qa.ts
RetrievalQAChain extends BaseChain, so it should inherit all the functionalities provided by BaseChain. However, I've noticed that function calls to RetrievalQAChain are filtered, causing some BaseChain features to malfunction.
Example: 
```
import {
ChatPromptTemplate,
SystemMessagePromptTemplate,
} from "langchain/prompts";
// 1: this prompt  wants to be used in RetrievalqaChain
const rolePrompt = 'You are a helpful assistant of {field} field.';
const systemMessagePrompt = SystemMessagePromptTemplate.fromTemplate(rolePrompt);
const chatPrompt = ChatPromptTemplate.fromPromptMessages([systemMessagePrompt]);
....
const chain = RetrievalQAChain.fromLLM(model, vectorStoreRetriever, {
prompt: chatPrompt,
});
//  2:  Invoking the 'call' function and passing the 'field' variable to the prompt …
```
=> fix(issue: 2417): Fixed the bug that the call's values will be filted in RetrivealQaChain

examples/src/retrievers/parent_document_retriever.ts, langchain/src/retrievers/parent_document.ts
Allow for specifying number of both child and parent documents in `ParentDocumentRetriever` that will be returned.
Assume that you have 3 documents that are split by `ParentDocumentRetriever` in following way:
* 1 document (300 child documents, 3 parent documents)
* 2 document (500 child documents, 5 parent documents)
* 3 document (200 child documents, 2 parent documents)
If you use `ParentDocumentRetriever` in the old way, let's say with `childK === 20`, vectorstore might give you only 20 found child documents from many more available, which will result in sending to LLM only one parent document instead of more.
**This MR (a little inspired by the recently added `Similarity Score Threshold`) is adding the possibility to control the final number of returned documents.**
So now you have …
=> Specify number of both child and parent documents in ParentDocumentRetriever

langchain/src/document_loaders/tests/recursive_url.int.test.ts, langchain/src/document_loaders/web/recursive_url.ts
I noticed a bug when running max depth as zero, which should only return the requested page but instead would return pages as max depth +1.
I also added a test for this with max depth as one.
=> Recursive url fix

docs/extras/modules/data_connection/vectorstores/integrations/redis.mdx, examples/src/indexes/vector_stores/redis/redis_delete.ts, langchain/package.json, langchain/src/vectorstores/redis.ts, langchain/src/vectorstores/tests/redis.test.ts
As [`FT.DROPINDEX`](https://redis.io/commands/ft.dropindex/) does not delete the documents associated with the index by default, this change adds a new option to delete documents when dropping an index.
=> feat(redis vectorstore): add deleteDocuments to redis vectorstore's dropIndex

langchain/src/chat_models/ollama.ts, langchain/src/llms/ollama.ts, langchain/src/util/ollama.ts
According to the [Ollama source code](https://github.com/jmorganca/ollama/blob/main/api/types.go#L168C2-L168C2) there are a few model options which langchainjs does not support yet. This PR adds support for the missing Ollama model params.
=> Support all Ollama model options

langchain/src/callbacks/handlers/run_collector.ts, langchain/src/callbacks/index.ts, langchain/src/callbacks/tests/run_collector.test.ts
Open to other alternatives, but this PR adds a simple callback handler that adds root traces to a queue so it is easier to retrieve the run ID regardless of the API someone uses within langchain.
An alternative would be to combine this logic in the langchain tracer since the immediate motivation for this is logging feedback to langsmith or a similar service using the run ID
=> Add JS Run Collector

langchain/src/llms/sagemaker_endpoint.ts
Typo fix for `AWS_SECRETE_ACCESS_KEY` -> `AWS_SECRET_ACCESS_KEY`
=> Fix typo for `AWS_SECRET_ACCESS_KEY` on sagemaker_endpoint LLM

langchain/src/document_loaders/web/github.ts
Adds User-Agent to request headers to fix `GithubRepoLoader`.
Fixes https://github.com/hwchase17/langchainjs/issues/2479
=> Add User-Agent to GithubRepoLoader Github API Requests

langchain/src/prompts/chat.ts, langchain/src/prompts/tests/chat.test.ts
Python version of Langchain does support specifying BaseMessage subclasses alongside message prompt templates in `from_messages`.
=> Add support for BaseMessage subclasses present in message prompt templates

examples/src/chains/openai_moderation.ts, langchain/src/chains/openai_moderation.ts, langchain/src/chains/tests/openai_moderation.int.test.ts
This is very useful for handling non-english language moderation inputs, as OpenAI moderation can sometimes result in false negatives but still detects the usage of some sort of abusive language. So this pull request allows users to set the boundary themselves by filtering by category_scores (see [OpenAI moderation doc](https://platform.openai.com/docs/guides/moderation/quickstart)).
=> New Feat: Passing results from OpenAI moderation call

docs/extras/modules/data_connection/vectorstores/integrations/redis.mdx, examples/src/indexes/vector_stores/redis/redis_index_options.ts, langchain/src/vectorstores/redis.ts, langchain/src/vectorstores/tests/redis.test.ts
This change is introducing a `createIndexOptions` config object that accepts the available options for [`ft.create`](https://redis.io/commands/ft.create/). 
I copied the [corresponding interface/type/enum](https://github.com/redis/node-redis/blob/294cbf8367295ac81cbe51ce2932493ab80493f1/packages/search/lib/commands/CREATE.ts#L4) from node-redis as they aren't exported.
Fixes #1488
=> feat(redis vectorstore): add options to redis index creation

langchain/src/agents/mrkl/outputParser.test.ts, langchain/src/agents/mrkl/outputParser.ts, langchain/src/agents/tests/mrkl_agent_output_parser.test.ts
Sometimes the LLM won't put spaces between key and value, which causes an error with the current regex. With the update, it works.
=> Loosen outputParser regex to allow lack of space

test-exports-cf/package.json, test-exports-cf/src/index.ts
=> Switch to `wrangler deploy` because `wrangler publish` is deprecated.

package.json
The `docker-ci-entrypoint.sh` script that runs inside all export containers contains a `yarn build`, so we don't need the CI `yarn build` to build them too.
If you'd prefer `yarn build` to build everything, I can instead make CI use a different build command — perhaps `yarn build:ci`?
=> `test-exports-*` are built in docker, don't build them globally too.

.github/workflows/ci.yml
If another push to the same PR or branch happens while this workflow is still running, cancel the earlier run in favor of the next run.
There's no point in testing an outdated version of the code. GitHub only allows a limited number of job runners to be active at the same time, so it's better to cancel pointless jobs early so that more useful jobs can run sooner.
=> Use concurrency groups to cancel pointless workflows early.

.github/workflows/ci.yml
Vercel is already building the docs, so we don't need to do it too:
- Don't run `yarn build` as a separate step, since that only builds docs, examples, and langchain — and the latter two are already tested in unit tests.
- Skip the CI workflow if *only* docs were changed: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
=> Remove docs build since Vercel is doing it, and don't run code tests on docs-only changes.

docs/extras/modules/data_connection/text_embedding/integrations/ollama.mdx, langchain/.gitignore, langchain/package.json, langchain/scripts/create-entrypoints.js, langchain/src/embeddings/ollama.ts, langchain/src/embeddings/tests/ollama.int.test.ts, langchain/src/load/import_map.ts, langchain/tsconfig.json
Based on the recent [PR](https://github.com/langchain-ai/langchain/pull/10124) by herrjemand in the Langchain python repository I have implemented a class for embeddings using Ollama.
I have only added a little bit of documentation and two simple test cases. This PR might very well not be production ready yet, feedback is much appreciated.
Current problems I see with the implementation:
1. The default optional constructor params "maxConcurrency" and "maxRetries" have to exist in order to extend the base Embeddings class, but are unused by the OllamaEmbeddings class.
2. In order to be consistent with the llms/ollama and chatModels/ollama classes, the api request params are supplied in camelCase ("useMMap") and are then converted to the snake_case format used by the ollama API ("use_mmap"). …
=> Add Ollama embeddings support

docs/extras/modules/data_connection/vectorstores/integrations/chroma.mdx
You must enter the cloned folder before launching `docker-compose` command.
=> Fix chroma documentation

examples/src/indexes/vector_stores/opensearch/opensearch.ts, langchain/src/vectorstores/opensearch.ts
**Description**:
This PR introduces an enhancement to the `addVectors` method in our OpenSearch module. The primary change is the inclusion of an optional `ids` parameter, which allows users to provide custom IDs for the documents they're adding to the OpenSearch index.
**Key Changes**:
- Added an optional parameter `options` to the `addVectors` function, which can accept a list of custom document IDs.
- If no custom IDs are provided, the method defaults to generating UUIDs, ensuring backward compatibility.
- Updated the `operations` construction logic to accommodate either custom or default UUID-based IDs.
This enhancement provides more flexibility to users who may have specific ID structures in their systems and want to retain them in the OpenSearch index.
Please review the changes and …
=> feat(vectorstore): Add Custom IDs Option param to OpenSearch addVectors Method

examples/src/models/llm/bedrock.ts, langchain/src/llms/bedrock.ts, langchain/src/llms/tests/bedrock.int.test.ts
Similar to python variant, enable ability to override the endpoint url to support different preview endpoints of bedrock service.
Unlike the Python LangChain Bedrock integration, the TypeScript implementation does not support overriding the **endpoint_url** which is still necessary for some preview access configurations.
https://github.com/langchain-ai/langchain/blob/eaf916f99989a31c398230f012931e97c400cf6e/libs/langchain/langchain/llms/bedrock.py#L74
=> feat(llms/bedrock): support custom bedrock endpoint url

langchain/src/llms/openai.ts, langchain/src/llms/tests/openai.int.test.ts
This PR fixes the issue where versioned `gpt-3.5-turbo-instruct` models, like `gpt-3.5-turbo-instruct-0914` were treated as Chat Models, throwing a fatal error and not allowing this model to be used.
Fixes #2669 
My twitter handle: https://twitter.com/getcreatr :)
Thank you!
=> Account for versioned instruct models

langchain/src/chat_models/ollama.ts, langchain/src/chat_models/tests/chatollama.int.test.ts, langchain/src/llms/ollama.ts, langchain/src/llms/tests/ollama.int.test.ts
Ollama was not using any callbacks when called through it's _call method. Now it just uses it's internal method _streamResponseChunks that does use those callbacks.
Fixes #2671
=> fix: ollama not using callbacks

langchain/src/llms/llama_cpp.ts, langchain/src/llms/tests/llama_cpp.int.test.ts
After a few responses, the system prompt starts to be returned at the end of each response. It is then duplicated with each subsequent response. The underlying LlamaContext is mutated in place which leads to differences in behavior within the LlamaChatSession when it is newly created for each new prompt. Instead of creating a new session for each prompt, create it once within the constructor.
This appears to fix the underlying issue for me with limited testing. However, I am not super familiar with this library and unsure if it is necessary to have a 1:1 mapping between context and session objects or if a 1:* should work as is currently implemented.
Fixes https://github.com/langchain-ai/langchainjs/issues/2561
=> Do not recreate LlamaChatSession on every prompt

langchain/src/agents/executor.ts, langchain/src/schema/output_parser.ts
Inspired by the same OutputParserException in python library, used the [LangChain Python to JS translator](https://langchain-translator.vercel.app/) to translate some code, that was pretty cool. This also keeps the existing ordering of the constructor params to avoid changes to existing code using the constructor.
Python library code:
- Output parser: https://github.com/langchain-ai/langchain/blob/96023f94d9db48b4ca3d6849711f030010c2454b/libs/langchain/langchain/schema/output_parser.py#L326-L362
- Agent executor: https://github.com/langchain-ai/langchain/blob/1bc3244db92faef6ac7961f935a6b45b6df7eab3/libs/langchain/langchain/agents/agent.py#L932-L937
=> Improve OutputParserException handling by adding observation and sendToLLM

langchain/src/schema/runnable/base.ts
The Python version invokes each of the `RunnableMap` branch in parallel, whereas the JS version invokes each branch sequentially, which this PR addresses.
Side note: this does mean that `execution_order` will be different, but doesn't seem to cause regressions in tests afaict.
=> Make sure RunnableMap invokes child sequences in parallel

langchain/src/document_loaders/tests/example_data/notion_api/notion_database_response.json, langchain/src/document_loaders/tests/example_data/notion_api/notion_page_response.json, langchain/src/document_loaders/tests/notionapi.int.test.ts, langchain/src/document_loaders/tests/notionapi.test.ts, langchain/src/document_loaders/web/notionapi.ts
- Fixes a bug with a page title properties being renamed in the database and getTitle failing to get the new name. 
- Adds unit tests that allow annotated titles for pages and databases
=> Fixes a bug in the NotionAPI loader for getTitle

langchain/src/vectorstores/supabase.ts
Currently, it only accepts an array of strings, but in our Supabase database, we can have a column of IDs as integers.
like your function [example](https://js.langchain.com/docs/modules/data_connection/vectorstores/integrations/supabase#create-a-table-and-search-function-in-your-database):
```sql
create table embeddings (
id bigserial primary key,
content text, -- corresponds to Document.pageContent
metadata jsonb, -- corresponds to Document.metadata
embedding vector(1536) -- 1536 works for OpenAI embeddings, change if needed
);
```
=> fix: supabase vector store delete params ids typo

langchain/src/tests/text_splitter.test.ts, langchain/src/text_splitter.ts
- In case of text splitting with the overlap option, _metadata.loc.lines_ can be wrong if the overlaped text contain line separator.
- In case first chunk start with a new line
Added tests  _A first chunked with overlap_  & _Chunks with overlap on multiple lines_ was failing before the fix.
Value of **_loc.lines.to_** was grater than the number of line of the content ....
=> Fix: Text splitter invalid loc.lines in case of chunk overlap

langchain/src/prompts/chat.ts, langchain/src/prompts/tests/chat.test.ts
Currently js has a bug, where if you pipe a ChatPromptTemplate into an LLM, it uses the raw json serialization as input to the model :(
- Python: https://smith.langchain.com/public/a2eb85bf-99bf-44c9-a4fb-b090b761577c/r/6935e177-ff27-4d28-8d19-3b3d0d88ffe2
- Javascript: https://smith.langchain.com/public/706de8fb-84db-4435-a1ab-19c7c9202cc5/r/03a0032e-ff17-4d46-81a0-c59cd514e871
=> Fix ChatPrompts with LLMs

langchain/src/stores/message/dynamodb.ts, langchain/tsconfig.json
New Interface:
```typescript
export class DynamoDBChatMessageHistory extends BaseListChatMessageHistory {
...
private dynamoKey: Record<string, AttributeValue> = {};
constructor({
tableName,
sessionId,
partitionKey,
sortKey,
messageAttributeName,
config,
key={},   // <=== added this key attribute and tried to leave partitionKey and sortKey alone for backwards compatability
}: DynamoDBChatMessageHistoryFields) {
super();
``` 
This allows conversation items in dynamo to look like this:
```JSON
{
"pk": "conversation#1111-1111-1111",
"sk": "1000#workspace#channel",
"messageAttributes": [
{
"text": "whats 5 * 6?",
"type": "human"
},
{
"text": "5 * 6 equals 30.",
"type": "ai"
}
]
}
```
=> Single table designs in dynamo require maximum flexibility. Adding key attribute to DynamoDB Chat History args.

langchain/src/chat_models/tests/chatbedrock.int.test.ts, langchain/src/util/bedrock.ts
The Bedrock chat client was expecting the wrong response object for the Titan express model. This updates it to the correct response body object. During my testing, I could not get Bedrock to respond with more than one result in the response body.
*Fun fact*: Titan Express refers to itself as `Kyoko`.
Fixes #2812
=> Fix for Bedrock `amazon.titan-text-express-v1`

langchain/src/vectorstores/prisma.ts
I would like to be able to access the PrismaSqlFilter type so I can create a function like this: 
```
export const initVectorStore = (filter: PrismaSqlFilter<Chunk>) => {
env.localModelPath = __dirname + "/../../models"
//@ts-ignore
env.allowRemoteModels = false
const vectorStore = PrismaVectorStore.withModel<Chunk>(prisma).create(
new HuggingFaceTransformersEmbeddings({
modelName: "BAAI/bge-large-en-v1.5",
}),
{
prisma: Prisma,
tableName: "Chunk",
vectorColumnName: "vector",
columns: {
id: PrismaVectorStore.IdColumn,
content: PrismaVectorStore.ContentColumn,
},
filter
},
)
return vectorStore
}
```
=> Expose PrismaSqlFilter type

langchain/src/util/stream.ts
This PR is to address the issue our team identified while we were integrating `BaseLLM` with our own AI to enable the streaming capability. The issue we faced was, after we implemented `*_streamResponseChunks` generator function, we noticed it did not terminated in many cases.
After investigation, we found out that our response stream would end by yielding empty string, and this behavior, paired with `IterableReadableStream`'s pull method, which only enqueue's value if it is not nullish, will hang the generator. Hence preventing it from terminating successfully.
=> fix(stream): Update "IterableReadableStream" pull method to enqueue nullish data (e.g. empty string)

examples/src/document_loaders/notionapi.ts, langchain/src/document_loaders/tests/notionapi.int.test.ts, langchain/src/document_loaders/web/notionapi.ts
Fixes #2807
Notion databases are often used as the data stored in the page properties, with an empty page. This means a user may expect a similarity search on the page properties. I have enabled an option where a user can prepend the page properties as a frontmatter header to enable similarity search.
It was bought to my attention that the preferred behaviour for the Document class is to not create documents with empty `pageContents`. 
This PR addresses both of these issues.
- Adding an option to prepend page properties as a front matter header
- Ensures would be empty `pageContents` pages do not create Documents
It also
- Adds integration tests for empty pageContents not creating a Document
- Adds integration tests for propertiesAsHeader option
- Update the database example to include …
=> NotionAPILoader: Fix for #2807 and add `propertiesAsHeader` option

langchain/src/chains/graph_qa/tests/cypher.int.test.ts, langchain/src/graphs/neo4j_graph.ts, langchain/src/graphs/tests/neo4j_graph.int.test.ts
So the LLMs can interpret them correctly.
Added to test.
Also updated some of the code to use best practices.
---
About me:
Twitter handle: @oskarhane
=> Fix: Convert Neo4j Integers to strings in the result sets

docs/extras/modules/data_connection/vectorstores/integrations/mongodb_atlas.mdx, langchain/src/vectorstores/mongodb_atlas.ts, langchain/src/vectorstores/tests/mongodb_atlas.int.test.ts
This PR is the JS equivalent of https://github.com/langchain-ai/langchain/pull/11139.
This PR add support for the $vectorSearch stage in the MongoDB Atlas VectorStore.  $vectorSearch was announced at MongoDB .local London.
Some notes:
- We don't have access to Cohere, so I changed the existing integration tests to use OpenAI.  I'm happy to change them back if needed but I'll need help getting access to Cohere.  The tests pass locally for me but I left them skipped because they're skipped in `main`.
- I made a few cleanups to the MongoDB atlas implementation and isolated them in [this](https://github.com/langchain-ai/langchainjs/commit/7c4a53b86baf0ca31528b6a5ea50b9f1ed55e2a3) commit.  Happy to revert.
Same as with the Python implementation, this is a breaking change.
=> Add support for MongoDB Atlas $vectorSearch vector search

langchain/src/retrievers/self_query/base.ts, langchain/src/retrievers/self_query/functional.ts, langchain/src/retrievers/self_query/index.ts, langchain/src/retrievers/self_query/tests/pinecone_self_query.int.test.ts
With this change we add a flag to enforce the searchParams as default filter to send to a vector db.
the usage will be:
` const selfQueryRetriever = await SelfQueryRetriever.fromLLM({
llm,
vectorStore,
documentContents,
attributeInfo,
structuredQueryTranslator: new PineconeTranslator(),
searchParams: {
filter: {
type: "movie",
},
mergeFiltersOperator: "and",
forceDefaultFilter: true // the filter "type": "movie" will be a default filter for all queries.
},
});`
twitter handle: @valdozzz1
Fixes #2875
=> added force default filter option to mergeFilters

langchain/src/prompts/chat.ts, langchain/src/prompts/tests/chat.test.ts, langchain/src/schema/index.ts
Closes #2871 
Throw when input passed to `MessagesPlaceholder.formatMessages` is not of correct type
=> Fix: validate input or throw when using MessagesPlaceholder

langchain/src/embeddings/bedrock.ts, langchain/src/embeddings/tests/bedrock.int.test.ts
Closes #2905 
Batch requests for aws bedrock embeddings
=> fix: batch embedding queries, fix get client in tests

docs/extras/modules/data_connection/vectorstores/integrations/cassandra.mdx, langchain/src/vectorstores/cassandra.ts, langchain/src/vectorstores/tests/cassandra.int.test.ts
- Improve Cassandra vector store documentation
=> Improve Cassandra vector store docs

.devcontainer/README.md, .github/contributing/INTEGRATIONS.md, .github/contributing/integrations/DOCUMENT_LOADERS.md, .github/contributing/integrations/LLMS.md, .github/contributing/integrations/MEMORY.md, .github/contributing/integrations/MESSAGE_STORES.md, .github/contributing/integrations/TOOLS.md, .github/contributing/integrations/VECTOR_STORES.md, .github/pull_request_template.md, CONTRIBUTING.md, README.md, docs/docs_skeleton/docs/community.md, docs/docs_skeleton/docusaurus.config.js, docs/extras/modules/data_connection/vectorstores/integrations/opensearch.md, docs/extras/use_cases/autonomous_agents/sales_gpt.mdx, docs/snippets/get_started/introduction.mdx, docs/snippets/modules/model_io/models/chat/how_to/streaming.mdx, docs/snippets/modules/model_io/models/llms/how_to/streaming_llm.mdx, examples/src/document_loaders/github.ts, examples/src/document_loaders/github_ignore_paths.ts, examples/src/document_loaders/github_submodules.ts, langchain/README.md, langchain/src/document_loaders/tests/github.int.test.ts, langchain/src/document_loaders/tests/github.test.ts, langchain/src/prompts/prompt.ts, langchain/src/util/axios-fetch-adapter.js, langchain/src/util/env.ts, langchain/src/util/event-source-parse.ts
The repo is now part of the `langchain-ai` GitHub org and not under the `hwchase17` account.
=> Update repo path to point to `langchain-ai` GitHub org.

examples/src/models/llm/llm_streaming_stream_method.ts
Removes unneeded comments that can cause confusion
- `.stream()` works without the need to add `streaming: true` to the LLM constructor
- Removes reference to `handleLLMNewToken` since `handleLLMNewToken` does not exist within [this example](https://js.langchain.com/docs/modules/model_io/models/llms/how_to/streaming_llm#using-stream)
https://twitter.com/cjtantay
=> fix: update llm_streaming_stream_method.ts doc

langchain/src/agents/chat/index.ts
This simple change allows users to fully overwrite the prompts when creating a chat agent, and optimize them for their use case. The change makes the agent code much more generally useful. Previously, they could overwrite everything except for FORMAT_INSTRUCTIONS, which is essential to customization.
=> Make format_instructions an optional argument in chat agent

.github/workflows/ci.yml, .github/workflows/test-exports.yml
This is about 6min faster than before: [~13min](https://github.com/langchain-ai/langchainjs/actions/runs/6550835570/job/17790748230) -> ~7min now. The issue previously was that we were running 7 CPU- and network-intensive docker containers on the same tiny 2-core GitHub runner. This PR splits each container on its own runner, which means they all run in parallel.
=> Run exports tests in parallel on GitHub CI.

examples/src/models/llm/llm_cancellation.ts
I have corrected a typo in the example for the models/llm/llm_cancellation
=> Fixed typo in documentation

langchain/src/storage/ioredis.ts, langchain/src/storage/tests/ioredis.int.test.ts, langchain/src/storage/tests/vercel_kv.int.test.ts, langchain/src/storage/vercel_kv.ts
When yielding keys, the `.yieldKeys(...)` method on `vercel_kv` & `ioredis` automatically checks if the prefix ends with `*`, and if not it applies it to the end.
Refactored tests a little to automatically clear all keys/disconnect
=> fix: wildcard suffix for yielding keys

docs/docs/expression_language/cookbook/_category_.yml, docs/docs/expression_language/how_to/_category_.yml, docs/docs/expression_language/interface.mdx, docs/docs/expression_language/why.mdx
Fixed the ordering of the LCEL sub menu which was not in sync with the python docs and not correctly ordered.
Also added input type and output type table in the interface page of better readability.
=> Fixed order of LCEL menu and added tables in interface page

langchain/src/util/stream.ts
Fixes #3001 IterableReadableStream.fromReadableStream didn't releaseLock source stream's reader
const reader = stream.getReader();
this reader can't be releaseLock!!! Sometimes, The target IterableReadableStream is cancel, but the source ReadableStream is continue work, e.g the websocket stream. So we should release the reader.
=> IterableReadableStream.fromReadableStream reader releaseLock

.github/workflows/docs-preview.yml, .github/workflows/docs-prod.yml
Two improvements:
- Ensure that shell command arguments that use env var expansion are always quoted if they are intended to be one argument. Otherwise they may expand to multiple arguments, and become a vector for shell injection attacks.
- Avoid using GitHub Actions templating (`${{ ... }}`) in shell commands, and use env vars instead. Such templating cannot be escaped against injection attacks since it runs before the shell sees the command, so it's always better to stick the templated data in an env var and use shell expansion instead.
I don't believe the current workflows were exploitable as currently written, but security is hard and it's always better to be safe than sorry.
=> Ensure shell expansions are quoted in docs workflows.

.github/workflows/ci.yml, .github/workflows/docs-preview.yml, .github/workflows/docs-prod.yml, .github/workflows/format.yml, .github/workflows/integration.yml
No major breaking changes, just good to keep up with major versions before we have to jump too many at a time which becomes problematic.
=> Upgrade `actions/checkout` to v4 in all workflows.

docs/docs/modules/data_connection/document_loaders/integrations/web_loaders/pdf.mdx, langchain/src/document_loaders/tests/webpdf.int.test.ts, langchain/src/document_loaders/web/pdf.ts
The node version of the `PDFLoader` allows for passing in a custom `pdfjs` build. Let's add that for the `WebPDFLoader` as well.
This allows fixing of errors like `Error: No "GlobalWorkerOptions.workerSrc" specified.` as issued here for example https://github.com/langchain-ai/langchainjs/issues/1296. It's a pretty common error when working with `pdfjs` -> https://github.com/mozilla/pdf.js/issues/10478#issuecomment-518673665
=> WebPDFLoader: allow usage of custom pdfjs build

langchain/src/tools/serpapi.ts
This PR fix a broken link on SerpApi documentation.
We moved from this /places-results this link to https://serpapi.com/local-results.
Thanks!
=> Update broken link on SerpApi documentation

langchain/src/callbacks/manager.ts
Fixes # LANGCHAIN_VERBOSE=false does not turn off verbose logging.
=> fix: LANGCHAIN_VERBOSE=false does not turn off verbose logging.

docs/docs/modules/model_io/prompts/example_selectors/similarity.mdx, examples/src/prompts/semantic_similarity_example_selector_custom_retriever.ts, langchain/src/prompts/selectors/SemanticSimilarityExampleSelector.ts, langchain/src/prompts/tests/selectors.test.ts
This will allow e.g. MMR searches in the selector.
@nfcampos can you take a quick look?
TODO: docs
=> Allow vectorstore retrievers in SemanticSimilarityExampleSelector.ts

langchain/src/vectorstores/milvus.ts
Milvus vector store integration should calculate required length for new collection's `langchain_text` field in bytes instead of characters. Otherwise inserting text containing multibyte characters fails due to actual data not being able to fit into newly created collection's `langchain_text` field.
Example:
```
import { Milvus } from "langchain/vectorstores/milvus";
import { OpenAIEmbeddings } from "langchain/embeddings/openai";
// Env variables OPENAI_API_KEY and MILVUS_URL must be set
await Milvus.fromTexts(
["München"],
[{ id: 1 }],
new OpenAIEmbeddings(),
{ collectionName: 'milvus_insert_test' }
);
```
... results in ...
```
Error: Error inserting data: {"succ_index":[],"err_index":[0],"status":{"error_code":"IllegalArgument","reason":"the length (8) of 0th string exceeds max length …
```
=> fix: calculate Milvus textlength in bytes

docs/docs/modules/data_connection/text_embedding/integrations/ollama.mdx
The example in this [the docs](https://js.langchain.com/docs/modules/data_connection/text_embedding/integrations/ollama) for `OllamaEmbeddings` shows `numThreads: 6` for `OllamaEmbeddings` but it should actually accept a `numThread` key, not `numThreads`.
```ts
import { OllamaEmbeddings } from "langchain/embeddings/ollama";
const embeddings = new OllamaEmbeddings({
model: "llama2", // default value
baseUrl: "http://localhost:11434", // default value
requestOptions: {
useMMap: true,
numThreads: 6, // <---- Should be `numThread`
numGpu: 1,
},
});
const documents = ["Hello World!", "Bye Bye"];
const documentEmbeddings = await embeddings.embedDocuments(documents);
```
The link to the [OllamaEmbeddings API source is here](https://github.com/langchain-ai/langchainjs/blob/b80dc8f5d8aaad857c72aade …
=> Update ollama.mdx - `numThreads` to `numThread`

docs/docs/modules/data_connection/text_embedding/integrations/ollama.mdx, langchain/src/embeddings/ollama.ts
[Link to discussion](https://github.com/langchain-ai/langchainjs/pull/3083#issuecomment-1783917599)
1. Updates `numThreads` to `numThread` in the docs to use the API correctly [ref](https://github.com/langchain-ai/langchainjs/blob/b80dc8f5d8aaad857c72aade9053f2b355e10970/langchain/src/embeddings/ollama.ts#L68C7-L68C7)
2. Adds a function in the `OllamaEmbeddings` class to fetch `127.0.0.1` if user puts `localhost` to work out of the box with node's fetch since it default resolves to ipv6 (`::1`) which Ollama server isn't listening to. Now it works out of the box. Issue is related to node's native fetch command not working when fetching `localhost` that isn't listening on the ipv6 localhost address but the ipv4 localhost address of `127.0.0.1` as per …
=> Ollama embedding - Changed `localhost` to `127.0.0.1`

langchain/src/storage/convex.ts, langchain/src/stores/message/convex.ts, langchain/src/vectorstores/convex.ts
Forgot to update these before merging. Now they will show up in the compiled .d.ts files (where jump to definition will lead people).
=> Convex: Fix defaults doc comments

docs/docs/expression_language/interface.mdx
When describing the [common interface](https://js.langchain.com/docs/expression_language/interface), there is a typo in the table that explains the different output types. 
This PR fixes the typo in the header of the table.
=> Fix typo in output types table

docs/docs/expression_language/how_to/cancellation.mdx, examples/src/guides/expression_language/how_to_cancellation.ts
I added documentation for cancelling LCEL/RunnableSequence invocations. @jacoblee93 mentioned that this was a documentation oversight!
Fixes # (issue) https://github.com/langchain-ai/langchainjs/issues/3096
------
@ shoutouts (I don't use twitter/x very much):
https://twitter.com/jon_will_do_it / https://linkedin/com/in/willisjon / https://github.com/jondwillis
=> add an example and how to documentation page for cancelling LCEL chains

langchain/src/stores/message/convex.ts
Updated the convex index type for ConvexChatMessageHistory as the basic ChatMessage history docs use a normal non-vector index for the session id.  I've included a [link](https://js.langchain.com/docs/integrations/chat_memory/convex) to the docs where the example chat memory setup is done.
=> fix: updated convex chat message history indexes to match documentation

langchain/src/chat_models/bedrock/web.ts
Should match: https://github.com/langchain-ai/langchainjs/blob/c2169e9facf5953cd3eca92f529107eb5cd392c8/langchain/src/llms/bedrock/web.ts#L99
Otherwise, this error is thrown:
```
✘ [ERROR] Could not resolve "@aws-sdk/credential-provider-node"
```
=> Fix invalid usage of defaultProvider in Bedrock web.

langchain/src/vectorstores/pinecone.ts, langchain/src/vectorstores/tests/pinecone.int.test.ts
This PR adds pass-through ability to delete records from Pinecone using metadata filtering which was [officially supported](https://sdk.pinecone.io/typescript/#md:delete-many-by-metadata-filter) in the v1 release of Pinecone's JS client.
This gives users the ability to delete vectors using matching metadata filters which can be more flexible than deleting by ID.
=> feat(pinecone): add support for delete by metadata filter

langchain/src/chat_models/openai.ts
This addresses a delta chunk issue that happens when you use a custom baseURL on the openai chat model. Some models like llama 2 on openrouter may have a empty delta and result in a undefined error.
Example error:
```
Cannot read properties of undefined (reading 'role')",
"error.stack": "TypeError: Cannot read properties of undefined (reading 'role')\n    at _convertDeltaToMessageChunk (/home/ubuntu/node_modules/langchain/dist/chat_models/openai.cjs:72:24)\n    at ChatOpenAI._streamResponseChunks (/home/ubuntu/node_modules/langchain/dist/chat_models/openai.cjs:409:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ChatOpenAI._streamIterator (/home/ubuntu/node_modules/langchain/dist/chat_models/base.cjs:77:34)\n    at async …
```
=> Fix delta role error when using custom LLM

langchain/src/util/openapi.ts
=> Use replaceAll instead of replace when generating operationid.

langchain/src/chat_models/bedrock/web.ts, langchain/src/chat_models/tests/chatbedrock.int.test.ts, langchain/src/llms/bedrock/web.ts, langchain/src/llms/tests/bedrock.int.test.ts, langchain/src/util/bedrock.ts
This change will add in meta support for models in BedrockChat. Currently this is only the 13B parameter Llama2 model. So long as the model payload does not change, this will also work if the 70B model gets added.
The BedrockChat test suite has also been updated with convenient methods to more simply write tests for various new models.
Fixes #3257
=> Meta Llama2 support for BedrockChat

langchain/package.json
CC @bracesproul removed API refs docs build from build in `langchain` workspace - that should happen somewhere else
=> Release 0.0.191

langchain/package.json, langchain/src/chat_models/tests/chatanthropic.int.test.ts, package.json, yarn.lock
=> Bump Anthropic + OpenAI versions

docs/core_docs/docs/integrations/vectorstores/prisma.mdx, examples/src/indexes/vector_stores/prisma_vectorstore/prisma.ts, langchain/src/vectorstores/prisma.ts
Add support for `IN` operator in `PrismaVectorStore` class to allow filter on multiple possible values
```
PrismaVectorStore.withModel(this.databaseService).create(
new OpenAIEmbeddings(),
{
prisma: Prisma,
tableName: 'Document',
vectorColumnName: 'vector',
columns: {
id: PrismaVectorStore.IdColumn,
content: PrismaVectorStore.ContentColumn,
},
filter: {
foreignKeyId: {
in: ['<id1>', '<id2>', ...],
},
},
},
);
```
The introduced code uses a `switch` instruction to make it easy to add other operators in the future.
Fixes #3301
=> Add PrismaVectorStore filter IN operator

langchain/src/util/googlevertexai-connection.ts
Remove console.log from googlevertexai-connection.ts
Problem:
- In case of invalid address, an error is logged exposing authentication token  in logs.
- this log should be handled by langchain callback mechanism.
=> Remove console.log from googlevertexai-connection.ts

langchain/src/vectorstores/opensearch.ts
Hi,
solves #3297 
In the future it can be extended further to implement other [term-level queries](https://opensearch.org/docs/latest/query-dsl/term/index/), but for now `term` and `terms` is sufficient enough, as they are imho the most used.
Since I am primarily working with OpenSearch in my workplace, I'll gladly add those features when the need arises.
=> feat: Added support of terms filter in OpenSearch vector store

langchain/src/schema/index.ts
The fields are mutually exclusive. This represents this in its type.
This will help with both avoiding wrong combinations as well as reduces unnecessary undefined checks.
=> Improve MessageContent type

docs/core_docs/docs/integrations/vectorstores/prisma.mdx, langchain/src/vectorstores/prisma.ts
Add support for missing SQL operators in `PrismaVectorStore` class filter:
* `isNull`
* `isNotNull`
* `like`
Fixes #3317
=> Add missing PrismaVectorStore filter operators

examples/package.json, langchain/package.json, yarn.lock
Closes #3340
Using a nextjs app create a new api route `api/test/route.ts`
Paste this code inside:
```typescript
import { DynamicStructuredTool, formatToOpenAITool } from "langchain/tools";
import { z } from "zod";
export const runtime = "edge";
export async function GET(request: Request) {
const imageTool = new DynamicStructuredTool({
name: "get_current_weather",
description: "Get the current weather in a given location",
func: async ({ location }) => {
if (location.toLowerCase().includes("tokyo")) {
return JSON.stringify({ location, temperature: "10", unit: "celsius" });
} else if (location.toLowerCase().includes("san francisco")) {
return JSON.stringify({
location,
temperature: "72",
unit: "fahrenheit",
});
} else {
return JSON.stringify({ location, temperature: "22", unit: "celsius" …
```
=> Pin zod-to-json-schema version

langchain/src/agents/openai/index.ts, langchain/src/agents/tests/runnable.int.test.ts
Handles the case when an `OpenAIAgent` is called with `.plan` on an `llmChain` instantiated with a `Runnable` instead of a regular chat model. Currently, this case is not handled and results in an error: `TypeError: llm.predictMessages is not a function`. This resolves the bug by checking if it's runnable and appropriately calling `runnable.invoke`
Fixes #3344
=> Update OpenAIAgent to support Runnable models

docs/core_docs/docs/integrations/document_loaders/web_loaders/github.mdx, examples/src/document_loaders/github_stream.ts, langchain/src/document_loaders/tests/github.int.test.ts, langchain/src/document_loaders/web/github.ts
Allow to stream Github files with `GithubRepoLoader`, using generators. 
Ths is useful on larges repositories to process them in a memory efficient manner.
Usage:
```typescript
const loader = new GithubRepoLoader(
"https://github.com/langchain-ai/langchainjs",
{
branch: "main",
recursive: false,
unknown: "warn",
maxConcurrency: 3,
}
);
const docs = [];
for await (const doc of loader.loadAsStream()) {
docs.push(doc);
}
console.log({ docs });
```
Fixes #3331
=> Allow to stream files with `GithubRepoLoader`

langchain/src/vectorstores/pgvector.ts, langchain/src/vectorstores/tests/pgvector.int.test.ts
This PR adds support for collection names in the PG Vector store integration that currently [already exists](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/pgvector.py#L113) in the python version of langchain. Collections add a nice way to logically group document embeddings in the vector store. My specific use case is around privilege preservation of certain types of documents. I'm creating and loading my embeddings table from the python version, but I'd like to be able to query it using the javascript version.
The gist of it is there's another table added and a foreign key referencing the uuid from the collections table. My goal is to make this a seamless addition by not causing any breaking changes to anyone not already using collections. So …
=> feat: add support for collection name in PG Vector

langchain/src/llms/hf.ts
IncludeCredentials parameter added to HuggingFaceInference to address the issue "The 'credentials' field on 'RequestInitializerDict' is not implemented." when using HuggingFace's HfInference on Cloudflare Workers.
=> fix: Add HuggingFaceInference includeCredentials param

langchain/src/graphs/neo4j_graph.ts, langchain/src/graphs/tests/neo4j_graph.int.test.ts
waiting for review from @oskarhane
=> Use less tokens to describe a Neo4j graph schema

docs/core_docs/docs/integrations/vectorstores/weaviate.mdx, examples/src/indexes/vector_stores/weaviate_mmr.ts, langchain/src/vectorstores/weaviate.ts
Following the examples of other vector stores.
=> integration[patch]: feat: implement max marginal relevance search for Weaviate vector store

langchain/src/vectorstores/weaviate.ts
Type is undefined but before this PR it was required which doesn't make sense.
Was also causing `examples/` build to fail with this type error
=> Make undefined input optional

langchain/src/vectorstores/xata.ts
This pull request fixes an issue where null or undefined records were causing an error in the Xata similarity search method. The method now checks if the records exist before processing them, and returns an empty array if they are null or undefined. This prevents the error from occurring and ensures the method can handle all types of records properly.
Fixes #3418
=> Fix null or undefined records causing error in Xata similarity search method

docs/core_docs/docs/integrations/chat/llama_cpp.mdx, examples/src/models/chat/integration_llama_cpp_stream.ts, examples/src/models/chat/integration_llama_cpp_stream_multi.ts, langchain/src/chat_models/llama_cpp.ts, langchain/src/chat_models/tests/chatllama_cpp.int.test.ts
The chat module for `llama_cpp` now handles multiple messages or a single string, see update documents.
=> langchain[minor]: Added multi-message streaming to llama_cpp

langchain-core/src/runnables/history.ts, langchain-core/src/runnables/tests/runnable_history.test.ts
=> core[tests]: Better tests for runnable history

docs/api_refs/package.json, examples/package.json, langchain-core/package.json, langchain/package.json, langchain/src/agents/tests/structured_output_runnables.int.test.ts, libs/create-langchain-integration/package.json, libs/langchain-anthropic/package.json, libs/langchain-openai/package.json, package.json, yarn.lock
Upgrades typescript to version ~5.1.6
The new features of typescript allows some better type inference ([unblocks this pr](https://github.com/langchain-ai/langchainjs/pull/3517))
Note: This limits the upgrade to 5.1, as in 5.2 there is a change that affects hybrid modules and will need more consideration.
=> chore: Upgrade Typescript to 5.1

langchain-core/package.json, yarn.lock
caret in ^0.0.x doesn't do anything, it matches only the exact specified version, whereas tilde ~0.0.x matches that and all 0.0.x versions up to 0.1.0
https://nodesource.com/blog/semver-tilde-and-caret/#majorandminorzero00z00z
Currently it results in two versions of `langsmith` to be installed in `node_modules` together with `langchain` (`0.0.48` and `0.0.49`), as `langchain` permits `~0.0.48` for `langsmith`, which installs the latest available `0.0.x` version, and `@langchain/core` allows only `0.0.48` with `^0.0.48`.
`yarn why langsmith`
=> core[chore]: widen semver range for langsmith

langchain-core/src/load/index.ts, langchain-core/src/runnables/base.ts, langchain-core/src/runnables/index.ts, langchain/src/load/tests/cross_language.int.test.ts, langchain/src/load/tests/load.int.test.ts, langchain/src/load/tests/load.test.ts, langchain/src/schema/runnable/base.ts
=> Use different import maps for core vs main langchain

libs/langchain-google-genai/src/chat_models.ts, libs/langchain-google-genai/src/tests/chat_models.int.test.ts, libs/langchain-google-genai/src/utils.ts
Changes to in google Generative AI chat model.
- Fixed a bug where `stopSequences` not getting sent in the api.
Addition:
- adding `candidateCount` property.
=> bugfixes in google Generative AI chat_model

langchain/src/experimental/openai_assistant/index.ts
Fix invert runId and threadId to match openai.beta.threads.runs.submitToolOutputs arguments
Fixes #3664
=> langchain[patch]: Fix invert runId and threadId

langchain/src/experimental/autogpt/output_parser.ts, langchain/src/experimental/autogpt/tests/output_parser.test.ts
=> experimental[patch]: Improve AutoGPT's output_parser to extract JSON code block

CONTRIBUTING.md
Adds a section in the contributor guide for adding integrations which require optional deps
=> docs[patch]: Add section about req optional dep

langchain-core/src/runnables/base.ts, langchain-core/src/runnables/tests/runnable_interface.test.ts, langchain-core/src/utils/stream.ts
CC @nfcampos @bracesproul 
~Is this actually a good idea?~ Yes, it is a good idea
=> core[patch]: Use an interface for runnables to allow more compatibility between core versions

docs/core_docs/docs/integrations/vectorstores/cassandra.mdx, libs/langchain-community/src/stores/tests/cassandra.int.test.ts, libs/langchain-community/src/vectorstores/cassandra.ts, libs/langchain-community/src/vectorstores/tests/cassandra.int.test.ts
Enhancements:
* Support for index options clause
* Support for multiple values on filter 
Fixes:
* Issue with Cassandra initialization where the table/indexes were not ready before attempting to insert
=> community[patch]: Cassandra init improvements

langchain-core/.gitignore, langchain-core/package.json, langchain-core/scripts/create-entrypoints.js, langchain-core/src/load/import_map.ts, langchain-core/src/utils/chunk_array.ts
Currently, it's defined inside `@langchain/community`, `@langchain/openai`, and `@langchain/mistralai`
Moving it to core will allow for deleting the duplicated code.
I'll put up a PR after core releases this, refactoring the other packages.
=> core[minor]: Move chunk array to core

examples/src/indexes/vector_stores/vectara.ts
Don't have enough context to know why the `summary` element is no longer returned, removed for now. cc @jacoblee93
=> examples[patch]: Fixes type error in vectara example

libs/langchain-community/src/llms/togetherai.ts
The [Together AI API Reference](https://docs.together.ai/reference/inference) states that the `stop` body parameter is supported, but the current implementation does not support this option. So I just added it.
=> Add `stop` option to Together AI

docs/core_docs/docs/expression_language/cookbook/agents.mdx, docs/core_docs/docs/integrations/chat/anthropic.mdx, examples/package.json, examples/src/agents/xml.ts, examples/src/agents/xml_runnable.ts, examples/src/chains/summarization_separate_output_llm.ts, examples/src/guides/evaluation/comparision_evaluator/pairwise_string_custom_llm.ts, examples/src/guides/evaluation/string/configuring_criteria_llm.ts, examples/src/guides/expression_language/cookbook_memory.ts, examples/src/guides/expression_language/cookbook_multiple_chains.ts, examples/src/guides/expression_language/cookbook_tools.ts, examples/src/guides/expression_language/how_to_routing_custom_function.ts, examples/src/guides/expression_language/how_to_routing_runnable_branch.ts, examples/src/guides/expression_language/runnable_maps_basic.ts, examples/src/guides/expression_language/runnable_maps_sequence.ts, examples/src/guides/fallbacks/model.ts, examples/src/memory/cloudflare_d1.ts, examples/src/models/chat/integration_anthropic.ts, examples/src/retrievers/multi_query.ts, examples/src/retrievers/multi_query_custom.ts, examples/src/use_cases/youtube/podcast_summary.ts, libs/langchain-anthropic/README.md, libs/langchain-anthropic/jest.config.cjs, libs/langchain-anthropic/package.json, libs/langchain-anthropic/scripts/jest-setup-after-env.js, libs/langchain-anthropic/src/chat_models.ts, libs/langchain-anthropic/src/tests/chat_models.int.test.ts, yarn.lock
=> Use new Anthropic beta endpoint in new package

langchain-core/src/messages/index.ts, langchain-core/src/messages/tests/base_message.test.ts
Currently, when deserialising, `additional_kwargs` are passed to constructor as `additionalKwargs`
=> Fix deserialisation of additional_kwargs and tool_call_id

langchain-core/src/runnables/base.ts, langchain/src/runnables/tests/runnable_remote.test.ts
=> core[patch]: Pass configurable as config when separating call options

langchain-core/src/callbacks/manager.ts, langchain-core/src/runnables/base.ts, langchain-core/src/runnables/config.ts, langchain-core/src/runnables/history.ts, langchain-core/src/runnables/passthrough.ts, langchain-core/src/runnables/tests/runnable_map.test.ts, langchain-core/src/utils/stream.ts, langchain-core/src/utils/testing/index.ts, langchain/src/runnables/remote.ts
=> core[minor]: Nc/dec26/runnable stream

docs/core_docs/code-block-loader.js, examples/src/chat/memory.ts, libs/langchain-community/src/utils/momento.ts
@jacoblee93 this will fix the issue you're having in #3802 (unless the import paths differ from the original langchain).
Before when imports were always `langchain/path`, the `moduleName` variable would always be the path. Now that the second arg will be `core` if importing from `core` this breaks.
=> docs[patch]: Fix more core imports

libs/langchain-community/src/utils/momento.ts
Patch for the issue:
MomentoChatMessageHistory is not working on the Cloudflare Workers because of the SDK difference #3784
=> fix: use @gomoment/sdk-core instead of @gomoment/sdk for edge server integrations (#3784)

langchain-core/src/output_parsers/list.ts, langchain-core/src/output_parsers/tests/output_parser.test.ts
- Implement streaming for CSV parser
- Implement two new streaming list parsers: Numbered list, Markdown List
=> core[minor]: Streaming List Parsers

docs/core_docs/docs/modules/agents/tools/how_to/_category_.yml, docs/core_docs/docs/modules/agents/tools/how_to/agents_with_vectorstores.mdx
- Fix position and name failure by adding _category_.yml file.
- Do not hide the agents_with_vectorstores.mdx just because there is only one document in the how-to.
=> fix(doc): Sidebar how_to (tools)

examples/src/chains/question_answering_map_reduce.ts
The old example doesn't showcase the utility of loadQAMapReduceChain, and the console.log output is not displayed in the docs. The new example is more relevant and includes a console.log output.
=> docs[patch]: relevant example for map reduce

libs/langchain-community/src/vectorstores/milvus.ts
Currently, the textFieldMaxLength in the dbconfig parameter is lost when using the Milvus.fromDocuments method
```
const vectorStore = await Milvus.fromDocuments(docs, new OpenAIEmbeddings(), {
collectionName: "goldel_escher_bach",
textFieldMaxLength: 1024
});
```
=> fix: textFieldMaxLength parameter missing

libs/langchain-community/src/graphs/neo4j_graph.ts
When a new major version of LangChainJS will be released, please change the code to propagate the error in Neo4jGraph.
Based on https://github.com/langchain-ai/langchainjs/pull/3849
=> Todo: propagate error in Neo4jGraph

libs/langchain-cohere/src/embeddings.ts
Input type is a required parameter when using v3 models. It is ignored for v2 models.
Adding it here satisfies both use cases and avoids a Cohere API rejection when using v3 models.
Fixes #3900
=> Update embedQuery to use inputType

.github/workflows/test-exports.yml, environment_tests/docker-compose.yml, environment_tests/test-exports-tsc/main.ts, environment_tests/test-exports-tsc/package.json, langchain-core/src/language_models/base.ts, langchain/src/evaluation/agents/trajectory.ts, langchain/src/evaluation/base.ts, langchain/src/evaluation/comparison/pairwise.ts, langchain/src/evaluation/criteria/criteria.ts, libs/langchain-community/src/chat_models/llama_cpp.ts, libs/langchain-community/src/llms/llama_cpp.ts, libs/langchain-community/src/llms/togetherai.ts
CC @nfcampos 
Partially address #3793
=> core[patch]: Factor out flaky property

langchain-core/src/utils/@cfworker/json-schema/src/dereference.ts
dereference.ts is taken from an upstream repo https://raw.githubusercontent.com/cfworker/cfworker/main/packages/json-schema/src/dereference.ts
which contains a fix for when self.location.origin is null (which can happen if being used in a nodejs environment). This PR ports over the fix in line with upstream
=> core[patch]: fix: update dereference.ts to match upstream

docs/core_docs/docs/integrations/chat/openai.mdx, examples/src/models/chat/integration_openai_callbacks.ts, examples/src/models/chat/integration_openai_generation_info.ts, langchain-core/src/language_models/base.ts, libs/langchain-openai/package.json, libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/types.ts, libs/langchain-openai/src/utils/azure.ts, libs/langchain-openai/src/utils/openai.ts, yarn.lock
Update `openai` to `^4.24.2` and include logprobs in `generationInfo` in `ChatOpenAI` `_generate`
=> Update openai to ^4.24.2 and include logprobs in `generationInfo`

libs/langchain-community/src/vectorstores/tests/weaviate.test.ts, libs/langchain-community/src/vectorstores/weaviate.ts
Weaviate metadata may be of type array. This means, also empty array values are supported.
The current implementation of the `flattenObjectForWeaviate` function however more or less accidentally omits empty arrays completely, so they never arrive at Weaviate.
If one specifies an empty array as metadata value, then this value should also arrive at Weaviate.
This PR fixes this.
=> allow empty arrays for Weaviate metadata

libs/langchain-community/package.json, libs/langchain-community/src/vectorstores/astradb.ts, libs/langchain-community/src/vectorstores/tests/astradb.int.test.ts, yarn.lock
Upgrades the Astra client to `0.1.3` and adds support for namespaces
=> community[minor]: Upgrade Astra client and add support for namespaces

langchain/src/chains/history_aware_retriever.ts
The in-code documentation has a typo:
```ts
const historyAwareRetrieverChain = await createHistoryAwareRetriever({
llm,
retriever,
rephrasePrompt,
});
const result = await chain.invoke({"input": "...", "chat_history": [] })  // <-- `chain` doesn't exist here.
```
twitter: @aristot_3rd
=> Fix typo in createHistoryAwareRetriever documentation

langchain-core/src/tracers/base.ts
@jacoblee93 are there env-specific gotchas with this? would be helpful to see the full stacktrace whenever there is an error
=> Add stacktrace to tracer errors

langchain-core/.gitignore, langchain-core/package.json, langchain-core/scripts/create-entrypoints.js, langchain-core/src/language_models/base.ts, langchain-core/src/load/import_map.ts, langchain-core/src/utils/function_calling.ts, langchain-core/src/utils/testing/index.ts, langchain-core/src/utils/tests/function_calling.test.ts, yarn.lock
We can look at unpinning/bumping `zod-to-json-schema` (as mentioned in #3983) in a separate PR.
=> core[minor]: Move function calling definitions and utils to core

examples/package.json, langchain-core/package.json, langchain/package.json, langchain/src/agents/structured_chat/index.ts, langchain/src/chains/openai_functions/base.ts, langchain/src/chains/openai_functions/extraction.ts, langchain/src/chains/openai_functions/openapi.ts, langchain/src/chains/openai_functions/structured_output.ts, langchain/src/chains/openai_functions/tagging.ts, langchain/src/chains/openai_functions/tests/openapi.test.ts, langchain/src/document_transformers/openai_functions.ts, langchain/src/experimental/autogpt/prompt_generator.ts, langchain/src/output_parsers/openai_functions.ts, langchain/src/output_parsers/structured.ts, langchain/src/tools/render.ts, libs/langchain-openai/package.json, yarn.lock
The version for zod-to-json-schema was originally pinned to solve #3340. This was reported and fixed in the zod-to-json-schema repo in this issue: https://github.com/StefanTerdell/zod-to-json-schema/issues/94
Based on the likeliness of this being the culprit I've bumped it and Zod for good measure. Also fixed some broken type imports.
All tests pass and it _works on my machine<sup>TM</sup>_
Fixes #4021 and #3983
=> Bump Zod & Zod-to-Json-Schema, fix imports

docs/core_docs/docs/expression_language/how_to/message_history.mdx
Documentation missing a required import statement for the `RunnableWithMessageHistory` module in the code given in the 'Adding message history' section. 
Link to the current live documentation page/section: [Adding message history](https://js.langchain.com/docs/expression_language/how_to/message_history#adding-message-history)
The corresponding code example file already has this required import, but it was missing in the documentation.
Corresponding code example file path: examples/src/guides/expression_language/message_history.ts
=> Updated "Add message history" documentation page for missing module import

docs/core_docs/docs/integrations/vectorstores/pinecone.mdx
Removing the Node-only warnings since [the release of v1.0.1](https://github.com/pinecone-io/pinecone-ts-client/releases/tag/v1.0.1), Pinecone can run on Edge. The Pinecone integration [now uses v2.0.0.](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-pinecone/package.json#L38)
=> docs[patch]: Remove pinecone node-only warnings

langchain/src/smith/config.ts, langchain/src/smith/runner_utils.ts, langchain/src/smith/tests/runner_utils.int.test.ts
We want to auto-populate the traces from evaluators, where possible. This PR enables that
=> langchain[patch]: Add eval source links

langchain/src/smith/runner_utils.ts
Previously, you could get an un-traced run id if `LANGCHAIN_TRACING_V2` was unset. This PR
1. Makes it so the evaluators will predictably be traced within the `runOnDataset` function
2. Sends their races to the `evalators` project (as is done in python)
=> langchain[patch]: Trace in Evaluators Project

docs/core_docs/docs/modules/agents/quick_start.mdx
This import is deprecated.
import { createRetrieverTool } from "langchain/agents/toolkits";
Should be:
import { createRetrieverTool } from "langchain/tools/retriever";
=> Fix Deprecated Import from docs/agents/quick_start.mdx

libs/langchain-cohere/src/chat_models.ts
Hi, I've been using `ChatCohere` and wanted chat memory. Using Cohere's internal chat history works fine with `conversationId`. But I was unable to get it working with Langchain's memory system. I was using `RunnableWithMessageHistory`.
I realize it's in beta, and wanted to help.
So it seems like sending messages with Cohere client does not work properly. I was able to get it working by renaming chat_history and changing the behavior of the history array.
1. rename `chat_history` to `chatHistory`
It seems to only work with "chatHistory", their docstring is a little confusing.
https://github.com/cohere-ai/cohere-typescript/blob/c7d02986e6e4378d431ae19df1bf96b3388f7d1d/src/api/client/requests/ChatStreamRequest.ts#L32
2. Another issue seems to be with using `concat` here which returns a …
=> cohere[patch]: Fix use of CohereChat with RunnableWithMessageHistory

examples/src/indexes/vector_stores/pgvector_vectorstore/docker-compose.example.yml
PGVector docker releases became more official:
https://github.com/pgvector/pgvector#docker
https://github.com/pgvector/pgvector?tab=readme-ov-file#docker-1
This updates the pgvector docker image to the new namespace. Old address is deprecated and will not be updated.
=> Update pgvector docker image

langchain-core/package.json, langchain/package.json, libs/create-langchain-integration/template/package.json, libs/langchain-anthropic/package.json, libs/langchain-cloudflare/package.json, libs/langchain-cohere/package.json, libs/langchain-community/package.json, libs/langchain-exa/package.json, libs/langchain-google-common/package.json, libs/langchain-google-gauth/package.json, libs/langchain-google-genai/package.json, libs/langchain-google-webauth/package.json, libs/langchain-mistralai/package.json, libs/langchain-openai/package.json, libs/langchain-pinecone/package.json, libs/langchain-scripts/package.json, libs/langchain-yandex/package.json
This allows each NPM package displayed readme to match the readme of that specific package
Tested with weaviate [here](https://www.npmjs.com/package/@langchain/weaviate)
cc @jacoblee93 incase adding this has unwanted side effects?
=> all[patch]: Add homepage to package.json for proper readmes

docs/core_docs/docs/modules/model_io/concepts.mdx
While reading the documentation I noticed some spelling errors, I fixed them in this commit
It is a small change but I would love a shoutout if possible https://twitter.com/barisbll_dev
=> Fix typos and grammer errors in concepts.mdx

langchain-core/.eslintrc.cjs, langchain-core/package.json, langchain-core/src/output_parsers/xml.ts, langchain-core/src/utils/event_source_parse.ts, langchain-core/src/utils/sax-js/LICENSE.md, langchain-core/src/utils/sax-js/sax.ts, yarn.lock
=> core[patch]: Inline more portable SAX parser, remove node-only type import

README.md
Changed the text "Fill out this form to get off the waitlist or speak with our sales team." to "Fill out this form to get on the waitlist or speak with our sales team."
=>  Correct waitlist instruction in README

docs/core_docs/vercel.json, langchain/src/document_loaders/tests/sitemap.test.ts, langchain/src/document_loaders/web/sitemap.ts
Looks like the path was changed & a redirect was added for backcompat, then it was changed again to the original path, and another redirect was added
=> langchain[patch],docs[patch]: Fix double redirect

docs/core_docs/docs/integrations/retrievers/dria.mdx, examples/src/retrievers/dria.ts, libs/langchain-community/.gitignore, libs/langchain-community/langchain.config.js, libs/langchain-community/package.json, libs/langchain-community/src/retrievers/dria.ts, libs/langchain-community/src/retrievers/tests/dria.int.test.ts, yarn.lock
[Dria](https://dria.co/) is a hub of public RAG models for developers to both contribute and utilize a shared embedding lake. This PR adds a retriever that can retrieve documents from Dria.
=> community[minor]: Add Dria retriever

docs/core_docs/docs/modules/model_io/prompts/quick_start.mdx
Trivial fix for [#1](https://github.com/TonyGravagno/langchainjs/issues/1) (forked) :  
Doc : Invalid function reference, ChatPromptTemplate `.formatPrompt`
Corrected to `.formatPromptValue`.
=> Fix doc typo for formatPromptValue in prompts/quick_start.mdx

langchain/src/chains/graph_qa/prompts.ts
Unlike vector results, the LLM has to completely trust the context of a graph database result, even if it doesn't provide whole context. We tried with instructions, but it seems that adding a single example is the way to go to solve this issue.
=> langchain[patch]: Update cypher qa prompt

libs/langchain-community/src/vectorstores/opensearch.ts
- Add possibility to specify the number of shards/replicas when creating indices for OpenSerach vector store.
=> community[patch]: allow to modify OpenSerach number of shards/replicas

langchain/src/experimental/openai_assistant/index.ts
Hi I couldn't figure out a good way to get threadId for OpenAIAssistantRunnable when used with AgentExecutor. It is returned when invoking the Runnable but it looks like AgentExecutor only returns values in `returnValues`.
Motivation:
Trying to send messages from client to api route and keep the same threadId for history.
The PR simply duplicates `runId` and `threadId` to `returnValues` which is the behavior in the python repository, [link](https://github.com/langchain-ai/langchain/blob/3925071dd61363db0d483412c9e64bc5a7c60307/libs/langchain/langchain/agents/openai_assistant/base.py#L493-L502).
```python
return OpenAIAssistantFinish(
return_values={
"output": answer,
"thread_id": run.thread_id,
"run_id": run.id,
},
log="",
run_id=run.id,
thread_id=run.thread_id,
)
```
Then it can be used …
=> experimental[patch]: Add threadId and runId to OpenAIAssistantRunnable returnValues for AgentExecutor

libs/langchain-community/src/vectorstores/neo4j_vector.ts, libs/langchain-community/src/vectorstores/tests/neo4j_vector.int.test.ts
Porting https://github.com/langchain-ai/langchain/pull/17396
=> community[patch]: Fix neo4j vector for multiple indexes

docs/core_docs/docs/get_started/quickstart.mdx, docs/core_docs/docs/modules/agents/quick_start.mdx, docs/core_docs/docs/use_cases/chatbots/quickstart.mdx, docs/core_docs/docs/use_cases/chatbots/retrieval.mdx, examples/src/agents/quickstart.ts, examples/src/get_started/quickstart2.ts, examples/src/get_started/quickstart3.ts, examples/src/use_cases/chatbots/quickstart.ts, examples/src/use_cases/chatbots/retrieval.ts, libs/langchain-community/src/indexes/base.ts
The URL to the overview page used in the [Retrieval Chain](https://js.langchain.com/docs/get_started/quickstart#retrieval-chain) section of the quick start page [returns a 404 not found error](https://docs.smith.langchain.com/overview)
This PR will replace the URL with a link to the [user guide page](https://docs.smith.langchain.com/user_guide) instead.
=> docs[minor]: Fix broken link used in quickstart

langchain/src/document_loaders/web/azure_blob_storage_container.ts, langchain/src/document_loaders/web/azure_blob_storage_file.ts, libs/langchain-azure-openai/src/chat_models.ts, libs/langchain-azure-openai/src/constants.ts, libs/langchain-azure-openai/src/embeddings.ts, libs/langchain-azure-openai/src/llms.ts, libs/langchain-community/src/vectorstores/azure_aisearch.ts, libs/langchain-community/src/vectorstores/azure_cosmosdb.ts
Adds `langchainjs*` in the user agent or logs, so LangChain.js usage is reported in Azure OpenAI
=> community[patch], azure-openai[patch]: tag langchainjs in azure integrations calls

libs/langchain-community/package.json, libs/langchain-community/src/graphs/neo4j_graph.ts, yarn.lock
* Added routing mode to allow the app to specify whether the query is routed to the leader or cluster - (defaults to `WRITE` for backwards compatibility)
* Modified `Neo4jGraph.query()` to accept generics for cleaner code
* Stopped `.query() from swallowing errors - a source of much personal confusion & frustration
* Bumped `neo4j-driver` version
Although the routing method defaults to Write, this isn't best practice.  Especially, if you consider the security note in the comments.  If possible, this should default to `READ`.
=> community[patch]: add neo4j-graph generics, don't swallow query execution errors

docs/core_docs/docs/guides/langsmith_evaluation.mdx, langchain/src/smith/config.ts, langchain/src/smith/runner_utils.ts
1. Getting rid of the list of eval types as last arg syntax, smaller API surface
2. Added more strict type constraints on which evaluators we do support
3. Add EmbeddingDistance() config factory
4. Introduce a subclass of RunTree, which uses LangChain Callback Manager to handle weird cases with LS batching and proper order
5. Fix stringification of errors for other non-chain callbacks
=> langchain[minor]: Fix missing traces when traceable used in runOnDataset, API update

langchain-core/src/prompts/chat.ts
The following code will produce `input_variables: [undefined]`
```
const template = ChatPromptTemplate.fromMessages([
HumanMessagePromptTemplate.fromTemplate([{ image_url: "url" }]),
]);
```
=> Fix undefined prompt variable when loading a non-templated image message part

docs/core_docs/docs/integrations/vectorstores/cloudflare_vectorize.mdx
Incorrect file extension type, causing the example to be unexecutable.
=> docs[patch]: Docs update: update cloudflare_vectorize.mdx

langchain/package.json, yarn.lock
Long term, we need to move self query retriever code out of `langchain` but this should be a good stopgap
=> langchain[patch]: Relax Weaviate peer dep

libs/langchain-groq/README.md
Fixes the example in the Groq readme.  It refers to an undefined variable.
=> groq[minor]: Fix Readme example

langchain-core/.gitignore, langchain-core/langchain.config.js, langchain-core/package.json, langchain-core/src/runnables/base.ts, langchain-core/src/runnables/config.ts, langchain-core/src/runnables/index.ts, langchain-core/src/runnables/passthrough.ts, langchain-core/src/singletons/index.ts, langchain-core/src/singletons/tests/async_local_storage.test.ts, langchain-core/src/tools.ts
`AsyncLocalStorage` a very useful API that is available in many environments but not all. We want to allow projects like LangGraph to take advantage of its convenience at the cost of supporting only a subset of environments.
The idea would be (before instantiating any `RunnableLambda`):
```ts
import { AsyncLocalStorageProviderSingleton } from "@langchain/core/singletons";
import { AsyncLocalStorage } from "node:async_hooks";
AsyncLocalStorageProviderSingleton.setClass(AsyncLocalStorage);
```
This PR also allows nested `RunnableLambdas` to automatically fetch config from the next level up, enabling more convenient tracing.
@nfcampos @bracesproul @dqbd
=> core[minor]: Allow injection of AsyncLocalStorage

libs/langchain-community/src/vectorstores/astradb.ts, libs/langchain-community/src/vectorstores/tests/astradb.int.test.ts
Currently in the `AstraDBVectorStore#initialize` method if there is an error while creating the collection, the error is suppressed, assuming the collection already exists. This is wrong because:
- if the collection already exists with the same options, the Astra Data API won't return errors
- In case of auth, network or server errors, the user can't really see the errors and no error is raised
=> community[patch]: fix astra initialize error

libs/langchain-community/src/graphs/neo4j_graph.ts
The `Neo4jGraph.query()` method would return `undefined` if an error was thrown at query time.  This is no longer the case, so the method will either throw or return an empty array if no records are returned.
=> community[patch]: Neo4j will no longer return undefined

libs/langchain-groq/src/chat_models.ts
=> groq[patch]: Set dangerouslyAllowBrowser = true in ChatGroq

libs/langchain-community/src/vectorstores/elasticsearch.ts
This PR adds support for filtering with "exists" for the elasticsearch vector store.
=> community[patch]: Add support for exists filter in the elasticsearch vector store.

langchain/package.json, yarn.lock
YouTube loader is currently broken due to using an old `youtubei.js` dependency version. This PR updates this optional peer dependency, fixing the issue.
=> langchain[patch]: update youtubei.js peer dependency, fixing YoutubeLoader

libs/langchain-openai/src/chat_models.ts
Turns out setting `tool_choice: "auto"` does not always guarantee tool usage, and is different between models.
This will force then model to use the provided tool.
=> openai[minor]: Force tool usage through tool_choice

libs/langchain-community/src/vectorstores/neo4j_vector.ts, libs/langchain-community/src/vectorstores/tests/neo4j_vector.int.test.ts
Sometimes, you want to use various parameters in the retrieval query of Neo4j Vector to personalize/customize results. Before, when there were only predefined chains, it didn't really make sense. Now that it's all about custom chains and LCEL, it is worth adding since users can inject any params they wish at query time. Isn't prone to SQL injection-type attacks since we use parameters and not concatenating strings.
=> community[patch]: Add retrieval params to neo4j vector

docs/core_docs/docs/modules/agents/agent_types/openai_tools_agent.mdx
Fix typo at openai_tools_agent.mdx
=> docs[minor]: Fix typo

libs/langchain-mistralai/src/chat_models.ts, libs/langchain-mistralai/src/tests/chat_models.int.test.ts
=> mistralai[patch]: Fix Mistral for non-tool calling models

docs/core_docs/docs/use_cases/question_answering/index.mdx
Fix broken [Table of contents](https://js.langchain.com/docs/use_cases/question_answering/#table-of-contents) links on the [Q&A with RAG](https://js.langchain.com/docs/use_cases/question_answering/) page. Also added a new link for the [Citations](https://js.langchain.com/docs/use_cases/question_answering/citations) page.
Side note: I don't know where the page is for the `Per-user retrieval` link. I can update this if someone points me to the right page.
=> Fix broken `Table of contents` links on `Q&A with RAG` page

CONTRIBUTING.md, docs/core_docs/docs/modules/memory/index.mdx
Resolves two minor typos in documentation.
=> docs[patch]: fix(docs): correct typos in docs

libs/langchain-community/src/vectorstores/elasticsearch.ts
For our project we needed to exclude some ids of certain entities when searching the VectorStore.
As the current implementation doesn't support the must_not filter yet, I've added it as an "exclude" operator to be flexible and populate the must_not filter accordingly.
=> community[patch]: Allow must_not filter in Elasticsearch VectorStore

langchain-core/src/output_parsers/base.ts, langchain-core/src/output_parsers/string.ts, langchain-core/src/output_parsers/tests/string.test.ts, langchain-core/src/output_parsers/transform.ts
Added a number of methods to `BaseLLMOutputParser` and call from `invoke()` to allow subclasses to override the string representation of a `BaseMessage`. Take advantage of this as part of `StringOutputParser` to make sure any text types are represented as human-readable strings.
Fixes #4695
=> core[minor]: StringOutputParser and text BaseMessage contents

docs/core_docs/docs/modules/data_connection/retrievers/parent-document-retriever.mdx, examples/src/retrievers/parent_document_retriever_chunk_header.ts, langchain/src/retrievers/parent_document.ts
Add possibility to use Contextual chunk headers in Parent Document Retriever.
This is particularly important if you have several fine-grained child chunks that need to be correctly retrieved from the vector store.
=> langchain[patch]: Add Possibility to use Contextual chunk headers in Parent Document Retriever

langchain/src/document_loaders/web/gitbook.ts
=> langchain[patch]: fix gitbook loader with shouldLoadAllPaths:true

langchain/src/document_loaders/fs/unstructured.ts
Unstructured API - Added missing API props to UnstructuredLoader.
Props added: multipage_sections, combine_under_n_chars, new_after_n_chars and max_characters.
Info about these props on https://unstructured-io.github.io/unstructured/apis/api_parameters.html
=> langchain[minor]: Add missing props to UnstructuredLoader

langchain-core/src/language_models/chat_models.ts, langchain-core/src/messages/index.ts
=> core[patch]: Merge response metadata fields

langchain-core/src/prompts/chat.ts, langchain-core/src/prompts/index.ts, langchain-core/src/prompts/structured.ts, langchain-core/src/prompts/tests/structured.test.ts
=> core[minor]: StructuredPrompt

libs/langchain-cohere/package.json, libs/langchain-cohere/src/chat_models.ts, libs/langchain-cohere/src/embeddings.ts, libs/langchain-cohere/src/llms.ts, yarn.lock
This bumps the version of the cohere-ai ts client. It fixes an issue with the cohere-ai package running on aws lambda to where the fetch function is not defined in some node versions because of the default export, more info mentioned on the issue below.
twitter.  `https://twitter.com/Gr33nLight_`
Fixes https://github.com/cohere-ai/cohere-typescript/issues/136
=> fix(cohere): bump client version

examples/src/indexes/vector_stores/pgvector_vectorstore/pgvector.ts, libs/langchain-community/src/vectorstores/pgvector.ts, libs/langchain-community/src/vectorstores/tests/pgvector/pgvector.int.test.ts
Add support for inner product and Euclidean distance to `PGVector`. The implementation is modeled after the `CassandraStore` implementation.
1. I can probably make this change in the Python library as well.
1. [PGVector Vector Operators](https://github.com/pgvector/pgvector/?tab=readme-ov-file#vector-operators)
2. [Discord thread](https://discord.com/channels/1038097195422978059/1076182741374214285/1217854243017588816)
=> community[patch]: Add support for inner product and Euclidean distance to `PGVector`

docs/core_docs/docs/modules/agents/index.mdx
[Python docs](https://python.langchain.com/docs/modules/agents/) have a link on `this getting started guide` which [JS docs](https://js.langchain.com/docs/modules/agents/) are missing
=> docs[patch]: Fix missing link to `Agents Quick Start`

libs/langchain-community/src/chat_models/bedrock/web.ts, libs/langchain-community/src/chat_models/tests/chatbedrock.int.test.ts, libs/langchain-community/src/llms/bedrock/web.ts, libs/langchain-community/src/utils/bedrock.ts
Mistral is now supported in AWS Bedrock. 
```
$ aws bedrock list-foundation-models --region us-east-1 --query 'modelSummaries[*].modelId' | grep mistral
"mistral.mistral-7b-instruct-v0:2",
"mistral.mixtral-8x7b-instruct-v0:1"
$
```
Langchain has a duplicated list of valid models. I'd argue that they both can be removed. Langchain doesn't need to validate the models before passing them on to Bedrock.
=> Add mistral as supported provider for AWS Bedrock

docs/core_docs/docs/expression_language/cookbook/retrieval.mdx
The current docs indicate that `@langchain/openai` should be installed, there are actually a couple of other dependencies thar need to be installed in order to execute the example code.
=> docs: adding missing dependencies to RAG documentation

libs/langchain-redis/src/tests/vectorstores.test.ts, libs/langchain-redis/src/vectorstores.ts
The `:` and `"` characters found in the stringified JSON are special characters in redisSearch queries, so we need to escape them in the stringified metadata if we want to be able to search the entire JSON object.
This enables key/value sub-string searches of the stringified metadata object for filtering purposes.
=> redis[patch]: Escape additional metadata characters for RedisSearch metadata filtering usage

libs/langchain-mistralai/src/chat_models.ts, libs/langchain-mistralai/src/tests/chat_models.int.test.ts
Closes #4809
Changes:
- omit `stop` from the mistral call options, not supported via their sdk
- move the error thrown if abort controller is aborted to inside the `for-await` loop since their sdk doesn't support aborting natively
- if timeout or signal is passed, make the `generate` method stream instead so we can properly abort
- add tests
=> mistralai[minor]: Fix throwing abort errors and add tests

libs/langchain-community/src/vectorstores/elasticsearch.ts
Fixes bug in discussion # ([discussion](https://github.com/langchain-ai/langchain/discussions/19396))
Description is in the attached issue/discussion. Basically, it was observed on `incremental` cleanup when calling the `index(...)` function a crash when trying to delete an empty list of elements. The deletion in Elastic is done by a `POST _bulk` request, which expects a non-emtpy list of operations. When there is no elements to delete, the list of operations is empty, hence the error. Easy to replicate straight in the Elastic Console (i.e. http://localhost:5601/app/dev_tools#/console) by writing just `POST _bulk`.
=> community[patch]: ElasticVectorSearch - fix error when no bulk operations 

libs/langchain-mistralai/package.json, libs/langchain-mistralai/src/chat_models.ts, libs/langchain-mistralai/src/tests/chat_models.int.test.ts, yarn.lock
This PR aims to adjust the `ChatMistralAI` class to ensure its compatibility with the `createOpenAIToolsAgent` interface, thereby enabling the use of Mistral models, specifically `mistral-large-latest` and `mistral-small-latest`, within the execution agent that utilizes tool calling in the manner of OpenAI. This modification aligns with the API specifications of Mistral for the mentioned models, making them compatible with the same implementations as those of recent OpenAI models, such as `gpt-4-0125-preview` and `gpt-3.5-turbo-0125`, as mentioned here: [LangChain Agents Documentation](https://api.js.langchain.com/functions/langchain_agents.createOpenAIToolsAgent.html).
The extended compatibility allows for the seamless integration of Mistral's capabilities within agents, using the …
=> mistral[minor]: integrating Mistral LLM with AgentExecutor

libs/langchain-groq/src/chat_models.ts, libs/langchain-groq/src/tests/chat_models.int.test.ts
=> groq[patch]: Allow custom headers passed into Groq

langchain-core/src/messages/index.ts, langchain-core/src/prompts/chat.ts, langchain-core/src/prompts/tests/chat.test.ts
=> core[patch]: Adds placeholder message BaseMessage type

docs/core_docs/docs/integrations/tools/duckduckgo_search.mdx, examples/package.json, examples/src/tools/duckduckgo_search_agent.ts, examples/src/tools/duckduckgo_search_simple.ts, libs/langchain-community/.gitignore, libs/langchain-community/langchain.config.js, libs/langchain-community/package.json, libs/langchain-community/src/tools/duckduckgo_search.ts, yarn.lock
Here is another try to add the DuckDuckGo as a community search tool. 
Duplicate of - [one](https://github.com/langchain-ai/langchainjs/pull/1184)  that unfortunately still stays in Open state that was reviewed by @dqbd 
I am open to any comments and suggestions for this merge request. I value your time and am willing to make the necessary changes to expedite its acceptance into the main branch as I consider these tools a valuable addition to the TS version of the community toolset. 
Thank you for the opportunity to contribute to the project!
DuckDuckGo tool that uses the existing mature under the hood.
Tools take the same options as the library it uses, plus the possibility to limit the max number of return results, as I experience that the initial amount might overload the context …
=> community[minor]: Add DuckDuckGoSearch tool

examples/src/memory/mongodb.ts
This PR adds logic similar to the implementation in Python added in https://github.com/langchain-ai/langchain/pull/13084. 
In JS, users instantiate `MongoClient`s and provide them to langchain instead of langchain instantiating the `MongoClient` for them.  As such, there's no way for langchain to add client metadata like the Python implementation does.  Additionally, there's no equivalent of `importlib.metadata` in Javascript that can return the version of a package.  So we'd like to just add this to the documentation example, so that when users use the code provided in the docs, they include the metadata as well.
=> docs[patch]: Add wrapping library metadata to MongoDB docs example

libs/langchain-azure-openai/src/chat_models.ts, libs/langchain-azure-openai/src/embeddings.ts, libs/langchain-azure-openai/src/llms.ts, libs/langchain-azure-openai/src/tests/chat_models.int.test.ts, libs/langchain-azure-openai/src/tests/embeddings.int.test.ts, libs/langchain-azure-openai/src/tests/llms.int.test.ts
=> azure-openai[patch]: fix azureOpenAIApiKey not working

langchain-core/src/runnables/base.ts, langchain-core/src/utils/testing/index.ts
When streaming a runnable sequence before, custom runId's were not properly handled and tracing would lose some items inside the sequence due to duplicate runIds
(also includes some missing formatting)
=> core[patch]: Fix handling custom run id in sequence streams

langchain/src/retrievers/self_query/index.ts
If there are no metadata filters (NO_FILTER), instead of explicitly returning [], it should fallback to a similarity search
This also matches the python implementation
=> langchain[patch]: SelfQueryRetriever - fallback to similarity search

libs/langchain-scripts/src/migrations/0_1.ts
- Migration script (updateEntrypointsFrom0_0_xTo0_1_x from @langchain/scripts/migrations) fails with the error below
```
TypeError: Cannot read properties of undefined (reading 'getKind')
at file:///Users/tomoima525/workspace/knot/noxx-hiring-cdk/node_modules/.pnpm/@langchain+scripts@0.0.10/node_modules/@langchain/scripts/dist/migrations/0_1.js:21:39
at Array.map (<anonymous>)
at file:///Users/tomoima525/workspace/knot/noxx-hiring-cdk/node_modules/.pnpm/@langchain+scripts@0.0.10/node_modules/@langchain/scripts/dist/migrations/0_1.js:18:74
at Array.flatMap (<anonymous>)
at getEntrypointsFromFile (file:///Users/tomoima525/workspace/knot/noxx-hiring-cdk/node_modules/.pnpm/@langchain+scripts@0.0.10/node_modules/@langchain/scripts/dist/migrations/0_1.js:12:48)
at async …
```
=> scripts[minor]:Some symbols have empty declarations

langchain/src/smith/runner_utils.ts, langchain/src/smith/tests/run_on_dataset.int.test.ts
=> langchain[patch]: Make thrown evaluator errors not interrupt dataset flow

libs/langchain-community/src/graphs/neo4j_graph.ts
=> community[patch]: Fix issue in Neo4jGraph.addGraphDocuments function where Document node is not populating text content

langchain-core/src/utils/testing/index.ts, libs/langchain-community/src/experimental/graph_transformers/llm.int.test.ts, libs/langchain-community/src/experimental/graph_transformers/llm.ts, libs/langchain-community/src/graphs/graph_document.ts
=> community[patch]: Fix strict mode comparison and formatting for llm graph transformer

langchain/src/document_loaders/web/github.ts
Occasionally .gitmodules files are not ending with a newline character. Still the file is valid.
This PR fixes the issue with the given regex by adding the newline character for parsing, if not present.
=> langchain[patch]: fix: make GithubRepoLoader robust against .gitmodules files w/o newline
