langchain/agents/executor.ts
langchain/agents/tests/agent.test.ts
langchain/agents/tests/calculator.test.ts
langchain/agents/tools/base.ts
langchain/agents/tools/calculator.ts
langchain/agents/tools/index.ts
langchain/agents/tools/serpapi.ts
langchain/babel.config.js
langchain/package.json
yarn.lock

With a calculator tool the agent test now passes

Add calculator tool

---

langchain/document.ts
langchain/text_splitter.test.ts
langchain/text_splitter.ts

Add document and text splitters

add document and text splitters

---

langchain/embeddings/base.ts
langchain/embeddings/index.ts
langchain/embeddings/openai.ts
langchain/embeddings/tests/openai.test.ts
langchain/llms/openai.ts
langchain/package.json
langchain/util/index.ts
langchain/vectorstores/base.ts
langchain/vectorstores/hnswlib.ts
langchain/vectorstores/index.ts
langchain/vectorstores/tests/hnswlib.test.ts
yarn.lock

This implements a vector store using HNSWLib https://github.com/nmslib/hnswlib, using the node bindings at https://github.com/yoshoku/hnswlib-node
HNSWLib is the ANN library used by Chroma

Add VectorStore base class and HNSWLib vector store

---

examples/src/customParameters/differentBaseUrl.ts
langchain/cache.ts
langchain/llms/base.ts
langchain/llms/openai.ts

Add configuration parameter to the constructor of OpenAI so that users can have more control of their

Added OpenAI CustomParameters to OpenAI constructor

---

langchain/agents/tools/bingserpapi.ts
langchain/agents/tools/dadjokeapi.ts
langchain/agents/tools/index.ts

- Adding support for Bing to be plugged in as a tool.
- Adding a dad-joke tool that uses https://icanhazdadjoke.com/ that return jokes by specified topic 'coz sometimes AI needs to be funny to be less intimidating.

Adding Bing SERP API and Dad Joke API tools

---

langchain/vectorstores/hnswlib.ts

Add warning on k being too high on hnswlib.similaritySearch

---

langchain/agents/tools/IFTTTWebhook.ts

Tool to allow LangChain apps to connect to the services in the IFTTT ecosystem.
Tool can be added multiple times into an agent with a different `name`, `description`, and webhook `url` for each instance to create a more powerful LangChain app that can play Spotify music, interact with smart-lights, etc.

IFTTT + LangChain

---

docs/docs/getting-started.md

update doc to suggest fewer more way of setting up the Api Key 

---

langchain/chains/analyze_documents_chain.ts

Post #97 This one must have been added after my PR

Update AnalyzeDocumentChain for new async api of resolveConfigFromFile

---

docs/package.json
yarn.lock

Version 0.0.37 fixes sources link issues, improves mobile UI, faster response time, and re-designed sources tab.

docs: Mendable Search v0.0.37 - Bug Fixes + Better Sources Tab + Feedback

---

langchain/src/util/axios-fetch-adapter.js

(which we shouldnt be using, but people's projects may have it around anyway)

Make axios fetch adapter more compatible with the next major version of axios 

---

test-exports/index.cjs
test-exports/package.json

Since we have this in the docs, we should test it (it does work)

Add test-exports case for CJS dynamic import

---

examples/src/prompts/few_shot.ts
langchain/src/prompts/few_shot.ts
langchain/src/prompts/tests/few_shot.test.ts

Fixes:
- `FewShotPromptTemplate -> format()` returning unresolved promises
- Add missing await to few_shot example

Fix issue with FewShotPromptTemplate

---

docs/docs/modules/llms/overview.md

Added a section to the LLMs Overview docs showing how to create a callback manager for debug logging

Update LLMs Overview Docs with debug logging

---

docs/docs/modules/chains/chat_vector_db_qa.md
docs/docs/modules/chains/question_answering.md
docs/docs/modules/chains/summarization.md
docs/docs/modules/chains/vector_db_qa.md
langchain/src/chains/vector_db_qa.ts

Hey! I would love to start contributing :^)
Here's my first & smallest PR ever!
I've made some changes to improve the cohesiveness of the sentence.

Fixed styling & english

---

langchain/src/vectorstores/supabase.ts

upsert returns 500/502/504 (yes really any of them) if given too many rows/characters
~2000 trips it, but my data is probably smaller than average pageContent and metadata
Also was eating the error, now throws it. Finally use insert not upsert as the primary key isnt being inserted, not possible to update
Linking #201

fix: supabase vectorstore addVectors chunking

---

langchain/src/cache.ts
langchain/src/document_loaders/directory.ts
langchain/src/document_loaders/srt.ts
langchain/src/document_loaders/tests/csv.test.ts
langchain/src/document_loaders/tests/directory.test.ts
langchain/src/document_loaders/tests/json.test.ts
langchain/src/document_loaders/tests/jsonl.test.ts
langchain/src/document_loaders/tests/notion_markdown.test.ts
langchain/src/document_loaders/tests/pdf.test.ts
langchain/src/document_loaders/text.ts
langchain/src/prompts/tests/load.test.ts
langchain/src/tests/cache.test.ts
langchain/src/util/index.ts
langchain/src/vectorstores/hnswlib.ts
langchain/src/vectorstores/tests/hnswlib.int.test.ts

Use node: import specifiers

---

examples/package.json
langchain/package.json
yarn.lock

Bump `@pinecone-database/pinecone` version which has no breaking change and better error handling. 
https://github.com/fraserxu/book-gpt/issues/13#issuecomment-1462910592

Upgrade pinecone package version

---

docs/docs/modules/agents/agents_with_vectorstores.md
docs/docs/modules/chains/llm_chain.md
docs/docs/modules/chains/vector_db_qa.md
docs/docs/modules/chat_models/overview.md
docs/docs/modules/llms/overview.md
examples/src/chains/llm_chain_stream.ts
examples/src/chat/streaming.ts
langchain/src/chains/analyze_documents_chain.ts
langchain/src/chat_models/openai.ts
langchain/src/llms/openai.ts

More from discord @nfcampos 
https://github.com/hwchase17/langchainjs/pull/328

fix textSplitter.createDocuments~ missing await

---

docs/package.json
yarn.lock

docs: Mendable Search Bug Fixes

---

langchain/src/chat_models/base.ts
langchain/src/chat_models/openai.ts
langchain/src/chat_models/tests/chatopenai.int.test.ts
langchain/src/llms/tests/openai.int.test.ts

Unless it wasnt there for some other reason

feat: ChatOpenAi support tokenUsage

---

langchain/src/agents/agent_toolkits/sql/sql.ts
langchain/src/agents/chat_convo/index.ts
langchain/src/agents/index.ts
langchain/src/agents/tools/zapier.ts
langchain/src/prompts/index.ts

feat: export parseTemplate and renderTemplate

---

langchain/src/agents/tools/index.ts

Add missing tool exports

---

docs/docs/modules/indexes/vector_stores/chroma.md

- Updated Chroma example to use native langchainjs query func
- Added example usage for query docs from existing collection on Chroma

docs: update Chroma usage docs example

---

langchain/src/prompts/chat.ts
langchain/src/prompts/tests/chat.test.ts

I thought I needed this so started on it, but dont think I need it now
I think this is related to https://github.com/hwchase17/langchainjs/pull/270

feat: partials for chatprompttemplate

---

docs/docs/modules/indexes/embeddings.md
examples/src/indexes/embeddings.ts
langchain/src/embeddings/cohere.ts
langchain/src/embeddings/index.ts
langchain/src/embeddings/tests/cohere.int.test.ts

I implemented this for a personal project and wanted to add it to the library since it is needed to achieve python parity.
Twitter: Rolilink

feat: adds cohere embeddings support

---

langchain/src/agents/tools/zapier.ts

This was failing very now and then when running integration tests

Add retry to zapier nla wrapper

---

docs/docs/production/callbacks.mdx
examples/src/callbacks/console_handler.ts
langchain/src/agents/executor.ts
langchain/src/agents/initialize.ts
langchain/src/agents/tools/base.ts
langchain/src/base_language/index.ts
langchain/src/callbacks/base.ts
langchain/src/chains/base.ts
langchain/src/chains/llm_chain.ts

Make verbose flag default to true when a callbackManager is passed in

---

langchain/package.json
langchain/src/chains/tests/chat_vector_db_qa_chain.int.test.ts
langchain/src/chat_models/openai.ts
langchain/src/llms/openai-chat.ts
langchain/src/llms/openai.ts
langchain/src/util/axios-fetch-adapter.d.ts
langchain/src/util/axios-fetch-adapter.js
yarn.lock

Streaming requests now use our axios fetch adapter

Enable streaming OpenAI requests to work outside of Node

---

langchain/src/vectorstores/tests/pinecone.test.ts

This is just adding a test for existing functionality

Add test for pinecone metadata flattening

---

docs/docs/modules/models/chat/additional_functionality.mdx
docs/docs/modules/models/llms/additional_functionality.mdx
examples/src/models/chat/chat_timeout.ts
examples/src/models/llm/llm_timeout.ts
langchain/src/chat_models/openai.ts
langchain/src/llms/openai-chat.ts
langchain/src/llms/openai.ts
langchain/src/util/async_caller.ts

Enable passing timeout to OpenAI models

---

docs/docs/modules/agents/tools/agents_with_vectorstores.md

s/"return_direct=True"/"returnDirect: true" and fix typo

Update docs page for VectorDBQAChain to reflect TypeScript style

---

langchain/src/vectorstores/base.ts

This is just a small fix for the retriever.

Fix the base retriever docs count

---

docs/docs/modules/models/chat/additional_functionality.mdx
docs/docs/modules/models/embeddings/additional_functionality.mdx
docs/docs/modules/models/llms/additional_functionality.mdx
examples/src/models/embeddings/openai_timeout.ts
langchain/src/embeddings/openai.ts

Closes https://github.com/hwchase17/langchainjs/issues/584
Thanks @nfcampos for closing https://github.com/hwchase17/langchainjs/issues/511 with https://github.com/hwchase17/langchainjs/pull/533 so quickly. I've just gone ahead and made the same changes for OpenAI embeddings

Add timeout for embeddings API

---

examples/src/document_loaders/example_data/notion.md
examples/src/document_loaders/unstructured.ts
langchain/src/document_loaders/fs/unstructured.ts

fix #738
Reference link [unstructured-api](https://github.com/Unstructured-IO/unstructured-api/pull/65#issuecomment-1492609008)

fix: pass file name to unstructured-api

---

langchain/src/chains/llm_chain.ts

Update LLMChain example

---

docs/package.json
docs/src/theme/SearchBar.js
yarn.lock

- Conversation now remains saved for as long as you are on the page.
- Clicking a source now open on the same page
- Fixed the focus bug pointed out by a Discord member

docs: Mendable Search (state is now saved + fixes)

---

langchain/src/vectorstores/prisma.ts

Fix prisma addModels

---

docs/docs/getting-started/guide-llm.mdx

- Added package installation step for `serpapi`

docs: Improved getting-started guide

---

langchain/src/chains/base.ts

This PR gives the ability to load the Map Reduce and Refine document chains from LangChainHub

feat: Add MapReduce and Refine Documents chains to deserialize method

---

langchain/scripts/create-entrypoints.js
langchain/src/retrievers/contextual_compression.ts
langchain/src/retrievers/document_compressors/index.ts
langchain/src/retrievers/index.ts

updated #915 branch (now on main repo not my fork)

Add contextual compression base classes

---

.github/workflows/ci.yml
README.md
docs/docs/getting-started/install.md
langchain/src/document_loaders/tests/pdf.test.ts

Add support for Node 20.x

---

langchain/src/agents/chat_convo/prompt.ts

See details here https://github.com/hwchase17/langchainjs/issues/986

Fix: Preserve new lines characters from LLM response

---

docs/docs/modules/indexes/vector_stores/integrations/hnswlib.mdx

Add Windows setup hint to `hnswlib-node` integration docs.

add Visual Studio mention for the setup of `hnswlib-node`

---

langchain/.gitignore
langchain/package.json
langchain/scripts/create-entrypoints.js
langchain/src/schema/index.ts
langchain/tsconfig.json
test-exports-cf/src/entrypoints.js
test-exports-cjs/src/entrypoints.js
test-exports-cra/src/entrypoints.js
test-exports-esm/src/entrypoints.js
test-exports-vercel/src/entrypoints.js
test-exports-vite/src/entrypoints.js

@nfcampos Im not sure if this is where you want this, but this got lost during the callbacks refactor

feat: re-expose BaseOutputParser, OutputParserException

---

langchain/src/embeddings/cohere.ts

This is a fix for a bug which results in the wrong inputs being sent to Cohere Embed API.

Fix cohere embed

---

docs/docs/modules/chains/other_chains/constitutional_chain.mdx
examples/src/chains/constitutional_chain.ts
langchain/src/chains/constitutional_ai/constitutional_chain.ts
langchain/src/chains/constitutional_ai/constitutional_principle.ts
langchain/src/chains/constitutional_ai/constitutional_prompts.ts
langchain/src/chains/index.ts
langchain/src/chains/serde.ts
langchain/src/chains/tests/constitutional_chain.int.test.ts
langchain/src/chains/tests/constitutional_chain.test.ts

Added constitutional chain translated from the main python langchain repo.
Translated from https://github.com/hwchase17/langchain/tree/master/langchain/chains/constitutional_ai

Added constitutional chain

---

docs/package.json
yarn.lock

Bug fixes, UI fixes, and improvements.

docs: Mendable Search Improvements

---

docs/docs/modules/agents/tools/webbrowser.mdx
examples/src/agents/custom_llm_agent.ts
examples/src/agents/custom_llm_agent_chat.ts
langchain/src/agents/mrkl/prompt.ts
langchain/src/agents/tests/mrkl_agent.int.test.ts
langchain/src/tools/webbrowser.ts

A small prompt change helped cue GPT-4 better. Should fix #1042, and we'll be looking into more robust ways to test agents long-term.

MRKL prompt fix, integration test

---

langchain/.eslintrc.cjs
langchain/src/retrievers/document_compressors/chain_extract.ts

Speed-up Contextual Compression by using parallel async for-of loop

Speed-up Contextual Compression by using parallel async for-of loop

---

langchain/src/chains/question_answering/map_reduce_prompts.ts
langchain/src/chains/question_answering/refine_prompts.ts
langchain/src/chains/question_answering/stuff_prompts.ts
langchain/src/prompts/index.ts
langchain/src/prompts/selectors/conditional.ts

I'm finding this Conditional Prompt Selector to be super useful. But it is not exported anywhere. So I've moved it to be under prompts and exported out so it can be used externally.

chore: export conditional prompt selector

---

docs/docs/modules/chains/other_chains/sql.mdx
examples/src/chains/sql_db.ts
examples/src/chains/sql_db_sql_output.ts
langchain/src/chains/sql_db/sql_db_chain.ts
langchain/src/chains/tests/sql_db_chain.int.test.ts

Add option to return used SQL in SqlDatabaseChain

---

docs/package.json
docs/src/theme/SearchBar.js
yarn.lock

- New redesigned UI
- Pretty Sources: display the sources by title / sub-section instead of long URL.
- Fixed Reset Button bugs and some other UI issues
- Higher accuracy on the responses
- Other tweaks

docs: Mendable Improvements

---

langchain/src/chains/query_constructor/prompt.ts

Fix a misspelling and added double quote on json formatting.

fix: query_constructor prompt fix

---

docs/docs/production/deployment.md

👋 Hey LangChainJS maintainers
We're fans of LangChain here at Kinsta, thus we thought we'd extend your documentation with [our starter template](https://github.com/kinsta/hello-world-langchainjs) repository to make our and LangChain users' life easier a bit. ❤️ _(just like we did [at the Python lib](https://github.com/hwchase17/langchain/pull/4445))_

[DOCS]: Add Kinsta to list of providers

---

examples/src/client/tracing_datasets.ts
langchain/src/client/langchainplus.ts
langchain/src/client/tests/langchainplus.int.test.ts

Add env var defaults and make it not required in the `create()` method

Make API URL optional when specifed via env var

---

docs/docs/modules/models/embeddings/integrations.mdx

Quick note about using Vertex AI embeddings with some providers.

Google Vertex AI docs update

---

langchain/src/chains/index.ts

- Fix export of APIChainOptions

fix: fixed export of APIChainOptions

---

examples/src/agents/chat_mrkl.ts

Fixes #
[langchain chat_mrl page](https://js.langchain.com/docs/modules/agents/agents/action/chat_mrkl
)
When the code on the page is applied, console.log outputs undefined.
```
console.log(
`Got intermediate steps ${JSON.stringify(
result.intermediateSteps,
null,
2
)}`)
```
Undefined log Screenshot:
Log output with corrected code

fix: intermediateSteps undefined problem.

---

docs/docs/modules/indexes/text_splitters/examples/latex.mdx
examples/src/indexes/latex_text_splitter.ts
langchain/src/tests/text_splitter.test.ts
langchain/src/text_splitter.ts

Addressing https://github.com/hwchase17/langchainjs/issues/1102

Add latex text splitter

---

docs/docs/modules/agents/tools/dynamic.mdx
docs/docs/modules/agents/tools/index.mdx

Makes it clearer that this is possible.

Adds separate docs page for custom tools

---

.github/pull_request_template.md

Helps us better show appreciation for all of our contributors' hard work 😄

Updates PR template to request Twitter handle for shoutouts!

---

docs/docs/modules/chains/index_related_chains/conversational_retrieval.mdx
examples/src/chains/conversational_qa_customization.ts
examples/src/chains/conversational_qa_external_memory.ts
langchain/src/chains/conversational_retrieval_chain.ts
langchain/src/chains/tests/conversational_retrieval_chain.int.test.ts

Allows use of built-in memory classes rather than having to pass/manage memory externally.

Adds support for built-in memory to ConversationalQARetrievalChain

---

langchain/src/agents/structured_chat/outputParser.ts

Fix structured agent output parser callbacks

---

langchain/src/agents/chat_convo/prompt.ts

Bring this chat convo agent prompt in sync with python library
Based on: https://github.com/hwchase17/langchain/pull/1989
https://github.com/hwchase17/langchain/blob/master/langchain/agents/conversational_chat/prompt.py#L57

Improve chat convo agent prompt

---

test-exports-esbuild/src/entrypoints.js

Missing entrypoint

---

langchain/src/agents/chat_convo/prompt.ts
langchain/src/agents/structured_chat/prompt.ts

Add missing commas in agent prompts json

---

langchain/src/chains/query_constructor/index.ts
langchain/src/chains/query_constructor/tests/query_chain.int.test.ts
langchain/src/retrievers/self_query/index.ts

s/loadQueryContstructorChain/loadQueryConstructorChain

Fix typo in method

---

langchain/src/vectorstores/milvus.ts

fix username and password for Milvus.fromText and Milvus.fromDocuments
Fixes #1491 (issue)
my Twitter is @DeeWoooo299

fix username and password for Milvus.fromText and Milvus.fromDocuments

---

docs/docs/modules/chains/index_related_chains/conversational_retrieval.mdx
examples/src/chains/conversational_qa_built_in_memory.ts
examples/src/chains/conversational_qa_streaming.ts

Clarifies streaming with the conversational retrieval QA chain.

Adds streaming example to the conversational retrieval QA chain docs

---

docs/docs/modules/prompts/prompt_templates/prompt_composition.mdx
examples/src/prompts/pipeline_prompt.ts
langchain/src/prompts/base.ts
langchain/src/prompts/chat.ts
langchain/src/prompts/index.ts
langchain/src/prompts/pipeline.ts
langchain/src/prompts/tests/pipeline.test.ts

Adds a new type of prompt that can use intermediate prompts in the final output value.

Adds pipeline prompt

---

langchain/src/vectorstores/milvus.ts
langchain/src/vectorstores/tests/milvus.int.test.ts

remove interface dependency for milvus sdk

---

examples/package.json
examples/src/client/tracing_datasets.ts
langchain/package.json
langchain/src/client/index.ts
langchain/src/client/langchainplus.ts
langchain/src/client/tests/langchainplus.int.test.ts
yarn.lock

Remove the implementation of LCP client and instead import from the SDK. Split out the `runOnDataset` method into a separate function (rather than extending the client. I think that could be more confusing. Open to pushback)

Use SDK Package for LCP Client

---

docs/docs/modules/models/llms/integrations.mdx
examples/src/llms/googlevertexai-code-bison.ts
examples/src/llms/googlevertexai-code-gecko.ts
langchain/src/llms/googlevertexai.ts
langchain/src/llms/tests/googlevertexai.int.test.ts

GoogleVertexAI "Codey" support for code-bison and code-gecko models

---

docs/package.json

Try to make docs build more reliable

---

langchain/package.json

Release 0.0.94

---

langchain/src/chains/base.ts
langchain/src/chains/tests/llm_chain.int.test.ts

Fix calling chain.run() with memory

---

langchain/src/agents/executor.ts
langchain/src/agents/initialize.ts
langchain/src/agents/openai/index.ts
langchain/src/agents/tests/openai.int.test.ts

This patch adds memory support to OpenAI Functions Agent.

Memory support for OpenAI Functions Agent

---

examples/src/models/chat/integration_openai.ts

Add more docs for calling chatopenai with functions

---

docs/docs/production/callbacks/index.mdx
examples/src/callbacks/docs_constructor_callbacks.ts
examples/src/callbacks/docs_request_callbacks.ts
examples/src/chains/advanced_subclass_call.ts

Add docs for tags

---

langchain/src/agents/openai/index.ts

Remove extra log

---

examples/src/models/chat/integration_anthropic.ts
langchain/src/chains/base.ts
langchain/src/chains/llm_chain.ts
langchain/src/chains/sequential_chain.ts
langchain/src/chains/tests/llm_chain.int.test.ts
langchain/src/chains/tests/simple_sequential_chain.int.test.ts
langchain/src/chat_models/anthropic.ts

Fix example for chatanthropic, Fix LLMChain cancellation when using memory, Allow any chain to be cancelled

---

.devcontainer/README

Add a readme in the .devcontainer folder to explain a bit more about how to use it. Following the same phrasing as https://github.com/hwchase17/langchain/pull/6189.
cc @vowelparrot

Add dev container readme

---

langchain/src/chat_models/openai.ts
langchain/src/llms/openai-chat.ts
langchain/src/llms/openai.ts

Add error handling for openai streaming when errors are sent as events in the SSE stream

---

langchain/package.json
langchain/src/base_language/count_tokens.ts
yarn.lock

Fix: Updated tiktoken to 1.0.7 and add gpt-3.5-turbo-16k to model token size.

---

langchain/package.json

Release 0.0.96

---

langchain/package.json
langchain/src/client/langchainplus.ts
yarn.lock

Use eval session rather than debug

Add eval mode

---

langchain/src/client/langchainplus.ts

Fix run on dataset errors from one run interrupting other runs

---

langchain/src/agents/initialize.ts

Add tags to agent executor on initialize

---

langchain/src/document_loaders/tests/cheerio.int.test.ts
langchain/src/document_loaders/web/cheerio.ts

Supports non-utf-8 character sets for Cheerio

Supports non-utf-8 character sets for Cheerio

---

langchain/src/chat_models/openai.ts

Add function_call to the request to chat open ai.

---

langchain/src/chains/index.ts

Added exporting of SQL prompts

---

langchain/package.json
langchain/src/callbacks/handlers/tracer_langchain.ts
langchain/src/callbacks/manager.ts
langchain/src/callbacks/tests/langchain_tracer.int.test.ts
langchain/src/client/langchainplus.ts
langchain/src/client/tests/langchainplus.int.test.ts
yarn.lock

Depends on a new SDK version - will bump the dependency when that occurs.

Update session references to project

---

langchain/src/document_loaders/fs/unstructured.ts

Move unstructured strategy flag to formData.

---

docs/package.json
yarn.lock

This PR introduces a new Mendable UI tailored to a better search experience.
We're more closely integrating our traditional search with our AI generation.
With this change, you won't have to tab back and forth between the mendable bot and the keyword search. Both types of search are handled in the same bar. This should make the docs easier to navigate. while still letting users get code generations or AI-summarized answers if they so wish. Also, it should reduce the cost.
Would love to hear your feedback :)

docs: New experimental UI for Mendable Search 

---

examples/src/models/llm/openai-batch.ts
langchain/src/callbacks/manager.ts
langchain/src/callbacks/tests/callbacks.test.ts
langchain/src/chat_models/base.ts
langchain/src/chat_models/tests/chatopenai.int.test.ts
langchain/src/llms/base.ts

split up batch runs for llms and chat models in generate

---

langchain/src/chat_models/googlevertexai.ts
langchain/src/chat_models/tests/chatgooglevertexai.int.test.ts
langchain/src/chat_models/tests/chatgooglevertexai.test.ts

Add support for Google Vertex AI PaLM Codey codechat- models. 

---

docs/docs/modules/indexes/vector_stores/index.mdx

mention weaviate as an option

---

langchain/src/callbacks/base.ts
langchain/src/callbacks/index.ts
langchain/src/callbacks/manager.ts
langchain/src/chains/openai_functions/tests/tagging.int.test.ts
langchain/src/chat_models/base.ts
langchain/src/chat_models/openai.ts
langchain/src/chat_models/tests/chatopenai.int.test.ts
langchain/src/llms/base.ts
langchain/src/llms/openai-chat.ts
langchain/src/llms/openai.ts
langchain/src/llms/tests/openai.int.test.ts
langchain/src/types/openai-types.ts

- multiple prompts are batch calls to generate()
- multiple completions are calls with n>1

Add streaming support for LLM and Chat Model calls with multiple prompts or completions

---

docs/docs/modules/memory/examples/buffer_memory.md

Add missing import to buffer_memory.md

---

docs/docusaurus.config.js

Small update that should improve readability

Improve contrast of code blocks in docs

---

langchain/src/document_loaders/web/apify_dataset.ts

JS version of https://github.com/hwchase17/langchain/pull/6862
A user has been testing the Apify integration inside langchain and he was not able to run saved Actor tasks.
This PR adds support for calling saved Actor tasks on the Apify platform to the existing integration. The structure of very similar to the one of calling Actors.

feat: Add `fromActorTaskCall` to `ApifyDatasetLoader`

---

langchain/src/client/langchainplus.ts

Add max concurrency to runOnDataset function

---

langchain/src/callbacks/base.ts
langchain/src/callbacks/manager.ts

Add tags to all callback handler methods

---

langchain/src/callbacks/handlers/tracer.ts

Collect llm new token events in tracer

---

langchain/package.json
yarn.lock

Update SDK Version

---

examples/src/callbacks/docs_request_callbacks.ts
langchain/src/agents/tests/openai.int.test.ts
langchain/src/base_language/index.ts
langchain/src/callbacks/manager.ts
langchain/src/callbacks/tests/langchain_tracer.int.test.ts
langchain/src/chains/base.ts
langchain/src/chains/llm_chain.ts
langchain/src/chains/tests/llm_chain.int.test.ts
langchain/src/chat_models/anthropic.ts
langchain/src/chat_models/base.ts
langchain/src/chat_models/openai.ts
langchain/src/llms/base.ts
langchain/src/llms/openai-chat.ts
langchain/src/llms/openai.ts
langchain/src/tools/base.ts
langchain/src/types/openai-types.ts

Update API for tags/metadata to avoid positional args

---

.husky/pre-commit
package.json
yarn.lock

Fix pre commit hooks setup

---

langchain/src/load/tests/__snapshots__/load.test.ts.snap
langchain/src/load/tests/load.test.ts
langchain/src/output_parsers/combining.ts
langchain/src/output_parsers/fix.ts
langchain/src/output_parsers/list.ts
langchain/src/output_parsers/regex.ts

Make some output parsers serializable

---

langchain/src/agents/tests/chat_convo_output_parser_with_retries.int.test.ts
langchain/src/agents/tests/evaluation.int.test.ts
langchain/src/experimental/plan_and_execute/tests/plan_and_execute.int.test.ts
langchain/src/schema/index.ts
langchain/src/stores/tests/dynamodb.int.test.ts
langchain/src/vectorstores/tests/mongodb_atlas.int.test.ts

Fix integration tests

---

examples/src/models/chat/integration_baiduwenxin.ts
langchain/src/chat_models/tests/chatbaiduwenxin.int.test.ts

The migration is related with examples and tests

Migrate HumanChatMessage to HumanMessage in Baidu Wenxin

---

langchain/src/base_language/count_tokens.ts

minor refactor to make the code more readable

refactor: only fallback to approximate if tiktoken fails

---

docs/docs/modules/models/llms/index.mdx
examples/src/models/llm/llm_advanced.ts

I had to dig around in the source code to find the -1 magic param for maxTokens.

docs: add advanced llm parameter example

---

langchain/src/base_language/count_tokens.ts
langchain/src/base_language/tests/count_tokens.test.ts

- test: adding tests for token counting
- fix: correct token counting for 3.5 16k and gpt 4 16k

fix: correct token count for larger context windows

---

langchain/src/chat_models/openai.ts

A simple addition of message type function recognition for PromptLayerChatOpenAI models
Fixes [#1939 ]

added-accommodate-message-type-function

---

langchain/package.json
langchain/src/util/math_utils.ts
langchain/src/util/tests/math_utils.test.ts
yarn.lock

Porting the cosine similarity and maximal marginal relevance functions from the Python package

Add cosine similarity and maximal marginal relevance functions

---

langchain/src/chains/sequential_chain.ts
langchain/src/chains/tests/sequential_chain.test.ts

Hello, I want to express my gratitude for this amazing project and for your efforts in bringing AI closer to Javascript.
The issue was related to the incorrect handling of memory in sub-chains within the sequential chain. This caused memory-based chains to be unable to operate as sub-chains of the sequential chain.
With this PR, sequential chains can now effectively utilise sub-chain memory. In the past, there was an issue where using memory in sub-chains of a sequential chain was problematic. The chain validation phase did not take into account the variables present in the memory of sub-chains, which resulted in memory-based chains being unable to function as sub-chains of the sequential chain. This pull request (PR) tackles and resolves this issue.
Twitter: …

fix(memory): allow composite chains to use sub-chains memory.

---

examples/src/experimental/generative_agents/generative_agents.ts
langchain/src/experimental/generative_agents/generative_agent.ts
langchain/src/experimental/generative_agents/generative_agent_memory.ts
langchain/src/experimental/generative_agents/tests/generative_agent.int.test.ts
langchain/src/retrievers/time_weighted.ts

Refactors generative agents to allow tracing

Generative agent tracing

---

examples/src/memory/redis-advanced.ts
examples/src/memory/redis.ts

Migrate redis memory examples to ioredis

chore(redis examples): use ioredis

---

docs/snippets/modules/chains/document/refine.mdx
examples/src/chains/qa_refine_custom_prompt.ts

Add prompt customization example to refine chain docs

---

examples/src/experimental/generative_agents/generative_agents.ts

fix dialogue to update conversation with each new contribution

---

langchain/src/base_language/index.ts
langchain/src/chains/base.ts
langchain/src/chains/conversation.ts
langchain/src/chains/tests/conversation_chain.int.test.ts
langchain/src/chat_models/anthropic.ts
langchain/src/chat_models/baiduwenxin.ts
langchain/src/chat_models/base.ts
langchain/src/chat_models/googlevertexai.ts
langchain/src/chat_models/openai.ts
langchain/src/chat_models/tests/chatanthropic.int.test.ts
langchain/src/chat_models/tests/chatopenai.int.test.ts
langchain/src/llms/base.ts
langchain/src/llms/googlevertexai.ts
langchain/src/llms/openai-chat.ts
langchain/src/llms/openai.ts
langchain/src/llms/tests/googlevertexai.int.test.ts
langchain/src/llms/tests/openai-chat.int.test.ts
langchain/src/llms/tests/openai.int.test.ts
langchain/src/schema/index.ts
langchain/src/schema/runnable.ts
langchain/src/schema/tests/runnable.test.ts
langchain/src/tools/base.ts
langchain/src/util/stream.ts

Enables more widespread streaming, batch calls.

Single call protocol in JS

---

langchain/src/vectorstores/milvus.ts

update object type of dbConfig in fromTexts method, so will be consistent where dbConfig defined.

Milvus - update object type in fromTexts method

---

docs/docs_skeleton/src/css/custom.css

Mark integrations as Node-only in docs

---

langchain/src/vectorstores/base.ts
langchain/src/vectorstores/mongodb_atlas.ts
langchain/src/vectorstores/tests/mongodb_atlas.int.test.ts

- Removed similaritySearch method override
- Changed similaritySearchVectorWithScore signature
Fixes # (2108)

Fix Issue 2108: Atlas vector store retriever breaking on getRelevantDocuments 

---

docs/docs_skeleton/package.json
docs/docs_skeleton/yarn.lock

Bugs from the current documentation site:
This was a docusaurus bug related to prefers-reduced-motion nested collapsible bug, see this: https://github.com/facebook/docusaurus/issues/8932

fix(docs): fix abnormal behavior when opening docs submenu

---

.husky/pre-commit
docs/extras/modules/data_connection/document_transformers/integrations/html-to-text.mdx
examples/package.json
examples/src/document_transformers/html_to_text.ts
langchain/.gitignore
langchain/package.json
langchain/scripts/create-entrypoints.js
langchain/src/document_transformers/html_to_text.ts
langchain/src/document_transformers/openai_functions.ts
langchain/src/document_transformers/tests/html_to_text.int.test.ts
langchain/src/load/import_constants.ts
langchain/src/load/import_type.d.ts
langchain/src/schema/document.ts
langchain/src/text_splitter.ts
langchain/tsconfig.json

Also makes document transformers runnable.

Make document transformers runnable, adds HTML to text document transformer

---

langchain/src/document_loaders/fs/unstructured.ts

Add check to stop empty documents being returned. Fixes #2144

---

docs/docs_skeleton/docs/modules/memory/index.mdx

Fix minor typo in memory docs

---

docs/extras/modules/data_connection/vectorstores/integrations/vectara.mdx
langchain/src/llms/googlevertexai.ts

This PR adds a couple enhancements to the Vectara vector store docs.

Update Vectara docs

---

langchain/src/vectorstores/milvus.ts

Adding an optional parameter for setting the `max_length` of the Text field.
https://github.com/hwchase17/langchainjs/issues/2186#issue-1838619019

Milvus text field max length

---

docs/docs_skeleton/package.json
docs/docs_skeleton/yarn.lock

This fixes Mendable not completing when tabbing out and fixes the duplicate message issue as well.

docs: (Mendable) Fixes it getting stuck when tabbing out 

---

langchain/src/chat_models/anthropic.ts
langchain/src/chat_models/tests/chatanthropic.int.test.ts

Add optional client options to Anthropic sdk to allow overridable default headers

---

docs/.gitignore
docs/docs_skeleton/docs/community.md
docs/docs_skeleton/sidebars.js
langchain/src/vectorstores/milvus.ts

Adds community page to docs, fix lint

---

docs/extras/use_cases/question_answering/index.mdx

- Keep variable name consistent

fix(qa-doc): rename vectorstore to vectorStore

---

docs/extras/guides/fallbacks.mdx
examples/src/guides/fallbacks/better_model.ts
examples/src/guides/fallbacks/chain.ts
examples/src/guides/fallbacks/long_inputs.ts
examples/src/guides/fallbacks/model.ts
langchain/src/schema/runnable.ts
langchain/src/schema/tests/runnable.test.ts

Distinguishing specific errors is a bit dicier/hacky in JS than Python at the moment, so will leave out handled exceptions for now.

Adds runnables with fallbacks

---

docs/extras/modules/data_connection/document_loaders/integrations/web_loaders/youtube.mdx
examples/src/document_loaders/youtube.ts
langchain/.gitignore
langchain/package.json
langchain/scripts/create-entrypoints.js
langchain/src/document_loaders/web/youtube.ts
langchain/src/load/import_constants.ts
langchain/src/load/import_type.d.ts
langchain/tsconfig.json
yarn.lock

Introducing the ability to load a transcription of an YouTube video using YouTube document loader.

Implement YouTube transcripts loader

---

langchain/src/vectorstores/elasticsearch.ts
langchain/src/vectorstores/tests/elasticsearch.int.test.ts

Passing k as size on elastic vector store
Also include test to validate the length
Fixes #2229

Add size parameter to elastic search query #2229

---

docs/docs_skeleton/docs/modules/agents/agent_types/index.mdx

Fixing grammar/typo (nixing extra, unnecessary word)
Twitter handle: `@mannybreno`

Minor content correction on Agent Types doc's

---

langchain/package.json
yarn.lock

Updated Langsmith-sdk package version to 0.0.26.

Update langsmith package version

---

langchain/src/chat_models/ollama.ts

Update ChatOllama instructions

---

docs/docs_skeleton/docs/modules/data_connection/index.mdx
docs/extras/modules/data_connection/text_embedding/how_to/caching_embeddings.mdx
docs/vercel.json

Update retrieval docs, move embeddings docs

---

docs/extras/modules/agents/tools/integrations/wolframalpha.mdx
examples/src/tools/wolframalpha.ts
langchain/src/tools/index.ts
langchain/src/tools/wolframalpha.ts

Add wolframalpha tool
@ArielHenryson

add wolframalpha tool

---

langchain/src/callbacks/handlers/tracer.ts
langchain/src/callbacks/tests/tracer.test.ts

Use an isostring for run events time in tracer

---

langchain/package.json
langchain/src/callbacks/base.ts
langchain/src/callbacks/handlers/tracer.ts
langchain/src/callbacks/handlers/tracer_langchain.ts
langchain/src/callbacks/manager.ts
langchain/src/schema/output_parser.ts
langchain/src/schema/runnable.ts
yarn.lock

Pass full transform streamed inputs into traces, fix run order

Runnable sequence tracing fixes

---

docs/extras/modules/model_io/models/chat/integrations/google_vertex_ai.mdx
docs/extras/modules/model_io/models/llms/integrations/google_vertex_ai.mdx
langchain/src/chat_models/tests/chatgooglevertexai.int.test.ts
langchain/src/llms/tests/googlevertexai.int.test.ts

Google announced public preview of text-bison-32k and chat-bison-32k.
Tested each and verified that they work.
Documented common available model names.
(There are no library code changes required.)

Verified and documented that text-bison-32k and chat-bison-32k work

---

langchain/.gitignore
langchain/package.json
langchain/scripts/create-entrypoints.js
langchain/src/load/import_map.ts
langchain/tsconfig.json
test-exports-cf/src/entrypoints.js
test-exports-cjs/src/entrypoints.js
test-exports-esbuild/src/entrypoints.js
test-exports-esm/src/entrypoints.js
test-exports-vercel/src/entrypoints.js
test-exports-vite/src/entrypoints.js

Export document base classes

---

langchain/package.json

Release 0.0.142

---

langchain/src/chat_models/openai.ts
langchain/src/embeddings/openai.ts
langchain/src/llms/openai-chat.ts
langchain/src/llms/openai.ts

Fallback to empty string for OpenAI key if Azure key is set

---

langchain/src/base_language/index.ts
langchain/src/chat_models/base.ts
langchain/src/prompts/chat.ts
langchain/src/prompts/tests/chat.test.ts
langchain/src/schema/index.ts

Allow a wider variety of message like objects into chat prompt templates and chat models

---

docs/extras/modules/data_connection/vectorstores/integrations/pinecone.md
langchain/src/vectorstores/pinecone.ts

Pinecone vectorstore is waiting for each request to finish before starting the new one. This code updates the requests to use Promise.all instead of a for loop.

perf(pinecone): update pinecone vectorstore to use Promise.all

---

langchain/src/vectorstores/tests/vectara.int.test.ts
langchain/src/vectorstores/vectara.ts

We are aware that this introduces a breaking change and we are okay with that.

Add file name property to addFiles function in Vectara

---

docs/snippets/modules/chains/popular/summarize.mdx
examples/src/chains/summarization_separate_output_llm.ts
examples/src/chains/summarization_seperate_output_llm.ts
langchain/src/chains/question_answering/load.ts
langchain/src/chains/summarization/load.ts

Refactor the code to achieve two goals:
1. Utilize a dedicated Language Model (LLM) as the final summary LLM to cater to specific LLM requirements at different stages of the chain.
2. Streamline the final results only, excluding the intermediate step's output from the streaming process.

Refactor: add combineLLM & refineLLM to loadQAChain&loadSummarizationChain

---

langchain/package.json
langchain/src/llms/replicate.ts
yarn.lock

Detect and set prompt key for a given Replicate model

---

docs/extras/expression_language/how_to/_category_.yml
docs/extras/expression_language/how_to/routing.mdx
examples/.eslintrc.cjs
examples/src/guides/expression_language/how_to_routing_custom_function.ts
examples/src/guides/expression_language/how_to_routing_runnable_branch.ts
langchain/src/schema/runnable/base.ts
langchain/src/schema/runnable/branch.ts
langchain/src/schema/runnable/index.ts
langchain/src/schema/tests/runnable.test.ts

Adds RunnableBranch

---

langchain/src/base_language/count_tokens.ts
langchain/src/types/openai-types.ts

Also adds a doc note about how tokens are calculated.

feat(minor): export model name type for easy reuse

---

langchain/src/chat_models/base.ts
langchain/src/chat_models/ollama.ts
langchain/src/llms/ollama.ts
langchain/src/util/ollama.ts

Fix Ollama tracing and output

---

docs/extras/use_cases/summarization.mdx
examples/src/use_cases/youtube/podcast_summary.ts

@SebastjanPrachovskij this will make it visible under https://js.langchain.com/docs/use_cases/summarization :)

Tweak summarization example, add to docs

---

README.md

Update `README.md` to better reflect what langchainjs is capable of. 
Added:
- 'What can this help with' section
Updated:
- Documentation section: Added overview of documentation
- What is this section: Added common uses and examples
- Contributing Section: Reworded text
- Relationship with Python LangChain: Added emoji
- Quick Install: Added emoji and more installation options
- Supported Environments: Added emoji

Update README.md to better describe LangChainJS and it's capabilities

---

docs/extras/modules/data_connection/vectorstores/integrations/vectara.mdx
langchain/src/vectorstores/vectara.ts

* Updated documentation (minor)
* Added X-Source in API header

Minor update to Vectara

---

langchain/src/prompts/few_shot.ts
langchain/src/prompts/prompt.ts
langchain/src/prompts/template.ts

Remove jinja2

---

langchain/src/chat_models/bedrock.ts
langchain/src/llms/bedrock.ts
langchain/src/llms/tests/bedrock.int.test.ts

Use invoke method for non-streaming Bedrock calls

---

docs/docs_skeleton/docs/get_started/quickstart.mdx

Fix: Corrected typos

---

docs/docs_skeleton/src/css/custom.css

Docs: Light mode node-only button style

---

langchain/src/callbacks/base.ts
langchain/src/callbacks/handlers/log_stream.ts
langchain/src/callbacks/manager.ts
langchain/src/chains/base.ts
langchain/src/chat_models/base.ts
langchain/src/llms/base.ts
langchain/src/schema/retriever.ts
langchain/src/schema/runnable/base.ts
langchain/src/schema/tests/lib.ts
langchain/src/schema/tests/runnable_binding.test.ts
langchain/src/schema/tests/runnable_stream_log.test.ts
langchain/src/tools/base.ts

Allow overriding runName in withConfig and update streamLog output

---

examples/src/chains/graph_db_custom_prompt.ts

Add good practices for providing custom queries for generating Cypher statements.

update custom cypher example

---

langchain/src/document_loaders/fs/unstructured.ts

This commit adds additional optional props for use with the UnstructuredLoader. Info about them retrieved from https://github.com/Unstructured-IO/unstructured-api and https://unstructured-io.github.io/unstructured/api.html

Unstructured API - additional props

---

langchain/src/vectorstores/elasticsearch.ts
langchain/src/vectorstores/tests/elasticsearch.int.test.ts

Updated the ElasticVectorSearch constructor to use a customized user-agent for the elasticsearch client for telemetry.

elasticsearch: customize user-agent for es client

---

docs/docs/security.md

General security doc, ported from PY docs

Feat: general security doc

---

examples/src/models/chat/integration_cloudflare_workersai.ts
examples/src/models/llm/cloudflare_workersai.ts
langchain/src/chat_models/cloudflare_workersai.ts
langchain/src/chat_models/tests/chatcloudflare_workersai.int.test.ts
langchain/src/experimental/chains/tests/violation_of_expectations_chain.int.test.ts
langchain/src/llms/cloudflare_workersai.ts
langchain/src/llms/tests/cloudflare_workersai.int.test.ts

Adds base URL support for Cloudflare WorkersAI

---

docs/docs/modules/agents/how_to/agent_structured.mdx

forgot to include this in the agent runnables pr 🫠

fix: updated title of docs and file name

---

examples/src/models/chat/integration_googlepalm.ts
langchain/src/llms/googlepalm.ts
langchain/src/llms/tests/googlepalm.test.ts

```
Error: 3 INVALID_ARGUMENT: * GenerateTextRequest.top_p: top_p must be in the range [0, 1].
```
Fixes ^

fix top_p value

---

langchain/src/vectorstores/qdrant.ts
langchain/src/vectorstores/tests/qdrant.int.test.ts

Also improves thrown error messages

Avoid hardcoding embedding size to OpenAI dimensions in Qdrant client

---

langchain/src/storage/file_system.ts

Use node: prefixed deps

---

langchain/src/vectorstores/pgvector.ts
langchain/src/vectorstores/tests/pgvector.int.test.ts

Closes #3045
fix bug where when you try to add more docs than the default chunk size (also made configurable in this PR) it failed
added a test to confirm.

Fix: bug where pgvector cant add more than chunk size

---

docs/docs/modules/data_connection/vectorstores/integrations/pinecone.md
langchain/src/vectorstores/pinecone.ts
langchain/src/vectorstores/tests/pinecone.int.test.ts

By popular demand, CC @zackproser 
TODO: docs

Adds MMR search for Pinecone

---

langchain/src/memory/index.ts

Adds getOutputValue to langchain/memory exports
Fixes #3031

Add getOutputValue to langchain/memory exports

---

langchain/src/vectorstores/convex.ts

Fix Convex typo

---

langchain/src/chat_models/googlevertexai/common.ts
langchain/src/chat_models/googlevertexai/index.ts
langchain/src/chat_models/googlevertexai/web.ts
langchain/src/chat_models/tests/chatgooglevertexai.int.test.ts
langchain/src/chat_models/tests/chatgooglevertexai_web.int.test.ts
langchain/src/embeddings/googlevertexai.ts
langchain/src/experimental/hubs/makersuite/googlemakersuitehub.ts
langchain/src/experimental/multimodal_embeddings/googlevertexai.ts
langchain/src/llms/googlevertexai/common.ts
langchain/src/llms/googlevertexai/index.ts
langchain/src/llms/googlevertexai/web.ts
langchain/src/llms/tests/googlevertexai.int.test.ts
langchain/src/llms/tests/googlevertexai_web.int.test.ts
langchain/src/types/googlevertexai-types.ts
langchain/src/util/googlevertexai-connection.ts
langchain/src/util/googlevertexai-gauth.ts
langchain/src/util/googlevertexai-webauth.ts
langchain/src/util/tests/googlevertexai-connection.test.ts
langchain/src/vectorstores/googlevertexai.ts

Fixes #2594 
Obsoletes #2625 (which can be abandoned and deleted).
The parser here is... probably not the most efficient, but should be efficient enough for the purposes. And it doesn't require any new outside libraries.

Implement streaming for GoogleVertexAI text and chat models

---

langchain/src/chat_models/bedrock.ts
langchain/src/chat_models/tests/chatbedrock.int.test.ts
langchain/src/llms/bedrock.ts
langchain/src/llms/tests/bedrock.int.test.ts
langchain/src/util/bedrock.ts

Fix streaming bug in Bedrock LLM family

---

examples/src/chains/graph_db_custom_prompt.ts
examples/src/chains/graph_db_neo4j.ts
examples/src/chains/graph_db_return_direct.ts

The examples didn't work as the graph schema was undefined if you start with an empty database.

Update Neo4j examples

---

docs/docs/modules/agents/agent_types/openai_functions_agent.mdx

<details open>
<summary>Docs added</summary>
</details>

With memory example to OAI functions agent

---

langchain/src/chat_models/iflytek_xinghuo/index.ts
langchain/src/chat_models/iflytek_xinghuo/web.ts

Was giving the `crypto could not be resolved. treating it as an optional dependency` warning on build (lost the exact warning message)

Fixed crypto could not be resolved warning on build

---

langchain/src/chat_models/baiduwenxin.ts
langchain/src/chat_models/tests/chatbaiduwenxin.int.test.ts

Fix wrong error handling in baidu wenxin chat model (#3115)

fix: wrong error handling in baidu wenxin chat model (#3115)

---

package.json
yarn.lock

Bump OpenAI dep

---

langchain/src/document_loaders/web/apify_dataset.ts

This PR adds the ability to have an asynchronous dataset mapping function for the `ApifyDatasetLoader`.
Normally, the [Website Content Crawler](https://apify.com/apify/website-content-crawler) dataset result items look like this:
```
{
"text": "This is the property that stores the pageContent of the scraped page",
"url": "https://scraped-url.com",
...,
}
```
However, it also supports a mode called [`saveFiles`](https://apify.com/apify/website-content-crawler/input-schema) where the crawler is able to save any files it encounters during the web crawl. A dataset item corresponding to this kind of web-page looks like this:
```
{
"text": null,
"url": "https://scraped-url.com/uploads/super-important-document.pdf"
...,
}
```
Notice that the page content is not readily available. Instead, one …

feat(apify): support async dataset mapping function

---

langchain/src/prompts/chat.ts
langchain/src/schema/tests/base_message.test.ts

Allow for formatting prompt strings when using openai image_url's in messages

format prompt messages with openai image content

---

cookbook/openai_vision_multimodal.ipynb
langchain/src/prompts/chat.ts

Before, chat prompt outputs would show as `not_implemented` in LangSmith
CC @nfcampos @bracesproul @dqbd 🤦

Fix chat prompt serialization

---

langchain/src/util/ollama.ts

Chunks aren't guaranteed to be split at newlines – only attempts to parse and yield json objects sent between newlines in the response

ollama: handle chunks that are not newline delimited

---

docs/core_docs/docs/modules/model_io/output_parsers/http_response.mdx
examples/src/prompts/http_response_output_parser.ts
examples/src/prompts/http_response_output_parser_custom.ts
examples/src/prompts/http_response_output_parser_event_stream.ts
langchain/src/output_parsers/http_response.ts
langchain/src/output_parsers/index.ts
langchain/src/output_parsers/openai_functions.ts
langchain/src/output_parsers/tests/http_response.test.ts
langchain/src/output_parsers/tests/openai_functions.int.test.ts
langchain/src/schema/output_parser.ts

Handy for emitting chunks as event streams
CC @nfcampos @dqbd @eyurtsev

Adds HTTP output parser to parse chunks into different content types

---

langchain/src/chat_models/bedrock/web.ts
langchain/src/llms/bedrock/web.ts

Fix broken fetch usage for CFW

---

langchain/src/retrievers/chaindesk.ts

reference: https://docs.chaindesk.ai/api-reference/endpoint/datastores/query
cc @gmpetrov

feat: add filters to `ChaindeskRetriever`

---

langchain/src/chat_models/bedrock/web.ts
langchain/src/llms/bedrock/web.ts

Fix streaming of Bedrock on Cloudflare Workers

---

docs/core_docs/docs/modules/agents/agent_types/openai_assistant.mdx
langchain/src/experimental/openai_assistant/index.ts
langchain/src/experimental/openai_assistant/tests/openai_assistant.int.test.ts

* You can now remove an OpenAI assistant
* Add modify and retrieve openAI assistant
1. Add doc
2. Add test
3. `yarn build` on `./langchain`

langchain[patch]: Add modify and retrieve openAI assistant

---

langchain-core/package.json
langchain-core/src/messages/index.ts
langchain/package.json
yarn.lock

core[patch]: Fix getBufferString method

---

CONTRIBUTING.md

Implementation for updating docs if run is deprecated
See below issue for details
Fixes #3480

chore: update contribution docs

---

langchain/src/agents/index.ts

langchain[patch]: Adds missing export

---

langchain-core/src/language_models/base.ts

core[patch]: Catch tiktoken errors

---

examples/src/llms/watsonx_ai.ts

Chore to remove the run block from this example to cleanup the documentation page

chore(WatsonX.ai example): remove run

---

docs/core_docs/docs/modules/agents/agent_types/openai_functions_agent.mdx
docs/core_docs/docs/modules/agents/agent_types/openai_tools_agent.mdx
examples/src/agents/openai_runnable_with_memory.ts

Fix OpenAI agent docs

---

langchain-core/src/runnables/base.ts
langchain-core/src/runnables/tests/runnable_history.test.ts

core[patch]: Simplify RunnableSequence transform implementation

---

langchain-core/src/tools.ts
langchain/src/agents/tests/mrkl_agent.int.test.ts
libs/langchain-community/src/tools/dynamic.ts

core[patch],community[patch]: Make traced DynamicTool runs use tool name

---

libs/langchain-mistralai/src/chat_models.ts
libs/langchain-mistralai/src/embeddings.ts

mistral[minor]: Dynamically import mistral

---

docs/core_docs/docs/integrations/chat/google_generativeai.mdx
docs/core_docs/docs/integrations/chat/google_palm.mdx
docs/core_docs/docs/integrations/llms/google_palm.mdx
docs/core_docs/docs/integrations/text_embedding/google_generativeai.mdx
docs/core_docs/docs/integrations/text_embedding/google_palm.mdx

Updated docs to reflect usage of PaLM based classes

Updated docs to reflect usage of PaLM based classes

---

docs/core_docs/docs/integrations/llms/togetherai.mdx
examples/src/models/llm/togetherai.ts
examples/src/models/llm/togetherai_stream.ts

todo: update streaming langsmith link in docs when it comes in

docs[patch]: Use mixtral default model for togetherai

---

docs/core_docs/docs/modules/agents/agent_types/openai_assistant.mdx

Fixes 3 documentation issues discussed with @jacoblee93 via Slack

Fix 1 typo in Assistants Docs and added 2 extra suggestions

---

libs/langchain-community/src/llms/togetherai.ts

Add support for setting max_tokens for TogetherAI

Add missing max_tokens option to TogetherAI

---

libs/langchain-google-genai/src/chat_models.ts
libs/langchain-google-genai/src/tests/chat_models.int.test.ts

google-genai[patch]: Hookup callbacks to stream & generate methods

---

langchain/src/index.ts

langchain[patch]: Adds warning when attempting to import from root entrypoint

---

libs/langchain-openai/package.json

integrations[patch]: Bump version

---

examples/src/agents/agent_structured.ts

docs[patch]: Fix structured agent output example

---

langchain-core/src/prompts/chat.ts
langchain-core/src/prompts/tests/chat.test.ts

Implement optional message placeholder in js

---

langchain-core/src/runnables/passthrough.ts
langchain-core/src/runnables/tests/runnable_map.test.ts

RunnablePassthrough.pick()

---

langchain-core/src/runnables/base.ts
langchain-core/src/runnables/tests/runnable.test.ts

Implement stream for runnable lambda

---

langchain-core/src/prompts/chat.ts
langchain-core/src/prompts/tests/chat.test.ts

core[patch]: Fix optional message placeholder use in a chat prompt template

---

langchain-core/src/runnables/base.ts

Add optional name for runnable sequence

---

langchain-core/src/chat_history.ts
langchain-core/src/runnables/history.ts
langchain-core/src/utils/testing/index.ts

core[patch]: Fix runnable with message history for async histories

---

docs/api_refs/typedoc.json
docs/core_docs/code-block-loader.js
docs/core_docs/docs/get_started/installation.mdx
docs/core_docs/docs/get_started/quickstart.mdx
environment_tests/test-exports-bun/src/entrypoints.js
environment_tests/test-exports-cf/src/entrypoints.js
environment_tests/test-exports-cjs/src/entrypoints.js
environment_tests/test-exports-esbuild/src/entrypoints.js
environment_tests/test-exports-esm/src/entrypoints.js
environment_tests/test-exports-vercel/src/entrypoints.js
environment_tests/test-exports-vite/src/entrypoints.js
examples/src/chat/memory.ts
examples/src/get_started/quickstart.ts
examples/src/get_started/quickstart2.ts
examples/src/get_started/quickstart3.ts
langchain-core/src/runnables/base.ts
langchain/.gitignore
langchain/package.json
langchain/scripts/create-entrypoints.js
langchain/src/chains/combine_documents/base.ts
langchain/src/chains/combine_documents/index.ts
langchain/src/chains/combine_documents/reduce.ts
langchain/src/chains/combine_documents/stuff.ts
langchain/src/chains/retrieval.ts
langchain/src/chains/tests/combine_docs_chain.int.test.ts
langchain/src/load/import_map.ts
libs/langchain-community/src/embeddings/ollama.ts
libs/langchain-community/src/utils/momento.ts

docs[major]: Update quickstart and installation pages

---

langchain-core/src/prompt_values.ts
langchain-core/src/runnables/base.ts
langchain-core/src/runnables/config.ts
langchain-core/src/runnables/index.ts
langchain-core/src/runnables/tests/runnable.test.ts
langchain-core/src/utils/stream.ts
langchain/src/schema/runnable/config.ts

core[patch]: Fix tracing order for transform streaming runnables

---

langchain-core/src/runnables/base.ts
langchain-core/src/utils/stream.ts

Return run manager arg to not being a promise

---

libs/langchain-google-genai/package.json

google-genai[patch]: Release 0.0.7

---

langchain-core/src/tracers/base.ts
langchain-core/src/tracers/tests/tracer.test.ts

core[patch]: Compute trace_id and dotted_run_id client side

---

libs/langchain-community/src/chat_models/bedrock/web.ts
libs/langchain-community/src/llms/bedrock/web.ts

fix a bug in Bedrock streaming

---

docs/core_docs/docs/modules/model_io/llms/quick_start.mdx

Fixes  https://github.com/langchain-ai/langchainjs/issues/3888 
Corrected typo in LLM quickstart section heading.

docs[patch]: update llm quickstart section heading

---

langchain-core/.gitignore
langchain-core/package.json
langchain-core/scripts/create-entrypoints.js
langchain-core/src/load/import_map.ts
langchain-core/src/tracers/initialize.ts
langchain-core/src/tracers/tracer_langchain_v1.ts

core[patch]: Readd core entrypoint

---

langchain-core/package.json
langchain-core/src/utils/stream.ts

core[patch]: Narrow iterable readable stream typing

---

libs/langchain-community/src/chat_models/ollama.ts
libs/langchain-community/src/chat_models/tests/chatollama.int.test.ts
libs/langchain-community/src/embeddings/ollama.ts
libs/langchain-community/src/llms/ollama.ts
libs/langchain-community/src/utils/ollama.ts

community[minor]: accept num_predict option as a param

---

langchain-core/src/prompts/template.ts

core[patch]: Add export

---

langchain-core/src/runnables/base.ts
langchain-core/src/runnables/tests/runnable_tracing.int.test.ts
langchain-core/src/tracers/tests/tracer.test.ts
langchain-core/src/utils/testing/index.ts

core[patch]: Enable tracer to handle Date outputs

---

docs/core_docs/docs/get_started/quickstart.mdx

docs[patch]: Fix bad import in docs

---

langchain-core/src/utils/stream.ts

Thank you @MattiasBuelens for the tip!

core[patch]: Adjust iterable readable stream typing

---

langchain/src/load/tests/load.test.ts

ci[patch]: Fix CI

---

docs/core_docs/docs/modules/agents/how_to/agent_structured.mdx
docs/core_docs/docs/modules/agents/how_to/custom_agent.mdx
examples/src/agents/agent_structured.ts
examples/src/agents/custom_agent.ts
examples/src/agents/openai_runnable.ts
examples/src/agents/openai_runnable_stream.ts
examples/src/agents/openai_runnable_stream_log.ts
examples/src/agents/openai_runnable_with_memory.ts
examples/src/agents/openai_tools_runnable.ts
langchain/package.json
langchain/src/agents/openai_functions/index.ts
langchain/src/agents/openai_functions/output_parser.ts
langchain/src/agents/openai_tools/index.ts
langchain/src/agents/openai_tools/output_parser.ts
langchain/src/agents/tests/runnable.int.test.ts
langchain/src/agents/tests/structured_output_runnables.int.test.ts
langchain/src/experimental/chat_models/anthropic_functions.ts
langchain/src/tools/convert_to_openai.ts
libs/langchain-community/src/chat_models/minimax.ts
libs/langchain-openai/package.json
libs/langchain-openai/src/chat_models.ts
libs/langchain-openai/src/utils/openai.ts
yarn.lock

langchain[patch], openai[patch]: Use new function calling utils in all docs

---

langchain-core/src/runnables/base.ts

core[patch]: Fix return type of .pipe()

---

langchain-core/src/runnables/base.ts
langchain-core/src/runnables/branch.ts
langchain-core/src/runnables/config.ts
langchain-core/src/runnables/index.ts

core[patch]: Refactor patchConfig method and add ensureConfig

---

docs/core_docs/docs/expression_language/interface.mdx
examples/src/guides/expression_language/interface_batch_with_options.ts
examples/src/retrievers/multi_vector_hypothetical.ts
examples/src/retrievers/multi_vector_summary.ts
langchain-core/src/language_models/base.ts
langchain-core/src/runnables/base.ts
langchain-core/src/runnables/router.ts

core[patch]: Use new batch maxConcurrency parameter in runnable config

---

libs/langchain-community/src/vectorstores/faiss.ts
libs/langchain-community/src/vectorstores/tests/faiss.int.test.data/faiss.int.test.py
libs/langchain-community/src/vectorstores/tests/faiss.int.test.data/requirements.txt
libs/langchain-community/src/vectorstores/tests/faiss.int.test.ts

fix #4027 loadFromPython failed

---

langchain-core/src/callbacks/manager.ts
langchain-core/src/retrievers.ts
langchain-core/src/runnables/base.ts
langchain-core/src/runnables/config.ts
langchain/src/runnables/tests/runnable_remote.test.ts

- merge now supports merging many configs
- fix issues in edge cases of merge
- call ensure everywhere configs are used
- ensure assigns primitive configurable keys to tracer metadata

Update runnable config ensure and merge to match py

---

libs/langchain-community/src/vectorstores/redis.ts
libs/langchain-community/src/vectorstores/tests/redis.int.test.ts
test-int-deps-docker-compose.yml

community[patch]: Add fallback for missing metadata in Redis documents

---

langchain-core/src/runnables/base.ts
langchain-core/src/runnables/config.ts
langchain-core/src/runnables/tests/runnable.test.ts
langchain-core/src/utils/stream.ts
langchain-core/src/utils/testing/index.ts

core[minor]: Buffer the first chunk on .stream() calls to catch streaming errors immediately on startup

---

docs/core_docs/docs/modules/model_io/index.mdx

fixed issue #4097

---

libs/langchain-community/package.json

Changelog (autogenerated):
* Add Memgraph support (#4008) (05c035ea)
* Add Amazon Knowledge Bases retriever support (#4035) (74269c30)
* community[patch]: Allow for firestore message history with dynamic collections & docs (#4122) (6abc84ed)
* Updated message_history.mdx documentation for missing module import (#4136) (7e8db5b8)
* all[patch]: Drop unused release-branch.sh script (#4134) (4d2f2d9c)
* Release 0.0.2 (#4135) (fc951159)
* scritps[minor]: use config file for scripts package (#4133) (826dd92e)
* Adds deployment guide (#4128) (5df71ccb)
* infra[minor]: Add codecov to CI & run all unit tests in CI (#4126) (e935b891)
* community[minor]: Add indexes module (#4081) (da22f3c6)
* PyInterpreter Import Notes (#4100) (f4dd83da)
* update docs (#4116) (c267f99e)

community[patch]: Release 0.0.20

---

langchain/package.json
yarn.lock

langchain[patch]: Relax legacy Pinecone dep

---

docs/core_docs/docs/guides/langsmith_evaluation.mdx
examples/src/guides/langsmith/eval_walkthrough.ts
langchain/src/smith/config.ts
langchain/src/smith/runner_utils.ts

langchain[patch]: Update evaluation docstrings and example

---

langchain-core/src/runnables/base.ts
langchain-core/src/runnables/branch.ts
langchain-core/src/runnables/tests/runnable_branch.test.ts

core[minor]: Add streaming for runnable branch

---

docs/core_docs/docs/integrations/text_embedding/openai.mdx
examples/src/embeddings/openai.ts
examples/src/embeddings/openai_dimensions.ts
libs/langchain-exa/src/tests/retrievers.int.test.ts
libs/langchain-openai/package.json
libs/langchain-openai/src/embeddings.ts
libs/langchain-openai/src/tests/embeddings.int.test.ts
yarn.lock

openai[patch]: Adds support for dimensions param for OpenAI v3 embeddings

---

libs/langchain-google-genai/src/utils.ts

I tried to use gemini pro with the code like one below, and it throws the following error:
```bash
.../app/node_modules/@langchain/google-genai/dist/utils.cjs:32
throw new Error(`Unknown / unsupported author: ${author}`);
```
also found null reference exception here: .../app/node_modules/@langchain/google-genai/dist/utils.cjs:173
```ts
const text = content?.parts[0]?.text ?? "";
```
```ts
import dotenv from 'dotenv';
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { MessagesPlaceholder, SystemMessagePromptTemplate } from "@langchain/core/prompts";
import { RunnableWithMessageHistory, RunnableSequence } from "@langchain/core/runnables";
import { ChatMessageHistory } from "langchain/stores/message/in_memory";
import { ChatGoogleGenerativeAI } from …
```

google-genai[patch]: fixing chat converstaion in the chat model

---

libs/langchain-google-genai/package.json
libs/langchain-google-genai/src/utils.ts
yarn.lock

google-genai[patch]: Bump SDK version, bugfix

---

libs/langchain-cohere/package.json

Changelog:
* cohere chat history (#4188) (e38cb99c)

cohere[patch]: Release 0.0.3

---

docs/core_docs/docs/get_started/quickstart.mdx

docs[patch]: Fix typo

---

langchain-core/src/runnables/base.ts
langchain/src/agents/tests/create_openai_functions_agent.int.test.ts
langchain/src/document.ts

core[patch]: Emit stream log chunks without awaiting for the first stream chunk

---

libs/langchain-weaviate/.gitignore
libs/langchain-weaviate/package.json

(from david's changes earlier today)

weaviate[patch]: Add build auto-gen missing components

---

libs/langchain-mistralai/package.json

mistralai[patch]: Release 0.0.7

---

libs/langchain-google-genai/package.json

google-genai[patch]: Release 0.0.9

---

langchain-core/src/runnables/base.ts

core[patch]: Pass runnable config directly to RunnableLambda

---

langchain-core/src/prompts/image.ts
langchain-core/src/prompts/index.ts

core[patch]: Properly export ImagePromptTemplate

---

.github/workflows/unit-tests.yml
langchain/src/chains/tests/constitutional_chain.int.test.ts

modified one line of LC code to trigger tests

ci[patch]: Set concurrency to 1 for unit tests ci

---

docs/core_docs/docs/expression_language/interface.mdx

docs[patch]: Fix broken link

---

environment_tests/test-exports-bun/src/entrypoints.js
environment_tests/test-exports-cf/src/entrypoints.js
environment_tests/test-exports-cjs/src/entrypoints.js
environment_tests/test-exports-esbuild/src/entrypoints.js
environment_tests/test-exports-esm/src/entrypoints.js
environment_tests/test-exports-vercel/src/entrypoints.js
environment_tests/test-exports-vite/src/entrypoints.js
langchain/src/load/import_constants.ts
langchain/src/load/import_map.ts

langchain[patch]: Rm unwanted build artifacts

---

langchain/package.json
yarn.lock

langchain[patch]: Bump langchainhub dep to latest

---

docs/core_docs/docs/integrations/vectorstores/cloudflare_vectorize.mdx
libs/langchain-cloudflare/src/vectorstores.ts

Support for metadata filtering using Cloudflare Vectorize

cloudflare[patch]: Add metadata filtering support to Cloudflare Vectorize

---

libs/langchain-azure-openai/package.json

azure-openai[patch]: Release 0.0.2

---

docs/core_docs/docs/get_started/quickstart.mdx

docs[patch]: Fix typo in quickstart walkthrough

---

libs/langchain-community/src/chat_models/ollama.ts
libs/langchain-community/src/embeddings/ollama.ts
libs/langchain-community/src/llms/ollama.ts
libs/langchain-community/src/utils/ollama.ts

Fixes # https://github.com/langchain-ai/langchainjs/issues/4282

community[patch]: Add `keep_alive` parameter to Ollama API.

---

libs/langchain-google-genai/README.md

small typo google gen ai readme.md

---

libs/langchain-community/src/utils/cassandra.ts

Similar option available in LangChain python (via CassIO): https://github.com/CassioML/cassio/pull/128

community[patch]: add support for customizable bundle url

---

langchain-core/package.json
langchain-core/src/runnables/base.ts
langchain/package.json
langchain/src/agents/agent.ts
langchain/src/agents/executor.ts
langchain/src/agents/tests/create_openai_tools_agent.int.test.ts
langchain/src/chains/base.ts
langchain/src/embeddings/fake.ts
libs/langchain-community/src/vectorstores/tests/astradb.int.test.ts
yarn.lock

core[patch],langchain[patch]: Fix runnable lambda and agent nested tracing

---

libs/langchain-mistralai/src/chat_models.ts
libs/langchain-mistralai/src/embeddings.ts

Related to
https://github.com/langchain-ai/langchainjs/issues/3662

mistral[patch]: import mistral via class method

---

docs/core_docs/docusaurus.config.js

docs[patch]: Update more dropdown & add chatjs langchain link

---

langchain-core/src/retrievers.ts

Fixes https://github.com/langchain-ai/langchainjs/issues/4510
X: @da_fant

core[patch]: Make `BaseRetriever` generic and pass `Metadata` type to `DocumentInterface`

---

docs/core_docs/data/people.yml

👥 Update LangChain people data

👥 Update LangChain people data

---

docs/core_docs/.gitignore
docs/core_docs/scripts/quatro-build.js

Allows for codeblock formatting!!

docs[minor]: Format notebooks after build

---

langchain-core/src/language_models/base.ts
langchain-core/src/language_models/tests/chat_models.test.ts
langchain-core/src/utils/testing/index.ts

core[minor]: Clean up withStructuredOutput typing

---

libs/langchain-community/src/vectorstores/pgvector.ts

Hi, I found there is an issue with pgvector using collections. This should fix it
Fixes # (issue) https://github.com/langchain-ai/langchainjs/issues/4540

community[patch]: Fix using collections for pgvector

---

langchain/package.json
libs/langchain-community/package.json
libs/langchain-mistralai/package.json
libs/langchain-mistralai/src/chat_models.ts
libs/langchain-openai/package.json
libs/langchain-openai/src/chat_models.ts
yarn.lock

openai[patch],mistral[patch]: Fix typing for withStructuredOutput

---

libs/langchain-mistralai/package.json

mistralai[patch]: Release 0.0.10

---

libs/langchain-openai/package.json

openai[patch]: Release 0.0.16

---

libs/langchain-redis/package.json

redis[patch]: Release 0.0.2

---

docs/core_docs/docs/modules/model_io/index.mdx

Fixes broken links on Model I/O page.

docs[minor]: fix links on model io page

---

langchain-core/src/language_models/base.ts
langchain-core/src/output_parsers/openai_tools/json_output_tools_parsers.ts
langchain-core/src/output_parsers/openai_tools/tests/json_output_tools_parser.test.ts

core[patch]: Allow tools output parser to take and use a Zod schema for validation

---

libs/langchain-openai/package.json
libs/langchain-openai/src/chat_models.ts
libs/langchain-openai/src/tests/chat_models.int.test.ts
libs/langchain-openai/src/tests/chat_models_structured_output.int.test.ts
libs/langchain-openai/src/tests/embeddings.int.test.ts
libs/langchain-openai/src/tests/llms.int.test.ts
yarn.lock

openai[patch]: Make withStructuredOutput validate if passed a Zod schema

---

langchain/package.json
libs/langchain-anthropic/package.json
libs/langchain-anthropic/src/experimental/tool_calling.ts
libs/langchain-mistralai/package.json
libs/langchain-mistralai/src/chat_models.ts
libs/langchain-mistralai/src/tests/chat_models.int.test.ts
libs/langchain-openai/src/chat_models.ts
yarn.lock

mistralai[patch],anthropic[patch]: Make Mistral and Anthropic withStructuredOutput methods validate if given Zod schema

---

libs/langchain-groq/src/chat_models.ts
libs/langchain-groq/src/tests/chat_models.int.test.ts

groq[patch]: Fix stop sequence binding

---

libs/langchain-anthropic/package.json
yarn.lock

anthropic[patch]: Bump SDK version

---

langchain-core/src/callbacks/base.ts
langchain-core/src/callbacks/manager.ts
langchain-core/src/language_models/tests/chat_models.test.ts
langchain-core/src/language_models/tests/llms.test.ts
langchain-core/src/runnables/tests/runnable_branch.test.ts
langchain-core/src/runnables/tests/runnable_stream_events.test.ts
langchain-core/src/tracers/log_stream.ts
langchain-core/src/tracers/root_listener.ts
langchain-core/src/tracers/run_collector.ts

Makes certain callback handlers always awaited.
CC @nfcampos @hinthornw

core[patch]: Fix stream events and stream log with global backgrounded callbacks, add warning

---

libs/langchain-openai/package.json
libs/langchain-openai/src/chat_models.ts
libs/langchain-openai/src/tests/chat_models-extended.int.test.ts
yarn.lock

openai[patch]: Support streaming logprobs

---

libs/langchain-anthropic/package.json

anthropic[patch]: Release 0.1.7

---

docs/core_docs/docs/integrations/text_embedding/zhipuai.mdx
examples/src/embeddings/zhipuai.ts
libs/langchain-community/.gitignore
libs/langchain-community/langchain.config.js
libs/langchain-community/package.json
libs/langchain-community/src/chat_models/tests/chatzhipuai.int.test.ts
libs/langchain-community/src/chat_models/zhipuai.ts
libs/langchain-community/src/embeddings/zhipuai.ts
libs/langchain-community/src/utils/zhipuai.ts

community[minor]: feat: Zhipuai embeddings

---

langchain/package.json

Release 0.1.28

---

langchain-core/src/language_models/chat_models.ts

core[patch]: Add llmOutput fields to response_metadata for single chat message generations

---

libs/langchain-cohere/package.json

cohere[patch]: Release 0.0.6

---

libs/langchain-community/src/chat_models/zhipuai.ts

community[patch]: fix: an issue where response not stopped correctly

---

libs/langchain-anthropic/src/experimental/tool_calling.ts
libs/langchain-mistralai/src/chat_models.ts
libs/langchain-mistralai/src/tests/chat_models.int.test.ts
libs/langchain-openai/src/chat_models.ts
libs/langchain-openai/src/tests/chat_models_structured_output.int.test.ts

openai[patch],anthropic[patch],mistralai[patch]: Support with structured output for OpenAI function definition schema

---

docs/core_docs/docs/use_cases/sql/quickstart.mdx

https://js.langchain.com/docs/use_cases/sql/quickstart

Docs[patch]: npm i guide issue in sql docs

---

examples/src/models/chat/integration_baiduwenxin.ts
libs/langchain-community/src/chat_models/baiduwenxin.ts
libs/langchain-community/src/chat_models/tests/chatbaiduwenxin.int.test.ts

ERNIE-Speed is Baidu's latest high-performance large language model released in 2024, with excellent general capabilities, better at handling specific scenario questions, and also has excellent inference performance.
It has been tested, and I can provide the baiduApiKey and baiduSecretKey if needed.

community[patch]: faat: Add ERNIE-Speed-8K, ERNIE-Speed-128K from Baidu Wenxin

---

libs/langchain-community/src/embeddings/zhipuai.ts

community[patch]: fix: zhipuai apikey double encode issue

---

docs/core_docs/docs/get_started/introduction.mdx
docs/core_docs/docs/modules/model_io/chat/function_calling.ipynb
docs/core_docs/src/theme/ChatModelTabs.js

docs[minor]: Add model selection tabs component

---

langchain-core/src/runnables/base.ts
langchain-core/src/runnables/config.ts
langchain-core/src/singletons/tests/async_local_storage.test.ts

core[patch]: Fix duplicated callbacks with async local storage

---

CONTRIBUTING.md

docs[patch]: Updates doc with node version required to build langchainjs

---

docs/core_docs/docs/ecosystem/langserve.mdx
examples/src/ecosystem/langsmith_stream_events.ts
examples/src/ecosystem/langsmith_stream_log.ts
langchain-core/src/runnables/remote.ts
langchain-core/src/runnables/tests/runnable_remote.int.test.ts
langchain-core/src/utils/event_source_parse.ts

Adds StreamEvents to Remote Runnable

---

libs/langchain-community/src/vectorstores/neo4j_vector.ts

community[patch]: Neo4j similaritySearchWithScore crashes on undefined

---

langchain-core/src/runnables/remote.ts

core[patch]: Fix typo

---

libs/langchain-google-common/package.json

google-common[patch]: Release 0.0.2

---

libs/langchain-google-vertexai/package.json

google-vertexai[patch]: Release 0.0.1

---

libs/langchain-groq/package.json

groq[patch]: Release 0.0.5

---

libs/langchain-azure-openai/package.json

azure-openai[patch]: Release 0.0.5

---

libs/langchain-azure-openai/package.json

azure-openai[patch]: Release 0.0.6

---

libs/langchain-anthropic/package.json
libs/langchain-anthropic/src/chat_models.ts
libs/langchain-anthropic/src/experimental/tests/tool_calling.int.test.ts
libs/langchain-anthropic/src/output_parsers.ts
libs/langchain-anthropic/src/tests/chat_models.test.ts
yarn.lock

anthropic[patch]: Add Zod validation, update Anthropic SDK version

---

libs/langchain-anthropic/package.json
libs/langchain-azure-openai/package.json
libs/langchain-cloudflare/package.json
libs/langchain-google-genai/package.json
libs/langchain-groq/package.json
libs/langchain-mistralai/package.json
libs/langchain-nomic/package.json
libs/langchain-openai/package.json

anthropic[patch]: Release 0.0.13
azure-openai[patch]: Release 0.0.7
cloudflare[patch]: Release 0.0.4
google-genai[patch]: Release 0.0.11
groq[patch]: Release 0.0.7
mistralai[patch]: Release 0.0.17
nomic[patch]: Release 0.0.4
openai[patch]: Release 0.0.27

[patch]: Many releases

---

libs/langchain-community/package.json

community[patch]: Release 0.0.48

---

libs/langchain-google-common/src/connection.ts

google-common[patch]: Fix Google Vertex-powered agent with no tools

---

libs/langchain-redis/package.json

redis[patch]: Release 0.0.3

---

CONTRIBUTING.md

docs[patch]: Improve release docs

---

libs/langchain-cohere/package.json

cohere[patch]: Release 0.0.7

---

libs/langchain-community/package.json

community[patch]: Release 0.0.49

---

libs/langchain-anthropic/src/chat_models.ts
libs/langchain-anthropic/src/tests/chat_models-tools.int.test.ts

anthropic[patch]: Support text content in AIMessage tool responses

---

libs/langchain-anthropic/src/chat_models.ts
libs/langchain-anthropic/src/tests/chat_models.int.test.ts
libs/langchain-google-common/src/types.ts
libs/langchain-google-common/src/utils/gemini.ts
libs/langchain-google-vertexai-web/src/tests/chat_models.int.test.ts
libs/langchain-google-webauth/src/tests/chat_models.int.test.ts

anthropic[patch],google-common[patch]: Update response_metadata fields

---

deno.json
docs/core_docs/docs/modules/model_io/chat/response_metadata.ipynb
docs/core_docs/docs/modules/model_io/chat/token_usage_tracking.mdx
examples/src/models/chat/token_usage_tracking.ts
examples/src/models/chat/token_usage_tracking_anthropic.ts
examples/src/models/chat/token_usage_tracking_callback.ts

docs[patch]: Update token usage tracking and response metadata docs

---

docs/core_docs/docs/integrations/chat/baidu_wenxin.mdx
examples/src/models/chat/integration_baiduwenxin.ts
libs/langchain-community/src/chat_models/baiduwenxin.ts

supports more ERNIE series models.  
Baidu official documentation: https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Nlks5zkzu#%E5%AF%B9%E8%AF%9Dchat

community[patch]: Add support for more WenXin models

---

libs/langchain-mistralai/src/chat_models.ts
libs/langchain-mistralai/src/tests/chat_models.int.test.ts

mistralai[patch]: Fix non-tool calling Mistral models

---

langchain/src/chains/history_aware_retriever.ts

Update history aware chain usage doc

---

libs/langchain-community/src/experimental/graph_transformers/llm.ts

community[patch]: Invoke toTitleCase only when string is present to avoid errors

---

libs/langchain-google-genai/package.json

google-genai[patch]: Release 0.0.12

---

libs/langchain-cohere/package.json
libs/langchain-cohere/src/rerank.ts
yarn.lock

Required for #4738
@bracesproul @karol-f

cohere[patch]: Make CohereRerank extend BaseDocumentCompressor

---

libs/langchain-community/src/chat_models/baiduwenxin.ts

fix: correct ernie-char-8k model name

---

libs/langchain-scripts/bin/build
libs/langchain-scripts/package.json
libs/langchain-scripts/src/types.ts

scripts[patch]: Release 0.0.13

scripts[patch]: Ability to add additional gitignore paths to lc config

---

docs/core_docs/scripts/code-block-loader.js

docs[patch]: Fix code block loader linking

---

libs/langchain-qdrant/README.md

qdrant[patch]: Added README.md

---

libs/langchain-qdrant/package.json

cc @Anush008 this is so the readme shows up on the [npm page](https://www.npmjs.com/package/@langchain/qdrant)

qdrant[patch]: Release 0.0.2

---

langchain/src/load/tests/__snapshots__/load.test.ts.snap
langchain/src/load/tests/load.test.ts

langchain[patch]: Remove outdated test

---

libs/langchain-openai/package.json

openai[patch]: Release 0.0.29

---

docs/core_docs/src/theme/Feedback.js

porting https://github.com/langchain-ai/langchain/pull/21606

docs[patch]: Add link for creating gh issue

---

docs/core_docs/docs/integrations/platforms/index.mdx

docs[patch]: Qdrant partner package reference

---

docs/core_docs/README.md

docs[patch]: Update README.md

---

langchain/src/smith/config.ts

fix[runOnDataset]: accept custom criteria in config factory

---

examples/.eslintrc.cjs
langchain-core/.eslintrc.cjs
langchain/.eslintrc.cjs
libs/create-langchain-integration/.eslintrc.cjs
libs/create-langchain-integration/template/.eslintrc.cjs
libs/langchain-anthropic/.eslintrc.cjs
libs/langchain-azure-openai/.eslintrc.cjs
libs/langchain-cloudflare/.eslintrc.cjs
libs/langchain-cohere/.eslintrc.cjs
libs/langchain-community/.eslintrc.cjs
libs/langchain-exa/.eslintrc.cjs
libs/langchain-google-common/.eslintrc.cjs
libs/langchain-google-gauth/.eslintrc.cjs
libs/langchain-google-genai/.eslintrc.cjs
libs/langchain-google-vertexai-web/.eslintrc.cjs
libs/langchain-google-vertexai/.eslintrc.cjs
libs/langchain-google-webauth/.eslintrc.cjs
libs/langchain-groq/.eslintrc.cjs
libs/langchain-mistralai/.eslintrc.cjs
libs/langchain-mongodb/.eslintrc.cjs
libs/langchain-nomic/.eslintrc.cjs
libs/langchain-openai/.eslintrc.cjs
libs/langchain-pinecone/.eslintrc.cjs
libs/langchain-qdrant/.eslintrc.cjs
libs/langchain-redis/.eslintrc.cjs
libs/langchain-scripts/.eslintrc.cjs
libs/langchain-textsplitters/.eslintrc.cjs
libs/langchain-weaviate/.eslintrc.cjs
libs/langchain-yandex/.eslintrc.cjs

all[patch]: Ignore no unused vars eslint rule in test files

---

docs/core_docs/vercel.json

docs[patch]: Fix docs infinite redirect, add redirect

---

docs/core_docs/docs/concepts.mdx
docs/core_docs/docs/contributing/documentation/style_guide.mdx
docs/core_docs/docs/how_to/qa_chat_history_how_to.ipynb
docs/core_docs/docs/introduction.mdx
docs/core_docs/sidebars.js
docs/core_docs/vercel.json

docs[patch]: Replace ecosystem pages with real links

---

libs/langchain-community/src/indexes/postgres.ts

Fixes #4851
Amends the SQL query used to check for the existence of documents by the record manager for Postgres. As it was before, this _should_ have worked, however for some reason the ordinality of the results does not always match the order of array items provided, meaning the docs flagged for removal/update are not always correct.
This has happened repeatedly for me when using the record manager to index documents. @MJDeligan was able to reproduce.
More specific details in the issue
Related integration tests all pass when un-skipped

community[patch]: preserve ordinality in postgres record manager when checking existence of documents

---

docs/core_docs/docs/tutorials/llm_chain.ipynb

docs[patch]: Fixed Typo on Build Simple LLM application page

---

langchain/src/util/sql_utils.ts

Added support for sqljs, the browser transpile of sqlite

langchain[patch]: Support for sqljs

---

libs/langchain-community/package.json
yarn.lock

Also bumps langchain dep to 0.2.3

community[patch]: Release 0.2.4

---

docs/core_docs/docs/introduction.mdx

docs[patch]: Fix security header

---

docs/core_docs/docs/integrations/chat/ollama_functions.mdx

docs[patch]: fix package path

---

libs/langchain-anthropic/package.json
libs/langchain-cohere/package.json
libs/langchain-community/package.json
libs/langchain-google-common/package.json
libs/langchain-google-genai/package.json
libs/langchain-mistralai/package.json

athropic[patch]: Release 0.2.1
cohere[patch]: Release 0.0.11
google-common[patch]: Release 0.0.18
google-genai[patch]: Release 0.0.17
mistralai[patch]: Release 0.0.24

partners[patch]: Release partner & community packages

---

libs/langchain-openai/package.json

openai[patch]: Release 0.1.2

---

libs/langchain-google-gauth/package.json
libs/langchain-google-vertexai-web/package.json
libs/langchain-google-vertexai/package.json
libs/langchain-google-webauth/package.json
yarn.lock

google-gauth[patch]: Release 0.0.18
google-webauth[patch]: Release 0.0.18
google-vertexai[patch]: Release 0.0.18
google-vertexai-web[patch]: Release 0.0.18

google[patch]: Release 0.0.18

---

docs/core_docs/docs/how_to/graph_prompting.ipynb
docs/core_docs/docs/tutorials/graph.ipynb

- fix for a ts error: Property 'schema' is protected and only accessible within class 'Neo4jGraph' and its subclasses.
- add console.log to show query result

docs: Graph tutorial updates

---

libs/langchain-google-genai/src/tests/chat_models.test.ts
libs/langchain-google-genai/src/utils/common.ts

google-genai[patch]: Update tool message parsing

---

langchain/package.json
yarn.lock

langchain[patch]: Bump deps

---

langchain-core/src/prompts/structured.ts
langchain-core/src/prompts/tests/structured.test.ts

Reverts langchain-ai/langchainjs#5882

Revert "core[patch]: Add check for bind tools in structured prompt"

---

libs/langchain-openai/package.json

openai[patch]: Release 0.2.1

---

docs/core_docs/docs/how_to/chatbots_tools.ipynb
docs/core_docs/docs/how_to/generative_ui.mdx
docs/core_docs/docs/how_to/stream_agent_client.mdx
docs/core_docs/docs/how_to/tools_prompting.ipynb
langchain/package.json
langchain/src/agents/openai_tools/index.ts
langchain/src/agents/structured_chat/index.ts
langchain/src/agents/tool_calling/index.ts
langchain/src/tools/render.ts
yarn.lock

langchain[minor],docs[minor]: openai formatted tools in create agent funcs

---

docs/core_docs/docs/additional_resources/tutorials.mdx

docs[patch]: Fix broken Scrimba link

---

libs/langchain-anthropic/src/tests/chat_models.int.test.ts

anthropic[patch]: Remove sleep after each test

---

libs/langchain-cohere/package.json

cohere[minor]: Release 0.2.0

---

libs/langchain-aws/src/common.ts
libs/langchain-cohere/src/chat_models.ts
libs/langchain-community/src/chat_models/bedrock/web.ts
libs/langchain-community/src/utils/bedrock/anthropic.ts
libs/langchain-google-common/src/utils/gemini.ts
libs/langchain-google-genai/src/utils/common.ts
libs/langchain-groq/src/chat_models.ts
libs/langchain-mistralai/src/chat_models.ts
libs/langchain-openai/src/chat_models.ts

anthropic update is in this PR: https://github.com/langchain-ai/langchainjs/pull/6056

partners[patch]: Add type field to all tool call integrations

---

libs/langchain-anthropic/src/chat_models.ts

anthropic[patch]: Remove log

---

libs/langchain-openai/src/tools/dalle.ts
libs/langchain-openai/src/tools/tests/dalle.int.test.ts

openai[minor]: Allow for multiple images to be returned with dalle

---

libs/langchain-ollama/package.json
yarn.lock

Closes https://github.com/langchain-ai/langchainjs/issues/6159

ollama[patch]: Fix min core version

---

examples/package.json
libs/langchain-pinecone/package.json
yarn.lock

pinecone[patch]: Bump pinecone dep to latest

---

libs/langchain-google-genai/src/tests/chat_models.int.test.ts
libs/langchain-standard-tests/src/integration_tests/chat_models.ts

dropped all console.logs from the test file too

genai[patch],standard-tests[patch]: Fix flaky tests/deprecated model

---

libs/langchain-google-common/package.json
libs/langchain-google-gauth/package.json
libs/langchain-google-vertexai-web/package.json
libs/langchain-google-vertexai/package.json
libs/langchain-google-webauth/package.json
yarn.lock

google-common[patch]: Release 0.0.22
google-gauth[patch]: Release 0.0.21
google-webauth[patch]: Release 0.0.21
google-vertexai[patch]: Release 0.0.21
google-vertexai-web[patch]: Release 0.0.21

google[patch]: Release 0.0.21/22

---

libs/langchain-anthropic/src/utils/message_inputs.ts

Didn't realize this function existed/already kind-of handled what #6257 implemented. With this refactor we can drop the util added in #6257 and keep the same functionality.
Current released code will work, so no need to cut a new release for this

anthropic[patch]: Refactor merging tool results

---

libs/langchain-anthropic/src/chat_models.ts

This PR addresses an issue where the token usage was being incorrectly calculated. The problem stemmed from redundant token usage accumulation within the package, despite the langchain-core already handling this logic. Consequently, the final token usage count was inflated.
**The fix:**
This PR removes the unnecessary token usage accumulation. By relying on the existing logic in langchain-core, we ensure accurate and consistent token usage tracking across all integrations.

anthropic[patch]: Prevent double-counting of token usage

---

libs/langchain-anthropic/src/chat_models.ts

anthropic[patch]: Pass custom headers through to request

---

docs/core_docs/docs/integrations/document_loaders/file_loaders/unstructured.mdx

Adds clarification and link to this external vendor

docs[patch]: add clarification

---

docs/core_docs/scripts/validate_notebook.ts

ci[patch]: Make notebook validation script handle default imports

---

docs/core_docs/scripts/validate_notebook.ts

ci[patch]: Fix notebook lint for namespace imports

---

docs/core_docs/scripts/quarto-build.js
docs/core_docs/scripts/validate_notebook.ts

docs[patch]: Add escape hatch

---

libs/langchain-google-genai/src/chat_models.ts

google-genai[patch]: Update ChatGoogleGenerativeAI serialization

---

libs/langchain-google-genai/package.json

google-genai[patch]: Release 0.0.24

---

environment_tests/test-exports-cf/package.json

Update wrangler in env test

---

libs/langchain-google-gauth/package.json
libs/langchain-google-vertexai-web/package.json
libs/langchain-google-vertexai/package.json
libs/langchain-google-webauth/package.json
yarn.lock

google-gauth[patch]: Release 0.0.22
google-webauth[patch]: Release 0.0.22
google-vertexai[patch]: Release 0.0.22
google-vertexai-web[patch]: Release 0.0.22

google[patch]: Release 0.0.22

---

.github/workflows/unit-tests-integrations.yml
.github/workflows/unit-tests-langchain-core.yml
.github/workflows/unit-tests-langchain.yml
langchain/package.json
langchain/src/chat_models/universal.ts
package.json
yarn.lock

Fixes [this issue](https://github.com/langchain-ai/langchainjs/actions/runs/10275691154/job/28434798119) which seems to present itself every time a new version of `@langchain/google-vertexai` is released...

langchain[patch]: Fix CI build

---

docs/core_docs/docs/integrations/chat/azure.ipynb
docs/core_docs/docs/integrations/chat/openai.ipynb

docs[patch]: Adds docs on passing custom headers to OpenAI + Azure OpenAI models

---

libs/langchain-community/package.json

community[patch]: Release 0.2.25

---

langchain-core/src/runnables/remote.ts
langchain-core/src/utils/event_source_parse.ts

core[patch]: Allow overriding the fetch implementation used in RemoteRunnable

---

langchain-core/package.json

core[patch]: Release 0.2.22

---

docs/core_docs/docs/integrations/chat/friendli.mdx
examples/src/models/chat/friendli.ts
libs/langchain-community/src/chat_models/friendli.ts

- Update `ChatFriendli`'s base model from `llama-2-13b-chat` to `meta-llama-3-8b-instruct`.

docs[minor]: Update base model in `ChatFriendli` ChatModel

---

docs/core_docs/docs/how_to/custom_tools.ipynb

docs[patch]: Fix broken tools API ref link

---

docs/core_docs/docs/integrations/chat/openai.ipynb

docs[patch]: Adds ChatOpenAI streamUsage docs on disabling stream usage

---

libs/langchain-community/package.json
yarn.lock

community[patch]: Relax googleapis peer dep to *

---

libs/langchain-google-gauth/package.json
libs/langchain-google-vertexai-web/package.json
libs/langchain-google-vertexai/package.json
libs/langchain-google-webauth/package.json
yarn.lock

google-gauth[patch]: Release 0.0.27
google-webauth[patch]: Release 0.0.27
google-vertexai[patch]: Release 0.0.27
google-vertexai-web[patch]: Release 0.0.27

google[patch]: Release 0.0.27

---

langchain/src/chains/conversational_retrieval_chain.ts
langchain/src/chains/llm_chain.ts
langchain/src/chains/retrieval_qa.ts

langchain[patch]: Update version for removal of deprecated code

---

docs/core_docs/docs/how_to/migrate_agent.ipynb

concerning issue https://github.com/langchain-ai/langchainjs/issues/6650

docs[patch]: Update migrate_agent.ipynb -> was refering to the wrong doc link

---

docs/core_docs/vercel.json

Remove rewrite

---

docs/core_docs/docs/tutorials/chatbot.ipynb

docs: Fix typo in chatbot tutorial

---

libs/langchain-google-common/src/chat_models.ts

feat(google-common): Export ChatConnection class

---

libs/langchain-mistralai/src/chat_models.ts

fix(mistral): Fix call options type

---

langchain-core/src/prompts/prompt.ts
langchain-core/src/prompts/template.ts
langchain-core/src/prompts/tests/chat.test.ts
langchain-core/src/prompts/tests/prompt.test.ts

feat(core): Allow more types of inputs in prompt templates

---

libs/langchain-qdrant/src/tests/vectorstores.int.test.ts
libs/langchain-qdrant/src/vectorstores.ts

Adds support for using custom IDs when adding docs to Qdrant.

fix(qdrant): Support for custom IDs when adding documents

---

langchain-core/src/messages/base.ts
langchain-core/src/messages/utils.ts

feat(core): Allow serialized messages as BaseMessageLikes

---

langchain-core/src/tools/index.ts
langchain-core/src/tools/tests/tools.test.ts

Fixes https://github.com/langchain-ai/langgraphjs/issues/588

fix(core): Fix config passing for single string input tools

---

langchain/src/agents/index.ts

Export `AgentRunnableSequence `type  for developers.

chore(langchain): export AgentRunnableSequence

---

libs/langchain-google-genai/src/utils/common.ts

See trace: https://smith.langchain.com/public/9dd89453-0200-4fe2-a27e-96a343ac471f/r

fix(google-genai): Type error parsing api res

---

libs/langchain-community/src/vectorstores/chroma.ts
libs/langchain-community/src/vectorstores/tests/chroma.test.ts

Fixes # [7013](https://github.com/langchain-ai/langchainjs/issues/7013)

fix(community): Add id in chroma search result

---

langchain-core/src/callbacks/manager.ts
langchain-core/src/singletons/tracer.ts
langchain-core/src/tracers/tracer_langchain.ts

This means that all runs will now share a single batch queue

fix(core): Use a single shared client instance for all runs

---

docs/core_docs/docs/integrations/text_embedding/tensorflow.mdx

docs: Fix import

---

libs/langchain-scripts/bin/build.js
libs/langchain-scripts/bin/filter_spam_comment.js
libs/langchain-scripts/bin/validate_notebook.js
libs/langchain-scripts/package.json

See https://stackoverflow.com/a/28646724

fix(scripts): add missing shebang in bin scripts

---

libs/langchain-qdrant/src/vectorstores.ts

Add a function to delete points in Qdrant.
Documentation: https://api.qdrant.tech/v-1-12-x/api-reference/points/delete-points

feat(qdrant): Add a Function to Delete Points in Qdrant

---

release_workspace.js

- allows releasing off of `main` or `release` branches
- auto-commit & push with auto-generated commit message
- dont run export tests anymore

fix(ci): Update release script to be more lenient

---

libs/langchain-google-common/src/utils/anthropic.ts

fix(google-common): Anthropic util using getType instead of _getType

---

libs/langchain-ollama/src/chat_models.ts
libs/langchain-ollama/src/embeddings.ts
libs/langchain-ollama/src/llms.ts

fix(ollama): Remove default keepalive for Ollama models

---

langchain/src/chat_models/universal.ts

feat(langchain): Infer o1 model strings in initChatModel

---

libs/langchain-ollama/src/embeddings.ts

Mistakenly thought examples build was a flake

fix(ci): Fix build

---

libs/langchain-anthropic/package.json
libs/langchain-anthropic/src/tests/chat_models.int.test.ts
libs/langchain-anthropic/src/utils/message_outputs.ts
yarn.lock

fix(anthropic): Properly populate usage_metadata for Anthropic models

---

docs/core_docs/docs/concepts/text_splitters.mdx

Noticed another broken link, wanted to submit a quick PR to fix it.
Thanks!

fix(docs): Fix broken hyperlink

---

libs/langchain-cohere/package.json

release(cohere): 0.3.2

---

examples/src/indexes/vector_stores/pgvector_vectorstore/pgvector.ts

fix(docs): link to setup for PGVectorStore

---

langchain-core/package.json

release(core): 0.3.27

---

libs/langchain-google-common/package.json
libs/langchain-google-gauth/package.json
libs/langchain-google-vertexai-web/package.json
libs/langchain-google-vertexai/package.json
libs/langchain-google-webauth/package.json
yarn.lock

release(google): 0.1.6

---

langchain/package.json
langchain/src/chat_models/universal.ts
yarn.lock

Need for running in LangGraph Platform

feat: Add google-vertexai-web to initChatModel

---

langchain-core/src/prompts/base.ts
langchain/src/hub.ts
langchain/src/tests/hub.int.test.ts

fix(langchain,core): Add metadata to pulled hub prompts

---

libs/langchain-google-common/package.json
libs/langchain-google-gauth/package.json
libs/langchain-google-vertexai-web/package.json
libs/langchain-google-vertexai/package.json
libs/langchain-google-webauth/package.json
yarn.lock

release(google-vertexai): 0.1.7

---

docs/core_docs/docs/integrations/llms/huggingface_inference.mdx

Fixes #7476 
update outdated docs

docs: Closes #7476

---

libs/langchain-community/src/embeddings/togetherai.ts

Fixes https://github.com/langchain-ai/langchainjs/issues/7544

fix(community): Updated Embeddings URL

---

langchain/src/chains/openai_moderation.ts

Fix typo in OpenAIModerationChain example
Fixes https://github.com/langchain-ai/langchainjs/issues/7527

docs: Fix typo in OpenAIModerationChain example

---

langchain/src/hub.ts
langchain/src/load/index.ts

fix(langchain): Allow pulling hub prompts with associated models

---

langchain-core/src/language_models/chat_models.ts

fix(chat-models): honor disableStreaming even for `generateUncached`

---

langchain-core/src/messages/tests/message_utils.test.ts
langchain-core/src/messages/transformers.ts

fix(core): Fix trim messages mutation

---

libs/langchain-openai/src/azure/chat_models.ts
libs/langchain-openai/src/chat_models.ts
libs/langchain-openai/src/tests/azure/chat_models.int.test.ts

fix(openai): Revert Azure default withStructuredOutput changes

---

docs/core_docs/docs/integrations/chat/novita.ipynb

Update Novita AI URLs in the doc and use DeepSeek R1 for examples.

feat: update Novita AI doc

---

libs/langchain-anthropic/README.md

Documentation fixes for `@langchain/anthropic` Typescript package

fix(docs): imports and call

---

docs/core_docs/docs/how_to/message_history.ipynb

docs: Update message_history.ipynb

---

libs/langchain-redis/src/vectorstores.ts

fix(redis): update wrong redis setup link

---

libs/langchain-google-common/package.json
libs/langchain-google-gauth/package.json
libs/langchain-google-vertexai-web/package.json
libs/langchain-google-vertexai/package.json
libs/langchain-google-vertexai/src/tests/chat_models.int.test.ts
libs/langchain-google-webauth/package.json
yarn.lock

release(google-vertex): 0.2.0

---

libs/langchain-google-genai/package.json

release(google-genai): Release 0.1.9

---

docs/core_docs/docs/integrations/retrievers/self_query/pinecone.ipynb
docs/core_docs/docs/integrations/text_embedding/pinecone.ipynb
docs/core_docs/docs/integrations/vectorstores/pinecone.ipynb
examples/package.json
libs/langchain-community/src/vectorstores/pinecone.ts
libs/langchain-pinecone/README.md
libs/langchain-pinecone/package.json
libs/langchain-pinecone/src/embeddings.ts
libs/langchain-pinecone/src/tests/embeddings.int.test.ts
libs/langchain-pinecone/src/tests/vectorstores.int.test.ts
libs/langchain-pinecone/src/vectorstores.ts
yarn.lock

fix(pinecone): Update Pinecone SDK to 5.0.0, make peer dep

---

libs/langchain-aws/src/common.ts
libs/langchain-aws/src/tests/chat_models.int.test.ts

fix(aws): fix content block ordering for claude reasoning on bedrock

---

langchain/src/vectorstores/tests/memory.test.ts

chore(langchain): add test to ensure sort order on MemoryVectorStore

---

langchain/package.json
libs/langchain-openai/package.json
libs/langchain-openai/src/types.ts
yarn.lock

fix(openai): Fix OpenAI type error

---

libs/langchain-azure-cosmosdb/src/azure_cosmosdb_mongodb.ts

Reverts langchain-ai/langchainjs#7825

Revert "fix(azure-cosmosdb): Update user agent of AzureCosmosDBMongoDBVectorStore"

---

libs/langchain-google-genai/package.json
yarn.lock

feat(google-genai): Bump GenAI SDK version

---

docs/core_docs/docs/tutorials/classification.ipynb

docs: Fix classification tutorial schema

---

docs/core_docs/static/llms.txt

Trying to match: https://github.com/langchain-ai/langchain/pull/30506

docs: add llms.txt

---

docs/core_docs/static/llms.txt

docs: fix typo in llms.txt to point to js docs

---

docs/core_docs/static/llms.txt

docs: llms.txt add trailing slashes to avoid redirects

---

libs/langchain-openai/src/tools/dalle.ts

fix(openai): openai OpenAIClient baseUrl is baseURL

---

libs/langchain-qdrant/src/vectorstores.ts

Fixes https://github.com/langchain-ai/langchainjs/issues/7924 + optional chaining for `customPayload`

fix(qdrant): Fix Qdrant indexing cleanup

---

libs/langchain-google-genai/src/chat_models.ts
libs/langchain-google-genai/src/tests/chat_models-extended.int.test.ts
libs/langchain-google-genai/src/utils/zod_to_genai_parameters.ts

Fixes https://github.com/langchain-ai/openevals/issues/33

fix(google-genai): Tolerate additional extra fields in withStructuredOutput

---

libs/langchain-anthropic/src/tests/chat_models-tools.int.test.ts
libs/langchain-anthropic/src/utils/message_inputs.ts

fix(anthropic): Fix Anthropic tool calling for tools with no args

---

libs/langchain-google-cloud-sql-pg/package.json

release(google-cloud-sql-pg): 0.0.1

---

libs/langchain-openai/src/chat_models.ts

Closes System messages are not propagated when using OpenAI Responses API #7950

fix(openai): handle system, developer messages

---

libs/langchain-community/package.json
libs/langchain-community/src/vectorstores/usearch.ts
yarn.lock

chore(community): bump usearch package version

---

langchain/src/chat_models/universal.ts
libs/langchain-openai/src/chat_models.ts

Fixes [#8039](https://github.com/langchain-ai/langchainjs/issues/8039)
sorry in advance if it doesn't follow contributing guidelines. I have to rush out the door so just let 4o analyze them on short notice

o4 reasoning model support (#8039)

---

langchain-core/src/prompts/chat.ts
langchain-core/src/prompts/dict.ts
langchain-core/src/prompts/index.ts
langchain-core/src/prompts/tests/chat.test.ts
langchain-core/src/prompts/tests/dict.test.ts

Implement DictPromptTemplate

---

langchain-core/src/prompts/dict.ts
langchain-core/src/prompts/tests/chat.test.ts
langchain-core/src/prompts/tests/dict.test.ts

feat(core): Add input_variables to serialized representation of DictPromptTemplate

---

libs/langchain-google-common/package.json
libs/langchain-google-gauth/package.json
libs/langchain-google-genai/package.json
libs/langchain-google-vertexai-web/package.json
libs/langchain-google-vertexai/package.json
yarn.lock

content blocks for google accidentally merged as part of #8065

chore(google): bump dep on core

---

langchain-core/src/prompts/structured.ts

feat(core): support method field in StructuredPrompt

---

libs/langchain-aws/src/common.ts
libs/langchain-aws/src/tests/chat_models.test.ts

Fixes #6724 and https://github.com/langchain-ai/langchain-aws/issues/192.

fix(aws): Merge consecutive messages correctly in ChatBedrockConverse

---

docs/core_docs/src/theme/ChatModelTabs.js

Adds Google Gemini to model tabs after OAI and Anthropic.

add google gemini

---

libs/langchain-anthropic/package.json
libs/langchain-anthropic/src/tests/chat_models.int.test.ts
libs/langchain-anthropic/src/tests/chat_models.standard.int.test.ts
libs/langchain-anthropic/src/types.ts
libs/langchain-anthropic/src/utils/message_inputs.ts
yarn.lock

Fixes #7839
The first commit in this PR should've been included in #8063 but was accidentally rebased out.

feat(anthropic): standard input blocks and better handling of image_url and anthropic image content blocks

---

langchain-core/src/callbacks/manager.ts
langchain-core/src/tracers/tracer_langchain.ts

Change is implemented in a way that is forward/backward compatible, but will only have a performance benefit with the version of LangSmith that contains the change in this pr: https://github.com/langchain-ai/langsmith-sdk/pull/1733

fix(core): tracing perf improvements

---

langchain-core/src/tools/index.ts
langchain-core/src/tools/tests/tools.test.ts
libs/langchain-anthropic/src/utils/message_inputs.ts

fix(core, anthropic): handling for undefined tool outputs

---

libs/langchain-aws/src/chat_models.ts

Ports https://github.com/langchain-ai/langchain-aws/pull/315.
fixes: #8114

feat(aws): add performanceConfig

---

libs/langchain-google-genai/src/chat_models.ts

fix(google-genai): fix undefined access error on safety refusal

---

libs/langchain-google-genai/src/chat_models.ts
libs/langchain-google-genai/src/utils/common.ts

fix(google-genai): handle responses with missing content

---

langchain/package.json
libs/langchain-anthropic/package.json
libs/langchain-aws/package.json
libs/langchain-cerebras/package.json
libs/langchain-cohere/package.json
libs/langchain-community/package.json
libs/langchain-deepseek/package.json
libs/langchain-google-common/package.json
libs/langchain-google-genai/package.json
libs/langchain-groq/package.json
libs/langchain-mistralai/package.json
libs/langchain-ollama/package.json
libs/langchain-openai/package.json
libs/langchain-tavily/package.json
libs/langchain-xai/package.json

Release PR for all the packages using the new interop core zod utilities

release: zod 4 integrations releases

---

docs/core_docs/docusaurus.config.js

incident banner

---

docs/core_docs/docusaurus.config.js

revert incident banner

---

libs/langchain-google-common/src/auth.ts
libs/langchain-google-common/src/utils/stream.ts
libs/langchain-google-gauth/package.json
libs/langchain-google-gauth/src/auth.ts
libs/langchain-google-vertexai/src/tests/chat_models.int.test.ts
yarn.lock

This is #8365 with code changes that fix typing issues and does some code cleanup in the process.
(I don't have permissions to change the original PR.)
cc: @lbennett-stacki @hntrl

minor(google): Upgrade Upgrade google-auth-library to latest major version (v10)

---

libs/langchain-google-common/src/tests/chat_models.test.ts
libs/langchain-google-common/src/tests/data/chat-4-mock.json
libs/langchain-google-common/src/types.ts
libs/langchain-google-common/src/utils/common.ts
libs/langchain-google-common/src/utils/gemini.ts

Some updates to how reasoning is handled.
Fixes #8298 
Fixes #8299

feat(google): Gemini thinking updates

---

libs/langchain-ollama/src/chat_models.ts
libs/langchain-ollama/src/embeddings.ts
libs/langchain-ollama/src/llms.ts

Adds the setting where we can change the fetch for the ollama.

refactor: update Ollama import and add fetch option to models

---

libs/langchain-community/src/chat_models/perplexity.ts
libs/langchain-community/src/chat_models/tests/chatperplexity.int.test.ts
libs/langchain-community/src/utils/output_parsers.ts
libs/langchain-community/src/utils/tests/output_parsers.test.ts

Fix(community): perplexity reasoning json parser error

---

libs/langchain-google-common/package.json
libs/langchain-google-gauth/package.json
libs/langchain-google-genai/package.json
libs/langchain-google-vertexai-web/package.json
libs/langchain-google-vertexai/package.json
libs/langchain-google-webauth/package.json
yarn.lock

release(google-*): 0.2.14

---

docs/core_docs/docs/versions/v0_3/index.mdx

chore(docs): upgrade 0.3 version guide

---

libs/langchain-openai/src/azure/chat_models.ts
libs/langchain-openai/src/chat_models.ts

fix(openai): thread _getClientOptions

---

libs/langchain-openai/src/chat_models.ts
libs/langchain-openai/src/tests/chat_models.test.ts

fix(openai): Fix ls structured output params

---

libs/langchain-anthropic/src/output_parsers.ts
libs/langchain-anthropic/src/tests/chat_models-web_search.int.test.ts
libs/langchain-anthropic/src/tests/chat_models-web_search.test.ts
libs/langchain-anthropic/src/tests/chat_models.int.test.ts
libs/langchain-anthropic/src/utils/message_outputs.ts

fix(anthropic): dont include server tools in tool_calls

---

libs/langchain-anthropic/src/chat_models.ts

Updated list of built in anthropic tool names

fix(anthropic): Update list of built in tools

---

langchain-core/src/runnables/base.ts

docs: fix RunnableParallel example output

---

docs/core_docs/docs/tutorials/sql_qa.ipynb

- Update tutorial content and examples
- Enhance code clarity and documentation

docs: improve SQL QA tutorial notebook

---

libs/langchain-community/src/vectorstores/clickhouse.ts

fix(community/clickhouse): support passthrough index param

---

libs/langchain-aws/package.json

release(aws): 0.1.13

---

.prettierignore
dependency_range_tests/scripts/with_standard_tests/anthropic/test-with-latest-deps.sh
dependency_range_tests/scripts/with_standard_tests/anthropic/test-with-lowest-deps.sh
dependency_range_tests/scripts/with_standard_tests/cohere/test-with-latest-deps.sh
dependency_range_tests/scripts/with_standard_tests/cohere/test-with-lowest-deps.sh
dependency_range_tests/scripts/with_standard_tests/community/test-with-latest-deps.sh
dependency_range_tests/scripts/with_standard_tests/community/test-with-lowest-deps.sh
dependency_range_tests/scripts/with_standard_tests/google-vertexai/test-with-latest-deps.sh
dependency_range_tests/scripts/with_standard_tests/google-vertexai/test-with-lowest-deps.sh
dependency_range_tests/scripts/with_standard_tests/openai/test-with-latest-deps.sh
dependency_range_tests/scripts/with_standard_tests/openai/test-with-lowest-deps.sh
libs/langchain-core/babel.config.cjs
libs/langchain/babel.config.cjs
libs/providers/langchain-anthropic/babel.config.cjs
libs/providers/langchain-azure-openai/babel.config.cjs
libs/providers/langchain-openai/babel.config.cjs

These files don't seem to have any function anymore. Let's get rid of them.

chore(v1): remove unused babel.config.cjs files

---

release_workspace.js

will be invalidated by move to changesets

chore(v1): patch release script for v1

---

libs/langchain/src/agents/index.ts
libs/langchain/src/agents/nodes/ToolNode.ts
libs/langchain/src/index.ts

fix(langchain) export ToolNode from langchain

---

.changeset/rare-pianos-retire.md
libs/langchain-community/src/document_loaders/tests/jira.test.ts
libs/langchain-community/src/document_loaders/web/jira.ts

feat(community): add jira issue title to metadata for documents

---

.changeset/open-worlds-visit.md
libs/langchain-redis/src/tests/vectorstores.int.test.ts
libs/langchain-redis/src/tests/vectorstores.test.ts
libs/langchain-redis/src/vectorstores.ts

This PR adds document deletion by ID functionality to the `RedisVectorStore` class, bringing feature parity with the Python implementation while maintaining full backward compatibility with existing code.
- **Enhanced `delete()` method** to support two deletion modes:
- `{ deleteAll: boolean }` - Existing functionality (drops entire index)
- `{ ids: string[] }` - **New functionality** (deletes specific documents by their IDs)
- **Backward compatibility maintained** - All existing code using `deleteAll` continues to work unchanged
- Uses Redis `DEL` command for efficient document removal by ID
- Type-safe implementation with proper TypeScript interfaces
- Comprehensive JSDoc documentation with usage examples
- **Unit tests** added to verify mock Redis client interactions
- **Integration …

feat(langchain-redis): support document deletion by ID in RedisVectorStore

---

examples/package.json
libs/langchain-community/package.json
libs/langchain-community/src/vectorstores/tests/milvus.test.ts
yarn.lock

fix(community): bump firebase-admin devDependencies

---

.changeset/strong-worms-sneeze.md
libs/langchain-core/src/prompts/chat.ts
libs/langchain-core/src/prompts/template.ts
libs/langchain-core/src/prompts/tests/chat.mustache.test.ts

fix(core/v1): make mustache prompt with nested object working correctly

---

.changeset/clever-jars-float.md
libs/langchain-core/src/messages/ai.ts
libs/langchain-core/src/messages/base.ts
libs/langchain-core/src/messages/tests/ai.test.ts

fix(core/v1): prevent tool call chunks from merging incorrectly in AIMessageChunk.concat()

---

.changeset/kind-tickle-bear.md
examples/package.json
libs/langchain-community/package.json
libs/langchain-community/src/stores/message/aurora_dsql.ts
libs/langchain-community/src/stores/tests/aurora_dsql.int.test.ts
yarn.lock

fix(@langchain/community) create index aurora dsql

---

.changeset/stupid-cows-grow.md
libs/langchain-community/src/vectorstores/hanavector.ts
libs/langchain-community/src/vectorstores/tests/hanavector.test.ts

fix(community/v1): allow any chars in delimited identifiers in hanavector

---

.changeset/fast-plants-wink.md
libs/langchain-core/src/embeddings.ts
libs/providers/langchain-openai/src/embeddings.ts
libs/providers/langchain-openai/src/tests/embeddings.int.test.ts

feat(openai/v1): encodingFormat support for embeddings

---

.changeset/thick-lamps-relax.md
langchain-core/src/output_parsers/structured.ts
langchain-core/src/output_parsers/tests/structured.test.ts

fix(core): handle backticks in structured output

---

.changeset/modern-melons-roll.md
libs/langchain-community/src/llms/tests/togetherai.test.ts
libs/langchain-community/src/llms/togetherai.ts

fix(community/v1): improve TogetherAI error handling for chat models

---

.changeset/thick-lamps-relax.md
libs/langchain-core/src/output_parsers/structured.ts
libs/langchain-core/src/output_parsers/tests/structured.test.ts

fix(core/v1): handle backticks in structured output

---

.changeset/wet-bikes-clap.md
libs/langchain/src/chat_models/tests/universal.int.test.ts
libs/langchain/src/chat_models/universal.ts

fix(langchain/v1): infer mistral in `initChatModel`

---

.changeset/slow-clouds-walk.md
libs/providers/langchain-weaviate/src/tests/vectorstores.int.test.ts

chore(weaviate/v1): Adds invalid metadata integration test

---

.changeset/angry-ads-retire.md
langchain/src/cache/file_system.ts
libs/langchain-azure-cosmosdb/src/caches/caches_mongodb.ts
libs/langchain-azure-cosmosdb/src/caches/caches_nosql.ts
libs/langchain-cloudflare/src/caches.ts
libs/langchain-community/src/caches/cloudflare_kv.ts
libs/langchain-community/src/caches/ioredis.ts
libs/langchain-community/src/caches/momento.ts
libs/langchain-community/src/caches/upstash_redis.ts
libs/langchain-community/src/caches/vercel_kv.ts
libs/langchain-redis/src/caches.ts

https://forum.langchain.com/t/insecure-cache-algorithms/1514

fix: use `keyEncoder` instead of insecure cache key getter

---

.changeset/metal-camels-join.md
libs/providers/langchain-openai/src/chat_models.ts
libs/providers/langchain-openai/src/tests/chat_models-extended.int.test.ts
libs/providers/langchain-openai/src/tests/chat_models.test.ts

fix(openai/v1): fix streaming in openai

---

libs/providers/langchain-aws/src/chat_models.ts
libs/providers/langchain-aws/src/tests/chat_models.int.test.ts
libs/providers/langchain-aws/src/tests/chat_models.test.ts
libs/providers/langchain-aws/src/utils/message_inputs.ts
libs/providers/langchain-aws/src/utils/message_outputs.ts

Adapts some of the breaking/deprecated chat model changes for aws

chore(aws): adapt message changes for aws

---

.github/labeler.yml
.github/workflows/labeler.yml

adapted from https://github.com/langchain-ai/docs/blob/main/.github/workflows/labeler.yml

chore: add PR labeler

---

libs/langchain/src/agents/middlewareAgent/middleware/hitl.ts
libs/langchain/src/agents/middlewareAgent/middleware/tests/hitl.test.ts

Ported from https://github.com/langchain-ai/langchain/pull/33195

feat(langchain/createAgent): allow to pass in a description factory for interrupted tool calls

---

examples/src/createAgent/middleware/modelCallLimit.ts
libs/langchain/src/agents/middlewareAgent/middleware/callLimit.ts
libs/langchain/src/agents/middlewareAgent/middleware/index.ts
libs/langchain/src/agents/middlewareAgent/middleware/tests/callLimit.test.ts
libs/langchain/src/agents/middlewareAgent/nodes/utils.ts

Alternative implementation for https://github.com/langchain-ai/langchain/pull/33178

feat(langchain/createAgent): new call limit middleware

---

langchain/src/agents/react/index.ts

fix doc comment
