langchain-ai/langchainjs

libs/langchain-cohere/package.json, libs/langchain-cohere/src/chat_models.ts, yarn.lock
Cohere messages now support three roles: `CHATBOT`, `SYSTEM`, or `USER`
https://docs.cohere.com/reference/chat
=> cohere[patch]: Add system type

docs/core_docs/docs/modules/data_connection/retrievers/self_query/chroma-self-query.mdx, docs/core_docs/docs/modules/data_connection/retrievers/self_query/hnswlib-self-query.mdx, docs/core_docs/docs/modules/data_connection/retrievers/self_query/index.mdx, docs/core_docs/docs/modules/data_connection/retrievers/self_query/memory-self-query.mdx, docs/core_docs/docs/modules/data_connection/retrievers/self_query/pinecone-self-query.mdx, docs/core_docs/docs/modules/data_connection/retrievers/self_query/supabase-self-query.mdx, docs/core_docs/docs/modules/data_connection/retrievers/self_query/vectara-self-query.mdx, docs/core_docs/docs/modules/data_connection/retrievers/self_query/weaviate-self-query.mdx, examples/src/retrievers/chroma_self_query.ts, examples/src/retrievers/hnswlib_self_query.ts, examples/src/retrievers/memory_self_query.ts, examples/src/retrievers/pinecone_self_query.ts, examples/src/retrievers/supabase_self_query.ts, examples/src/retrievers/vectara_self_query.ts, examples/src/retrievers/weaviate_self_query.ts, langchain/src/retrievers/self_query/index.ts, langchain/src/retrievers/self_query/pinecone.ts, langchain/src/retrievers/self_query/tests/chroma_self_query.int.test.ts, langchain/src/retrievers/self_query/tests/hnswlib_self_query.int.test.ts, langchain/src/retrievers/self_query/tests/memory_self_query.int.test.ts, langchain/src/retrievers/self_query/tests/pinecone_self_query.int.test.ts, langchain/src/retrievers/self_query/tests/supabase_self_query.int.test.ts, langchain/src/retrievers/self_query/tests/vectara_self_query.int.test.ts, langchain/src/retrievers/self_query/tests/weaviate_self_query.int.test.ts
Fixes https://github.com/langchain-ai/langchainjs/discussions/5096
=> langchain[patch],docs[patch]: Remove unnecessary `await` from `SelfQueryRetriever.fromLLM` calls

langchain-core/src/messages/ai.ts
In langchain-core/src/messages/ai.ts
The code currently only checks for undefined on rawToolCalls.  However, the provider (deep-infra in this case)  can return toolCalls=null, which passed the conditional but will then produce an error when rawToolCalls.length is accessed.
Changed the conditional to !(rawToolCalls == null) to address the issue, and verified that this fixed the issue.
Note that `rawToolCalls == null` is true if rawToolCalls is null OR undefined, thus handling both cases.
=> core[patch]: Update ai.ts

libs/langchain-community/src/embeddings/alibaba_tongyi.ts
corrects the type declaration for the `text_type` parameter in Alibaba Tongyi embeddings. The previous declaration incorrectly listed `text` as an option, which is not supported. The corrected declaration includes the intended options: `query` and `document` as shown in [official docs](https://help.aliyun.com/zh/dashscope/developer-reference/text-embedding-api-details) and comment above it.
Translation for the original comment: 
```js
/**
* Value: query or document, default value is document
* Description: After text is converted into vectors, it can be applied to downstream tasks such as retrieval, clustering, and classification.
* For asymmetric tasks like retrieval, to achieve better retrieval effects, it is recommended to distinguish between query text (query) and
* document text …
```
=> fix: incorrect text_type type declaration in Alibaba Tongyi Embeddings

docs/core_docs/docs/integrations/vectorstores/neon.mdx, examples/src/indexes/vector_stores/neon/example.ts, libs/langchain-community/.gitignore, libs/langchain-community/langchain.config.js, libs/langchain-community/package.json, libs/langchain-community/src/vectorstores/neon.ts, yarn.lock
This PR adds Neon Postgres (backed by the pgvector extension) as a vector store. The code mostly follows the vercel-postgres integration but uses the Neon database serverless driver (https://github.com/neondatabase/serverless), which is quicker for one-shot queries. 
(I write technical content for Neon)
=> add neon postgres as a vector store

libs/langchain-community/package.json, libs/langchain-community/src/vectorstores/astradb.ts, libs/langchain-community/src/vectorstores/tests/astradb.int.test.ts, yarn.lock
After upgrading the astra client in https://github.com/langchain-ai/langchainjs/pull/5080, there existing code is not 100% compatible anymore. 
The client now checks if the collection already exists by default and in that case, throws an error. 
In this PR we disable that flag by default to restore the same behaviour as before the upgrade.
Related issue: https://github.com/langchain-ai/langchainjs/issues/5133
(also bump min version to 1.0.1 which contains some bugfixes)
=> community[patch]: astradb: set collection checkExists=false by default

docs/core_docs/docs/integrations/vectorstores/qdrant.mdx, libs/langchain-community/src/vectorstores/qdrant.ts
This PR intends to make the keys used to store documents and metadata in Qdrant configurable.
Since LangchainPy uses differently named keys, the 2 are currently not interoperable.
The default values maintain backward compatibility.
Effort to resolve https://github.com/langchain-ai/langchainjs/issues/2408.
=> community[patch]: refactor: configurable payload keys in  Qdrant vectorstore

libs/langchain-community/src/vectorstores/astradb.ts, libs/langchain-community/src/vectorstores/tests/astradb.int.test.ts
While using AstraDB there are cases whereas the collection already exists and you don't want to store to try to initialize it. For example, you might have read only permission and trying to create the collection will give you 403
Add boolean flag `skipCollectionProvisioning` to just assume the collection is already there with the correct settings.
=> community[patch]: AstraDB: add option to skip create collection call

libs/langchain-community/src/vectorstores/azure_aisearch.ts, libs/langchain-community/src/vectorstores/tests/azure_aisearch.int.test.ts
This PR improves the existing Azure Cosmos DB vector store in the following ways:
- Add support for custom credentials
- Set default search query type
=> community[minor]: Improve Azure AI Search vector store support

libs/langchain-community/src/vectorstores/astradb.ts
Same indexing default as python langchain.
Also fixes a rebase issue after https://github.com/langchain-ai/langchainjs/pull/5170 and https://github.com/langchain-ai/langchainjs/pull/5142
=> community[patch]: ensure AstraDB createCollectionOptions are aligned with py version

docs/core_docs/docs/get_started/quickstart.mdx
I noticed a missing "s" at the end of "application" in the sentence where it looks to be meant to be plural. Thought I'd submit a quick PR to fix it.
Thanks!
=> docs[patch]: Add missing "s" to end of word

libs/langchain-community/src/chat_models/zhipuai.ts, libs/langchain-community/src/embeddings/zhipuai.ts, libs/langchain-community/src/utils/zhipuai.ts
=> community[patch]: fix: Zhipu api key expired after 3 minutes

langchain-core/src/runnables/index.ts
This matches the Python implementation and is needed to implement `RunnableCallable` in LangGraphJS.
Python implementation of `RunnableCallable`: https://github.com/langchain-ai/langgraph/blob/main/langgraph/utils.py#L5
=> core[patch]: Export `mergeConfigs()`

libs/langchain-community/src/chat_models/baiduwenxin.ts
=> community[patch]: bug-fix: manipulate data by Unint8Array

libs/langchain-groq/src/chat_models.ts
Groq no longer supports llama2 (see [here](https://console.groq.com/docs/models))
=> groq[patch]: Update default Groq model to Llama3 8B

docs/core_docs/docs/modules/data_connection/retrievers/vectorstore.mdx
This update fixes the variable name in a code snippet located at https://js.langchain.com/docs/modules/data_connection/retrievers/vectorstore.
=> docs: fix code snippet in retrievers/vectorstore article

libs/langchain-azure-openai/src/embeddings.ts, libs/langchain-azure-openai/src/tests/embeddings.int.test.ts
When batching is enabled, only the first embedding for the batch was generated. This PR fixes that.
=> azure-openai[patch]: fix only first embedding generated when batching enabled

langchain/src/document_loaders/web/s3.ts
Fixes #5253 
The S3Loader return an unclear error message when trying to load an S3 object without a file type. This PR fixes that.
=> Fix unclear S3Loader error message

libs/langchain-google-common/src/tests/utils.test.ts, libs/langchain-google-common/src/types.ts, libs/langchain-google-common/src/utils/zod_to_gemini_parameters.ts
=> google-common[patch]: remove all additionalProperties for gemini

libs/langchain-community/src/chat_models/zhipuai.ts
=> community[patch]: fix: #4997 zhipu chat model response typeError

docs/core_docs/docs/integrations/chat_memory/firestore.mdx
In the example, the `FirestoreChatMessageHistory` configuration object has a missing comma after `docs: ["user-id"]`
This commit updates the config example. 
```
const messageHistory = new FirestoreChatMessageHistory({
collections: ["chats"],
docs: ["user-id"],
sessionId: "user-id",
userId: "a@example.com",
config: {
projectId: "YOUR-PROJECT-ID",
credential: admin.credential.cert({
projectId: "YOUR-PROJECT-ID",
privateKey:
"-----BEGIN PRIVATE KEY-----\nCHANGE-ME\n-----END PRIVATE KEY-----\n",
clientEmail: "CHANGE-ME@CHANGE-ME-TOO.iam.gserviceaccount.com",
}),
},
});
```
=> Add missing a comma to FirestoreChatMessageHistory example

langchain-core/src/runnables/base.ts, langchain-core/src/runnables/remote.ts, langchain-core/src/runnables/tests/runnable_stream_events.test.ts, langchain-core/src/runnables/wrappers.ts
@bracesproul @eyurtsev not sure on form factor, we could just expose the helper method instead
=> Adds additional text/event-stream encodign format for streamEvents

docs/core_docs/docs/integrations/document_loaders/web_loaders/firecrawl.mdx
Replace the wrong firecrawl npm package with the correct one.
`npm install @mendableai/firecrawl-js (incorrect)`
`npm install @mendable/firecrawl-js (correct)`
=> fix(doc):  Firecrawl package issue

docs/core_docs/docs/integrations/vectorstores/azure_aisearch.mdx, libs/langchain-community/src/vectorstores/azure_aisearch.ts
This PRs includes the following changes:
- Fix missing `await initPromise` when doing a delete with filter, causing race conditions
- Set default search mode to hybrid to improve search results relevance
- Add documentation on hybrid search and semantic ranking
=> community[patch]: fix Azure AI search delete and improve documentation 

libs/langchain-google-gauth/src/auth.ts, libs/langchain-google-gauth/src/tests/auth.test.ts
Fixes #5285
- There were only integration tests in google-gauth, but I have added some unit tests. Is this okay?
- I also used npm link to verify locally that the issue has been resolved.
=> fix handling of multibyte characters in streams for google-gauth

libs/langchain-community/src/vectorstores/prisma.ts
=> community[patch]: prisma vectorStore support not in operator

langchain/src/agents/executor.ts
=> langchain[patch]: Fix passing run configs through in AgentExecutor

langchain-core/src/runnables/base.ts, langchain-core/src/runnables/iter.ts, langchain-core/src/runnables/tests/runnable.test.ts, langchain-core/src/singletons/index.ts
=> core[minor]: RunnableLambda should consume (async) iterator if the wrapped function returns one

langchain/package.json, langchain/src/experimental/openai_assistant/index.ts, libs/langchain-openai/package.json, libs/langchain-openai/src/azure/chat_models.ts, libs/langchain-openai/src/azure/embeddings.ts, libs/langchain-openai/src/azure/llms.ts, libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/embeddings.ts, libs/langchain-openai/src/index.ts, libs/langchain-openai/src/llms.ts, libs/langchain-openai/src/tests/azure/chat_models.int.test.ts, libs/langchain-openai/src/tests/azure/embeddings.int.test.ts, libs/langchain-openai/src/tests/azure/llms.int.test.ts, libs/langchain-openai/src/types.ts, yarn.lock
Cherry pick OpenAI changes into 0.1
@sarangan12 @bracesproul
=> openai[minor]: Cherry pick OpenAI changes into 0.1

langchain-core/package.json, langchain-core/src/language_models/base.ts, langchain/package.json, libs/langchain-azure-openai/package.json, libs/langchain-openai/package.json, libs/langchain-textsplitters/package.json, yarn.lock
=> chore[deps]: update js-tiktoken to 1.0.12 to support o200k_base

docs/core_docs/docusaurus.config.js
=> docs: disable contextual search

libs/langchain-anthropic/package.json, libs/langchain-anthropic/src/load/import_map.ts, libs/langchain-azure-openai/package.json, libs/langchain-cloudflare/package.json, libs/langchain-cohere/package.json, libs/langchain-exa/package.json, libs/langchain-google-common/package.json, libs/langchain-google-gauth/package.json, libs/langchain-google-genai/package.json, libs/langchain-google-vertexai-web/package.json, libs/langchain-google-vertexai/package.json, libs/langchain-google-webauth/package.json, libs/langchain-groq/package.json, libs/langchain-mistralai/package.json, libs/langchain-mongodb/package.json, libs/langchain-nomic/package.json, libs/langchain-openai/package.json, libs/langchain-pinecone/package.json, libs/langchain-qdrant/package.json, libs/langchain-redis/package.json, libs/langchain-textsplitters/package.json, libs/langchain-weaviate/package.json, libs/langchain-yandex/package.json, yarn.lock
anthropic[patch]: Release 0.1.18
azure-openai[patch]: Release 0.0.9
cloudflare[patch]: Release 0.0.5
cohere[patch]: Release 0.0.9
exa[patch]: Release 0.0.4
google-common[patch]: Release 0.0.14
google-gauth[patch]: Release 0.0.15
google-webauth[patch]: Release 0.0.14
google-vertexai[patch]: Release 0.0.15
google-vertexai-web[patch]: Release 0.0.14
google-genai[patch]: Release 0.0.13
groq[patch]: Release 0.0.10
mistralai[patch]: Release 0.0.20
mongodb[patch]: Release 0.0.2
nomic[patch]: Release 0.0.5
openai[patch]: Release 0.0.30
pinecone[patch]: Release 0.0.5
qdrant[patch]: Release 0.0.3
redis[patch]: Release 0.0.4
textsplitters[patch]: Release 0.0.1
weaviate[patch]: Release 0.0.2
yandex[patch]: Release 0.0.2
=> partnet packages[patch]: Release all

libs/langchain-anthropic/src/load/import_map.ts
Missing formatting. Build script seems to be adding extra newlines
=> anthropic[patch]: Run formatting

libs/langchain-openai/src/azure/chat_models.ts, libs/langchain-openai/src/azure/embeddings.ts, libs/langchain-openai/src/azure/llms.ts, libs/langchain-openai/src/utils/azure.ts
This PR is to:
1.  Add a default user agent to header requests for Azure requests in the `@langchain/openai` library.
2. We need to check for instance name & deployment name when using the token provider
@achandmsft @deyaaeldeen @xirzec FYI.....
=> Update default headers azure & Add Token Provider Check

docs/core_docs/docs/contributing/repo_structure.mdx
fix monorepo typo. `monorep` -> `monorepo`
=> docs[patch]: fix monorepo typo

docs/core_docs/src/theme/DocPaginator/index.js
Only hide on how to's and tutorials. Other pages appear to work just fine
=> docs[minor]: Hide prev/next buttons on how to and tutorials

docs/core_docs/docs/how_to/qa_chat_history_how_to.ipynb, docs/core_docs/docs/how_to/qa_citations.ipynb, docs/core_docs/docs/how_to/qa_sources.ipynb, docs/core_docs/docs/how_to/qa_streaming.ipynb, docs/core_docs/docs/how_to/vectorstore_retriever.mdx, docs/core_docs/docs/how_to/vectorstores.mdx, docs/core_docs/docs/integrations/retrievers/vectorstore.mdx, docs/core_docs/docs/tutorials/local_rag.ipynb, docs/core_docs/docs/tutorials/qa_chat_history.ipynb, docs/core_docs/docs/tutorials/rag.ipynb
everywhere `await pull...` is used I added extra cells logging the actual value of the prompt.
Also some link/bug fixes
=> docs[minor]: Log actual prompt when using prompt hub

langchain-core/src/language_models/chat_models.ts, langchain-core/src/runnables/tests/runnable_stream_events.test.ts, libs/langchain-anthropic/src/chat_models.ts, libs/langchain-cohere/src/chat_models.ts, libs/langchain-community/src/chat_models/fireworks.ts, libs/langchain-community/src/chat_models/ollama.ts, libs/langchain-community/src/chat_models/togetherai.ts, libs/langchain-mistralai/src/chat_models.ts, libs/langchain-openai/src/azure/chat_models.ts, libs/langchain-openai/src/chat_models.ts
openai[minor]
anthropic[minor]
community[minor]
cohere[minor]
mistral[minor]
=> core[minor]: Unified model params for LS

docs/core_docs/docs/how_to/document_loader_csv.mdx, docs/core_docs/docs/how_to/index.mdx, docs/core_docs/docs/tutorials/index.mdx
deleted all links to docs which are not yet implemented in how to/tutorials
=> docs[patch]: Remove links to missing docs

langchain-core/src/runnables/base.ts, langchain-core/src/runnables/passthrough.ts, langchain-core/src/runnables/tests/runnable_stream_events.test.ts, langchain-core/src/singletons/tests/async_local_storage.test.ts, langchain-core/src/utils/stream.ts
@nfcampos can you have a look please?
=> core[patch]: Move async generator consumption code into local storage context

libs/create-langchain-integration/template/package.json, libs/langchain-anthropic/package.json, libs/langchain-azure-openai/package.json, libs/langchain-cloudflare/package.json, libs/langchain-cohere/package.json, libs/langchain-community/src/vectorstores/tests/convex/package.json, libs/langchain-exa/package.json, libs/langchain-google-common/package.json, libs/langchain-google-gauth/package.json, libs/langchain-google-genai/package.json, libs/langchain-google-vertexai-web/package.json, libs/langchain-google-vertexai/package.json, libs/langchain-google-webauth/package.json, libs/langchain-groq/package.json, libs/langchain-mistralai/package.json, libs/langchain-mongodb/package.json, libs/langchain-nomic/package.json, libs/langchain-openai/package.json, libs/langchain-pinecone/package.json, libs/langchain-qdrant/package.json, libs/langchain-redis/package.json, libs/langchain-textsplitters/package.json, libs/langchain-weaviate/package.json, libs/langchain-yandex/package.json, yarn.lock
=> all[minor]: Update partner packages core dep semver

libs/langchain-pinecone/package.json, libs/langchain-weaviate/package.json, yarn.lock
=> pinecone[patch],weaviate[patch]: Bump weaviate and pinecone core deps

libs/langchain-google-common/src/connection.ts, libs/langchain-google-gauth/src/tests/chat_models.int.test.ts, libs/langchain-google-vertexai/src/tests/chat_models.int.test.ts, libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
Fixes #5475 
Not sure where or how, but it looks like we weren't aggregating streamed responses when streaming was false.
Since Vertex AI now supports non-streaming mode, it wasn't necessary anymore anyway. (It used to be.) So updated `AbstractGoogleLLMConnection.buildUrlMethodGemini()` to use the `streaming` setting.
Some of the tests were also failing because they were expecting structured, and not string, responses. No idea when that changed either, but adjusted the tests to handle.
=> google-common [patch], google-* [tests]: Fix streaming false

libs/langchain-community/src/chat_models/moonshot.ts
Moonshot does not return `data.usage` when `stream` is `true`. So we need to add a default value to avoid errors.
=> community[patch]: fix data.usage error because Moonshot sometimes does not return

libs/langchain-google-gauth/package.json, libs/langchain-google-vertexai-web/package.json, libs/langchain-google-vertexai/package.json, libs/langchain-google-webauth/package.json, yarn.lock
=> google-*[patch]: Release 0.0.17

langchain-core/src/singletons/index.ts
Sets `AsyncLocalStorage` on `globalThis` instead of encapsulating it in a singleton.
This enables a few things:
- Removes some of the need for a reverse peer dependency from LangSmith -> core
- If multiple instances of core get installed (e.g. if someone doesn't set `resolutions` and the package manager makes bad decisions), tracing will still use a single instance.
@dqbd @nfcampos
=> core[patch]: Set global async local storage instance

libs/langchain-community/src/graphs/neo4j_graph.ts
Fixes broken formatSchema function when not using enhancedSchema option.
=> community[patch]: Fix bug in Neo4j new enhancedSchema flag

libs/langchain-community/src/vectorstores/neo4j_vector.ts
Fixes #5594
Now we can emulate the `similaritySearch` function but also get back the score.
=> community[patch]: overriding similaritySearchWithScore in neo4j vector store to enable filtering

docs/core_docs/docs/integrations/vectorstores/googlevertexai.mdx
Fix import paths: some components have been moved to a `@langchain/community` package
=> [Docs] Fix wrong import paths at googlevertexai.mdx

langchain-core/src/callbacks/promises.ts
Fix JSDoc parameter description typo
=> core[patch]: Fix JSDoc parameter description typo

docs/core_docs/docs/how_to/document_loader_html.ipynb, docs/core_docs/docs/how_to/document_loader_markdown.ipynb, docs/core_docs/docs/integrations/document_loaders/file_loaders/unstructured.mdx
Fixes #5621- Update Unstructured Docker Image Reference in Documentation
=> docs[patch]: Update Unstructured Docker Image Reference in Documentation

libs/langchain-mongodb/src/vectorstores.ts
Method `delete` was missing in `MongoDBAtlasVectorSearch` class and it's needed if `incremental` _indexing_ strategy is used.
Be aware of the `// eslint-disable-line @typescript-eslint/no-explicit-any` as the `$in` operator needs explicitly an `ObjectID` type (as discussed [here](https://www.mongodb.com/community/forums/t/cant-use-string-ids-with-typescript/262793)) instead allowing an _union type_ `string | ObjectId`. The ids coming in are `uuid v4` ids, which don't match `ObjectID` type but it works just fine as a mongodb `_id`.
=> mongodb[minor]: add, implement delete method

libs/langchain-community/src/graphs/neo4j_graph.ts
This method allows that also neo4j 4.x is supported
=> community[patch]: Change neo4j verify connectivity method

libs/langchain-textsplitters/package.json, yarn.lock
=> textsplitters[patch]: Bump dependency range for @langchain/textsplitters

docs/core_docs/docs/tutorials/rag.ipynb
Found out that has wrong  API reference link on `rag.ipynb`
- https://js.langchain.com/v0.2/docs/tutorials/rag#go-deeper-1
please check here Interface external link above. 
[AS-IS]
- https://v02.api.js.langchain.com/classes/langchain_text_splitter.TextSplitter.html
- https://v02.api.js.langchain.com/modules/langchain_schema_document.html#BaseDocumentTransformer
[TO-BE]
- https://v02.api.js.langchain.com/classes/langchain_textsplitters.TextSplitter.html
- https://v02.api.js.langchain.com/classes/langchain_core_documents.BaseDocumentTransformer.html
=> docs[patch]: replace wrong interface API reference link

docs/core_docs/docs/integrations/chat/openai.mdx, examples/src/models/chat/integration_openai_parallel_tool_calls.ts, libs/langchain-openai/package.json, libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models_structured_output.int.test.ts, yarn.lock
Also bumped openai to latest version
=> openai[minor],docs[minor]: Add parallel tool calls call option and docs

libs/langchain-community/src/indexes/postgres.ts, libs/langchain-community/src/indexes/tests/postgres.int.test.ts
This is a proposal to support passing an instance of Pool when instantiating PostgresRecordManager. This would enable the reuse of an existing database connection pool.
```ts
import pg from "pg";
const pool = new pg.Pool(postgresConnectionOptions);
const providedPoolRecordManager = new PostgresRecordManager("test", {
...config,
pool,
});
```
https://github.com/langchain-ai/langchainjs/discussions/5676
=> community[patch]: allow to use postgres pool instance on PostgresRecordManager

docs/core_docs/docs/tutorials/agents.mdx, docs/core_docs/docs/tutorials/rag.ipynb, examples/src/retrievers/parent_document_retriever_rerank.ts, examples/src/retrievers/qdrant_self_query.ts
Closes https://github.com/langchain-ai/langchainjs/issues/5743
=> docs,examples[patch]: Replace .getRelevantDocuments with .invoke

libs/langchain-mistralai/package.json, libs/langchain-mistralai/src/chat_models.ts, libs/langchain-mistralai/src/tests/chat_models.int.test.ts, libs/langchain-mistralai/src/tests/chat_models.standard.int.test.ts, yarn.lock
=> mistral[minor]: Populate usage metadata for mistral

environment_tests/test-exports-cjs/package.json, environment_tests/test-exports-cjs/src/import.js, environment_tests/test-exports-cjs/src/index.mjs, environment_tests/test-exports-cjs/src/index.ts, environment_tests/test-exports-cjs/src/require.js, environment_tests/test-exports-esm/package.json, environment_tests/test-exports-esm/src/import.cjs, environment_tests/test-exports-esm/src/index.js, environment_tests/test-exports-esm/src/index.ts, environment_tests/test-exports-esm/src/require.cjs, libs/langchain-community/src/embeddings/hf_transformers.ts
Fixes #2992 
```
const transformers_1 = require("@xenova/transformers");
^
Error [ERR_REQUIRE_ESM]: require() of ES Module .\node_modules\@xenova\transformers\src\transformers.js from .\node_modules\langchain\dist\embeddings\hf_transformers.cjs not supported.
Instead change the require of transformers.js in .\node_modules\langchain\dist\embeddings\hf_transformers.cjs to a dynamic import() which is available in all CommonJS modules.
```
=> Fix [ERR_REQUIRE_ESM] error when importing hf_transformers

examples/src/models/chat/integration_googlevertexai-streaming.ts, examples/src/models/chat/integration_googlevertexai-tools.ts, examples/src/models/chat/integration_googlevertexai-wsa.ts, examples/src/models/chat/integration_googlevertexai.ts
=> update model name in these for making them eligible for multimodality

libs/langchain-community/src/vectorstores/milvus.ts
- Add configurable parameters for index creation,  So we can configure the index using index_type and metric_type.
=> community[minor]: Support configurable index creation for Milvus

examples/src/models/chat/integration_openai_parallel_tool_calls.ts
Correcting the Weather Schema's city type.
z.enum() -> z.string()
=> docs[patch]: Correcting zod types for OAI parallel tool calling doc

libs/langchain-community/src/vectorstores/milvus.ts, libs/langchain-community/src/vectorstores/tests/milvus.int.test.ts
Summary:
- Fixed issue with inserting into Milvus with `autoId` enabled 
- When `autoId` is enabled, the `insert` method is used
- When `autoId` is not enabled, the `upsert` method is used
- Added test from issue
Fixes #5813
=> community[patch]: Fix issue with inserting documents in Milvus with autoId enabled

langchain/src/retrievers/multi_query.ts
The MultiQueryRetriever can accept an instance of DocumentCompressor, but when executing compression - it will not pass the run manager and effectively, any chains executed inside DocumentCompressor will not get callbacks executed. 
This PR fixes this issue.
=> langchain[patch]: fix:pass runManager to DocumentCompressor in MultiQueryRetriever

langchain-core/src/documents/document.ts, langchain-core/src/tests/document.test.ts
=> core[patch]: fix: Document should handle empty pageContent (fixes #5884)

.github/workflows/compatibility.yml, dependency_range_tests/docker-compose.yml, dependency_range_tests/scripts/with_standard_tests/community/npm-install.sh
`npm` has rather severe peer dependency resolution requirements, this will verify that we are not violating any of them.
CC @bracesproul
=> ci[patch]: Adds npm install test for conflicting deps

libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models.int.test.ts
=> openai[patch]: Set stream_usage to false by default for Azure

langchain-core/src/language_models/tests/chat_models.test.ts, langchain-core/src/messages/base.ts, langchain-core/src/messages/utils.ts, langchain-core/src/prompts/chat.ts, langchain-core/src/prompts/tests/chat.test.ts
CC @agola11 @efriis @madams0013 @hinthornw
=> core[patch]: Adds support for plain message objects as shorthand for messages

libs/langchain-redis/src/chat_histories.ts, libs/langchain-redis/src/connections.ts
This is a premature optimization after having reviewed the code.
When supplied with a config instead of a client instance, a new connection will be opened each time a history is loaded.
Instead, we can reuse opened clients by keeping them in a "pool".
This PR affects the proposed change.
=> redis[patch]: Adds a connection pool to RedisChatHistory

.devcontainer/devcontainer.json, .yarnrc.yml
=> Fixes issue with local build from a devcontainer

libs/langchain-community/src/document_loaders/fs/unstructured.ts, libs/langchain-community/src/document_loaders/tests/unstructured.int.test.ts
=> community[patch]: unstructured loader support extractImageBlockType option

libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/azure/chat_models.int.test.ts, libs/langchain-openai/src/tests/chat_models-extended.int.test.ts, libs/langchain-openai/src/tests/chat_models.int.test.ts
Tests which relied on callbacks are flaky if `LANGCHAIN_CALLBACKS_BACKGROUND` is set to `true`. This is due to those callback funcs not necessarily completing until after the parent fn (in this case a chat model) has resolved. To solve this, I wrapped those tests in a `try { ... } finally { ... }` and set `LANGCHAIN_CALLBACKS_BACKGROUND` to false at the start of the test, and inside the `finally` block I reset it to the original value.
I also updated the Azure test `Test Azure ChatOpenAI with bearer token provider` to first check if the required env vars are set. If they are, it runs the test as normal. If not, it marks the test as skipped. Ideally we remove this code once we get our hands on those vars 🙃
=> openai[patch]: Fix integration tests

libs/langchain-standard-tests/src/integration_tests/chat_models.ts
Context: groq sometimes fails with this error:
```
Failed to call a function. Please adjust your prompt. See 'failed_generation' for more details.
```
This new prompting fixes that
=> standard-tests[minor]: Improve prompting to force model to call tool

libs/langchain-aws/src/tests/chat_models.int.test.ts, libs/langchain-cloudflare/src/tests/chat_models.int.test.ts, libs/langchain-cloudflare/src/tests/llms.int.test.ts, libs/langchain-cohere/src/tests/llms.int.test.ts, libs/langchain-google-genai/src/tests/chat_models.int.test.ts, libs/langchain-openai/src/tests/azure/llms.int.test.ts, libs/langchain-openai/src/tests/legacy.int.test.ts, libs/langchain-openai/src/tests/llms.int.test.ts
Updates all relevant integration tests which use callbacks to first set `LANGCHAIN_CALLBACKS_BACKGROUND` to `false` and cleanup at the end by resetting to whatever value it was originally.
I opted to not update deprecated tests such as those in the `langchain-azure-openai` package.
=> partners[patch]: Handle setting background callbacks to false in all relevant int tests

libs/create-langchain-integration/template/scripts/jest-setup-after-env.js, libs/langchain-anthropic/scripts/jest-setup-after-env.js, libs/langchain-aws/scripts/jest-setup-after-env.js, libs/langchain-azure-dynamic-sessions/scripts/jest-setup-after-env.js, libs/langchain-azure-openai/scripts/jest-setup-after-env.js, libs/langchain-baidu-qianfan/scripts/jest-setup-after-env.js, libs/langchain-cloudflare/scripts/jest-setup-after-env.js, libs/langchain-cohere/scripts/jest-setup-after-env.js, libs/langchain-community/scripts/jest-setup-after-env.js, libs/langchain-exa/scripts/jest-setup-after-env.js, libs/langchain-google-genai/scripts/jest-setup-after-env.js, libs/langchain-groq/scripts/jest-setup-after-env.js, libs/langchain-mistralai/scripts/jest-setup-after-env.js, libs/langchain-mixedbread-ai/scripts/jest-setup-after-env.js, libs/langchain-mongodb/scripts/jest-setup-after-env.js, libs/langchain-nomic/scripts/jest-setup-after-env.js, libs/langchain-pinecone/scripts/jest-setup-after-env.js, libs/langchain-qdrant/scripts/jest-setup-after-env.js, libs/langchain-redis/scripts/jest-setup-after-env.js, libs/langchain-standard-tests/scripts/jest-setup-after-env.js, libs/langchain-textsplitters/scripts/jest-setup-after-env.js, libs/langchain-weaviate/scripts/jest-setup-after-env.js
there's far too many console logs in our tests... this makes it difficult to diagnose failures in ci and similar. This PR allows for setting an env var (`DISABLE_CONSOLE_LOGS`) which will prevent `console.log` calls from actually logging anything.
=> all[minor]: Add ability to disable console logs in tests

docs/core_docs/docs/integrations/vectorstores/redis.mdx
Added missing dependency installation in docs for Redis VectorStore
pnpm add @langchain/openai @langchain/community -> 
pnpm add @langchain/openai @langchain/community @langchain/redis
=> docs[patch]: Update installation instructions with missing packages in redis docs

libs/langchain-google-common/src/utils/gemini.ts
=> google-common[patch]: Fix Gemini temperature validation

langchain-core/src/messages/base.ts, langchain-core/src/messages/tests/base_message.test.ts
Port of [#22002](https://github.com/langchain-ai/langchain/pull/22002/)
=> core[minor]: Allow concatenation of messages with multi part content

langchain/src/retrievers/parent_document.ts
Fix for bug introduced in https://github.com/langchain-ai/langchainjs/pull/5989 (sorry about this).
Fixes error: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
@PetersClemens
=> langchain[patch]: Bug fix for ParentDocumentRetriever

libs/langchain-community/src/chat_models/bedrock/web.ts, libs/langchain-community/src/chat_models/tests/chatbedrock.int.test.ts, libs/langchain-community/src/langgraph/checkpointers/tests/checkpointer.int.test.ts, libs/langchain-community/src/utils/bedrock/anthropic.ts, libs/langchain-community/src/utils/bedrock/index.ts
=> community[patch]: Adds support for Bedrock Anthropic tool streaming

docs/core_docs/docs/how_to/generative_ui.mdx
=> docs[patch]: Update Gen UI docs

docs/core_docs/docs/integrations/vectorstores/typesense.mdx
=> docs[patch]: Fix import path in typesense doc

libs/langchain-cohere/src/chat_models.ts, libs/langchain-community/src/chat_models/bedrock/web.ts, libs/langchain-google-common/src/chat_models.ts, libs/langchain-google-common/src/types.ts, libs/langchain-google-genai/src/chat_models.ts
Throw an error if `tool_choice` is passed to a model which does not support it. Updated instances where call options interface extended `BaseLanguageModelCallOptions` instead of `BaseChatModelCallOptions`
=> partners[minor]: Throw error if tool_choice is supplied but not supported

langchain-core/src/messages/ai.ts, langchain-core/src/messages/base.ts, langchain-core/src/messages/chat.ts, langchain-core/src/messages/modifier.ts, langchain-core/src/messages/tool.ts
Checked `console.dir(message, { depth: null })` and `JSON.stringify(message)`
Before:
```
AIMessage {
lc_serializable: true,
lc_kwargs: {
content: '',
tool_calls: [ [Object] ],
invalid_tool_calls: [],
additional_kwargs: { function_call: undefined, tool_calls: [Array] },
response_metadata: {},
id: 'chatcmpl-9m7NDoFInLTEzw9rF8cLv8mbE2BxQ'
},
lc_namespace: [ 'langchain_core', 'messages' ],
content: '',
name: undefined,
additional_kwargs: { function_call: undefined, tool_calls: [ [Object] ] },
response_metadata: {
tokenUsage: { completionTokens: 30, promptTokens: 63, totalTokens: 93 },
finish_reason: 'tool_calls'
},
id: 'chatcmpl-9m7NDoFInLTEzw9rF8cLv8mbE2BxQ',
tool_calls: [
{
name: 'pet_expert',
args: [Object],
type: 'tool_call',
id: 'call_kKW7x1wBsICArIvQwdo5Oty0'
}
],
invalid_tool_calls: …
```
=> core[patch]: Improve console.log format for messages

docs/core_docs/.gitignore, docs/core_docs/docs/how_to/index.mdx, docs/core_docs/docs/how_to/tool_choice.ipynb, langchain-core/src/language_models/chat_models.ts
Depends on `@langchain/core` v `0.2.17` releasing
Depends on `@langchain/openai` v `0.2.4` releasing
Depends on `@langchain/groq` v `0.0.15` releasing
Depends on `@langchain/aws` v `0.0.3` releasing
=> docs[minor]: Add tool choice how to guide

libs/langchain-aws/src/common.ts, libs/langchain-aws/src/tests/chat_models.test.ts
=> aws[patch]: Fix error when processing empty string chunk conent

docs/core_docs/docs/integrations/platforms/aws.mdx, docs/core_docs/docs/integrations/text_embedding/bedrock.mdx, examples/src/embeddings/bedrock.ts, libs/langchain-aws/package.json, libs/langchain-aws/src/embeddings.ts, libs/langchain-aws/src/index.ts, libs/langchain-aws/src/tests/embeddings.int.test.ts, libs/langchain-community/src/embeddings/bedrock.ts, yarn.lock
Ported from community
Added `langchain` as workspace dev dep so I can access `MemoryVectorStore` in tests
=> aws[major]: Add bedrock embeddings to aws package

docs/core_docs/docs/integrations/callbacks/upstash_ratelimit_callback.mdx
In the Upstash Ratelimit Callback docs, `limiter` should be set to `Ratelimit.fixedWindow(10, "60 s")` instead of `Ratelimit.fixedWindow(1, "60 s")`.
This is because the comment above it says "10 requests per window, where window size is 60 seconds:". The current docs have it as 1 request every 60 seconds
If you visit the Upstash docs, you see the correct syntax is as follows:
=> docs[patch]: Typo fixed in Upstash Ratelimit Callback

docs/core_docs/docs/tutorials/sql_qa.mdx
This PR will remove the duplicate content from the SQL QA tutorial doc page.
**Before**
**After**
=> docs[patch]: remove duplicate content from sql QA tutorial page

examples/src/chains/llm_chain.ts, examples/src/chat/agent.ts
Description: Added LangChain v0.2 support For the LangChain AgentExecutor using react agent executor which manages a state that is defined by a list of messages in a similar way to the AgentExecutor.  Removed classes as well like LLMChain which were deprecated from LangChain v0.1.
Used the LangChain Expression Language (LCEL) instead of LLMChain deprecated class
=> docs[minor]: Replace deprecated code examples with LCEL & AgentExecutor

libs/langchain-community/src/embeddings/baidu_qianfan.ts
model name `bge-large-en` should be `bge_large_en` like `bge_large_zh`
at line 188 in the same file： `https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/embeddings/${this.modelName}?access_token=${this.accessToken}`
`${this.modelName}` directly used in the URL
URL for the image：`https://cloud.baidu.com/doc/WENXINWORKSHOP/s/mllz05nzk`
=> community[patch]: Fix typo in modelName options of `BaiduQianfanEmbeddings`

libs/langchain-google-common/src/chat_models.ts, libs/langchain-google-common/src/tests/chat_models.test.ts, libs/langchain-google-common/src/types.ts, libs/langchain-google-common/src/utils/common.ts, libs/langchain-google-vertexai/src/tests/chat_models.int.test.ts
Closes https://github.com/langchain-ai/langchainjs/issues/6158
Also fixes callbacks by actually calling `handleLLMNewToken`
=> google-common[patch]: Add streaming constructor param

libs/langchain-scripts/bin/build.js, libs/langchain-scripts/package.json, libs/langchain-scripts/src/build_v2.ts, libs/langchain-scripts/src/check-tree-shaking.ts
Also properly throw if a side effect is detected
=> build[patch]: Add way to escape side effects within an entrypoint

libs/langchain-anthropic/src/chat_models.ts, libs/langchain-anthropic/src/tests/chat_models-tools.int.test.ts
Fixes https://github.com/langchain-ai/langchainjs/issues/6045
When anthropic extracts tokens during tool use, it's throwing an error on the `message_start` event, as it results in a chunk with an empty content array, but the current token parsing assumes that a single content item always exists. This PR fixes the issue.
```
{
type: 'message_start',
message: {
id: 'msg123',
type: 'message',
role: 'assistant',
model: 'claude-3-5-sonnet-20240620',
content: [],
stop_reason: null,
stop_sequence: null,
usage: { input_tokens: 1486, output_tokens: 12 }
}
}
```
The current error thrown:
```
error: TypeError: Cannot use 'in' operator to search for 'input' in undefined
at extractToken
```
=> anthropic[patch]: ensure content exists when parsing tool tokens

docs/core_docs/src/theme/ChatModelTabs.js
port https://github.com/langchain-ai/langchain/pull/24583
update with latest models
=> docs: Update ChatModelTabs defaults

docs/core_docs/docs/tutorials/llm_chain.ipynb
=> docs[patch]: Fix ChatModelTabs openai model typo

docs/core_docs/docs/how_to/index.mdx
@bracesproul let's try not to prefix API ref links
=> docs[patch]: Fix broken link

libs/langchain-aws/package.json, libs/langchain-aws/src/retrievers/bedrock.ts, libs/langchain-aws/src/retrievers/tests/bedrock.int.test.ts, yarn.lock
Adds optional `filter` and optional `overrideSearchType` parameters to the Bedrock knowledge base client:
```ts
export interface AmazonKnowledgeBaseRetrieverArgs {
knowledgeBaseId: string;
topK: number;
region: string;
clientOptions?: BedrockAgentRuntimeClientConfig;
filter?: RetrievalFilter;
overrideSearchType?: SearchType;
}
```
Also, updates the source location of the document depending on the KB configuration: S3, WEB, CONFLUENCE, SALESFORCE, SHAREPOINT
=> bedrock[minor]: Allow knowledge bases to use filters and searchType

libs/langchain-google-common/src/utils/gemini.ts, libs/langchain-google-vertexai/package.json, libs/langchain-google-vertexai/src/tests/chat_models.int.test.ts, libs/langchain-google-vertexai/src/tests/chat_models.standard.int.test.ts, yarn.lock
todo:
- verify we have a standard test that checks models can stream tool calls.
=> google-common[minor]: Fix streaming tool calls

docs/core_docs/docs/how_to/agent_executor.ipynb, docs/core_docs/docs/tutorials/pdf_qa.ipynb
https://js.langchain.com/v0.2/docs/how_to/agent_executor/#using-language-models
https://js.langchain.com/v0.2/docs/tutorials/pdf_qa/#question-answering-with-rag
This PR fixes the same type of typo as in #6191.
=> docs[patch]: Fix ChatModelTabs openaiParams typo

libs/langchain-groq/package.json, libs/langchain-groq/src/chat_models.ts, libs/langchain-groq/src/tests/chat_models.int.test.ts, libs/langchain-groq/src/tests/chat_models.standard.int.test.ts, yarn.lock
Their API doesn't appear to yield more than one chunk.
This change simply calls the streaming endpoint instead of non-streaming when tools are passed.
=> groq[minor]: Implement streaming tool calls

docs/core_docs/docs/how_to/streaming.ipynb, libs/langchain-cohere/src/tests/chat_models.standard.int.test.ts, libs/langchain-community/src/chat_models/tests/chatbedrock.standard.int.test.ts, libs/langchain-google-genai/src/tests/chat_models.standard.int.test.ts, libs/langchain-google-vertexai/src/tests/chat_models.standard.int.test.ts, libs/langchain-groq/src/tests/chat_models.standard.int.test.ts, libs/langchain-openai/src/tests/azure/chat_models.standard.int.test.ts, libs/langchain-openai/src/tests/chat_models.standard.int.test.ts, libs/langchain-standard-tests/src/integration_tests/chat_models.ts
Also skip tests in partner repos which are known failures
=> standard-tests[patch]: Add descriptive comments/docstrings to standard tests

libs/langchain-mistralai/src/chat_models.ts, libs/langchain-mistralai/src/tests/chat_models.standard.test.ts, libs/langchain-mistralai/src/tests/chat_models.test.ts, libs/langchain-mistralai/src/utils.ts
Port of https://github.com/langchain-ai/langchain/pull/24668
I couldn't use the built in `crypto` module because it is not avail in all js environments, so instead I implemented my own method.
=> mistralai[patch]: Translate tool call ids to mistral compat format

langchain/package.json, libs/langchain-google-gauth/package.json, libs/langchain-google-vertexai/package.json, yarn.lock
also bump min version for google-vertexai in langgraph
=> google[patch]: Set min core version for vertex and gauth

libs/langchain-mistralai/src/tests/chat_models.int.test.ts
Mistral sometimes hallucinates tools in this case, so instead just verify it calls a tool.
=> mistralai[patch]: Fix flaky tool calling test

langchain-core/src/messages/tests/message_utils.test.ts, langchain-core/src/messages/utils.ts, langchain-core/src/runnables/remote.ts
- Fixes mapStoredMessageToChatMessage to check on generic role when creating ChatMessage
- Added test to ensure that when an instance of ChatMessage is converted to StoredMessage, it can be converted back.
=> fix: fix mapStoredMessageToChatMessage to check on generic role when creating ChatMessage

libs/langchain-community/src/vectorstores/xata.ts
* fix: TypeError when using VectorSearchWithScore
The xata client created with the xata init command probably has changed its response, creating a TypeError, as the property xata does not exist in the response created by the client. This stops the code execution, as it is trying to access object.xata.score.
Currently, the expected score is found in the object.xata_score property.
In order to prevent breaking changes, the old way is preserved, but it checks if the property exists first. If it does not exist, it access the "current" property
Fixes #6240
=> community[patch]: fix TypeError using the client created with xata init

docs/core_docs/.gitignore, docs/core_docs/README.md, docs/core_docs/docs/how_to/streaming.ipynb, docs/core_docs/package.json, docs/core_docs/scripts/quarto-build.js, docs/core_docs/scripts/validate_notebook.ts, yarn.lock
=> docs[patch]: Support hidden docs cells and TS validation in notebooks

libs/langchain-community/src/document_loaders/web/github.ts
This PR avoids the `shouldIgnore` check on directories when looping over files in a github repo that is loaded using the `GithubRepoLoader`. 
The issue with checking `shouldIgnore` on a directory is that a directory path might match an ignore pattern while its content does not. For instance, `ignorePaths: ["*", "!*/", "!**/*.txt"]` results in `ignore.ignores("subfolder") == true` but `ignore.ignores("subfolder/file.txt") == false`. Before this fix, the `GithubRepoLoader` will miss `subfolder/file.txt` and any other files in subfolders that should be included. My solution here is to avoid the `shouldIgnore` test on directories and only check `shouldIgnore` on files. This means all directories will be traversed in a recursive load but only the correct files will be loaded. 
I was unsure how …
=> community[patch]: avoid shouldIgnore on folders for GithubRepoLoader

libs/langchain-google-common/src/chat_models.ts
This allows for Google VertexAI to properly handle message histories where two or more tool results are passed back at once.
I am still unable to make Google VertexAI actually call two functions at once.
=> google-common[patch]: Merge adjacent function results in google common

libs/create-langchain-integration/docs/chat.ipynb
TODO later:
- refactor CLI so you can create one of these via cli
=> cli[minor]: Add base chat model integration template

langchain-core/src/messages/base.ts, langchain-core/src/messages/tool.ts, langchain-core/src/runnables/remote.ts, langchain-core/src/tools/index.ts, langchain-core/src/tools/tests/tools.test.ts
Added new `status` field to tools.
TODO in separate PR:
- [update anthropic to use this field](https://github.com/langchain-ai/langchain/pull/24628/files#diff-e2dea7070f0cc79e3fc72e08f7a809d2ae17ae8924794bd917c72d37dc65cc1c)
- doc section on `status` field.
- update LangGraph `ToolNode` to use `status` field.
=> core[minor]: Add status field to tool

docs/core_docs/package.json, docs/core_docs/scripts/validate_notebook.ts, yarn.lock
=> ci[patch]: Allow duplicate imports in notebooks

docs/core_docs/docs/how_to/callbacks_custom_events.ipynb
`@langchain/callbacks/dispatch/web` -> `@langchain/core/callbacks/dispatch/web`
=> docs[patch]: Fix import path in dispatching events doc

libs/langchain-scripts/src/cli/docs/chat.ts, libs/langchain-scripts/src/cli/docs/index.ts, libs/langchain-scripts/src/cli/docs/templates/chat.ipynb
adds new `--community` flag for `@langchain/community` integrations
=> scripts[patch]: Update chat model template cli to support community integrations

langchain-core/src/tools/index.ts, langchain-core/src/tools/tests/tools.test.ts
If you init a tool with JSON schema, it will not currently validate/infer any types.
Types are starting to get pretty hairy in general but I've added some tests around them.
CC @bracesproul @nfcampos
=> core[patch]: Allow dynamic tools to be initialized with JSON schema

langchain/src/tools/sql.ts
In the `sqlAgent`, the `query-checker` step currently references `sqlite` specifically in the prompt, which is incorrect since the `sqlAgent` can interact with multiple types of databases. To make this prompt more accurate and applicable to various SQL databases, I have replaced `sqlite` with `SQL`.
=> langchain[patch]: Fix: Change sqlite to SQL in query checker prompt

.github/workflows/validate_new_notebooks.yml
=> ci[patch]: Make notebook validation only run in core_docs

langchain-core/src/callbacks/manager.ts, langchain-core/src/language_models/tests/chat_models.test.ts, langchain-core/src/utils/testing/index.ts
Using:
```ts
await runManager?.handleCustomEvent("some_test_event", {
someval: true,
});
```
Some concerns about misuse but I think generally useful as an escape hatch.
CC @afirstenberg
=> core[patch]: Allow any module to emit a custom event

libs/langchain-anthropic/src/output_parsers.ts, libs/langchain-anthropic/src/tests/chat_models-tools.int.test.ts
=> anthropic[patch]: Fix Anthropic streaming calls with withStructuredOutput

libs/langchain-community/src/vectorstores/pgvector.ts
Issue:
We're working on a tenant based SaaS platform where we use separate tables for each tenant (to avoid infinitely growing tables).
The `createHnswIndex` function translates into a query like 
```
CREATE INDEX IF NOT EXISTS vector_embedding_hnsw_idx
ON tenant_123_index USING hnsw ((vector::vector(1536)) vector_cosine_ops)
WITH (
m=16,
ef_construction=64
);
```
where the index name is always `vector_embedding_hnsw_idx`.
Within the same schema in PostgreSQL, the index name must be unique across all tables.
This means it’s created for the first tenant, but not for anyone else since then the index with that static name already exists.
This PR allows to pass an optional `namespace` string to `createHnswIndex` which is used a prefixing the index name.
=> community[patch]: Add namespace to allow indexing multiple tables within the same schema

libs/langchain-mongodb/src/storage.ts
When retrieving records from MongoDBStore the value was always JSON.stringified even if the value was already in JSON.  As a result, MongoDBStore does not work with standard retrievers like the ParentRetriever as it would always return documents with undefined for pageContent.  This corrects that behavior by look at the value and only JSON.stringify if it is an Object.  If it is a string then it just returns the value as is.
=> mongodb[patch]: Fix bug in mongodb storage.ts

package.json, yarn.lock
=> Lock protobufjs version to resolve critical vulnerability

libs/langchain-community/src/chat_models/fireworks.ts
- ChatFireworks manifest sometimes uses `modelName` to define the model, which incorrectly leads to defaulting to the default model
- Existing default model has been deprecated by Fireworks, causing it to error out. Update default model to llama-3.1-8b
=> community[patch]: support modelName param and update default fireworks model to Llama 3.1 8B

langchain-core/src/runnables/base.ts, langchain-core/src/runnables/tests/runnable_with_fallbacks.test.ts
=> core[patch]: Adds streaming for RunnableWithFallbacks, update input

libs/langchain-community/package.json, libs/langchain-community/src/document_loaders/web/firecrawl.ts, yarn.lock
Fixes #6489 
JS Version of langchain-ai/langchain/pull/24747
This PR would provide support for users to use self-hosted instances of Firecrawl.
The FirecrawlApp class already has support to pass this argument. See https://github.com/mendableai/firecrawl/blob/main/apps/js-sdk/firecrawl/src/index.ts#L9
=> community[patch]: Support for specifying api url for firecrawl document loader

langchain-core/src/runnables/tests/signal.test.ts, langchain-core/src/utils/signal.ts
Partially fixes #6461, though if more than 10 runnables in a chain run in parallel this warning will likely resurface.
CC @nfcampos
=> core[patch]: Remove signal event listener when completed

libs/langchain-google-common/src/tests/utils.test.ts, libs/langchain-google-common/src/utils/stream.ts
Fixes #6501 
I have fixed this issue similarly to #5286.
The approach is the same, but we need to use components that work in the Browser environment instead of Node.
I previously fixed the same issue for `@langchain/google-vertexai` in #5285.
Although I don't use `@langchain/google-vertexai-web` myself, I've also fixed this package as it was requested in the issue.
=> google[patch]: fix: handling multibyte characters in stream for google-vertexai-web

libs/langchain-aws/src/chat_models.ts
When using the Converse APIs in `ChatBedrockConverse` the `AbortSignal` wasn't being passed in. 
This prevented the cancellation from working.
=> aws[patch]: Use abort signal when available with SDK requests

libs/langchain-community/src/document_loaders/fs/unstructured.ts
* This issue was raised here https://github.com/langchain-ai/langchainjs/issues/2144
* It was fixed int he old `langchain` module and still is fixed here https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/document_loaders/fs/unstructured.ts#L328
* The community version, however, doesn't have this check. 
This also adds the missing field https://github.com/Unstructured-IO/unstructured-api?tab=readme-ov-file#chunking-elements
=> community[patch]: bugfix: Unstructured empty text

libs/langchain-pinecone/src/tests/vectorstores.int.test.ts, libs/langchain-pinecone/src/vectorstores.ts
When querying for documents using the `PineconeStore` via the various search methods, the documents getting returned from Pinecone currently have their `id` property set to `undefined`.
This is because `id` is omitted when the result is converted to a document prior to being returned, as shown below for each query method respectively:
`similaritySearchVectorWithScore`
https://github.com/langchain-ai/langchainjs/blob/abdcd1fa3b74f066e4a7cbe3688a99f719f8f75b/libs/langchain-pinecone/src/vectorstores.ts#L424-L426
`maxMarginalRelevanceSearch`
https://github.com/langchain-ai/langchainjs/blob/abdcd1fa3b74f066e4a7cbe3688a99f719f8f75b/libs/langchain-pinecone/src/vectorstores.ts#L476-L478
This PR adds a new private method named `_formatMatches` that accepts an array of matches …
=> pinecone[patch]: Fix document ID not getting set when returned from PineconeStore

libs/langchain-aws/src/chat_models.ts, libs/langchain-openai/src/azure/chat_models.ts, libs/langchain-openai/src/chat_models.ts
cc @jacoblee93 remember to run the jsdoc examples to verify there aren't type errors
=> parnters[patch]: Fix type errors in JSDoc examples

libs/langchain-groq/src/chat_models.ts, libs/langchain-groq/src/tests/chat_models.standard.int.test.ts
New concatenated `AIMessage` as a result of calling `.stream` looks like this:
```txt
AIMessageChunk {
"id": "req_01j5pkw120f7wbwsxqs62742nj",
"content": "The color of the sky can appear different depending on the time of day, weather, and location. On a clear day, the",
"additional_kwargs": {},
"response_metadata": {
"finishReason": "length",
"id": "chatcmpl-0f82c5dc-5701-4d67-9fe7-a403468466f0",
"object": "chat.completion.chunk",
"created": 1724114666,
"model": "mixtral-8x7b-32768",
"system_fingerprint": "fp_c5f20b5bb1",
"x_groq": {
"id": "req_01j5pkw120f7wbwsxqs62742nj",
"usage": {
"queue_time": 0.012457195,
"prompt_tokens": 14,
"prompt_time": 0.002072875,
"completion_tokens": 26,
"completion_time": 0.04022823,
"total_tokens": 40,
"total_time": 0.042301105
}
}
},
"tool_calls": [], …
```
=> groq[minor]: Fix streaming metadata back to client

libs/langchain-scripts/src/build_v2.ts
cc @jacoblee93 touches your allow side effects code
=> scripts[patch]: Fix bug for checking allowed side effects comment

langchain-core/src/runnables/graph.ts
Used within LangGraphJS and LangGraphJS API
=> fix(core): return conditional edge in toJSON

langchain/src/agents/react/output_parser.ts
Fixes #6374 for ReAct agents
`handleParsingErrors` does not work for ReAct agents. This fixes it.
=> langchain[patch]: Fixes bug in ReAct agent that prevents parsing error handling

langchain-core/src/tracers/console.ts
Prior to this change, when `onToolEnd` is called, it assumed the value of `run.outputs.output` is always of type `string`. In cases when it wasn't a string, this would cause a `TypeError` to be thrown.
Note that it appeared that the same issue could occur in `onToolStart`, so I corrected that case as well.
=> core[patch]: Prevent ConsoleCallbackHandler from throwing TypeError when logging

.github/workflows/spam-comment-filter.yml
Good to sanitize the comment - otherwise the spammer could quite literally do much worse than spam the repository.
My [tool](https://github.com/adnaneKhan/gato-x) picked this up on a nightly scan I run (just running on the repo here):
```
.d8888b.         d8888 88888888888  .d88888b.         Y88b   d88P
d88P  Y88b       d88888     888     d88P" "Y88b         Y88b d88P
888    888      d88P888     888     888     888          Y88o88P
888            d88P 888     888     888     888           Y888P
888  88888    d88P  888     888     888     888           d888b
888    888   d88P   888     888     888     888 888888   d88888b
Y88b  d88P  d8888888888     888     Y88b. .d88P         d88P Y88b
"Y8888P88 d88P     888     888      "Y88888P"         d88P   Y88b
By @adnanthekhan - …
```
=> infra[patch]: Sanitize body in spam filter

docs/core_docs/docs/tutorials/agents.mdx
=> docs[patch]: Fix typos in Agents tutorial

libs/langchain-openai/src/chat_models.ts
OpenAI SDK's `ClientOptions` includes `apiKey`. It looks like `@langchain/openai`'s `ChatOpenAI` constructor does not honor that field. 
Referenced in the docs [here](https://v02.api.js.langchain.com/interfaces/_langchain_openai.ClientOptions.html).
=> fix(openai): Check `configuration.apiKey` in `ChatOpenAI` constructor

libs/langchain-community/src/vectorstores/elasticsearch.ts, libs/langchain-community/src/vectorstores/tests/elasticsearch.int.test.ts
=> fix(community): ElasticVectorSearch: exclude metadata filters not working due changing to term instead of terms

docs/core_docs/docs/tutorials/llm_chain.ipynb
=> Fix tiny typo in llm_chain.ipynb

docs/core_docs/docs/integrations/chat/anthropic.ipynb, docs/core_docs/package.json, libs/langchain-anthropic/package.json, libs/langchain-anthropic/src/chat_models.ts, libs/langchain-anthropic/src/tests/chat_models.int.test.ts, yarn.lock
Support for custom Anthropic clients using @langchain/anthropic, which will allow the use of @anthropic-ai/vertex-sdk and @anthropic-ai/bedrock-sdk, and also support custom Anthropic, such as supporting a modified version of the edge runtime.
```ts
import { expect, it } from 'vitest'
import { authenticate } from '../authenticate'
import { ChatAnthropic } from '@langchain/anthropic'
import { AnthropicVertex } from '@anthropic-ai/vertex-sdk'
import { GoogleAuth } from 'google-auth-library'
import { AnthropicVertexWeb } from '../AnthropicVertex'
it('Call Anthropic Vertex on nodejs', async () => {
const client = new AnthropicVertex({
region: import.meta.env.VITE_VERTEX_ANTROPIC_REGION,
projectId: import.meta.env.VITE_VERTEX_ANTROPIC_PROJECTID,
googleAuth: new GoogleAuth({
credentials: { …
```
=> feat(anthropic): langchain-anthropic support custom create anthropic client

libs/langchain-community/package.json, package.json, yarn.lock
Prior to this change, running `yarn` in the top-level directory of the repo failed on node >= v22. After this change, it succeeds.
This was cased by the version of the `better-sqlite3` package being pinned to 9.4.0 in the top-level `package.json`. This change was introduced by @jacoblee93 in [#5694](https://github.com/langchain-ai/langchainjs/pull/5694/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R64). It's not clear from that PR why he added the package to the top-level `package.json` (I can't find anything that references it in the top-level), or why he pinned it to that specific version. Perhaps he could chime in here.
Edit: I updated this change to remove the range definition from the top-level `resolutions` object, as my initial change would've had the …
=> Fix top-level dependency install for node 22+

libs/langchain-openai/package.json, libs/langchain-openai/src/chat_models.ts, yarn.lock
=> fix(openai): Fix type import issue

libs/langchain-openai/src/tools/dalle.ts
This simple pull request adds the `baseUrl` to DallEAPIWrapper. It can be used for Cloudflare AI Gateway or other use cases.
=> feat(openai): baseUrl for DallEAPIWrapper

libs/langchain-anthropic/src/tests/chat_models.int.test.ts, libs/langchain-anthropic/src/utils/message_inputs.ts
=> anthropic[patch]: Fix passing cache control through in messages

libs/langchain-anthropic/src/chat_models.ts, libs/langchain-anthropic/src/tests/chat_models-tools.int.test.ts
=> anthropic[minor]: Allow different tool types to be bound

examples/src/indexes/vector_stores/chroma/fromDocs.ts
Simply changes the chroma docs link.
I checked existing PRs and issues and couldn't find something relevant already existing. Please give me feedback :)
=> docs[patch]: fix chroma distance function reference link

environment_tests/test-exports-tsc/main.ts, environment_tests/test-exports-tsc/package.json, langchain-core/src/utils/stream.ts
=> fix(core): Pin TypeScript version for now for export test failures, add asyncDispose

libs/langchain-baidu-qianfan/src/chat_models.ts
Even when `streaming` is set to `true`, the original `completionWithRetry` function waits until all chunks are received before triggering the event and returning the result.
This PR updates the `completionWithRetry`, `_generate` and use `_streamResponseChunks` function to handle streaming chunk from BaiduQianFan.
The refactor also fixed the original error of `Invalid "runId" provided to "handleLLMNewToken" callback.`
=> baidu-qianfan[patch]: Fix streaming mode of Qianfan

docs/core_docs/docs/integrations/chat/anthropic.ipynb, libs/langchain-anthropic/src/chat_models.ts
Fixes https://github.com/langchain-ai/langchainjs/pull/6615#issuecomment-2334981613
=> fix(anthropic): Do not check for apiKey existence when createClient parameters are present

langchain-core/package.json, langchain/package.json, yarn.lock
Resolves the circular peer dep issue that is now seen when running `npm install`
Fixes #6792
Fixes #6789
=> fix(core, langchain): Update langsmith dep to rc

docs/core_docs/docusaurus.config.js
wait to merge until 0.3 sites are hosted at js.langchain.com/docs, and algolia crawler for js-langchain-latest has been run.
=> docs: new algolia index

docs/core_docs/docs/integrations/document_loaders/web_loaders/firecrawl.ipynb
Firecrawl integration is currently on v0 - which is supported until version 0.0.36.
@rafaelsideguide is working on a pr for v1 but meanwhile we should fix the docs.
=> docs: Fix Firecrawl v0 version in the docs

.github/workflows/deploy-api-refs-prod.yml
Only deploy to prod if the branch is `main`. This allows us to deploy `v0.1` and `v0.2` via this workflow
=> fix(ci): Conditionally deplpy api refs to prod

docs/core_docs/docs/tutorials/chatbot.ipynb
Thank you very much for maintaining langchain in JS.
:)
=> docs(tutorial): fix typo

libs/langchain-anthropic/src/index.ts, libs/langchain-anthropic/src/tests/chat_models.test.ts, libs/langchain-anthropic/src/tests/prompts.int.test.ts, libs/langchain-anthropic/src/utils/prompts.ts, libs/langchain-openai/src/index.ts, libs/langchain-openai/src/tests/prompts.int.test.ts, libs/langchain-openai/src/utils/prompts.ts
=> feat(anthropic,openai): Add payload formatting utils to Anthropic and OpenAI

libs/langchain-ollama/src/chat_models.ts
[Not yet supported](https://ollama.com/blog/tool-support#:~:text=Tool%20choice%3A%20force%20a%20model%20to%20use%20a%20tool)
=> fix(ollama): Drop tool_choice from docstrings

langchain-core/src/language_models/chat_models.ts
Long overdue, remove the need for various casts
Still allows optionality for models to return broader types in the future
CC @dqbd @hinthornw @bracesproul
=> fix(core): Narrow chat model return type

libs/langchain-community/src/structured_query/supabase.ts
This PR fixes a minor error in the `SupabaseTranslator` file, specifically in the `visitComparisonAsString()` function that takes in a Comparison object and converts it to a format suitable for RPC.
- The change fixes an extra `}` that causes the API call to Supabase to return no rows.
=> fix(community): supabase comparison to string function

libs/langchain-community/src/vectorstores/hanavector.ts
* Description: This PR fixes an issue with SAP HANA Cloud QRC03 version. In that version the number to indicate no length being set for a vector column changed from -1 to 0. The change in this PR support both behaviours (old/new).
* Dependencies: No dependencies have been introduced.
The same issue has been fixed in the python library as well:
https://github.com/langchain-ai/langchain/pull/23516
https://github.com/langchain-ai/langchainjs/issues/6913
=> fix(community): Column VEC_VECTOR has the wrong length

langchain-core/.gitignore, langchain-core/langchain.config.js, langchain-core/package.json, langchain-core/src/callbacks/dispatch/index.ts, langchain-core/src/context.ts, langchain-core/src/singletons/index.ts, langchain-core/src/tests/context.test.ts, langchain-core/src/tracers/tests/langsmith_interop.test.ts, yarn.lock
Modifies the `RunTree` object to maintain backwards compatibility with older LangSmith instances
=> feat(core): Adds support for context variables

libs/langchain-community/src/vectorstores/pgvector.ts
Currently the ids are not returned when querying a pgvector store. This adds them to the returned document.
=> feat(community): Return document ids when querying pgvector store

libs/langchain-aws/src/common.ts
Currently, Amazon Bedrock supports text, images and documents in their [Converse API](https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference-examples.html). 
It appears that the [langchain-aws](https://github.com/langchain-ai/langchain-aws) (the python version), has added support for both of these message content types:
- Link to the [Issue](https://github.com/langchain-ai/langchain-aws/issues/132)
- Link to the [Pull Request](https://github.com/langchain-ai/langchain-aws/pull/143)
This change adds support for both `type === 'document'` and  `type === 'image'` per the Converse API examples.
Fixes #6955
=> feat(aws): Added AWS Bedrock Document and Image Support

docs/core_docs/docs/how_to/installation.mdx, langchain-core/package.json, langchain-core/src/utils/tests/polyfill_stream.test.ts, libs/langchain-scripts/src/tests/__mdx__/modules/index.mdx, libs/langchain-scripts/src/tests/__mdx__/modules/two.mdx, yarn.lock
it is useless when `import "web-streams-polyfill/es6"` ，When `web-streams-polyfill` is at version 3, 
it should be referenced like in the file `langchain-core\src\utils\tests\polyfill_stream.test.ts`. That is, import "web-streams-polyfill".
=> fix(docs): usage web-streams-polyfill

docs/core_docs/docs/integrations/document_loaders/web_loaders/apify_dataset.mdx, examples/src/document_loaders/apify_dataset_existing.ts, examples/src/document_loaders/apify_dataset_new.ts, libs/langchain-community/src/document_loaders/web/apify_dataset.ts
- Add Origin/langchain to Apify's client's user-agent to attribute API activity to LangChain (at Apify, we aim to monitor our integrations to evaluate whether we should invest more in the LangChainjs integration regarding functionality and content).
- Fix issues in documentation (and improve content)
=> feat(community): Add Origin/langchain to Apify's client's user-agent to attribute API activity to langchainhs

docs/core_docs/docs/integrations/chat/openai.ipynb, libs/langchain-openai/package.json, libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models.int.test.ts, libs/langchain-openai/src/types.ts, yarn.lock
TODO:
- run standard int tests
- test azure
- add docs
=> feat(openai): Support audio output

libs/langchain-community/src/experimental/llms/chrome_ai.ts
Using latest interface definitions from prompt-api spec.
=> fix(community): AILanguageModel interface

langchain-core/src/memory.ts, langchain/src/memory/tests/buffer_window_memory.test.ts
This PR addresses the issue that happens when a model is used together with a memory, and LLM produces an empty output (empty string).
Because of the coercion to boolean, saving the history to memory fails when the output is an empty string:
https://github.com/langchain-ai/langchainjs/blob/391bc4645036fd0c2c41b5ed35236919732edf2a/langchain-core/src/memory.ts#L93C1-L98C4
Here is the minimal reproducible example:
```js
const { ChatOpenAI } = require("@langchain/openai");
const { initializeAgentExecutorWithOptions } = require("langchain/agents");
const { SerpAPI } = require("langchain/tools");
const { Calculator } = require("@langchain/community/tools/calculator");
const { BufferMemory } = require("langchain/memory");
// Initialize the language model
const model = new ChatOpenAI({ …
```
=> fix(core): Handle empty model output in memory

docs/core_docs/docs/introduction.mdx
Noticed a place in the docs where it references "Python" instead of "JavaScript", thought I'd submit a quick PR to fix it.
Thanks!
=> docs: Fix typo

libs/langchain-community/src/vectorstores/elasticsearch.ts, libs/langchain-community/src/vectorstores/tests/elasticsearch.int.test.ts
We have recently implemented a new functionality in our application where the customer is able to archive items.
As we want to exclude archived items by default from our vectorstore search we need a filter to add a statement to the must_not  filtering being a must_not exists and then we pass ```{ field: 'archivedAt', operator: 'not_exists' }``` .
If we then want to include archived items later one, we can just not pass this filter.
I think by adding this custom check, we add a lot of flexibility to the similarity search as well.
=> feat(community): ElasticVectorSearch: add a not_exists filter 

docs/core_docs/docs/integrations/vectorstores/libsql.mdx, libs/langchain-community/src/vectorstores/libsql.ts, libs/langchain-community/src/vectorstores/tests/libsql.int.test.ts
This PR fixes issue #7040, which causes SQL syntax errors due to newline characters, quotes, or similar characters not being properly escaped.
The proposed solution uses `@libsql/client`'s built-in object syntax with placeholders to use the internal mechanism for escaping values and therefore fixes the mentioned problem.
Fixes #7040
=> fix(community): Escape libSQL vector store inserts by using object syntax with placeholders

libs/langchain-ollama/package.json, libs/langchain-ollama/src/chat_models.ts, libs/langchain-ollama/src/embeddings.ts, libs/langchain-ollama/src/llms.ts, yarn.lock
Adding optional HTTP Headers to ChatOllama, after they were added to ollama in [v0.5.6](https://github.com/ollama/ollama-js/releases/tag/v0.5.9).
Fixes #6631
=> feat(ollama): Add support for optional headers 

libs/langchain-community/src/chat_models/ibm.ts, libs/langchain-community/src/chat_models/tests/ibm.test.ts, libs/langchain-community/src/embeddings/tests/ibm.test.ts, libs/langchain-community/src/llms/tests/ibm.test.ts, libs/langchain-community/src/utils/ibm.ts, libs/langchain-community/src/vectorstores/libsql.ts, libs/langchain-community/src/vectorstores/tests/libsql.int.test.ts
@jacoblee93 Sorry to tag directly, just noticed you were working here last!
- used named parameters throughout
- in the `addVectors` function we've used the `vector(:embedding)` libsql function
- see: https://docs.turso.tech/features/ai-and-embeddings#functions
-  returned every row id on insert
- ensure that we return a `String` wherever id's are returned per the `Document` type
- implemented the delete all and delete function
- allow creating and searching from table with an implicit ROWID column
I'd suspect that we should use `OpenAIEmbeddings` throughout so we can run all tests against a local `libsql` db and a remote hosted db. Right now I used  `OllamaEmbeddings` in all the new test because the `OPENAI_API_KEY` in my .env was not picked up.  `OllamaEmbeddings` with the default model …
=> feat(community): Add delete and allow default row id in libsql 

libs/langchain-anthropic/src/tests/chat_models-tools.int.test.ts, libs/langchain-anthropic/src/utils/message_inputs.ts
Fixes handling multi-part (e.g. image and text) `ToolMessage`s.
For Anthropic these need to be handled as `HumanMessage`s with a `type: "tool_result"` MessageContentComplex, which itself can have a multipart content part (formatted according to anthropic's requirements).
https://x.com/gingerhendrixai
=> fix(anthropic): Fix multipart tool message

docs/core_docs/docs/tutorials/pdf_qa.ipynb
Refer the correct variable name
In the tutorial the, llm is instantiated under the variable name **`model`**. But while creating the createStuffDocumentsChain in the following steps, the variable name referred is `llm`.
The issue comes in because the variable llm exists in python documentation and the same is copied here in js documentation
=> docs: Update pdf_qa.ipynb

langchain/src/agents/chat_convo/prompt.ts
This PR fixes a typo in the conversational agent formatting instructions
=> fix(langchain): Correct typo in format instructions for conversational agent

CONTRIBUTING.md, libs/langchain-community/src/vectorstores/pgvector.ts
The ?? operator is the nullish coalescing operator, which only checks for null or undefined. However, the expression before it `getEnvironmentVariable("LANGCHAIN_VERBOSE") === "true"` is a boolean expression and will never be null or undefined.
@PetersClemens
=> fix(community): Fix logic issue

libs/langchain-community/src/embeddings/ollama.ts, libs/langchain-ollama/src/embeddings.ts, libs/langchain-ollama/src/tests/embeddings.test.ts
=> feat(ollama): Allow passthrough of other options

examples/package.json, libs/langchain-pinecone/package.json, yarn.lock
Due to a recent `@pinecone/pinecone-database` release (`v4.0.0`), there is a type collision between `@langchain/pinecone` and `@pinecone/pinecone-database`, since `@langchain/pinecone` still uses `v3.0.0`.
Here is the issue in the `pinecone-ts-client` repository which mentions this bug: https://github.com/pinecone-io/pinecone-ts-client/issues/309
Updating the `@langchain/pinecone` module to use the `v4.0.0` version of `@pinecone/pinecone-database` fixes the issue.
=> pinecone[patch]: Update `@pinecone/pinecone-database` version to resolve type errors

libs/langchain-community/src/vectorstores/chroma.ts, libs/langchain-community/src/vectorstores/tests/chroma.test.ts
=> fix(community): chroma search without filter

libs/langchain-community/src/chat_models/ibm.ts
Fixed missing tool_choice in call options of chat model.
Was not aware of this issue until actually looking into langgraph implementation, maybe there could be an option to avoid such problems in the future?
=> fix[community]: Fixed missing tool_choice in call options of chat IBM

libs/langchain-community/src/vectorstores/libsql.ts
- adds generics to the LibSQLVectorStore
=> feat(community): allow metadata generics to flow through LibSQLVectorStore

langchain/src/chat_models/tests/universal.int.test.ts, langchain/src/chat_models/universal.ts
CC @baskaryan @efriis @bracesproul
=> fix(langchain): Fix serialization for initChatModel

docs/core_docs/docs/concepts/index.mdx
=> docs: Add missing streaming concept

libs/langchain-community/src/utils/bedrock/anthropic.ts
=> fix(community): bedrock parsing array content/tool blocks

libs/langchain-community/src/retrievers/bm25.ts
In the BM25Retriever, include the score in each document's metadata.
The score is useful for performing reranking, combining BM25 with other algorithms.
=> feat(community): Incorporate BM25 score in the results

libs/langchain-community/src/vectorstores/prisma.ts
When an an empty array is passed to IN or NOTIN operator in PrismaVectorStore's filter, it will be directly passed to Prisma.join and cause
**TypeError: Expected `join([])` to be called with an array of multiple elements, but got an empty array**
This PR adds a separate logic for handling empty arrays in SQL queries:
* [`libs/langchain-community/src/vectorstores/prisma.ts`](diffhunk://#diff-5b221be6896a52539d6efcdf50be7c50df05b6a025c8737730b782b672c90164R440-R449): Added a condition to check if the array is empty and handle `IN` and `NOT IN` operators appropriately. For empty arrays, `IN ()` will return `FALSE` and `NOT IN ()` will return `TRUE`.
=> fix(community): PrismaVectorStore handle empty array in filter

libs/langchain-google-gauth/package.json, yarn.lock
Failed to commit this when it was released.
=> release(google-gauth): 0.1.3

libs/langchain-community/package.json, yarn.lock
This simply bumps faker dev dependency in community dir (to be used in another PR to come).
=> chore(community): Bump faker dev dep to 8.4.1

examples/src/memory/azure_cosmosdb_nosql.ts, libs/langchain-azure-cosmosdb/package.json, libs/langchain-azure-cosmosdb/src/azure_cosmosdb_nosql.ts, libs/langchain-azure-cosmosdb/src/chat_histories.ts, libs/langchain-azure-cosmosdb/src/tests/caches.int.test.ts, libs/langchain-azure-cosmosdb/src/tests/chat_histories.int.test.ts, yarn.lock
- Added generic `context` object saved along the session. This can be used for example to give a title or save any additional properties along with a session.
- Added method to retrieve all sessions for a user (without the messages)
- Update to latest CosmosDB SDK (had to fix a few types in vector search integrations)
@jacoblee93 Not directly related to the PR, but I've found some memory integration that uses `RunnableWithMessageHistory` like ours, and other using `BufferMemory` which one is the recommended approach? Thanks
=> feat(azure-cosmosdb): add session context and retrieve all sessions for a user

libs/langchain-community/src/chat_models/ibm.ts, libs/langchain-community/src/chat_models/tests/ibm.int.test.ts, libs/langchain-community/src/chat_models/tests/ibm.standard.int.test.ts, libs/langchain-community/src/document_compressors/ibm.ts, libs/langchain-community/src/document_compressors/tests/ibm.int.test.ts, libs/langchain-community/src/llms/ibm.ts, libs/langchain-community/src/llms/tests/ibm.int.test.ts
Providing fixes to some known bugs that came out during usage of the new package, fixing some tests.
=> fix(community): Fix bugs in IBM community, provide some tests and fix existing tests

libs/langchain-anthropic/src/chat_models.ts, libs/langchain-anthropic/src/types.ts
This PR fixes an error when importing `ChatAnthropic`, due to missing declaration file.
Fixes #7332
=> Fix anthropic sdk import

libs/langchain-community/src/document_loaders/web/airtable.ts
Fixes #7288
Added interface to kwargs property.
Added 2 new parameters to kwargs: maxRows and filterByFormula
=> feat(community): Add additional fields to airtable loader

libs/langchain-google-gauth/src/auth.ts
It should be up to the user if they want to log error responses or not. Prompts logged could contain sensitive information.
=> fix(google-gauth): Remove logging of error responses

docs/core_docs/docs/integrations/memory/file.mdx, examples/src/memory/file.ts, libs/langchain-community/src/stores/message/file_system.ts, libs/langchain-community/src/stores/tests/file_chat_history.int.test.ts
- Fixes `getAllSessions()` method not return `id` property
- Fixes doc
=> fix(community): file system chat history

libs/langchain-ollama/src/embeddings.ts
Fixes issue https://github.com/langchain-ai/langchainjs/issues/7375
Fixes #7375
=> fix(ollama): Update embeddings.ts headers type to match Ollama

langchain-core/src/callbacks/base.ts, langchain-core/src/language_models/chat_models.ts, langchain-core/src/language_models/llms.ts, langchain-core/src/tracers/event_stream.ts, langchain-core/src/tracers/log_stream.ts
=> feat(core): Generalize streaming usage for language models based on passed callback handlers

examples/src/document_transformers/html_to_text.ts
The `text-to-html` transformer example was using the `CheerioWebBaseLoader` to fetch HTML, but the `CheerioWebBaseLoader` already strips HTML using Cheerio's `.text()` function. So the `html-to-text` transformer wasn't really doing anything.
This commit updates the example to use the `HTMLWebBaseLoader` instead, to give the `html-to-text` transformer something to do in its own example.
=> docs: updates text-to-html example

langchain-core/src/callbacks/manager.ts, langchain-core/src/callbacks/tests/manager.test.ts
Set a campaign manager, if we know there are callback managers we'd like to use
This preserves existing behavior except for when library creators want handlers registered with the `registerConfigureHook` function. In that case, we want to make sure we return a callback manager.
Twitter: @ibolmo
=> fix(core): Make sure to return a callback manager if configure hooks

libs/langchain-anthropic/src/tests/chat_models-tools.int.test.ts, libs/langchain-anthropic/src/types.ts, libs/langchain-anthropic/src/utils/message_inputs.ts
=> fix(anthropic): Handle parallel tool result blocks

docs/core_docs/docs/concepts/rag.mdx
The current RAG tutorials link on the RAG concepts page links to a header that was previously deleted. I've updated the link to the new location.
=> fix(docs): Fix broken RAG tutorials link

docs/core_docs/docs/concepts/index.mdx
I noticed a handful of broken links in the glossary on the concepts page, thought I'd submit a quick PR to fix them.
Thanks!
=> fix(docs): Fix broken glossary links on concepts page

libs/langchain-google-common/src/embeddings.ts, libs/langchain-google-vertexai/src/tests/embeddings.int.test.ts
The URL path for Vertex AI typically includes a publisher name.
For LLMs, this publisher name is determined based on model name.
For embeddings, the publisher name never matched, so was assigned a name of "unknown".
Oddly enough, in some regions and with some embedding models - this was fine. But in other regions, this returned an error.
Fix is to make sure that all embedding models (at least for now) are considered published by Google.
Fixes #7390
=> fix(google-common, google-vertexai): Invalid URL for embeddings model

libs/langchain-google-common/src/chat_models.ts, libs/langchain-google-common/src/utils/gemini.ts
When using `.withStructuredOutput` we need to force tool use. If not, the model tends produce an empty response and the chain eventually returns `undefined`.
1. Modified tool_use param in gemini utils to handle structured output
2. withStructuredOutput will now bind tool_use parameter
3. anthropic utils already handles the tool use param by setting the tool use object to the function name if provided
=> fix(google-common): add tool_use param when using structured outputs

libs/langchain-google-genai/src/chat_models.ts
This PR extends multimodal support to include the Gemini 2 family of models by updating the `_isMultimodalModel` check. 
- https://github.com/langchain-ai/langchainjs/issues/7355
=> fix(google-genai): Update multimodal model check to include gemini-2 support

examples/src/cache/chat_models/upstash_redis.ts, examples/src/cache/upstash_redis.ts, libs/langchain-community/src/caches/upstash_redis.ts
Ref to https://github.com/langchain-ai/langchainjs/discussions/7377
This PR adds support for setting a Time-To-Live (TTL) value in the `UpstashRedisCache` JavaScript implementation. This feature allows users to define expiration times for cached items, aligning the functionality with the Python version of `UpstashRedisCache`.
=> feat(community): Add TTL support to UpstashRedisCache

libs/langchain-community/src/document_loaders/web/airtable.ts
=> fix(community): Change airtable API request to use POST

langchain/src/chains/combine_documents/base.ts, libs/langchain-cohere/src/rerank.ts
Fixes #7370
1. Prevent the ```invalid request: list of documents must not be empty``` error caused by ```compressDocuments``` method due to ```documents``` being empty. Added a condition to check if ```documents``` is empty. If yes, return an empty array.
2. Prevent exception thrown from ```formattedDocs``` methods when ```documents``` is empty. Added a condition to check if ```documents``` is empty. If yes, return an empty string.
=> fix(cohere,langchain): handle exceptions in compressDocuments and formatDocuments methods due to empty documents

examples/src/caches/azure_cosmosdb_nosql/azure_cosmosdb_nosql.ts
=> fix(docs): Cosmos Db Cache sample link

CONTRIBUTING.md
- update OpenAI link.
- update Apify link.
- update Redis link.
=> fix(contributing): broken links

libs/langchain-aws/src/common.ts
When executing this logic, an error occurs:
```
TypeError: Iterator value text is not an entry object
```
The code here should use `Object.entries()` instead of `Object.values()`
=> fix(aws): fix error message output

docs/core_docs/docs/integrations/chat/llama_cpp.mdx, docs/core_docs/docs/integrations/llms/llama_cpp.mdx, docs/core_docs/docs/integrations/text_embedding/llama_cpp.mdx, examples/src/embeddings/llama_cpp_basic.ts, examples/src/embeddings/llama_cpp_docs.ts, examples/src/models/chat/integration_llama_cpp.ts, examples/src/models/chat/integration_llama_cpp_chain.ts, examples/src/models/chat/integration_llama_cpp_stream.ts, examples/src/models/chat/integration_llama_cpp_stream_invoke.ts, examples/src/models/chat/integration_llama_cpp_stream_multi.ts, examples/src/models/chat/integration_llama_cpp_system.ts, examples/src/models/llm/llama_cpp.ts, examples/src/models/llm/llama_cpp_stream.ts, libs/langchain-community/src/chat_models/llama_cpp.ts, libs/langchain-community/src/llms/llama_cpp.ts
Fixes [#7365](https://github.com/langchain-ai/langchainjs/issues/7365)
The updated documentation also changes the tutorial for installing llama 2 based on the changes needed to install llama 3 instead, based on updates made to the following two repos:
- https://github.com/meta-llama/llama-models
- https://github.com/ggerganov/llama.cpp
=> fix(docs): Fix outdated documentation for llama cpp

libs/langchain-google-common/src/chat_models.ts, libs/langchain-google-common/src/tests/chat_models.test.ts, libs/langchain-google-common/src/tests/data/chat-6-mock.json, libs/langchain-google-common/src/types.ts, libs/langchain-google-common/src/utils/common.ts, libs/langchain-google-common/src/utils/gemini.ts, libs/langchain-google-vertexai/src/tests/chat_models.int.test.ts, libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
Assorted updates, primarily to support Gemini 2.0 (fixes #7345)
- Extensive testing across multiple models
- Extensive testing across both the GCP and Google AI Studio platforms
- Backward and (limited) forward compatibility for grounding with Google Search tool (related to stuff found with PR #7280)
- Add grounding detailed results to response (related to #5073 and #7280)
- Do not use API Key for Google Cloud Platform (fixes issues #5000 and #7399)
Some things to note:
- The tests against "gemini-2.0-flash-thinking-exp" have been commented out. While it works for some things, this model doesn't support tools yet, and we need to look at how to handle the reasoning tokens which are provided. (See #7434)
- Functions work with Gemini 2.0, however the prompting for them is more finicky, at …
=> fix(google-common,google-*) Gemini 2.0 support

libs/langchain-groq/src/chat_models.ts
The `maxRetries` field is not respected with the Groq integration. This PR fixes this issue.
By default, the Groq SDK automatically retries any request twice.   
So with a default of 6 max retries, this results in 6 * 3 = 18 retries before the request is passed on to a fallback provider or failing.
=> fix(groq): Fix Max Retries for Groq

libs/langchain-community/src/llms/togetherai.ts
Apparently togetherAI now have more than one response format, other than the old one it also have a format like this:
```json
{
"id": "8fef9f62bf2dbef4-YYC",
"object": "text.completion",
"created": 1736375327,
"model": "deepseek-ai/DeepSeek-V3",
"choices": [
{
"index": 0,
"text": " Paris",
"logprobs": null,
"finish_reason": "length",
"matched_stop": null
}
],
"usage": {
"prompt_tokens": 11,
"total_tokens": 12,
"completion_tokens": 1,
"prompt_tokens_details": null
},
"prompt": []
}
```
This PR will update the code to handle format like that. Thanks for your time to review this!
Fixes # (issue) #6993 
https://github.com/langchain-ai/langchainjs/issues/6993
=> fix(community): togetherai response different format handling

deno.json, docs/core_docs/docs/integrations/document_loaders/web_loaders/youtube.mdx, libs/langchain-community/package.json, libs/langchain-community/src/document_loaders/tests/youtube.int.test.ts, libs/langchain-community/src/document_loaders/web/youtube.ts, yarn.lock
- Removes `youtube-transcript` dependency
- Updates `youtubei.js` dependency and made peer dependency versioning lenient
- Refactored `YoutubeLoader` to use `youtubei.js` Innertube API instead or relying on `youtube-transcript` web scraping (may solve some issues regarding [YT IP banning](https://github.com/Kakulukian/youtube-transcript/issues/11#issuecomment-2244224076))
- Added test for YoutubeLoader
As YT transcript loading is often broken and requires frequent package updates, this change will (hopefully) simplify the maintenance by now relying on a single package that can be updated independently of @langchain/community package.
=> fix(community): update YoutubeLoader implementation

libs/langchain-google-common/src/output_parsers.ts, libs/langchain-google-common/src/tests/output_parsers.test.ts
Problem: 
If using a subclass of `BaseGoogleSearchOutputParser` where the input doesn't have grounding info, it attempts to dereference undefined.
Solution:
Return the input text, unchanged, if there is no grounding info to annotate.
Fix and tests for same.
=> fix(google-common): Search grounding formatting

langchain-core/src/language_models/chat_models.ts, libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models.int.test.ts
=> feat(core,openai): Add support for disable_streaming, set for o1

examples/src/document_loaders/notionapi.ts, libs/langchain-community/src/document_loaders/web/notionapi.ts
Fixes #7494 
update outdated docs
=> docs: Closes #7494

libs/langchain-google-common/src/chat_models.ts, libs/langchain-google-common/src/tests/chat_models.test.ts, libs/langchain-google-common/src/utils/gemini.ts
Fixes #7509 
This only explicitly uses `logprobs` and `topLogprobs` if `logprobs` is explicitly set. `topLogprobs` is only set if logprobs is explicitly true.
=> fix(google-vertexai): fix bug when not using logprobs

libs/langchain-google-common/src/tests/chat_models.test.ts, libs/langchain-google-common/src/tests/llms.test.ts, libs/langchain-google-common/src/tests/mock.ts, libs/langchain-google-common/src/utils/failed_handler.ts
Introduced in 5030088c; where all errors are thrown even though certain statuses are checked.
Fixes #7493
=> fix(google-common,google-*): fix retryable errors 

langchain-core/src/messages/tests/message_utils.test.ts, langchain-core/src/messages/transformers.ts
=> fix(core): Fix trim messages mutation bug

libs/langchain-community/src/utils/bedrock/index.ts
=> fix(community): make sure guardrailConfig can be added even with anthropic models

libs/langchain-community/src/document_loaders/web/airtable.ts
=> fix(community): Airtable url

docs/core_docs/docs/integrations/tools/google_calendar.mdx, examples/src/tools/google_calendar.ts, libs/langchain-community/src/tools/google_calendar/base.ts, libs/langchain-community/src/tools/google_calendar/commands/run-create-events.ts, libs/langchain-community/src/tools/google_calendar/commands/run-view-events.ts, libs/langchain-community/src/tools/tests/google_calendar.test.ts
Resolves #7483 , resolves #7274 
update /docs/integrations/tools/google_calendar/
=> docs: Resolves #7483, resolves #7274

docs/core_docs/docs/how_to/tool_calling_parallel.ipynb, docs/core_docs/docs/how_to/tool_results_pass_to_model.ipynb, langchain/src/chains/openai_moderation.ts
correct misspelling
fix: #7527
=> docs: correct misspelling

langchain/src/agents/mrkl/index.ts
Fix ZeroShotAgent createPrompt with correct formatted tool names
=> fix(langchain): Fix ZeroShotAgent createPrompt with correct formatted tool names

libs/langchain-community/src/experimental/graph_transformers/llm.ts
Although difficult to reproduce, I've ran into a few times when `relationshipType` was undefined and so the extraction fails. 
In these cases I'd still like to have the relationship being captured in my knowledge graph, so it seems appropriate to provide the transformer with a fallback value it can use, in this case defaulted to `"unknown"`. This also allows for the value to be overridden with something else in cases where `"unknown"` already means something in an existing context.
I'm happy to contribute to anything that may need to be updated to reflect this info, like documentations, just need a pointer :)
=> feat(community): Provide fallback relationshipType in case it is not present in graph_transformer

langchain-core/src/prompts/chat.ts, langchain-core/src/prompts/tests/chat.mustache.test.ts, langchain/src/hub.ts, langchain/src/tests/hub.int.test.ts
Also fixes placeholder shorthand when declaring mustache templates
=> fix(langchain,core): Add shim for hub mustache templates with nested input variables

libs/langchain-ollama/src/embeddings.ts
We are already exporting `ChatOllamaInput` in `@langchain/ollama`. It would be great to also export `OllamaEmbeddingsParams` for embeddings instance.
=> chore(ollama): Export `OllamaEmbeddingsParams` interface

docs/core_docs/docs/concepts/structured_outputs.mdx
=> docs: Clarify tool creation process in structured outputs documentation

libs/langchain-community/src/callbacks/handlers/upstash_ratelimit.ts
Fixes #7279
When I tried initializing `UpstashRatelimitHandler` directly using the source code, `awaitHandlers` and `raiseError` were set to true. But when I installed the package, `awaitHandlers` was false.
Then I checked the build, and I noticed that `raiseError` is set after `super()`:
Since `raiseError` is set after `super()`, `awaitHandlers` stays false ([because in this line `raiseError` is still false](https://github.com/langchain-ai/langchainjs/blob/5bdbb755bdbb05c3f2bca30c8bd3c64b8295b02a/langchain-core/src/callbacks/base.ts#L381)).
With this PR, we set the `awaitHandlers` directly in the `UpstashRatelimitHandler` constructor.
I believe this was working correctly before and somehow broke. Wanted to share in case there are similar problems in other integrations.
=> fix(community): Set awaitHandlers to true in upstash ratelimit

libs/langchain-community/src/indexes/postgres.ts
Make postgresConnectionOptions optional in PostgresRecordManager to be more in line with PGVectorStore
Fixes #7579
=> fix(community): Make postgresConnectionOptions optional in PostgresRecordManager

libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models.int.test.ts
=> feat(openai): Refactor to allow easier subclassing

langchain-core/src/runnables/base.ts, langchain-core/src/runnables/tests/runnable_stream_events_v2.test.ts
Curiously, this did not happen if we consume at least one chunk from the iterator
Fixes https://github.com/langchain-ai/langgraphjs/issues/812
=> fix(core): Fix stream events bug when errors are thrown too quickly during iteration

libs/langchain-community/src/tools/tavily_search.ts
I needed a property of the API (`includeDomains`) that was not in the `TavilySearchAPIRetrieverFields`, so I decided to update all of the body params from the [Tavily API reference](https://docs.tavily.com/docs/rest-api/api-reference).
Let me know if you have remarks, this is my first contribution 😇
=> feat(community): improve support for Tavily search tool args

libs/langchain-community/src/structured_query/supabase.ts, libs/langchain-community/src/structured_query/tests/supabase_self_query.int.test.ts
This pull request introduces support for boolean filters in the Supabase structured query translator and adds corresponding tests to ensure the functionality works as expected.
Support for boolean filters:
* [`libs/langchain-community/src/structured_query/supabase.ts`](diffhunk://#diff-05e57f6dabe3863de15ad33a8a91cdcbe597aee7a4b36292baa0aef8ba119c40R15): Added `isBoolean` to the import statements and updated the `SupabaseTranslator` class to handle boolean values in the `metadata` attribute. [[1]](diffhunk://#diff-05e57f6dabe3863de15ad33a8a91cdcbe597aee7a4b36292baa0aef8ba119c40R15) [[2]](diffhunk://#diff-05e57f6dabe3863de15ad33a8a91cdcbe597aee7a4b36292baa0aef8ba119c40R138-R139)
Testing for boolean filters:
* [`libs/langchain-community/src/structured_query/tests/supabase_self_query.int.test …
=> feat(community): Add boolean metadata type support in Supabase structured query translator

libs/langchain-google-genai/src/utils/common.ts
Adds support for fileUri type which accepts Google AI Filemanager URIs.
This allows uploading large files and passing the uri as per the Gemini documentation without having to send inline data.
=> feat(google-genai): Add support for fileUri in media type in Google GenAI

langchain-core/src/messages/tests/base_message.test.ts, langchain-core/src/messages/utils.ts
=> fix(core): Fix coercion of serialized tool and function messages

libs/langchain-weaviate/src/vectorstores.ts
- Added `className` as part of Document metadata.
- If we have multiple weaviate classes and use wrapper retrievers like `EnsembleRetriever`, we don't know where the docs are coming from.
=> weaviate[minor]: Add Document className as metadata

libs/langchain-community/package.json, libs/langchain-community/src/chat_models/ibm.ts, libs/langchain-community/src/chat_models/tests/ibm.int.test.ts, libs/langchain-community/src/chat_models/tests/ibm.standard.int.test.ts, libs/langchain-community/src/chat_models/tests/ibm.test.ts, libs/langchain-community/src/llms/ibm.ts, libs/langchain-community/src/llms/tests/ibm.int.test.ts, libs/langchain-community/src/llms/tests/ibm.test.ts, libs/langchain-community/src/types/ibm.ts, libs/langchain-community/src/utils/ibm.ts, yarn.lock
This PR adds chat deployment options to Watsonx IBM class allowing user to use langchain with their deployed models
=> feat[community]: Add chat deployment to IBM chat class

langchain-core/src/callbacks/base.ts, langchain-core/src/load/serializable.ts
Plan will be to publish a new version of core, and publish new releases of integration packages. Then keep a running list of keys that we can serialize for each classes where important
@baskaryan @madams0013 @dqbd
=> feat(core): Add a way to manually specify serializable fields

libs/langchain-openai/package.json, libs/langchain-openai/src/azure/chat_models.ts, libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/azure/chat_models.test.ts, libs/langchain-openai/src/tests/chat_models.test.ts, libs/langchain-scripts/bin/extract_serializable_fields.js, libs/langchain-scripts/package.json, libs/langchain-scripts/src/extract_serializable_fields.ts, yarn.lock
=> fix(openai): Prevent extra constructor params from being serialized, add script

langchain/src/experimental/openai_assistant/index.ts
Fixing openai assistants thread run. Parameters to create and run a thread do not match the latest from openai. 
This results in a unknown parameter error when trying to provide a file.
See docs:
https://platform.openai.com/docs/api-reference/runs/createThreadAndRun#runs-createthreadandrun-thread
Langchain Docs:
https://js.langchain.com/v0.1/docs/modules/agents/agent_types/openai_assistant/#use-file-in-ai-assistant
Fixes [# (issue)](https://github.com/langchain-ai/langchainjs/issues/7665)
=> fix(experimental): openai assistant attachments

libs/langchain-community/src/document_loaders/tests/recursive_url.int.test.ts, libs/langchain-community/src/document_loaders/web/recursive_url.ts
Hide console errors from JSDOM on RecursiveUrlLoader.
=> fix(community): hide console errors on RecursiveUrlLoader

libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models.int.test.ts, libs/langchain-openai/src/types.ts
=> feat(openai): Properly pass through max_completion_tokens

docs/core_docs/docs/how_to/sequence.ipynb, docs/core_docs/docs/tutorials/rag.ipynb
There is a broken link when the user click on that it redirect to page not found instead taking the user to api reference.
=> docs: Fix the broken link

docs/core_docs/docs/tutorials/chatbot.ipynb
Fixed a type in the [message persistence section](https://js.langchain.com/docs/tutorials/chatbot#message-persistence)
=> fix: typo in the chatbot tutorial

libs/langchain-community/src/experimental/llms/chrome_ai.ts
Trying to use `ChromeAI` with Chrome 133 (`Version 133.0.6943.99 (Official Build) (arm64)`) on MacOS seems to be giving very weird results:
Using the fix proposed in this PR (with `patch-package` locally to test more easily):
It's not clear if something changed in a later version of Chrome? It looks like it could be related to the new 133 release, since it was working fine with 132 before.
---
Below is a minimal app to reproduce the issue:
<details>
**package.json**
```json
{
"name": "langchainjs-minimal-example-chromeai",
"private": true,
"version": "0.0.1",
"type": "module",
"scripts": {
"dev": "vite --debug",
"build": "vite build",
"preview": "vite preview"
},
"dependencies": {
"@langchain/community": "^0.3.30",
"@langchain/core": "^0.3.40"
},
"devDependencies": {
"vite": "^5.0.8"
}
} …
```
=> fix(community): Fix handling of ChromeAI chunks

libs/langchain-redis/src/tests/vectorstores.test.ts, libs/langchain-redis/src/vectorstores.ts
hi team, want to address this [ask](https://github.com/langchain-ai/langchainjs/discussions/7632). It's a tiny change and python already supported it.  In addition, I also tested it in local redis stack.
=> fix(redis): Add TTL support for redis vector store

docs/core_docs/docs/integrations/text_embedding/voyageai.mdx, libs/langchain-community/src/embeddings/voyage.ts
=> feat(community): Update Voyage embeddings parameters

langchain-core/src/output_parsers/bytes.ts
Fixes #7247 without loosing the typing
This pull request makes a small but important change to the `BytesOutputParser` class in the `langchain-core` package. The change involves updating the type of the `textEncoder` property to use a more specific type.
`globalThis.TextEncoder` (when not imported from `node:util`) is a value, not a type. In this case, the type is actually `InstanceType<typeof TextEncoder>`.
* [`langchain-core/src/output_parsers/bytes.ts`](diffhunk://#diff-d38c7f72b0e15d5088141cc1fcbaa2dfb397a6107d941ce71e780e972e05529bL16-R16): Updated the `textEncoder` property to use `InstanceType<typeof TextEncoder>` instead of `any` for better type safety.
=> fix(core): Fix issue in .d.ts typing for TextEncoder

libs/langchain-google-genai/src/chat_models.ts, libs/langchain-google-genai/src/tests/chat_models.test.ts
Changes range of temperature checked
Fixes #7696
=> fix(google-genai): Support larger range of temperatures for Gemini models

libs/langchain-google-common/src/chat_models.ts, libs/langchain-google-common/src/tests/chat_models.test.ts, libs/langchain-google-common/src/utils/gemini.ts
This eliminates the hard coded default values for:
* temperature
* maxOutputTokens
* topP
* topK
and makes sure that values that aren't set aren't even sent in the request.
=> fix(google-common): Eliminate hard-coded default values in favor of model-based defaults

langchain-core/src/indexing/base.ts
While indexing with an incremental cleanup, a list of UIDs is generated, which is passed off to the vector store to be deleted.
https://github.com/langchain-ai/langchainjs/blob/d303e909d6b73da0bda4c0b7065ff974a980e5b0/langchain-core/src/indexing/base.ts#L343-L355
Sometimes, this list of UIDs is empty, and ChromaDB seems to have a problem with that:
```
InvalidArgumentError:
You must provide either ids, where, or where_document to delete. If
you want to delete all data in a collection you can delete the
collection itself using the delete_collection method. Or alternatively,
you can get() all the relevant ids and then delete them.
``` 
ChromaDB should probably just not do anything instead of throwing an error in such a scenario. Still, it's probably more efficient to skip performing the …
=> fix(core): Skip delete operation if not necessary during incremental index

libs/langchain-google-genai/src/chat_models.ts
Fix corrupted token count (output & total) for Google Genai provider in streaming mode.
Problem was that when using streaming mode we assume `candidatesTokenCount` and `totalTokenCount` are present. They are not initially so the value gets corrupted (`NaN`) and this error carries forward.
Fixes #7444
=> fix(google-genai): Fix Google Genai usage token

langchain-core/src/runnables/remote.ts
=> fix(core): add artifact to ToolMessage and ToolMessageChunk for RemoteRunnable

libs/langchain-deepseek/package.json
the `Homepage` link from [npm repository](https://www.npmjs.com/package/@langchain/deepseek) seems wrong
=> fix(deepseek): wrong home link for @langchain/deepseek

docs/core_docs/docs/integrations/document_loaders/web_loaders/google_cloud_storage.mdx, examples/src/document_loaders/google_cloud_storage.ts, libs/langchain-community/.gitignore, libs/langchain-community/langchain.config.js, libs/langchain-community/package.json, libs/langchain-community/src/document_loaders/web/google_cloud_storage.ts, libs/langchain-community/src/load/import_map.ts, yarn.lock
self explanatory, tested in local. Our platform is GCP, it's a bit helpful to developer if langchain could support cloud storage. 
Please review. thanks!
=> feat(community): Support google cloud storage document loader

libs/langchain-aws/package.json
Updates `@langchain/aws` to support Claude 3.7 with extended thinking mode on bedrock.
=> release(aws): 0.1.5

libs/langchain-google-vertexai/src/tests/chat_models.int.test.ts, libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
No code changes - just tests.
Verify code works with gemini-2.0-flash-lite-001 (or that failures are documented and understood).
(Flash Lite doesn't support every feature, and these are documented.)
=> tests(google-vertex,webauth): Verify code works with gemini-2.0-flash-lite-001

libs/langchain-community/src/tools/google_calendar/base.ts, libs/langchain-community/src/tools/google_calendar/commands/run-create-events.ts, libs/langchain-community/src/tools/google_calendar/commands/run-view-events.ts, libs/langchain-community/src/tools/google_calendar/create.ts, libs/langchain-community/src/tools/google_calendar/prompts/create-event-prompt.ts, libs/langchain-community/src/tools/google_calendar/prompts/view-events-prompt.ts, libs/langchain-community/src/tools/google_calendar/view.ts, libs/langchain-community/src/tools/tests/google_calendar.test.ts
- Added access token support via Google OAuth
- Added keyfile support for consistency with Gmail tool
- Fix prompts since output was not in correct format
=> Google oauth support for Google calender tool

.gitignore, docs/core_docs/docs/integrations/tools/gmail.mdx, examples/src/tools/gmail.ts, libs/langchain-community/src/tools/gmail/base.ts, libs/langchain-community/src/tools/gmail/create_draft.ts, libs/langchain-community/src/tools/gmail/descriptions.ts, libs/langchain-community/src/tools/gmail/get_message.ts, libs/langchain-community/src/tools/gmail/get_thread.ts, libs/langchain-community/src/tools/gmail/search.ts, libs/langchain-community/src/tools/gmail/send_message.ts, libs/langchain-community/src/tools/tests/gmail.test.ts
- Adds support for OAuth access tokens. This is a much better option for use in applications for end users to use their own email account via federated Oauth token exchange using IdPs supporting the feature
- Fixes the search, get message and get thread tools to work properly with google gmail API v1
=> Google oauth support + fix tools for API v1

docs/core_docs/docs/tutorials/classification.ipynb
Fix typos in classification example
=> docs: FIx typos

docs/core_docs/docs/integrations/chat/ibm.ipynb, docs/core_docs/docs/integrations/llms/ibm.ipynb, libs/langchain-community/src/chat_models/ibm.ts, libs/langchain-community/src/chat_models/tests/ibm.test.ts, libs/langchain-community/src/llms/ibm.ts, libs/langchain-community/src/llms/tests/ibm.test.ts
Providing small changes in order to allow user to use inference methods in both LLM and chat class
=> feature(community): Enable using chat and llms without providing project/space/development id (lightweight engine IBM)

libs/langchain-google-genai/src/utils/common.ts
In callbacks of google-genai chat models, the `llmOutput` doesn't contain a `tokenUsage` key, only `generations`, while the usage is known and computed at this point. This PR makes the llmOutput consistent with openai chat models.
Context: Trying to use [`UpstashRatelimitHandler`](https://js.langchain.com/docs/integrations/callbacks/upstash_ratelimit_callback/) with google-genai models raises this error:
```
Failed to log token usage for Upstash rate limit. It could be because the LLM returns the token usage in a different format than expected. See UpstashRatelimitHandler parameters. Got error: TypeError: Cannot read properties of undefined (reading 'promptTokens')
```
=> feat(google-common): Add tokenUsage to llmOutput of google-genai

docs/core_docs/docs/concepts/chat_models.mdx
This PR fixes broken link on Chat models docs page.
=> docs: broken link in chat models page

docs/core_docs/docs/integrations/document_loaders/web_loaders/google_cloud_storage.mdx, libs/langchain-community/src/document_loaders/web/google_cloud_storage.ts
A quick fix for https://github.com/langchain-ai/langchainjs/pull/7740#discussion_r1976549027
=> fix(community): Optional google cloud storage options for GCS doc loader

libs/langchain-azure-cosmosdb/src/azure_cosmosdb_mongodb.ts
Add UA in order to track the usage of AzureCosmosDBMongoDBVectorStore
=> fix(azure-cosmosdb): Update user agent of AzureCosmosDBMongoDBVectorStore

libs/langchain-aws/src/common.ts
When invoking the DeeSeek R1 model on Bedrock, there exists a possibility that the model may generate reasoningContent with an  empty text string.
```json
{
"reasoningContent": {
"text": ""
}
}
```
Modify the code to prevent the `Invalid reasoning content` exception from being thrown in this scenario.
=> fix(aws): fix `Invalid reasoning content` exception on empty reasoning chunk

libs/langchain-community/src/tools/google_calendar/commands/run-create-events.ts, libs/langchain-community/src/tools/google_calendar/commands/run-view-events.ts
Adding a structured output parser for Google Calendar view and event creation. This removes the possibility that the LLM returns more than just the formatted JSON and causes a JSON parsing error.
=> fix(community): adding structured output parser for Google Calendar

libs/langchain-community/src/chat_models/bedrock/web.ts, libs/langchain-community/src/llms/bedrock/web.ts
See https://aws.amazon.com/blogs/aws/deepseek-r1-now-available-as-a-fully-managed-serverless-model-in-amazon-bedrock/
IMHO this validation of model providers is redundant. Bedrock will let the user know if the model is invalid. Strictly enforcing it in client libs makes no sense to me.
=> feat(community): add deepseek to allowed bedrock models

libs/langchain-community/src/vectorstores/azure_aisearch.ts
The description of the return argument for similarity search is incorrect. 
@dfberry
Fixes #7866
=> fix(community): Azure AI Search - similaritySearch return description is incorrect

langchain-core/src/prompts/chat.ts
When using the static method fromTemplate, this PR allows the type of the input to be strictly enforced.
When using the following example :
```typescript
const chatPrompt = ChatPromptTemplate.fromTemplate<{foo: string, bar: string}>("Hello {foo}, I'm {bar}");
const messages = await chatPrompt.formatPromptValue({
foo: "Foo",
bar: "Bar",
});
```
If an input is missing you got a type error `Property 'foo' is missing in type '{ bar: string; }' but required in type 'TypedPromptInputValues<{ foo: string; bar: string; }>'`
I have reused the declarations found in `PromptTemplate.fromTemplate` with the eslint-disabled for the banned type `Symbol` to stay consistent.
Let me know if you have any feedback.
Thanks for the great work !
=> fix(core): Add typing in ChatMessagePromptTemplate.fromTemplate

libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/llms.ts
=> fix(openai): Fix stop sequence passing in constructor for text completion models

libs/langchain-google-genai/src/chat_models.ts, libs/langchain-google-genai/src/tests/chat_models-extended.int.test.ts, libs/langchain-google-genai/src/tests/chat_models.int.test.ts, libs/langchain-google-genai/src/tests/chat_models.standard.int.test.ts, libs/langchain-google-genai/src/tests/chat_models.standard.test.ts, libs/langchain-google-genai/src/tests/chat_models.test.ts, libs/langchain-google-genai/src/tests/context_caching.int.test.ts
Also removes model default, since `gemini-pro` no longer seems valid
Will minor bump
CC @afirstenberg too
=> feat(google-genai): Implement and use Google's new structured output methods

libs/langchain-community/src/document_loaders/web/jira.ts
This pull request adds optional (?) chaining to certain values which may be undefined to handle errors.
=> fix(community): add optional chaining to JiraDocumentConverter to prevent undefined errors

libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
* Add Gemini 2.5 Pro Experimental to test runs against AI Studio
* Adjust tests to remove Max Token setting for streaming tests since it was triggering no output on "thinking" model. 
* Fix bug in placement of multimodal output testing.
Note that tests weren't done against Vertex since it isn't supported there yet.
No code changes.
**No need for new release.**
=> test(google): Gemini 2.5

libs/langchain-community/src/tools/tavily_search.ts
As far as I can see, the authorization in Tavily moved from request body to `Authorization` header: https://docs.tavily.com/documentation/api-reference/endpoint/search#authorization-authorization
This change makes it easier to proxy requests together with `apiUrl`, because the proxy service would only need to rewrite headers and not change request bodies.
=> feat(community): move `api_key` from body to header for Tavily tool

libs/langchain-community/src/chat_models/tests/chatbedrock.int.test.ts, libs/langchain-community/src/utils/bedrock/index.ts
Satisfies old TODO before we supported complex message content types properly
Fixes #7942
=> fix(community): Return raw response content when calling Bedrock Anthropic tools

docs/core_docs/docs/tutorials/rag.ipynb
Fix a typo while reading the RAG part1 tutorial
=> fix(docs): fix a typo

docs/core_docs/docs/how_to/structured_output.ipynb
Fix a typo in the structured output guide documentation:
- Changed "downstrem" to "downstream" in the introduction paragraph
=> docs: fix typo in structured output guide

libs/langchain-anthropic/src/tests/chat_models-tools.int.test.ts, libs/langchain-anthropic/src/utils/message_inputs.ts
As mentioned in https://github.com/langchain-ai/langchainjs/pull/7943#issuecomment-2807991300, Anthropic's tool use inputs are Javascript objects at this point rather than JSON strings, so we only need to parse the input if it's a string.
Without this change, the tool input is silently dropped when converting messages due to the try/catch.
=> fix: don't drop tool input when converting messages to Anthropic payload

libs/langchain-google-common/src/utils/anthropic.ts, libs/langchain-google-vertexai/src/tests/chat_models.int.test.ts
System Message types aren't supposed to be handled in `baseToAnthropicMessage()`, but they were generating a warning there. Make sure there isn't a warning and add a test to confirm.
Fixes #8011
=> fix(google-common): Fix warning about system message in Vertex Anthropic

langchain/src/chains/index.ts, langchain/src/chains/openai_functions/openapi.ts
Make function `convertOpenAPISpecToOpenAIFunctions` available for imports. It's pretty useful function outside of the library, and helps to save a lot of time in API management with LLM
=> feat(community): make convertOpenAPISpecToOpenAIFunctions available for imports

langchain/src/sql_db.ts
An error message in SqlDatabase incorrectly uses "include_tables" instead of "includeTables" when both includeTables and ignoreTables are specified. This commit fixes the typo to maintain consistent camelCase naming convention throughout the codebase and to avoid confusing anyone.
Fixes #7974
=> fix(langchain): Fix typo in error message for SqlDatabase options

libs/langchain-google-genai/src/utils/common.ts
The invocation of a multi-level agent fails when using Gemini models and passing it messages from a previous run (either by using checkpointer/MemorySaver or by passing the messages directly). However, it works perfectly when using another model, such as OpenAI. It works with gemini models when adding the `supervisor` case to `convertAuthorToRole()`.
Fixes #7979 
Also see the bug report for reproducer code.
=> fix(google-genai): Add support for supervisor author name

libs/langchain-tavily/src/tests/search.test.ts, libs/langchain-tavily/src/utils.ts
While using the TavilySearch tool, I noticed that the provided options were not being applied correctly. Upon investigation, I identified a mismatch between the camelCase keys used in the API wrapper and the snake_case format expected by the Tavily API.
- Introduced an abstract base class to:
- Unify apiKey handling for both search and extract wrappers.
- Add a private utility method that converts camelCase option keys to snake_case before making API requests. This ensures compatibility with Tavily's expected format without introducing breaking changes.
@michaelgriff if you have spare second, please take a look.
=> fix(tavily): convert search/extract API parameters to snake_case in request body

libs/langchain-google-common/src/chat_models.ts, libs/langchain-google-common/src/tests/chat_models.test.ts, libs/langchain-google-common/src/types.ts, libs/langchain-google-common/src/utils/common.ts, libs/langchain-google-common/src/utils/gemini.ts, libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
Initial support for Gemini 2.5 Flash
* Adds support for the "thinking budget" through a "maxReasoningTokens" parameter
* Also supports a "thinkingBudget" and "reasoningEffort" for compatibility
* Tests for everything
Fixes #8038 
I'd like to get this out ASAP, even if there are some pending issues.
Some notes:
* Gemini 2.5 Flash defaults to using "thinking tokens" unless you set this off by setting the budget to 0. We don't do anything specific about this.
* Specifying the "maxReasoningTokens" for models that don't support reasoning causes an error. We can discuss if / how we want to address this.
Still pending, but I'd like to get this release out asap while I add these:
* Documentation (where should we document this, exactly?)
* Information in `OutputTokenDetails`
* Google has a bug …
=> feat(google-common): Gemini 2.5 flash

libs/langchain-community/src/vectorstores/typeorm.ts
Added schema name to override it when needed.
It's backward-compatible and should not break existing functionality. 
Fixes https://github.com/langchain-ai/langchainjs/issues/4503
=> feat(community): Add schema support for `ensureTableInDatabase` in typeorm vectorstore.

langchain/package.json
Make `OpenAPISpec` class available outside of package in order to use with function `convertOpenAPISpecToOpenAIFunctions` from https://github.com/langchain-ai/langchainjs/pull/7955
=> fix(community): export openapi util

langchain/src/agents/react/output_parser.ts, langchain/src/tests/react_agent_output_parser.test.ts
react agent parser is replacing all '"' - in the text and this is incorrect, we can not parse a json
E.g.
console.log('"hello world"'.replace(/^"|"$/g, ""));  // Output: hello world
console.log('"hello "world" "'.replace(/^"|"$/g, "")); // Output: hello "world" 
console.log('"hello"world"'.replace(/^"|"$/g, "")); // Output: hello"world
console.log('hello world'.replace(/^"|"$/g, ""));  // Output: hello world (unchanged)
=> fix(langchain): fix react agent quote handling in JSON parsing

libs/langchain-tavily/src/tavily-search.ts, libs/langchain-tavily/src/utils.ts
Adds missing `chunks_per_source` parameter in the latest tavily search class
=> feat(tavily): use chunks per source arg

libs/langchain-openai/package.json, libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models.int.test.ts, libs/langchain-openai/src/tools/dalle.ts, libs/langchain-openai/src/types.ts, yarn.lock
Includes the following changes:
- Updates to latest OpenAI SDK version
- Adds `zdrEnabled` constructor option to `ChatOpenAI`, which to disables automatic `ChatOpenAI` features that depend on OpenAI data storage
- Populates [`previous_response_id`](https://platform.openai.com/docs/guides/conversation-state?api-mode=responses#openai-apis-for-conversation-state) automatically by default, unless ZDR is enabled.
- Populates the ID of previous message items when using the Responses API, unless ZDR is enabled.
- Deprecates `reasoningEffort` and `reasoning_effort` parameters in favor of the forwarded OpenAI `reasoning` object
- These deprecated parameters are still respected if they are provided
- Adds missing fields to the `lc_serializable_keys` property
- Improves API docs to detail cases when …
=> feat(openai): Response API support for reasoning summaries, stateful conversations, and Zero Data Retention

libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models_responses.int.test.ts
=> fix(openai): Responses API: fix function call ID handling on stream

libs/langchain-google-common/src/utils/gemini.ts, libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
As per discussion with @benjamincburns, the token usage information should only come from the last chunk when streamed.
Fixes #8102
=> fix(google-common): stream warnings

libs/langchain-google-common/src/connection.ts, libs/langchain-google-common/src/experimental/media.ts, libs/langchain-google-common/src/tests/chat_models.test.ts
This is an issue that has gotten raised a few times as people have tried to use `@langchain/google-webauth` instead of `@langchain/google-genai`. For calls to AI Studio, default to using the "v1beta" API Version.
(There is no change when using Vertex or if the user explicitly sets `apiVersion`.)
=> fix(google-common): Default AI Studio ("gai") platform to use "v1beta" API Version

libs/langchain-tavily/src/tests/search.test.ts, libs/langchain-tavily/src/utils.ts
When trying to create a release for tavily package, i've noticed that recent PR to the @langchain/tavily package created issues with tests: https://github.com/langchain-ai/langchainjs/pull/8081
- the default parameters were not updated with `chunksPerSource`
- adjustment in the camelCase conversion method created regression
=> fix(tavily): Fix unit tests 

langchain/src/util/openapi.ts
**fix(openapi): add global flag to `replaceAll` in `getCleanedOperationId`**
This update amends the `getCleanedOperationId` utility so that each call to `String.prototype.replaceAll` uses a **global** regular expression, preventing a `TypeError` when invoked with a non-global `RegExp`.
The ECMAScript 2021 specification requires that any `RegExp` passed to `replaceAll` must include the `/g` flag, or the method will throw a `TypeError`. In practice, the previous implementation omitted this flag, causing runtime failures when sanitizing operation IDs.
- Aligns with ECMAScript 2021 §22.1.3.27: `String.prototype.replaceAll` must be called with a global regex.  
- Restores the intended behavior of replacing **all** matches without altering the sanitization logic.
- MDN Web Docs: …
=> fix(openapi): add global flag to replaceAll in getCleanedOperationId

langchain-core/src/messages/ai.ts, libs/langchain-google-common/src/types.ts, libs/langchain-google-common/src/utils/gemini.ts, libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
***Note that this includes changes in langchain-core***
Done:
* Changes to `InputTokenDetails` and `OutputTokenDetails` that split out the common modalities field into a new type. Added several modalities based on those available from Gemini.
* Changes in Gemini output processing to handle "thinking" token count, which is not included in the output token count.
* Add the modalities/details from Gemini to the token details
* Tests
* Note that some tests fail because of a bug in the AI Studio API. I'm working with Google to resolve.
Fixes #8127
=> feat(google-common), feat(core): Improve token counting

libs/langchain-google-common/src/utils/gemini.ts, libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
Fix logic check for when to include `thinkingConfig` in the generation config.
Add test to confirm reasoning can be turned off.
Change Gemini 2.5 Pro model to latest preview.
Fixes #8145
=> fix(gemini-common): Allow reasoning to be turned off by setting maxReasoningTokens to 0.

libs/langchain-aws/src/common.ts
It looks like with the current version, a small bug was introduced: after the recent refactoring, the handling of image_url was changed to assume it's always a string. However, image_url can also be an object with a url property, which seems to be causing errors. I'm reintroducing the previous logic to handle both cases properly
=> fix(aws): handle image_url object format in block type extraction

libs/langchain-google-common/src/chat_models.ts, libs/langchain-google-common/src/connection.ts, libs/langchain-google-common/src/tests/chat_models.test.ts, libs/langchain-google-common/src/types.ts, libs/langchain-google-common/src/utils/common.ts, libs/langchain-google-common/src/utils/gemini.ts, libs/langchain-google-vertexai/src/tests/chat_models.int.test.ts, libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
From May 1-10, Google has announced a variety of updates to Gemini. This adds support for many of those features, including:
* Implicit caching. Cache results now included in token count. (Fixes #8146)
* Vertex "global" region support
* "seed" is now a valid parameter
* Added "vertexai" parameter for compatibility with Google's "genai" library as alias for "platformType" functionality
Added tests against the latest model names and announced features. Including:
* Gemini image generation model publicly available in Vertex
* Gemma on AI Studio now supports images
=> feat(google): Assorted updates and tests from recent announcements

libs/langchain-google-common/src/tests/chat_models.test.ts, libs/langchain-google-common/src/types.ts, libs/langchain-google-common/src/utils/zod_to_gemini_parameters.ts, libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
See #8162 for detailed analysis.
Resolved the issue by using the existing `removeAdditionalProperties()` function in zod_to_gemini_parameters.ts to cleanup the `type` property and possibly add the `nullable` property.
Fixes #8162
=> fix(google): Using .nullish() in zod.

langchain/src/hub/base.ts, langchain/src/hub/node.ts, libs/langchain-google-vertexai-web/src/chat_models.ts, libs/langchain-google-vertexai/src/chat_models.ts
Fixes # (https://github.com/langchain-ai/langchainjs/issues/8136)
1. `ChatGoogleVertexAI` was incorrect and should be `ChatVertexAI`
2. Fixed langchain doc urls
=> fix(langchain): vertex ai model name pulled from hub

libs/langchain-community/src/document_loaders/web/azure_blob_storage_container.ts, libs/langchain-community/src/document_loaders/web/azure_blob_storage_file.ts
Make sure connection string is hidden when serialization occurs
=> fix(community): mark Azure blob storage connection string as secrets

libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models.int.test.ts
I had streaming of o1 up and running until I upgraded to `@langchain/openai` version 0.5.3, which introduced the change this PR is reverting: #7503.
I'm not sure whether all deployments of o1 support streaming yet, but at least it is working on my deployment of o1 version 2024-12-17 in Azure, swedencentral, Data zone standard :)
=> fix(openai): allow streaming o1 responses

libs/langchain-google-genai/README.md
Added missing HumanMessage import for `@langchain/google-genai` readme
=> chore(genai): fix code sample in README

docs/core_docs/docs/integrations/tools/tavily_search_community.ipynb
=> chore(community): fix docs typo in tavily_search_community

libs/langchain-community/src/vectorstores/opensearch.ts
Currently the ids are not returned when querying an opensearch vector store. This adds them to the returned document.
Related to https://github.com/langchain-ai/langchainjs/pull/6963
=> feat(community): Return document ids when querying opensearch vector store

libs/langchain-community/src/vectorstores/prisma.ts
This PR fixes an issue where filtering on enum values using Prisma would fail due to a type mismatch. The fix ensures enum values are correctly cast to text in the default SQL query, allowing filters to work as expected for enums.
Context: When using where filters with enums in a vector store powered by Prisma, the generated SQL failed due to a type mismatch (enum vs. text). This cast to ::text resolves the issue.
Fixes #7953
=> fix(prisma): filter on enum value

libs/langchain-mcp-adapters/README.md, libs/langchain-mcp-adapters/__tests__/client.int.test.ts, libs/langchain-mcp-adapters/__tests__/fixtures/dummy-http-server.ts, libs/langchain-mcp-adapters/__tests__/tools.test.ts, libs/langchain-mcp-adapters/src/client.ts, libs/langchain-mcp-adapters/src/tools.ts
=> feat(mcp-adapters): respect tool timeouts

libs/langchain-mongodb/src/storage.ts, libs/langchain-mongodb/src/tests/chat_history.int.test.ts, libs/langchain-mongodb/src/tests/setup.ts, libs/langchain-mongodb/src/tests/storage.int.test.ts, libs/langchain-mongodb/src/tests/vectorstores.int.test.ts
We (MongoDB) have started running the langchainjs MongoDB integration periodically in our own CI to get early alerting if something were to break.  We'd like to also make sure the tests provide good coverage of the integration.
This PR updates the existing MongoDB integration test suite to more exhaustively test the integration.
=> test(mongodb): add more comprehensive testing to MongoDB integration 

libs/langchain-openai/src/chat_models.ts
In LangGraph if a message does not have an ID, it will persist with auto-generated UUID instead. This ID is considered incorrect by Responses API, but Responses API still permits submitting runs with `call_id` instead, so rely on this for now.
=> fix[openai]: avoid sending auto-generated tool ID

langchain-core/src/utils/env.ts
Node 21 added the navigator interface, so the JSDom check in env.ts will always return true for recent Node versions:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator#browser_compatibility
JSDom's default user agent contains the string "jsdom" so it still should be fine:
https://github.com/jsdom/jsdom?tab=readme-ov-file#advanced-configuration
Same fix as https://github.com/langchain-ai/langsmith-sdk/pull/1784
=> fix(core): Fix JSDom check for recent Node versions

libs/langchain-google-genai/README.md
I was updating package '@langchain/google-genai' to 0.2.10 from 0.1.8 and noticed that docs are mentioning old param `modelName`. By looking at typings from `ChatGoogleGenerativeAI` i see that it has been renamed to `model`
`GoogleGenerativeAIEmbeddingsParams` has alias for both so this raises question should alias be supported for `ChatGoogleGenerativeAI` - if yes i would like to work on it
=> Fix param in langchain-google-genai README

langchain/src/chains/openai_functions/openapi.ts, langchain/src/experimental/openai_assistant/index.ts, langchain/src/experimental/openai_files/index.ts, libs/langchain-openai/package.json, libs/langchain-openai/src/azure/chat_models.ts, libs/langchain-openai/src/azure/embeddings.ts, libs/langchain-openai/src/azure/llms.ts, libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/embeddings.ts, libs/langchain-openai/src/llms.ts, libs/langchain-openai/src/types.ts, libs/langchain-openai/src/utils/headers.ts, yarn.lock
Some strange behavior I noticed with ChatOpenAI is that it would assume it should use an existing responses call when it was passed a previously generated AIMessage (containing `response_metadata.id`) unless `zdrEnabled: true` was provided in the constructor params, meaning even if you wanted to selectively involve context (e.g. trimming messages) it would still use an existing responses call if it could find it on a passed in message. (context is [existing messages on openai's side] U [messages passed in on invoke] if an `AIMessage` contained an openai ID)
```ts
const model = new ChatModel({ model: "o4-mini" });
const firstResponse = await model.invoke("hello")
await model.invoke([firstResponse, "hello"])
await model.invoke([firstResponse, "hello"])
const output = await …
```
=> patch(openai): upgrade sdk & defer zdr handling to openai

langchain-core/src/language_models/base.ts, libs/langchain-anthropic/src/chat_models.ts, libs/langchain-groq/src/chat_models.ts, libs/langchain-mistralai/src/chat_models.ts, libs/langchain-ollama/src/chat_models.ts, libs/langchain-openai/src/chat_models.ts, libs/langchain-standard-tests/src/integration_tests/chat_models.ts, libs/langchain-standard-tests/src/utils.ts, yarn.lock
Fixes #8144 
The change in python was to replace the structured_output_format config option, but here we never had one to begin with! Any items that aren't a model or runnable param get passed through to `options` in the trace, so we're relying on the integration package to provide it rather than trying to transform that in core
before trace: https://smith.langchain.com/public/82b3d21d-28a6-4abf-b2b9-1d429af84948/r
after trace: https://smith.langchain.com/public/7560ef8e-b839-494c-8de1-2a5fd1197c0e/r
=> feat: add `ls_structured_output_format` tracing

libs/langchain-google-genai/src/embeddings.ts, libs/langchain-google-genai/src/tests/embeddings.int.test.ts
Small addition of the baseUrl property that already exists on the google-genai chat model to the embeddings. This should enable the use of proxies / custom base urls as it's already supported on the chat model.
=> feat(google-genai): Add baseUrl property to embeddings

libs/langchain-standard-tests/README.md
=> fix(tests): correct typos and formatting in standard tests README.md

langchain-core/src/output_parsers/tests/structured.test.ts, langchain-core/src/utils/json_schema.ts, langchain-core/src/utils/tests/json_schema.test.ts, langchain-core/src/utils/types/tests/zod.test.ts, langchain-core/src/utils/types/zod.ts
=> fix(core): use input param for schema serialization

libs/langchain-google-gauth/package.json, yarn.lock
Upgrades `google-auth-library` dep to latest major version (v10.1.0).
=> minor(google-gauth): Upgrade google-auth-library to latest major version (v10)

libs/langchain-google-common/src/connection.ts, libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
Tests for Gemini 2.5 models
* Gemini 2.5 Pro is now GA
* Gemini 2.5 Flash is now GA
* Gemini 2.5 Flash Lite is in preview
Fix:
* Gemini 2.5 Flash Lite for Vertex is only available in the "global" region. Changed default region for it.
Notes:
* Gemini 2.5 Pro cannot have reasoning turned off
* Gemini 2.5 Flash Lite defaults to reasoning off, but can be turned on
* There is a discrepancy between the AI Studio and Vertex AI reporting for output tokens. AI Studio does not report the modality of output tokens, while Vertex AI does. Issue opened with Google.
Otherwise - integration tests performed as expected.
=> fix(google): Gemini 2 5

docs/core_docs/docs/troubleshooting/errors/index.mdx, docs/core_docs/docs/troubleshooting/warnings/insecure-cache-algorithm.mdx, langchain-core/.eslintrc.cjs, langchain-core/.gitignore, langchain-core/langchain.config.js, langchain-core/package.json, langchain-core/src/caches/base.ts, langchain-core/src/caches/tests/in_memory_cache.test.ts, langchain-core/src/indexing/base.ts, langchain-core/src/utils/hash.ts, langchain-core/src/utils/js-sha1/hash.ts, langchain-core/src/utils/js-sha256/LICENSE.md, langchain-core/src/utils/js-sha256/hash.ts, langchain-core/src/utils/tests/hash.test.ts
This PR deprecates the `insecureHash` and introduces a support for Custom Key Encoders for Caching and Indexing.
Note: The `insecureHash` function is currently based on SHA-1 algorithm, which may lead to security issues as discussed with @sinedied and @jacoblee93
=> fix(core): add custom key encoder and deprecate insecureHash

langchain-core/src/utils/json_schema.ts, langchain-core/src/utils/tests/json_schema.test.ts, langchain-core/src/utils/types/tests/zod.test.ts, langchain-core/src/utils/types/zod.ts
see https://github.com/langchain-ai/langchainjs/issues/8367#issuecomment-2990283636
=> patch[core]: allow for inner transforms in schema serialization

langchain-core/src/runnables/base.ts
Fixes #7963
We are seeing this error on prod at Anara. 
We are using Vercel Fluid compute to optimize serverless execution.
This results in long running processes. The `addEventListener` is not being cleaned up when doing multiple executions.
This error also happened a year ago. Implemented a similar fix.
https://github.com/langchain-ai/langchainjs/issues/6461
> adds an abort listener to the passed options.signal, but never removes it manually.
> 
> When Runnable.stream() or streamEvents() is called repeatedly with the same signal (or multiple times in parallel), the listeners accumulate, eventually triggering:
> 
> (node:75561) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. MaxListeners is 10. Use …
=> fix(core): max event listeners error long running process

libs/langchain-mcp-adapters/src/client.ts, libs/langchain-mcp-adapters/src/tools.ts
The current class signatures return a `StructuredToolInterface` type which doesn't have the `withConfig` function, meaning the note on setting tool timeouts in the README is inaccurate currently.
See https://github.com/langchain-ai/langchainjs/issues/8279#issuecomment-2938421697
=> fix(mcp-adapters): use DynamicStructuredTool instead of interface type

langchain-core/src/messages/base.ts, libs/langchain-standard-tests/src/integration_tests/chat_models.ts, libs/langchain-standard-tests/src/utils/types.ts
Working toward bringing some parity with the Python lib to the integration tests. Includes a fair bit of rewording to improve semantics.
- In `testStream`, we weren't checking that `content` was defined, and further, that it was composed of a valid string or MessageContentComplex[]. To do this, I added some helpers (`isMessageContentComplex`, `isMessageContentImageUrl`, `isMessageContentText`).
- Adds a missing test to check double-texting (`testDoubleMessageConversation`).
- Ensure that `model_name` is in the `response_metadata` (`testUsageMetadata`).
- Add missing `type=tool_call` to AIMessage `tool_calls[]`
- Rearrange some tests for better grouping & narrative flow
- Resolve TODO by finding TEST_AUDIO_URL and add corresponding conditional block to `testStandardAudioContentBlocks`
=> fix(tests): `chat_models` int tests updates and sync

internal/net-mocks/example/__tests__/chat_models.test.ts, internal/net-mocks/package.json, yarn.lock
running `yarn test` from root locally would require ANTHROPIC_API_KEY without this
=> fix(net-mocks): dont put example tests on CI hot path

libs/langchain-community/src/chat_models/bedrock/web.ts, libs/langchain-community/src/chat_models/tests/chatbedrock.test.ts, libs/langchain-community/src/llms/bedrock/web.ts
- Add "apac" to AWS_REGIONS list in both chat models and LLMs
- Add comprehensive test suite for model provider detection
- Test various regional model prefixes (eu, apac, us-gov, us)
- Ensure proper handling of different model ID formats and providers
- Add validation for unsupported custom model ARNs
This enables support for APAC-specific Bedrock model IDs like: `apac.anthropic.claude-3-5-sonnet-20240620-v1:0`
This change resolves the issue where users in APAC regions couldn't use region-specific Bedrock model identifiers. Previously, attempting to use models with the `apac.` prefix would result in an "Unknown model provider" error because the APAC region prefix wasn't recognized in the AWS_REGIONS configuration.
The fix includes:
- Adding "apac" to the supported AWS regions in both …
=> fix: add missing APAC region prefix in Bedrock models

libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models_responses.int.test.ts
If user decides to create AIMessage themselves, LangGraph will auto-generate a message ID (using uuidv4), which Responses API does not handle. This PR will ignore the message IDs that are seen as invalid by Responses API.
=> fix(openai): exclude external message IDs for AIMessage when using responses API

docs/core_docs/docusaurus.config.js
This fixes the JS langchain's doc website, which does not respect the user-defined system theme.
I added a docusaurus config based on what is described in their documentation: [here](https://docusaurus.io/docs/api/themes/configuration#defaultMode) 
Fixes #8390
=> added config for (https://js.langchain.com/docs/introduction/) to respect user theme

libs/langchain-aws/README.md, libs/langchain-aws/package.json, libs/langchain-community/package.json, yarn.lock
AWS Bedrock has introduced API key support on 7/7, simplifying authentication for the Amazon Bedrock API. To enable this new feature in langchainjs, this update bumps the required "@aws-sdk/client-bedrock-runtime" version to "^3.840.0". It has been tested and worked as expected with new `AWS_BEARER_TOKEN_BEDROCK` environment variable.
=> support api key authentication for Bedrock API

libs/langchain-google-common/src/connection.ts, libs/langchain-google-common/src/embeddings.ts, libs/langchain-google-common/src/types.ts, libs/langchain-google-vertexai/src/tests/embeddings.int.test.ts, libs/langchain-google-webauth/src/tests/embeddings.int.test.ts
Updates support for embeddings on Google platforms, including:
* Adds support for the AI Studio API in addition to previously supported Vertex AI API
* Adds "dimensions" parameter to optionally set a reduced dimension size for the returned vector.
* This term was chosen for maximum cross-platform compatibility. Google's term, "outputDimensionality" is also accepted as an alias.
* The AI Studio API and "gemini-embedding-001" in Vertex AI don't accept batches. Forced batch size to 1 for all models
* Updates tests
* Tested using the webauth package as well as vertexai package
* Obsoleted "textembedding-gecko" is no longer tested
* Added "gemini-embedding-001" model to test
Fixes #8490
=> feat(google): Updates to embeddings

docs/core_docs/docs/integrations/vectorstores/azure_cosmosdb_nosql.mdx
This pull request adds a new section to the Azure Cosmos DB integration documentation, focusing on security considerations when using filters. It highlights the risks of SQL injection and provides recommendations to mitigate them.
Documentation updates on security:
* [`docs/core_docs/docs/integrations/vectorstores/azure_cosmosdb_nosql.mdx`](diffhunk://#diff-4c4e9428e8cae1baabe6b682695879faed4b203f171cd664f0268059eab678e0R42-R53): Added a warning about the security risks of using filters with user-provided input. Included guidance on using Azure Cosmos DB's parameterized query mechanism to prevent SQL injection attacks.
=> Added note on security considerations when using filters and Azure Cosmos DB for NoSQL

libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models.test.ts
previous alias: https://github.com/langchain-ai/langchainjs/blob/c4a6ef85c40840587e9b18f5a6c7e66bd6b77c1f/libs/langchain-openai/src/chat_models.ts#L1799
=> fix(openai): revert to previous model alias

langchain-core/src/tools/index.ts, langchain-core/src/tools/types.ts
in lieu of RunnableBinding which we're planning to rework in the coming releases
(partial change for #8279)
=> patch(core): add default config for tools

libs/langchain-mcp-adapters/README.md, libs/langchain-mcp-adapters/__tests__/client.basic.test.ts, libs/langchain-mcp-adapters/__tests__/client.comprehensive.test.ts, libs/langchain-mcp-adapters/__tests__/client.int.test.ts, libs/langchain-mcp-adapters/src/types.ts
The current default for mcp-adapters is to prefix the server name to each returned tool by default. We generally think that it's not very intuitive to set prefixes on tool names this way, which is motivation for the change.
MCP spec also makes mention that this is something that sdk clients ***can*** do to avoid tool name conflicts, but isn't be the default behavior.
This is being released as a minor version as to not automatically change tool context when package managers upgrade to the latest patch.
=> minor[mcp]: disable disambiguation by default

libs/langchain-google-common/src/connection.ts, libs/langchain-google-webauth/src/tests/chat_models.int.test.ts
* Since Gemini 2.5 Flash Lite on Vertex now works in more regions, use the same default region as other models (us-central1). (The previous default region is still valid.)
* Update tests to use release name gemini-2.5-flash-lite
=> patch[gemini]: Gemini 2 5 Flash-Lite

langchain-core/src/messages/ai.ts, langchain-core/src/messages/tests/base_message.test.ts, libs/langchain-openai/src/tests/chat_models-extended.int.test.ts
Fixes a bug where tool calls with empty schemas (`z.object({})`) were being dropped in streaming mode but worked correctly in non-streaming mode.
The issue occurred because `AIMessageChunk` constructor was filtering out tool call chunks that didn't have an ID. OpenAI sometimes sends chunks without IDs for tools with empty parameter schemas, causing these tool calls to be completely lost in streaming mode while working fine in non-streaming mode.
**Changes:**
- Modified tool call chunk grouping logic in `langchain-core/src/messages/ai.ts` to assign fallback IDs for chunks without IDs (format: `"fallback-{index}"`)
- Preserve original IDs when present to maintain backward compatibility
- Added comprehensive unit tests for chunks without IDs in …
=> fix(core): handle tool call chunks without IDs in streaming mode

langchain-core/src/prompts/template.ts, langchain-core/src/prompts/tests/chat.mustache.test.ts, langchain-core/src/prompts/tests/prompt.mustache.test.ts
This PR fixes a bug in Mustache template parsing where variables inside conditional sections were not being extracted as input variables.
**Problem**: 
When using Mustache templates with conditional sections like `"Hey {{name}}, {{#isTrue}}{{myvar}}{{/isTrue}}"`, the variable `myvar` inside the conditional block was not being recognized as an input variable. The `inputVariables` array would only contain `["name", "isTrue"]` instead of the expected `["name", "isTrue", "myvar"]`.
**Root Cause**: 
The `mustacheTemplateToNodes` function in `langchain-core/src/prompts/template.ts` was not recursively processing nested content inside Mustache sections. It only extracted the section variable (`isTrue`) but ignored variables inside the section (`myvar`).
**Solution**: 
- Modified …
=> fix(core): extract variables from inside Mustache sections

libs/langchain-tavily/package.json, libs/langchain-tavily/src/tavily-crawl.ts, libs/langchain-tavily/src/tavily-extract.ts, libs/langchain-tavily/src/tavily-map.ts, libs/langchain-tavily/src/tavily-search.ts
With Zod 3.25.68+ we're observing elevated incidence count of "Type instantiation is excessively deep and possibly infinite," which is caused by packages importing from `"zod"` rather than `"zod/v3"`
=> fix(tavily): pin zod to v3 to avoid "Type instantiation is excessively deep and possibly infinite" error

libs/langchain-openai/src/chat_models.ts
I'm pretty sure this console.log is a left over from development. This PR removes that line.
=> openai/chat_models: remove console.log line

libs/langchain-aws/src/common.ts, libs/langchain-aws/src/tests/chat_models.test.ts
Fixes a `ValidationException` that occurred when using `ChatBedrockConverse` with AWS Bedrock models:
It's related to the issue #5960.
The error occurred when message chunks contained only whitespace or newlines (e.g., `'  '`, `'\n '`, `' '`). In these cases, the AWS Bedrock's Converse API was throwing the following exception:
`ValidationException: The text field in the ContentBlock object at messages.X.content.Y is blank. Add text to the text field, and try again.`
Modified the text block processing logic in `convertAIMessageToConverseMessage` to:
- Detect whitespace-only content by trimming and checking for empty strings
- Merge whitespace-only blocks with the previous text block to preserve content
- Update test case `"Streaming supports empty string chunks"` to verify proper handling …
=> fix: ValidationException for blank text blocks in ChatBedrockConverse

docs/core_docs/docusaurus.config.js, langchain/src/util/sql_utils.ts
Add `better-sqlite3` to the DataSource type check
Example code:
```typescript
import { SqlDatabase } from "langchain/sql_db";
import { DataSource } from "typeorm";
const datasource = new DataSource({
type: "better-sqlite3",
database: "test.db",
readonly: true,
});
const db = await SqlDatabase.fromDataSourceParams({
appDataSource: datasource,
});
console.log(await db.getTableInfo())
```
Execution before fix:
```
❯ pnpm exec tsx index-mini.ts
file:///home/lemon/Documents/text-to-sql-mcp/node_modules/.pnpm/langchain@0.3.30_@langchain+core@0.3.70_@opentelemetry+api@1.9.0_openai@5.12.2_zod@4.0.17___@_oks7tym3ksu5msad6f4d7govii/node_modules/langchain/dist/util/sql_utils.js:140
throw new Error("Database type not implemented yet");
^
Error: Database type not implemented yet
at …
```
=> fix: add better-sqlite3 to getTableAndColumnsName

libs/langchain/package.json, libs/langchain/src/hub/base.ts, libs/langchain/src/hub/node.ts, pnpm-lock.yaml
We should not list `langsmith` as direct dependency for `langchain` given that it is mainly used within the hub module which doesn't seem to be relevant for most `langchain` package users.
=> fix(langchain): make `langsmith` an optional dependency

libs/langchain-cloudflare/src/vectorstores.ts
Fixes # 
- similaritySearchVectorWithScore not returning id
-  use existing document.id if available when generating documentIds
=> fix(cloudflare): similaritySearchVectorWithScore not returning id

libs/langchain/package.json, libs/langchain/src/chains/sql_db/sql_db_chain.ts, libs/langchain/src/load/import_constants.ts, pnpm-lock.yaml
The `langchain` package had a dependency to `js-tiktoken` for a basic type import. This is not necessary and we can clean this up.
=> fix(langchain): remove `js-tiktoken` dependency

libs/langchain-aws/src/chat_models.ts
Makes sure that Bedrock guardrailCondig object can be passed and not be overriden when setting invocation parameters.
=> Support passing of Bedrock guardrails parameter

environment_tests/test-exports-cf/package.json, environment_tests/test-exports-cjs/package.json, environment_tests/test-exports-esbuild/package.json, environment_tests/test-exports-esm/package.json, environment_tests/test-exports-vercel/package.json, internal/build/index.ts, libs/langchain-community/package.json, libs/langchain-standard-tests/package.json, libs/langchain/package.json, libs/providers/langchain-anthropic/package.json, pnpm-lock.yaml
It seems like I've never enabled the "unused dependency check" in tsdown. This patch enables it again and removes unused dependencies found in the repository.
=> fix(internal): re-enable unused dependency check

libs/langchain-textsplitters/package.json, libs/langchain/package.json, libs/langchain/src/agents/tests/types.test-d.ts, libs/langchain/src/hub/base.ts, pnpm-lock.yaml
Bumping peer dependencies to `@langchain/core` and `@langchain/textsplitters`
=> fix(langchain): bump peer dep to core

libs/langchain-core/src/tools/types.ts, libs/langchain/src/agents/ReactAgent.ts, libs/langchain/src/agents/nodes/AgentNode.ts, libs/langchain/src/agents/tests/reactAgent.int.test.ts, libs/langchain/src/agents/tests/reactAgent.test.ts, libs/langchain/src/agents/types.ts, libs/langchain/src/hub/base.ts, libs/langchain/src/index.ts
This creates parity with Python.
=> feat(agents): allow createReactAgent to take in a model as string property

libs/langchain/src/agents/nodes/ToolNode.ts, libs/langchain/src/agents/tests/ToolNode.test.ts
Minor oversight on my part. Discovered while updating docs.
=> fix(langchain): handle tool errors when handleToolErrors is set to `true` (default)

.changeset/easy-masks-post.md, langchain-core/.gitignore, langchain-core/langchain.config.js, langchain-core/package.json, langchain-core/src/index.ts
=> fix(core): add missing root export to package.json

.changeset/hot-bugs-clap.md, libs/langchain-community/src/indexes/postgres.ts
Hello,
When running the SQL query included in the `getTime()` function on PostgreSQL 13.18, I got the following result:
```csv
date_part
1755534822.917985
```
This causes the function to return `NaN` since the `extract` property does not exist.
When the `getTime` function returns `NaN`, both the `incremental` and `full` cleanup operations remove all added documents, rendering the indexing feature unusable:
```js
{ numAdded: 1, numDeleted: 1, numUpdated: 0, numSkipped: 0 }
```
This PR fixes the issue by always adding an alias using the `AS` SQL keyword.
=> fix(community): postgres indexes getTime returning NaN due to missing alias

.changeset/major-lamps-walk.md, libs/langchain-community/src/retrievers/tests/bm25.test.ts, libs/langchain-community/src/utils/@furkantoprak/bm25/BM25.ts
Fixes #8746 
**Problem:** 
unescaped RegExp(term) throws on `**`, `[`, `?`, etc., crashing BM25 based retrieval functionality
**Fix:** 
escape metacharacters via `term.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&")` before constructing `RegExp`
=> BM25Retriever: escape regex metacharacters in getTermFrequency to prevent crashes

libs/langchain/src/agents/nodes/AgentNode.ts, libs/langchain/src/agents/responses.ts, libs/langchain/src/agents/tests/responses.test.ts
This is something I've missed from the Python implementation of structured output.
=> fix(langchain): add support for toolMessageContent

.changeset/puny-poems-sink.md, langchain/src/chains/openai_functions/openapi.ts, langchain/src/chains/openai_functions/tests/openapi.test.ts
This PR fixes the conversion of $ref items in array schemas and adds this case to the existing test.
I also added a test for the conversion of refs that are not in an array schema.
Example:
```yaml
openapi: 3.1.0
info:
title: A fake spec for testing
version: 0.0.1
paths:
/foo:
post:
operationId: createFoo
description: Create multiple foo
parameters:
- name: fooArray
in: query
schema:
type: array
items:
$ref: '#/components/schemas/Foo'
responses:
'201':
description: Created
content:
application/json:
schema:
properties:
success:
type: boolean
components:
schemas:
Foo:
type: object
properties:
bar:
type: string
```
Converting the `fooArray` schema would result in
```json
{
"type": "array",
"items": {
"type": "string"
}
}
```
After the fix it gets converted into:
```json
{
"type": "array", …
```
=> fix: add support for conversion of ref in array schema

docs/api_refs/package.json, langchain-core/src/callbacks/manager.ts, langchain-core/src/tracers/tests/langsmith_interop.int.test.ts, langchain-core/src/tracers/tests/langsmith_interop.test.ts, yarn.lock
If a `LangChainTracer` instance were already present in the callback manager, the if statement here would never trigger:
```ts
if (
tracingEnabled &&
!callbackManager.handlers.some(
(handler) => handler.name === "langchain_tracer"
)
) {
...
}
```
And the parent/child relationship would break.
=> fix(core): Always inherit parent run id onto callback manager from context

.changeset/strong-worms-sneeze.md, langchain-core/src/prompts/chat.ts, langchain-core/src/prompts/template.ts, langchain-core/src/prompts/tests/chat.mustache.test.ts
~This PR adds a test case that reveals a circumstance in which Mustache nested objects do not work correctly.~
~Since I don't have a detailed enough understanding to make code changes, I'll start by adding test cases.~
~This test case passes on @langchain/core@0.3.64 which I'm using for now.~
~This issue may be caused by the following PR: https://github.com/langchain-ai/langchainjs/pull/8580.~
This PR fixes an mustache template issue that nested objects won't work correctly.
=> fix(core): make mustache prompt with nested object working correctly

.github/workflows/compatibility.yml, dependency_range_tests/scripts/langchain/node/update_resolutions_latest.js
`langchain` depends on `-alpha.3` which we're overriding to `-alpha.1` in dep tests
=> chore(langchain): remove constraint on lower core alpha

libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models.test.ts
=> fix(openai/0.x): add streaming support for custom tools

libs/providers/langchain-openai/src/chat_models.ts, libs/providers/langchain-openai/src/tests/chat_models.test.ts
This PR fixes a regression where OpenAI streaming stopped working since v0.6.10. The issue was caused by improper handling of the `disableStreaming` property when it was passed as `undefined`.
When `disableStreaming` was passed as `undefined` (either explicitly or as part of a fields object), the nullish coalescing operator (`??`) would preserve the `undefined` value instead of falling back to the default `false` from the parent class:
```typescript
// Before (problematic):
this.disableStreaming = fields?.disableStreaming ?? this.disableStreaming;
// When fields.disableStreaming is undefined:
// undefined ?? undefined = undefined ❌
```
Changed to use a strict boolean check that ensures type safety and predictable behavior:
```typescript
// After (fixed):
this.disableStreaming = …
```
=> fix(openai/v1): handle undefined disableStreaming to restore streaming functionality

libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models.test.ts, libs/langchain-openai/src/utils/output.ts
=> fix(openai/0.x): handle OpenRouter image generation responses

libs/providers/langchain-openai/src/chat_models.ts, libs/providers/langchain-openai/src/tests/chat_models.test.ts, libs/providers/langchain-openai/src/utils/output.ts
This PR adds support for OpenRouter's image generation API response format in the ChatOpenAI integration.
When using OpenRouter's image generation models (e.g., `google/gemini-2.5-flash-image-preview`), the generated images were not being received in LangChain.js responses. OpenRouter returns images in a separate `choices[0].message.images` array, which differs from the standard OpenAI format.
- Modified `_convertCompletionsMessageToBaseMessage` to detect and extract images from OpenRouter's response format
- Convert the images to LangChain's standard `Multimodal.Image` content blocks
- Preserve backward compatibility by also adding image URLs to `additional_kwargs`
Added comprehensive unit tests covering:
- Single image responses
- Multiple image responses  
- Text-only responses (no …
=> fix(openai/v1): handle OpenRouter image generation responses

langchain/src/document_loaders/fs/buffer.ts, langchain/src/document_loaders/fs/text.ts
- Update buffer.ts and text.ts to import BaseDocumentLoader directly from @langchain/core
- Resolves runtime import errors where BaseDocumentLoader was not exported from ../base.js
- Fixes issues with PDF and CSV loaders that depend on these base classes
Fixes import errors:
- "BaseDocumentLoader is not exported from '../base.js'" in buffer.js
- "BaseDocumentLoader is not exported from '../base.js'" in text.js
Fixes #8441
=> fix: Fix BaseDocumentLoader import errors in fs document loaders

libs/langchain-community/src/vectorstores/chroma.ts
In the collection.query method, the parameter queryEmbeddings should accept a number[][] instead of a number[]. Multiple query conditions are required.
Fixes #8314
=> fix chroma query param error

yarn.lock
Some PRs came with dep changes and it was not possible to get `yarn.lock` updated without requesting users to take action. This PR will fix the issue with that.
=> fix(build): update yarn.lock

libs/langchain-community/src/memory/zep.ts
When using Zep Memory with Anthropic's Claude models, the integration fails because Claude only permits system messages as the first message. This causes errors when the memory retrieval mechanism in `ZepMemory` returns a `SystemMessage` containing summary content followed by other message types.
This PR adds utility functions and a configuration option to handle Claude's limitation with system messages, similar to the solution already implemented in `ZepCloudMemory`:
1. Added a new `separateMessages` option that controls how memory is returned:
- When `true` (default): Returns separate messages with proper types (SystemMessage, HumanMessage, AIMessage) - maintains backward compatibility
- When `false`: Condenses all memory content into a single HumanMessage for Claude compatibility
2. …
=> fix(community): add Claude-compatible mode to ZepMemory

libs/providers/langchain-openai/src/chat_models.ts, libs/providers/langchain-openai/src/tools/tests/custom.int.test.ts
core wasn't rebased for the first alpha release, so the core changes needed to make custom tools work weren't released
=> fix(openai): re-enable custom tools

.changeset/tame-impalas-battle.md, libs/langchain-google-cloud-sql-pg/src/tests/vectorstore.int.test.ts, libs/langchain-google-cloud-sql-pg/src/vectorstore.ts
continuation of #8335
Fixes #8334
=> fix(google-cloud-sql-pg): properly handle explicit metadata columns in PostgresVectorStore

.changeset/stupid-cows-grow.md, libs/langchain-community/src/vectorstores/hanavector.ts, libs/langchain-community/src/vectorstores/tests/hanavector.test.ts
=> fix(community): allow any chars in delimited identifiers in hanavector

.changeset/seven-papayas-mix.md, docs/core_docs/docs/integrations/vectorstores/prisma.mdx, examples/src/indexes/vector_stores/prisma_vectorstore/prisma/schema_uuid.prisma, examples/src/indexes/vector_stores/prisma_vectorstore/prisma_uuid.ts, libs/langchain-community/src/vectorstores/prisma.ts, libs/langchain-community/src/vectorstores/tests/prisma.test.ts
This PR adds column type configuration support to PrismaVectorStore to fix SQL type casting errors when using PostgreSQL native types like UUID.
When using Prisma's `@db.Uuid` columns, PrismaVectorStore would generate SQL queries that attempted to compare UUID columns with text values without proper type casting, resulting in the error: `operator does not exist: uuid = text`.
- Added a new `columnTypes` configuration option to specify PostgreSQL column types
- Implemented proper SQL type casting in `addVectors` and `buildSqlFilterStr` methods
- Supports `uuid`, `integer`, `bigint`, `jsonb`, and `text` column types
- Maintains full backward compatibility - the `columnTypes` parameter is optional
- ✅ Added `ColumnTypeConfig` interface
- ✅ Updated PrismaVectorStore implementation with type …
=> fix(community): add column type configuration to PrismaVectorStore for proper SQL casting (#8583)

.changeset/modern-melons-roll.md, libs/langchain-community/src/llms/tests/togetherai.test.ts, libs/langchain-community/src/llms/togetherai.ts
This PR fixes an issue where users attempting to use chat/instruct models with the `TogetherAI` class would encounter a cryptic error: `Cannot read properties of undefined (reading 'choices')`. This happened because the TogetherAI API returns different response formats for text completion models vs chat models, and users were unknowingly using the wrong class.
1. **Improved Error Handling**: Added proper error handling in the `_call` method to catch when the API response doesn't match the expected format and provide a helpful error message directing users to use `ChatTogetherAI` instead.
2. **Model Type Detection**: Implemented automatic detection of chat/instruct models (based on patterns like "instruct", "chat", "vision", or "turbo" in model names) and added a console warning when users …
=> fix(community): improve TogetherAI error handling for chat models

.changeset/serious-yaks-invite.md, libs/providers/langchain-google-common/package.json, libs/providers/langchain-google-common/src/tests/utils.test.ts, libs/providers/langchain-google-common/src/utils/gemini.ts, pnpm-lock.yaml
This PR fixes a critical issue where `@langchain/google-vertexai` version 0.2.17+ was causing 400 Bad Request errors when using `image_url` content blocks with external URLs.
When using `image_url` content blocks with external URLs (non-data URLs), the Google Vertex AI API was returning 400 Bad Request errors. This was a breaking change that affected all users trying to send images via URLs to Gemini models.
The issue occurred during the conversion from OpenAI-style `image_url` blocks to Gemini's expected format. When the standard content block converter processed external image URLs, it was sending an empty string for the MIME type, which the Vertex AI API rejects.
- Added `inferMimeTypeFromUrl()` function to detect MIME types from file extensions
- Updated `fromStandardImageBlock()` to …
=> fix(google-common): fix 400 Bad Request error for external image URLs in Vertex AI

docs/core_docs/docs/integrations/vectorstores/redis.ipynb
This PR updates the Redis vectorstore documentation to include the new delete by IDs feature that was introduced in [PR #8738](https://github.com/langchain-ai/langchainjs/pull/8738) (commit: [e4c183d](https://github.com/langchain-ai/langchainjs/commit/e4c183ddca1443a1647cccce3bcef40731ff8b31)).
- **Added documentation for delete by IDs feature**: Document the new `delete({ ids: string[] })` method alongside the existing `delete({ deleteAll: boolean })` method
- **Updated section structure**: Changed "Deleting an index" to "Deleting documents" with clear subsections for both deletion methods
- **Added key prefix clarification**: Document that the configured key prefix is automatically added to the provided IDs
- **Updated limitation note**: Removed outdated statement about deletion not …
=> docs(langchain-redis): add delete documents by IDs documentation

.changeset/curly-spoons-build.md, libs/providers/langchain-azure-cosmosdb/src/chat_histories/nosql.ts
=> fix(azure-cosmosdb/v1): missing init while retrieving context

.changeset/angry-ads-retire.md
=> fix(v1): use `keyEncoder` instead of insecure cache key getter (#8978)

.changeset/afraid-paws-give.md, langchain-core/src/messages/base.ts, langchain-core/src/messages/tests/ai.test.ts
This PR updates the logic so that if tool chunk indices match and one chunk does not have an ID, the tool chunks are then merged.
Fixes https://github.com/langchain-ai/langchainjs/issues/8985
=> fix(core): update chunk concat logic to match on missing ID fields

.changeset/honest-hats-brush.md, langchain-core/src/messages/ai.ts, langchain-core/src/messages/base.ts, langchain-core/src/messages/tests/base_message.test.ts
Fixes an issue where tool call chunks that were missing an ID were showing up as separate tool calls
Fixes #8990
=> fix(core): omit tool call chunks without tool call id

.changeset/metal-camels-join.md, libs/langchain-openai/src/chat_models.ts, libs/langchain-openai/src/tests/chat_models-extended.int.test.ts, libs/langchain-openai/src/tests/chat_models.test.ts
A previous change has caused streaming to break in OpenAI. This patch fixes that.
=> fix(openai): fix streaming in openai

examples/src/createAgent/accessLongTermMemory.ts, examples/src/createAgent/accessLongTermMemoryInTools.ts, examples/src/createAgent/middleware/hitl.ts, examples/src/createAgent/middleware/simpleHitl.ts, examples/src/createAgent/postModelHook.ts, examples/src/createAgent/tools.ts, examples/src/createAgent/updateLongTermMemoryInTools.ts, libs/langchain/src/index.ts
We should not re-export LangGraph primitives from `langchain` canonical.
=> fix(langchain): remove MemorySaver re-export

libs/langchain-openai/src/chat_models.ts
This pull request makes a minor update to the example configuration for the `ChatOpenAIFields` interface in `chat_models.ts`. The change clarifies how to specify the `baseURL` using the `configuration` object instead of a direct property.
* Updated the example for setting `baseURL` to use the `configuration` object, improving clarity for users configuring the API client.
[@recabasic](https://x.com/recabasic)
Fixes #3565 #3086
=> Correct baseURL configuration usage

.changeset/green-squids-fetch.md, langchain/src/chat_models/tests/universal.int.test.ts, langchain/src/chat_models/universal.ts
Adds support for Perplexity AI models in the universal chat model factory.
- Added 'perplexity' to `_SUPPORTED_PROVIDERS` array
- Added perplexity case to `initChatModel()` switch statement
- Updated `_inferModelProvider()` to recognize `sonar*` and `pplx*` model names
- Added integration test for Perplexity support
```typescript
import { initChatModel } from "langchain/chat_models/universal";
// Auto-inferred from model name
const model = await initChatModel("sonar-pro", {
apiKey: "your-perplexity-key"
});
// Or explicitly specified
const model2 = await initChatModel("sonar-deep-research", {
modelProvider: "perplexity",
apiKey: "your-perplexity-key"
});
```
- Added integration test that verifies perplexity models work with the universal API
- Test covers model initialization and basic …
=> feat: Add Perplexity support to universal chat model

libs/langchain/src/agents/middlewareAgent/ReactAgent.ts, libs/langchain/src/agents/middlewareAgent/middleware/bigTool.ts, libs/langchain/src/agents/middlewareAgent/middleware/index.ts, libs/langchain/src/agents/middlewareAgent/middleware/tests/bigTool.test.ts, libs/langchain/src/agents/middlewareAgent/nodes/AgentNode.ts, libs/langchain/src/agents/middlewareAgent/nodes/middleware.ts, libs/langchain/src/agents/middlewareAgent/types.ts
This PR introduces the **`llmToolSelectorMiddleware`** - a new middleware for LangChain agents that intelligently selects the most relevant tools for each user query using an LLM-based strategy. This middleware helps reduce cognitive load on the main model and improves response quality by filtering tools before they reach the primary agent model.
- **Intelligent Tool Selection**: Uses an LLM to analyze user queries and select the most relevant tools from the available set
- **Configurable Limits**: Set maximum number of tools to select per query
- **Retry Logic**: Built-in retry mechanism with configurable attempts for robust tool selection
- **Full History Support**: Option to include conversation history in tool selection decisions
- **Flexible Model Configuration**: Use a separate …
=> feat(langchain/createAgent): llmToolSelectorMiddleware implementation

.changeset/silver-dingos-wonder.md, langchain/src/hub/base.ts, langchain/src/hub/tests/hub.int.test.ts
=> fix(langchain): Bind schemas for other types of pulled hub prompts

.changeset/strong-drinks-sell.md, langchain/src/hub/base.ts, langchain/src/hub/node.ts
=> fix(mistral-ai): hub.pull with ChatMistralAI auto-instanciate

libs/langchain/src/agents/index.ts, libs/langchain/src/agents/interrupt.ts, libs/langchain/src/agents/middlewareAgent/middleware/hitl.ts, libs/langchain/src/agents/middlewareAgent/types.ts, libs/langchain/src/index.ts
This patch ensures we properly export all external symbols to allow TypeScript to properly infer all types correctly. See this fix in deepagentjs: https://github.com/langchain-ai/deepagentsjs/pull/32/commits/08b561d8496f2d8d78136183dd8d1c489faba8fc
=> fix(langchain/createAgent): export all symbols so TypeScript can properly infer types

CONTRIBUTING.md
It appears it was using the old location of langchain-core
=> fix(CONTRIBUTING.md): update directory path for langchain-core build instructions

examples/src/createAgent/dynamicTools/advanced.ts, examples/src/createAgent/dynamicTools/simple.ts, libs/langchain/src/agents/middlewareAgent/middleware.ts, libs/langchain/src/agents/middlewareAgent/middleware/dynamicSystemPrompt.ts, libs/langchain/src/agents/middlewareAgent/middleware/hitl.ts, libs/langchain/src/agents/middlewareAgent/middleware/llmToolSelector.ts, libs/langchain/src/agents/middlewareAgent/nodes/AfterModalNode.ts, libs/langchain/src/agents/middlewareAgent/nodes/AgentNode.ts, libs/langchain/src/agents/middlewareAgent/nodes/BeforeModalNode.ts, libs/langchain/src/agents/middlewareAgent/nodes/middleware.ts, libs/langchain/src/agents/middlewareAgent/nodes/utils.ts, libs/langchain/src/agents/middlewareAgent/tests/middleware.test-d.ts, libs/langchain/src/agents/middlewareAgent/tests/middleware.test.ts, libs/langchain/src/agents/middlewareAgent/types.ts
We've decided to keep `tools` in `ModelRequest` a list of tool instances so users have access on more tool information. This also removes `tools` and `toolCalls` from runtime as it differs from our middleware designs.
=> fix(langchain/createAgent): tools in ModelRequest back to tool instance

libs/langchain/src/agents/middlewareAgent/ReactAgent.ts, libs/langchain/src/agents/middlewareAgent/types.ts
Instead of using a Proxy as proposed in #9016 this patch just adds additional methods needed by LangGraph to fetch graph information, making it run successfully:
```
npx @langchain/langgraph-cli dev
Welcome to
╦  ┌─┐┌┐┌┌─┐╔═╗┬─┐┌─┐┌─┐┬ ┬
║  ├─┤││││ ┬║ ╦├┬┘├─┤├─┘├─┤
╩═╝┴ ┴┘└┘└─┘╚═╝┴└─┴ ┴┴  ┴ ┴.js
- 🚀 API: http://localhost:2024
- 🎨 Studio UI: https://smith.langchain.com/studio?baseUrl=http://localhost:2024
This in-memory server is designed for development and testing.
For production use, please use LangGraph Cloud.
info:    ▪ Starting server...
warn:    ┏ Some LangGraph.js dependencies are not up to date. Please make sure to update them to the required version.
warn:    ┗ [1] { '@langchain/langgraph-checkpoint': { version: '0.0.0', required: '~0.0.16 || ^0.1.0' } }
info:    ▪ Initializing …
```
=> fix(langchain/createAgent): fix LangGraph integration

libs/langchain/src/agents/middlewareAgent/ReactAgent.ts, libs/langchain/src/agents/middlewareAgent/middleware.ts, libs/langchain/src/agents/middlewareAgent/middleware/index.ts, libs/langchain/src/agents/middlewareAgent/middleware/modelFallback.ts, libs/langchain/src/agents/middlewareAgent/middleware/tests/modelFallback.test.ts, libs/langchain/src/agents/middlewareAgent/nodes/AgentNode.ts, libs/langchain/src/agents/middlewareAgent/tests/middleware.test.ts, libs/langchain/src/agents/middlewareAgent/types.ts
This PR implements the `retryModelRequest` middleware hook and `ModelFallbackMiddleware`, mirroring the [Python implementation](https://github.com/langchain-ai/langchain/pull/33275).
Added a new optional hook to the `AgentMiddleware` interface that allows middleware to intercept model invocation errors and optionally retry with modified requests:
```typescript
retryModelRequest?(
error: Error,
request: ModelRequest,
state: AgentBuiltInState,
runtime: Runtime,
attempt: number
): Promise<ModelRequest | void> | ModelRequest | void;
```
- **Parameters:**
- `error`: The exception that occurred during model invocation
- `request`: The original model request that failed
- `state`: The current agent state
- `runtime`: The runtime context
- `attempt`: The current attempt number (1-indexed)
- …
=> feat(langchain/createAgent): implement retry model request hook in middleware

.changeset/mighty-moments-know.md, examples/src/memory/mongodb.ts, libs/langchain-mongodb/package.json, libs/langchain-mongodb/src/chat_history.ts, libs/langchain-mongodb/src/storage.ts, libs/langchain-mongodb/src/tests/chat_history.int.test.ts, libs/langchain-mongodb/src/tests/storage.int.test.ts, libs/langchain-mongodb/src/tests/vectorstores.int.test.ts, libs/langchain-mongodb/src/vectorstores.ts, libs/langchain-mongodb/src/version.ts, libs/langchain-mongodb/tsconfig.json, yarn.lock
Instead of using the docs show users how to set metadata, this PR adds the ability to add the name to the metadata post client construction in the MongoDB vcetor search, memory, and chat history modules.
=> feat(mongodb): auto append client metadata for mongodb
